### PR TITLE
Port mapping is lost after VCH is reboot for non-default bridge network

### LINKED ISSUE #8523: Port mappings will be lost for non default bridge network when VCH is rebooted from VC
#### Summary
Reboot the VCH and the port mappings for all networks except the default bridge network disappear. 

#### Environment information
VIC 1.4.x
VC 6.7

##### Steps to reproduce
 1. Make a new network. "docker network create somenet"
 2. Make something with port mappings "docker run -d -p 1111:80 --network somenet nginx"
 3. Check connection to container in browser and validate page shows. Check "docker ps" and validate mapping shows.
 4. Reboot VCH from vSphere
 5. Check connection to container in browser and it fails. Check "docker ps" and the mappings do not exist. 

##### Expected behavior
The  port mappings is still there

### PR DESCRIPTION
**Pull request by yuyangbj**
After make a new network bridge network, the port mapping for containers which
uses this new network will be lost after the VCH is rebooted from VC. And the
iptables for the port mapping in VCH are also lost.

Fixes #8523 
[specific ci=Group1-Docker-Commands.1-10-Docker-PS]

### CODE REVIEW

File: lib/apiservers/portlayer/restapi/handlers/scopes_handlers.go [hunk 1]
```diff
@@ -398,12 +399,18 @@ func toEndpointConfig(e *network.Endpoint) *models.EndpointConfig {
...
 
-	return &models.EndpointConfig{
+	ret := models.EndpointConfig{
 		Address:   addr,
 		Container: e.ID().String(),
 		ID:        e.ID().String(),
 		Name:      e.Name(),
 		Scope:     e.Scope().Name(),
 		Ports:     ecports,
+		Gateway:   e.Gateway().String(),
```
Comment (YanzhaoLi) [inline lib/apiservers/portlayer/restapi/handlers/scopes_handlers.go]: We have example code in containerhandler: `Direct: e.Network.Type == constants.ExternalScopeType`. How about it?
