### PR TITLE
Fix oob shutdown on cvm during vic machine delete

### LINKED ISSUE #7716: 1-40-Docker Restart - failed to cleanup VCH datastore folder
https://ci-vic.vmware.com/vmware/vic/18274/7

```time="2018-04-11T22:26:34Z" level=warning msg="Failed to remove datastore files for VM VirtualMachine:vm-19208 with folder path VCH-18274-1262: Cannot delete file [datastore1] VCH-18274-1262/V1.4.0-DEV-0-1C4E2E2-bootstrap.iso"```

vic-machine.log:
```
Apr 11 2018 22:26:29.177Z INFO  op=1910.1: ### Removing VCH ####
Apr 11 2018 22:26:29.177Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/validate.NewValidator:89]
Apr 11 2018 22:26:29.230Z DEBUG op=1910.1: Accepting host "10.158.214.103" thumbprint 61:32:90:11:91:EC:C9:74:0F:3E:8E:4E:11:4B:30:2A:12:4C:F2:D8
Apr 11 2018 22:26:29.230Z DEBUG op=1910.1: Creating VMOMI session with thumbprint 61:32:90:11:91:EC:C9:74:0F:3E:8E:4E:11:4B:30:2A:12:4C:F2:D8
Apr 11 2018 22:26:29.278Z DEBUG Session Environment Info: 
Apr 11 2018 22:26:29.278Z DEBUG op=1910.1: vSphere resource cache populating...
Apr 11 2018 22:26:29.282Z DEBUG op=1910.1: Cached dc: 
Apr 11 2018 22:26:29.288Z DEBUG op=1910.1: Cached cluster: 
Apr 11 2018 22:26:29.304Z DEBUG op=1910.1: Cached pool: 
Apr 11 2018 22:26:29.306Z DEBUG op=1910.1: Cached folders: 
Apr 11 2018 22:26:29.306Z DEBUG op=1910.1: Error count populating vSphere cache: (1)
Apr 11 2018 22:26:29.306Z DEBUG op=1910.1: new validator Session.Populate: Failure finding ds (): default datastore resolves to multiple instances, please specify
Apr 11 2018 22:26:29.306Z DEBUG [ END ] op=1910.1 [vic/lib/install/validate.NewValidator:89] [129.055028ms] 
Apr 11 2018 22:26:29.306Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/validate.(*Validator).ValidateTarget:346]
Apr 11 2018 22:26:29.306Z INFO  op=1910.1: Validating target
Apr 11 2018 22:26:29.306Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/validate.(*Validator).target:421]
Apr 11 2018 22:26:29.306Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/validate.(*Validator).managedbyVC:428]
Apr 11 2018 22:26:29.306Z DEBUG [ END ] op=1910.1 [vic/lib/install/validate.(*Validator).managedbyVC:428] [7.397µs] 
Apr 11 2018 22:26:29.306Z DEBUG [ END ] op=1910.1 [vic/lib/install/validate.(*Validator).target:421] [26.631µs] 
Apr 11 2018 22:26:29.306Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/validate.(*Validator).ListIssues:273]
Apr 11 2018 22:26:29.306Z DEBUG [ END ] op=1910.1 [vic/lib/install/validate.(*Validator).ListIssues:273] [7.166µs] 
Apr 11 2018 22:26:29.306Z DEBUG [ END ] op=1910.1 [vic/lib/install/validate.(*Validator).ValidateTarget:346] [94.169µs] 
Apr 11 2018 22:26:29.306Z DEBUG [BEGIN]  [vic/lib/install/management.NewDispatcher:79]
Apr 11 2018 22:26:29.306Z DEBUG [ END ]  [vic/lib/install/management.NewDispatcher:79] [10.471µs] 
Apr 11 2018 22:26:29.306Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).NewVCHFromComputePath:91] path "/dc1/host/cls", name "VCH-18274-1262"
Apr 11 2018 22:26:29.306Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/validate.(*Validator).ResourcePoolHelper:60] /dc1/host/cls
Apr 11 2018 22:26:29.315Z DEBUG [ END ] op=1910.1 [vic/lib/install/validate.(*Validator).ResourcePoolHelper:60] [8.932394ms] /dc1/host/cls
Apr 11 2018 22:26:29.315Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).findVirtualApp:88] /dc1/host/cls/Resources/VCH-18274-1262
Apr 11 2018 22:26:29.324Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).findVirtualApp:88] [9.161847ms] /dc1/host/cls/Resources/VCH-18274-1262
Apr 11 2018 22:26:29.337Z DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).isVCH:76] /dc1/host/cls/Resources/VCH-18274-1262/VCH-18274-1262
Apr 11 2018 22:26:29.337Z DEBUG [BEGIN] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] VM(VirtualMachine:vm-19208) Properties([config.extraConfig])
Apr 11 2018 22:26:29.337Z DEBUG op=1910.1: properties: [config.extraConfig summary.runtime.connectionState]
Apr 11 2018 22:26:29.345Z DEBUG [ END ] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] [7.577662ms] VM(VirtualMachine:vm-19208) Properties([config.extraConfig])
Apr 11 2018 22:26:29.346Z DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).isVCH:76] [9.113318ms] /dc1/host/cls/Resources/VCH-18274-1262/VCH-18274-1262
Apr 11 2018 22:26:29.346Z DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).InitDiagnosticLogsFromVCH:177]
Apr 11 2018 22:26:29.346Z DEBUG op=1910.1: Cannot find image stores from configuration; attempting to find from vm datastore
Apr 11 2018 22:26:29.346Z DEBUG [BEGIN] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] VM(VirtualMachine:vm-19208) Properties([datastore])
Apr 11 2018 22:26:29.346Z DEBUG op=1910.1: properties: [datastore summary.runtime.connectionState]
Apr 11 2018 22:26:29.348Z DEBUG [ END ] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] [1.525876ms] VM(VirtualMachine:vm-19208) Properties([datastore])
Apr 11 2018 22:26:29.488Z DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).InitDiagnosticLogsFromVCH:177] [141.408614ms] 
Apr 11 2018 22:26:29.488Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).NewVCHFromComputePath:91] [182.042834ms] path "/dc1/host/cls", name "VCH-18274-1262"
Apr 11 2018 22:26:29.488Z INFO  op=1910.1: 
Apr 11 2018 22:26:29.488Z INFO  op=1910.1: VCH ID: VirtualMachine:vm-19208
Apr 11 2018 22:26:29.488Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).GetNoSecretVCHConfig:182]
Apr 11 2018 22:26:29.488Z DEBUG [BEGIN] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] VM(VirtualMachine:vm-19208) Properties([config.extraConfig])
Apr 11 2018 22:26:29.488Z DEBUG op=1910.1: properties: [config.extraConfig summary.runtime.connectionState]
Apr 11 2018 22:26:29.500Z DEBUG [ END ] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] [11.438867ms] VM(VirtualMachine:vm-19208) Properties([config.extraConfig])
Apr 11 2018 22:26:29.501Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).GetNoSecretVCHConfig:182] [13.057176ms] 
Apr 11 2018 22:26:29.501Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).DeleteVCH:47] VCH-18274-1262
Apr 11 2018 22:26:29.501Z DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).findApplianceByID:369]
Apr 11 2018 22:26:29.503Z DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).findApplianceByID:369] [1.839951ms] 
Apr 11 2018 22:26:29.505Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).DeleteVCHInstances:220] VCH-18274-1262
Apr 11 2018 22:26:29.505Z INFO  op=1910.1: Removing VMs
Apr 11 2018 22:26:29.510Z DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).isVCH:76]
Apr 11 2018 22:26:29.510Z DEBUG [BEGIN] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] VM(VirtualMachine:vm-19210) Properties([config.extraConfig])
Apr 11 2018 22:26:29.510Z DEBUG op=1910.1: properties: [config.extraConfig summary.runtime.connectionState]
Apr 11 2018 22:26:29.515Z DEBUG [ END ] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] [5.359873ms] VM(VirtualMachine:vm-19210) Properties([config.extraConfig])
Apr 11 2018 22:26:29.515Z DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).isVCH:76] [5.879184ms] 
Apr 11 2018 22:26:29.515Z DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).isContainerVM:99]
Apr 11 2018 22:26:29.515Z DEBUG [BEGIN] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] VM(VirtualMachine:vm-19210) Properties([config.extraConfig])
Apr 11 2018 22:26:29.516Z DEBUG op=1910.1: properties: [config.extraConfig summary.runtime.connectionState]
Apr 11 2018 22:26:29.525Z DEBUG [ END ] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] [9.36502ms] VM(VirtualMachine:vm-19210) Properties([config.extraConfig])
Apr 11 2018 22:26:29.526Z DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).isContainerVM:99] [10.225753ms] 
Apr 11 2018 22:26:29.526Z DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).isVCH:76]
Apr 11 2018 22:26:29.526Z DEBUG [BEGIN] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] VM(VirtualMachine:vm-19209) Properties([config.extraConfig])
Apr 11 2018 22:26:29.526Z DEBUG op=1910.1: properties: [config.extraConfig summary.runtime.connectionState]
Apr 11 2018 22:26:29.526Z DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).deleteVM:154] vm "VirtualMachine:vm-19210", force true
Apr 11 2018 22:26:29.531Z DEBUG [ END ] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] [5.696143ms] VM(VirtualMachine:vm-19209) Properties([config.extraConfig])
Apr 11 2018 22:26:29.532Z DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).isVCH:76] [6.280026ms] 
Apr 11 2018 22:26:29.532Z DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).isContainerVM:99]
Apr 11 2018 22:26:29.532Z DEBUG [BEGIN] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] VM(VirtualMachine:vm-19209) Properties([config.extraConfig])
Apr 11 2018 22:26:29.532Z DEBUG op=1910.1: properties: [config.extraConfig summary.runtime.connectionState]
Apr 11 2018 22:26:29.542Z DEBUG [ END ] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] [10.323085ms] VM(VirtualMachine:vm-19209) Properties([config.extraConfig])
Apr 11 2018 22:26:29.543Z DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).isContainerVM:99] [11.223622ms] 
Apr 11 2018 22:26:29.543Z DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).isVCH:76]
Apr 11 2018 22:26:29.543Z DEBUG [BEGIN] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] VM(VirtualMachine:vm-19211) Properties([config.extraConfig])
Apr 11 2018 22:26:29.543Z DEBUG op=1910.1: properties: [config.extraConfig summary.runtime.connectionState]
Apr 11 2018 22:26:29.543Z DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).deleteVM:154] vm "VirtualMachine:vm-19209", force true
Apr 11 2018 22:26:29.552Z DEBUG [ END ] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] [8.246241ms] VM(VirtualMachine:vm-19211) Properties([config.extraConfig])
Apr 11 2018 22:26:29.552Z DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).isVCH:76] [8.93087ms] 
Apr 11 2018 22:26:29.552Z DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).isContainerVM:99]
Apr 11 2018 22:26:29.552Z DEBUG [BEGIN] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] VM(VirtualMachine:vm-19211) Properties([config.extraConfig])
Apr 11 2018 22:26:29.552Z DEBUG op=1910.1: properties: [config.extraConfig summary.runtime.connectionState]
Apr 11 2018 22:26:29.560Z DEBUG [ END ] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] [7.394401ms] VM(VirtualMachine:vm-19211) Properties([config.extraConfig])
Apr 11 2018 22:26:29.561Z DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).isContainerVM:99] [8.57547ms] 
Apr 11 2018 22:26:29.561Z DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).isVCH:76]
Apr 11 2018 22:26:29.561Z DEBUG [BEGIN] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] VM(VirtualMachine:vm-19208) Properties([config.extraConfig])
Apr 11 2018 22:26:29.561Z DEBUG op=1910.1: properties: [config.extraConfig summary.runtime.connectionState]
Apr 11 2018 22:26:29.561Z DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).deleteVM:154] vm "VirtualMachine:vm-19211", force true
Apr 11 2018 22:26:29.578Z DEBUG [ END ] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] [17.224101ms] VM(VirtualMachine:vm-19208) Properties([config.extraConfig])
Apr 11 2018 22:26:29.581Z DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).isVCH:76] [19.794631ms] 
Apr 11 2018 22:26:29.587Z DEBUG op=1910.1: No disks found attached to VM
Apr 11 2018 22:26:29.938Z DEBUG [BEGIN] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] VM(VirtualMachine:vm-19210) Properties([config.files.vmPathName])
Apr 11 2018 22:26:29.938Z DEBUG op=1910.1: properties: [config.files.vmPathName summary.runtime.connectionState]
Apr 11 2018 22:26:29.940Z DEBUG [ END ] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] [2.188249ms] VM(VirtualMachine:vm-19210) Properties([config.files.vmPathName])
Apr 11 2018 22:26:29.940Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Apr 11 2018 22:26:29.941Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Apr 11 2018 22:26:29.942Z DEBUG op=1910.1: Getting list of the devices for VM "upbeat_easley-a29389ffbe68"
Apr 11 2018 22:26:29.948Z DEBUG op=1910.1: Removing disks from VM "upbeat_easley-a29389ffbe68"
Apr 11 2018 22:26:29.978Z DEBUG [BEGIN] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] VM(VirtualMachine:vm-19211) Properties([config.files.vmPathName])
Apr 11 2018 22:26:29.978Z DEBUG op=1910.1: properties: [config.files.vmPathName summary.runtime.connectionState]
Apr 11 2018 22:26:29.979Z DEBUG [BEGIN] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] VM(VirtualMachine:vm-19209) Properties([config.files.vmPathName])
Apr 11 2018 22:26:29.979Z DEBUG op=1910.1: properties: [config.files.vmPathName summary.runtime.connectionState]
Apr 11 2018 22:26:29.981Z DEBUG [ END ] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] [3.234006ms] VM(VirtualMachine:vm-19211) Properties([config.files.vmPathName])
Apr 11 2018 22:26:29.981Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Apr 11 2018 22:26:29.982Z DEBUG [ END ] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] [3.184166ms] VM(VirtualMachine:vm-19209) Properties([config.files.vmPathName])
Apr 11 2018 22:26:29.982Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Apr 11 2018 22:26:29.985Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Apr 11 2018 22:26:29.985Z DEBUG op=1910.1: Getting list of the devices for VM "dreamy_boyd-e8e343ae08c5"
Apr 11 2018 22:26:29.986Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Apr 11 2018 22:26:29.986Z DEBUG op=1910.1: Getting list of the devices for VM "eager_wright-073b9f7054da"
Apr 11 2018 22:26:29.989Z DEBUG op=1910.1: Removing disks from VM "dreamy_boyd-e8e343ae08c5"
Apr 11 2018 22:26:29.990Z DEBUG op=1910.1: Removing disks from VM "eager_wright-073b9f7054da"
Apr 11 2018 22:26:30.135Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [193.964791ms] 
Apr 11 2018 22:26:30.135Z DEBUG op=1910.1: Destroying VM "upbeat_easley-a29389ffbe68"
Apr 11 2018 22:26:30.137Z DEBUG op=1910.1: unexpected soap fault on task retry: types.MethodDisabled{RuntimeFault:types.RuntimeFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}, Source:"VIC"}
Apr 11 2018 22:26:30.138Z DEBUG op=1910.1: Destroy is disabled. Enabling destroy for VM "upbeat_easley-a29389ffbe68"
Apr 11 2018 22:26:30.138Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Apr 11 2018 22:26:30.141Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [3.210226ms] 
Apr 11 2018 22:26:30.141Z DEBUG op=1910.1: Retrying destroy of VM "upbeat_easley-a29389ffbe68" again
Apr 11 2018 22:26:31.187Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [1.246891185s] 
Apr 11 2018 22:26:31.187Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:111] path "a29389ffbe685455336288f34ddc900c462dab5c2269cf729251795ca613c0d0", force true
Apr 11 2018 22:26:31.187Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsFolder:261] [datastore1] a29389ffbe685455336288f34ddc900c462dab5c2269cf729251795ca613c0d0
Apr 11 2018 22:26:31.244Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [1.258182862s] 
Apr 11 2018 22:26:31.244Z DEBUG op=1910.1: Destroying VM "eager_wright-073b9f7054da"
Apr 11 2018 22:26:31.247Z DEBUG op=1910.1: unexpected soap fault on task retry: types.MethodDisabled{RuntimeFault:types.RuntimeFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}, Source:"VIC"}
Apr 11 2018 22:26:31.248Z DEBUG op=1910.1: Destroy is disabled. Enabling destroy for VM "eager_wright-073b9f7054da"
Apr 11 2018 22:26:31.248Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Apr 11 2018 22:26:31.253Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [4.91517ms] 
Apr 11 2018 22:26:31.253Z DEBUG op=1910.1: Retrying destroy of VM "eager_wright-073b9f7054da" again
Apr 11 2018 22:26:31.307Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsFolder:261] [119.739415ms] [datastore1] a29389ffbe685455336288f34ddc900c462dab5c2269cf729251795ca613c0d0
Apr 11 2018 22:26:31.307Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteFilesIteratively:159] [datastore1] a29389ffbe685455336288f34ddc900c462dab5c2269cf729251795ca613c0d0
Apr 11 2018 22:26:31.307Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVMFSFiles:188] [datastore1] a29389ffbe685455336288f34ddc900c462dab5c2269cf729251795ca613c0d0
Apr 11 2018 22:26:31.328Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [1.345518705s] 
Apr 11 2018 22:26:31.328Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:111] path "073b9f7054daf576c4bd2339ac86356eea61b6c3751a2443c2aab91304e9f17f", force true
Apr 11 2018 22:26:31.328Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsFolder:261] [datastore1] 073b9f7054daf576c4bd2339ac86356eea61b6c3751a2443c2aab91304e9f17f
Apr 11 2018 22:26:31.338Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsFolder:261] [9.977716ms] [datastore1] 073b9f7054daf576c4bd2339ac86356eea61b6c3751a2443c2aab91304e9f17f
Apr 11 2018 22:26:31.338Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteFilesIteratively:159] [datastore1] 073b9f7054daf576c4bd2339ac86356eea61b6c3751a2443c2aab91304e9f17f
Apr 11 2018 22:26:31.338Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVMFSFiles:188] [datastore1] 073b9f7054daf576c4bd2339ac86356eea61b6c3751a2443c2aab91304e9f17f
Apr 11 2018 22:26:31.357Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVMFSFiles:188] [50.282118ms] [datastore1] a29389ffbe685455336288f34ddc900c462dab5c2269cf729251795ca613c0d0
Apr 11 2018 22:26:31.357Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteFilesIteratively:159] [50.395578ms] [datastore1] a29389ffbe685455336288f34ddc900c462dab5c2269cf729251795ca613c0d0
Apr 11 2018 22:26:31.357Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:111] [170.288143ms] path "a29389ffbe685455336288f34ddc900c462dab5c2269cf729251795ca613c0d0", force true
Apr 11 2018 22:26:31.357Z DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).deleteVM:154] [1.831383309s] vm "VirtualMachine:vm-19210", force true
Apr 11 2018 22:26:31.399Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVMFSFiles:188] [61.280116ms] [datastore1] 073b9f7054daf576c4bd2339ac86356eea61b6c3751a2443c2aab91304e9f17f
Apr 11 2018 22:26:31.399Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteFilesIteratively:159] [61.428309ms] [datastore1] 073b9f7054daf576c4bd2339ac86356eea61b6c3751a2443c2aab91304e9f17f
Apr 11 2018 22:26:31.399Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:111] [71.531978ms] path "073b9f7054daf576c4bd2339ac86356eea61b6c3751a2443c2aab91304e9f17f", force true
Apr 11 2018 22:26:31.399Z DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).deleteVM:154] [1.855766751s] vm "VirtualMachine:vm-19209", force true
Apr 11 2018 22:26:31.403Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [1.418148181s] 
Apr 11 2018 22:26:31.403Z DEBUG op=1910.1: Destroying VM "dreamy_boyd-e8e343ae08c5"
Apr 11 2018 22:26:31.405Z DEBUG op=1910.1: unexpected soap fault on task retry: types.MethodDisabled{RuntimeFault:types.RuntimeFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}, Source:"VIC"}
Apr 11 2018 22:26:31.407Z DEBUG op=1910.1: Destroy is disabled. Enabling destroy for VM "dreamy_boyd-e8e343ae08c5"
Apr 11 2018 22:26:31.407Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Apr 11 2018 22:26:31.411Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [4.308323ms] 
Apr 11 2018 22:26:31.411Z DEBUG op=1910.1: Retrying destroy of VM "dreamy_boyd-e8e343ae08c5" again
Apr 11 2018 22:26:31.744Z ERROR op=1910.1: unexpected fault on task retry: &types.InvalidPowerState{InvalidState:types.InvalidState{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}, RequestedState:"poweredOff", ExistingState:"poweredOn"}
Apr 11 2018 22:26:31.746Z ERROR Operation failed with task.Error{LocalizedMethodFault:(*types.LocalizedMethodFault)(0xc4203488c0)}
Apr 11 2018 22:26:31.746Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [1.76435s] 
Apr 11 2018 22:26:31.746Z WARN  op=1910.1: Destroy VM VirtualMachine:vm-19211 failed with The attempted operation cannot be performed in the current state (Powered on)., unregister the VM instead
Apr 11 2018 22:26:31.746Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Apr 11 2018 22:26:31.755Z ERROR Operation failed with soap.soapFaultError{fault:(*soap.Fault)(0xc420466410)}
Apr 11 2018 22:26:31.755Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [8.731973ms] 
Apr 11 2018 22:26:31.755Z ERROR op=1910.1: Unregister the VM failed: ServerFaultCode: The attempted operation cannot be performed in the current state (Powered on).
Apr 11 2018 22:26:31.755Z DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).deleteVM:154] [2.19363392s] vm "VirtualMachine:vm-19211", force true
Apr 11 2018 22:26:31.755Z DEBUG op=1910.1: Error deleting container VMs [ServerFaultCode: The attempted operation cannot be performed in the current state (Powered on).]
Apr 11 2018 22:26:31.755Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).DeleteVCHInstances:220] [2.249741242s] VCH-18274-1262
Apr 11 2018 22:26:31.755Z ERROR op=1910.1: ServerFaultCode: The attempted operation cannot be performed in the current state (Powered on).
Apr 11 2018 22:26:31.755Z WARN  op=1910.1: Proceeding with delete of VCH due to --force
Apr 11 2018 22:26:31.755Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteImages:40]
Apr 11 2018 22:26:31.755Z INFO  op=1910.1: Removing image stores
Apr 11 2018 22:26:31.760Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:111] path "VCH-18274-1262/VIC", force true
Apr 11 2018 22:26:31.760Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsFolder:261] [datastore1] VCH-18274-1262/VIC
Apr 11 2018 22:26:31.772Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsFolder:261] [11.800959ms] [datastore1] VCH-18274-1262/VIC
Apr 11 2018 22:26:31.772Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteFilesIteratively:159] [datastore1] VCH-18274-1262/VIC
Apr 11 2018 22:26:31.772Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVMFSFiles:188] [datastore1] VCH-18274-1262/VIC
Apr 11 2018 22:26:32.167Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVMFSFiles:188] [395.344312ms] [datastore1] VCH-18274-1262/VIC
Apr 11 2018 22:26:32.167Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteFilesIteratively:159] [395.41915ms] [datastore1] VCH-18274-1262/VIC
Apr 11 2018 22:26:32.167Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:111] [407.327836ms] path "VCH-18274-1262/VIC", force true
Apr 11 2018 22:26:32.168Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:111] path "VCH-18274-1262/kvStores", force true
Apr 11 2018 22:26:32.168Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsFolder:261] [datastore1] VCH-18274-1262/kvStores
Apr 11 2018 22:26:32.198Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsFolder:261] [30.407549ms] [datastore1] VCH-18274-1262/kvStores
Apr 11 2018 22:26:32.198Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteFilesIteratively:159] [datastore1] VCH-18274-1262/kvStores
Apr 11 2018 22:26:32.198Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVMFSFiles:188] [datastore1] VCH-18274-1262/kvStores
Apr 11 2018 22:26:32.234Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVMFSFiles:188] [36.028605ms] [datastore1] VCH-18274-1262/kvStores
Apr 11 2018 22:26:32.234Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteFilesIteratively:159] [36.155038ms] [datastore1] VCH-18274-1262/kvStores
Apr 11 2018 22:26:32.234Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:111] [66.706112ms] path "VCH-18274-1262/kvStores", force true
Apr 11 2018 22:26:32.234Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsSubFolder:235] [datastore1] VCH-18274-1262
Apr 11 2018 22:26:32.245Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsSubFolder:235] [10.268507ms] [datastore1] VCH-18274-1262
Apr 11 2018 22:26:32.245Z DEBUG op=1910.1: Image store parent directory not empty, leaving in place. Still contains the following entries: %q[datastore1] VCH-18274-1262/vic-machine_2018-04-11T22:11:21Z_create_1080.1.log, [datastore1] VCH-18274-1262/V1.4.0-DEV-0-1C4E2E2-bootstrap.iso, [datastore1] VCH-18274-1262/V1.4.0-DEV-0-1C4E2E2-appliance.iso, [datastore1] VCH-18274-1262/vmx-VCH-18274-1262-1885116791-1.vswp, [datastore1] VCH-18274-1262/VCH-18274-1262.nvram, [datastore1] VCH-18274-1262/VCH-18274-1262.vmx.lck, [datastore1] VCH-18274-1262/VCH-18274-1262-705c9977.vswp, [datastore1] VCH-18274-1262/VCH-18274-1262.vmxf, [datastore1] VCH-18274-1262/VCH-18274-1262.vmx~, [datastore1] VCH-18274-1262/tether.debug, [datastore1] VCH-18274-1262/VCH-18274-1262.vmx, [datastore1] VCH-18274-1262/VCH-18274-1262-5ac6738b.hlog, [datastore1] VCH-18274-1262/VCH-18274-1262.vmsd, [datastore1] VCH-18274-1262/vmware.log
Apr 11 2018 22:26:32.245Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteImages:40] [489.842911ms] 
Apr 11 2018 22:26:32.245Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVolumeStoreIfForced:317]
Apr 11 2018 22:26:32.245Z INFO  op=1910.1: Removing volume stores
Apr 11 2018 22:26:32.245Z DEBUG op=1910.1: Provided datastore URL: "[datastore1] VCH-18274-1262-VOL"
Apr 11 2018 22:26:32.245Z DEBUG op=1910.1: Parsed volume store path: "VCH-18274-1262-VOL"
Apr 11 2018 22:26:32.245Z INFO  op=1910.1: Deleting volume store "default" on Datastore "datastore1" at path "VCH-18274-1262-VOL"
Apr 11 2018 22:26:32.249Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:111] path "VCH-18274-1262-VOL", force true
Apr 11 2018 22:26:32.249Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsFolder:261] [datastore1] VCH-18274-1262-VOL
Apr 11 2018 22:26:32.261Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsFolder:261] [12.465741ms] [datastore1] VCH-18274-1262-VOL
Apr 11 2018 22:26:32.261Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteFilesIteratively:159] [datastore1] VCH-18274-1262-VOL
Apr 11 2018 22:26:32.261Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVMFSFiles:188] [datastore1] VCH-18274-1262-VOL
Apr 11 2018 22:26:32.289Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVMFSFiles:188] [28.119436ms] [datastore1] VCH-18274-1262-VOL
Apr 11 2018 22:26:32.290Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteFilesIteratively:159] [28.242051ms] [datastore1] VCH-18274-1262-VOL
Apr 11 2018 22:26:32.290Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:111] [40.869645ms] path "VCH-18274-1262-VOL", force true
Apr 11 2018 22:26:32.290Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVolumeStoreIfForced:317] [44.878974ms] 
Apr 11 2018 22:26:32.290Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteNetworkDevices:295] VCH-18274-1262
Apr 11 2018 22:26:32.290Z INFO  op=1910.1: Removing appliance VM network devices
Apr 11 2018 22:26:32.535Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).networkDevices:329]
Apr 11 2018 22:26:32.538Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).networkDevices:329] [2.975966ms] 
Apr 11 2018 22:26:33.767Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteNetworkDevices:295] [1.47772773s] VCH-18274-1262
Apr 11 2018 22:26:33.768Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).removeNetwork:89] VCH-18274-1262
Apr 11 2018 22:26:33.768Z DEBUG op=1910.1: Remove network is not supported for vCenter
Apr 11 2018 22:26:33.768Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).removeNetwork:89] [51.371µs] VCH-18274-1262
Apr 11 2018 22:26:33.768Z DEBUG [BEGIN]  [vic/lib/install/management.(*Dispatcher).deleteVM:154] vm "VirtualMachine:vm-19208", force true
Apr 11 2018 22:26:33.770Z DEBUG [BEGIN] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] VM(VirtualMachine:vm-19208) Properties([config.files.vmPathName])
Apr 11 2018 22:26:33.770Z DEBUG op=1910.1: properties: [config.files.vmPathName summary.runtime.connectionState]
Apr 11 2018 22:26:33.772Z DEBUG [ END ] op=1910.1 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:568] [2.350503ms] VM(VirtualMachine:vm-19208) Properties([config.files.vmPathName])
Apr 11 2018 22:26:33.772Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Apr 11 2018 22:26:33.774Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Apr 11 2018 22:26:33.774Z DEBUG op=1910.1: Getting list of the devices for VM "VCH-18274-1262"
Apr 11 2018 22:26:33.779Z DEBUG op=1910.1: Disk list is empty for VM "VCH-18274-1262"
Apr 11 2018 22:26:33.779Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [4.638272ms] 
Apr 11 2018 22:26:33.779Z DEBUG op=1910.1: Destroying VM "VCH-18274-1262"
Apr 11 2018 22:26:33.780Z DEBUG op=1910.1: unexpected soap fault on task retry: types.MethodDisabled{RuntimeFault:types.RuntimeFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}, Source:"VIC"}
Apr 11 2018 22:26:33.782Z DEBUG op=1910.1: Destroy is disabled. Enabling destroy for VM "VCH-18274-1262"
Apr 11 2018 22:26:33.782Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Apr 11 2018 22:26:33.789Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [6.207709ms] 
Apr 11 2018 22:26:33.789Z DEBUG op=1910.1: Retrying destroy of VM "VCH-18274-1262" again
Apr 11 2018 22:26:34.899Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [1.126837606s] 
Apr 11 2018 22:26:34.899Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:111] path "VCH-18274-1262", force true
Apr 11 2018 22:26:34.899Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsFolder:261] [datastore1] VCH-18274-1262
Apr 11 2018 22:26:34.915Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsFolder:261] [15.429553ms] [datastore1] VCH-18274-1262
Apr 11 2018 22:26:34.915Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteFilesIteratively:159] [datastore1] VCH-18274-1262
Apr 11 2018 22:26:34.915Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVMFSFiles:188] [datastore1] VCH-18274-1262
Apr 11 2018 22:26:34.939Z DEBUG op=1910.1: Failed to delete "[datastore1] VCH-18274-1262": Cannot delete file [datastore1] VCH-18274-1262
Apr 11 2018 22:26:34.939Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVMFSFiles:188] [24.152149ms] [datastore1] VCH-18274-1262
Apr 11 2018 22:26:34.939Z DEBUG op=1910.1: Attempt to delete top level folder [datastore1] VCH-18274-1262 failed. Remove the children files instead.
Apr 11 2018 22:26:34.939Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsSubFolder:235] [datastore1] VCH-18274-1262
Apr 11 2018 22:26:34.958Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).lsSubFolder:235] [18.631624ms] [datastore1] VCH-18274-1262
Apr 11 2018 22:26:34.958Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVMFSFiles:188] [datastore1] VCH-18274-1262/V1.4.0-DEV-0-1C4E2E2-bootstrap.iso
Apr 11 2018 22:26:34.975Z DEBUG op=1910.1: Failed to delete "[datastore1] VCH-18274-1262/V1.4.0-DEV-0-1C4E2E2-bootstrap.iso": Cannot delete file [datastore1] VCH-18274-1262/V1.4.0-DEV-0-1C4E2E2-bootstrap.iso
Apr 11 2018 22:26:34.975Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteVMFSFiles:188] [16.924462ms] [datastore1] VCH-18274-1262/V1.4.0-DEV-0-1C4E2E2-bootstrap.iso
Apr 11 2018 22:26:34.975Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteFilesIteratively:159] [59.984695ms] [datastore1] VCH-18274-1262
Apr 11 2018 22:26:34.975Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).deleteDatastoreFiles:111] [75.605582ms] path "VCH-18274-1262", force true
Apr 11 2018 22:26:34.975Z WARN  op=1910.1: Failed to remove datastore files for VM VirtualMachine:vm-19208 with folder path VCH-18274-1262: Cannot delete file [datastore1] VCH-18274-1262/V1.4.0-DEV-0-1C4E2E2-bootstrap.iso
Apr 11 2018 22:26:34.975Z DEBUG [ END ]  [vic/lib/install/management.(*Dispatcher).deleteVM:154] [1.207386789s] vm "VirtualMachine:vm-19208", force true
Apr 11 2018 22:26:34.977Z DEBUG [BEGIN] op=1910.1 [vic/lib/install/management.(*Dispatcher).destroyResourcePoolIfEmpty:97]
Apr 11 2018 22:26:34.977Z INFO  op=1910.1: Removing Resource Pool "VCH-18274-1262"
Apr 11 2018 22:26:34.979Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).destroyResourcePoolIfEmpty:97] [1.904475ms] 
Apr 11 2018 22:26:34.979Z WARN  op=1910.1: VCH resource pool is not removed: Resource pool is not empty: ""
Apr 11 2018 22:26:34.979Z DEBUG [ END ] op=1910.1 [vic/lib/install/management.(*Dispatcher).DeleteVCH:47] [5.478193631s] VCH-18274-1262
Apr 11 2018 22:26:34.979Z INFO  op=1910.1: ----------
Apr 11 2018 22:26:34.979Z INFO  op=1910.1: If firewall changes were made for VIC during install, they were not reverted during delete
Apr 11 2018 22:26:34.980Z INFO  op=1910.1: To modify firewall rules see vic-machine update firewall --help
Apr 11 2018 22:26:34.980Z INFO  op=1910.1: ----------
Apr 11 2018 22:26:34.980Z INFO  op=1910.1: Completed successfully
```

### PR DESCRIPTION
**Pull request by matthewavery**
fixes #7716 #6079 

Currently, part of the issue surrounding the bootstrap.iso not being removable was due to a container vm still being around that relied upon it. This was caused by an OOB poweron during the forced removal of the VM. Now we will retry the unregister action during a forced removal.

EDIT: 

I have added code to apply the `InvalidPowerState` retry to the destroy action as well. This means that we will try our hardest to power off the vm and then destroy it before attempting the unregister path.

[specific ci=1-40-Docker-Restart --suite Group6-Vic-Machine]

### CODE REVIEW

File: pkg/vsphere/tasks/waiter.go [hunk 1]
```diff
@@ -268,6 +268,23 @@ func IsNotFoundError(err error) bool {
 	return false
 }
 
+func IsInvalidPowerStateError(err error) bool {
```
Comment (matthewavery) [inline pkg/vsphere/tasks/waiter.go]: This function is likely overlycomplicated. But, I do not see a reason not to cover all the bases here. Feel free leave additional thoughts!

File: lib/install/management/appliance.go [hunk 2]
```diff
@@ -181,19 +181,39 @@ func (d *Dispatcher) deleteVM(vm *vm.VirtualMachine, force bool) error {
...
+	retryRemovalError := func(err error) bool {
+		return tasks.IsConcurrentAccessError(err) || tasks.IsInvalidPowerStateError(err)
+	}
+
+	// Only retry VM destroy on ConcurrentAccess error
+	var destroyFirstAttempt bool
 	err = retry.Do(func() error {
+		if !destroyFirstAttempt {
+			d.op.Debugf("detected an OOB powerOn for container (%s) attempting an additional shutdown before removal", vm.Reference().String())
+			vm.PowerOff(d.op)
```
Comment (matthewavery) [inline lib/install/management/appliance.go]: In light of this code. Another path is to stop trying to power everything down right away and move to a power off case by case. Thoughts?

Comment (AngieCris) [reply lib/install/management/appliance.go]: idk how possible this case is, but what if at first attempt, we power off the VM, destroy fails with `ConcurrentAccess`, we retry again after several seconds, an OOB power-on happens during the time. Since it's not first attempt, we go ahead and delete, it fails with `InvalidPowerState` again?
what if we do something like an additional check in the retry function, if it's invalid power state, we power off, otherwise we do nothing

File: lib/install/management/appliance.go [hunk 3]
```diff
@@ -181,19 +181,39 @@ func (d *Dispatcher) deleteVM(vm *vm.VirtualMachine, force bool) error {
 		}
 	}
 
-	// Only retry VM destroy on CurrentAccess error
+	retryRemovalError := func(err error) bool {
+		return tasks.IsConcurrentAccessError(err) || tasks.IsInvalidPowerStateError(err)
+	}
+
+	// Only retry VM destroy on ConcurrentAccess error
```
Comment (AngieCris) [inline lib/install/management/appliance.go]: we might want to remove this comment (and maybe add some comments on why we're retrying on invalid power state I guess)

File: lib/install/management/appliance.go (hunk 2 above)
Comment (AngieCris) [reply lib/install/management/appliance.go]: idk how possible this is, but what if at first attempt, we power off the vm, and later delete fails with `ConcurrentAccess`. Then we retry after several seconds, during which an OOB power on occurred, and second delete fails with `InvalidPowerState`
do we want to do something like a conditional check in the retry function, for ex if the error is `ConcurrentAccess`, we power off the VM, otherwise do nothing

File: pkg/vsphere/tasks/waiter.go [hunk 4]
```diff
@@ -268,6 +268,23 @@ func IsNotFoundError(err error) bool {
...
+		_, ok2 := soap.ToVimFault(err).(*types.InvalidPowerStateFault)
+		return ok1 || ok2
+	}
+
+	if soap.IsSoapFault(err) {
+		_, ok1 := soap.ToSoapFault(err).VimFault().(types.InvalidPowerState)
+		_, ok2 := soap.ToSoapFault(err).VimFault().(types.InvalidPowerStateFault)
+		// sometimes we get the correct fault but wrong type
+		return ok1 || ok2 || soap.ToSoapFault(err).String == "vim.fault.InvalidArgument" ||
+			soap.ToSoapFault(err).String == "vim.fault.InvalidArgumentFault"
```
Comment (zjs) [inline pkg/vsphere/tasks/waiter.go]: `vim.fault.InvalidArgument` and `vim.fault.InvalidArgumentFault` don't seem like the right things to be check for in `IsInvalidPowerStateError`.

File: lib/install/management/appliance.go [hunk 5]
```diff
@@ -181,19 +181,39 @@ func (d *Dispatcher) deleteVM(vm *vm.VirtualMachine, force bool) error {
...
+			if !unregisterFirstAttempt {
+				d.op.Debugf("detected an OOB powerOn for container (%s) attempting an additional shutdown before unregister", vm.Reference().String())
+				// NOTE: ignore the error here. If it is a RuntimeFault then the following unregister will fail as well.
+				vm.PowerOff(d.op)
+			}
+			unregisterFirstAttempt = true
+
 			return vm.Unregister(d.op)
-		}, tasks.IsConcurrentAccessError)
+			// TODO: retry on InvalidPowerState. Unregister does not have the potential to return a ConcurrentAccess return
```
Comment (zjs) [inline lib/install/management/appliance.go]: If `vm.Unregister` can't return a concurrent access error, what about `vm.PowerOff`?

File: pkg/vsphere/tasks/waiter.go (hunk 4 above)
Comment (matthewavery) [reply pkg/vsphere/tasks/waiter.go]: ah thanks... the perils of copy and paste...

File: lib/install/management/appliance.go (hunk 5 above)
Comment (matthewavery) [reply lib/install/management/appliance.go]: I need to remove that comment. In one of the linked tickets there was a log that actually showed us getting a concurrent access error from `vm.unregister` oddly enough that is not listed in the vsphere documentation. I suspect the type for that error return does not show up as `ConcurrentAccessFault`

File: lib/install/management/delete.go [hunk 6]
```diff
@@ -321,7 +321,7 @@ func (d *Dispatcher) DeleteVCHInstances(conf *config.VirtualContainerHostConfigS
 				errs = append(errs, err.Error())
 				mu.Unlock()
 			}
-			d.op.Debugf("Successfully deleted container: %s", child.InventoryPath)
+			d.op.Debugf("Successfully deleted container: %s", child.Reference().String())
```
[the remark this answers is not in the document]
Comment (matthewavery) [reply lib/install/management/delete.go]: This has changed because InventoryPath is often empty. I think `ObjectName` is going to be more reliable, thanks!

File: lib/install/management/appliance.go [hunk 7]
```diff
@@ -181,19 +181,39 @@ func (d *Dispatcher) deleteVM(vm *vm.VirtualMachine, force bool) error {
 		}
 	}
 
-	// Only retry VM destroy on CurrentAccess error
+	retryRemovalError := func(err error) bool {
```
[the remark this answers is not in the document]
Comment (matthewavery) [reply lib/install/management/appliance.go]: very cool :)

File: lib/install/management/delete.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (matthewavery) [reply lib/install/management/delete.go]: Is it worth going back to the property collector to populate the name field of this log message? child.ObjectName will have to go back to vsphere to get the name

[the remark this answers is not in the document]
Comment (matthewavery) [reply lib/install/management/delete.go]: @zjs thoughts on the above?

File: lib/install/management/appliance.go (hunk 5 above)
Comment (matthewavery) [reply lib/install/management/appliance.go]: @zjs so `vm.PowerOff` will return an `InvalidPowerState` fault if the vm is in any other powerstate than `PoweredOn` so it can. But I do not think we should be concerned if the vm.PowerOff returns an InvalidPowerstate so much. We will when we move to doing the additional poweroff in the retry certifier function(comment from @hickeng below). We do need to be careful that we are not retrying on InvalidPowerstate from a PowerOff as it indicates the opposite case of `destroy` and `unregister` and that would then cause a infinite retry loop(until timeout). I was trying to be careful to make sure we did not do that. I will make sure that is still the case after I respond to everyone's comments.

File: lib/install/management/appliance.go (hunk 2 above)
Comment (matthewavery) [reply lib/install/management/appliance.go]: That case is plausible, but in our case what will happen now is that we will retry on the concurrent access and then we will retry on the invalid power state and during the retry decision process attempt to power off the vm again. So that case should be covered now :)

File: pkg/vsphere/vm/vm.go [hunk 8]
```diff
@@ -576,6 +577,24 @@ func (vm *VirtualMachine) IsInvalidState(ctx context.Context) bool {
 	return false
 }
 
+// IsInvalidPowerStateError is a error certifier function for errors coming back from vsphere. It checks for an InvalidPowerStateFault
```
Comment (jzt) [inline pkg/vsphere/vm/vm.go]: s/is a/is an

File: lib/install/management/delete.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (zjs) [reply lib/install/management/delete.go]: If we deleted it, we won't be able to go back and get the name will we?

[the remark this answers is not in the document]
Comment (matthewavery) [reply lib/install/management/delete.go]: hmmm, yeah we should not actually be able to do that. We could get it before hand. I was just curious of the merit of this log line. I am  all for it, but to get the name we are going to have to query vsphere again. I was trying to decide if that was worth it.

[the remark this answers is not in the document]
Comment (matthewavery) [reply lib/install/management/delete.go]: We also log the Reference in most of the other places. which is why I opted for the reference here. Though I agree with @hickeng the reference is almost useless.

[the remark this answers is not in the document]
Comment (zjs) [reply lib/install/management/delete.go]: It looks like `d.deleteVM` already calls `vm.ObjectName` in a few places, mostly for error handling.

I wonder if it'd be easier just to call `vm.ObjectName` once at the beginning of `d.deleteVM`, update the error logging to use that already-retrieved name, and move this success log into `d.deleteVM` where it could use that same name.

(In general, I think there's value in explicitly logging what we've deleted. For example, it makes it easier for someone wondering whether a missing VM was deleted by VIC to verify whether or not that's what happened to it.)
