### PR TITLE
fix NPE in vic-machine caused by vm invalid state error

### LINKED ISSUE #2818: RPC error in docker stop, and eventually, vic-machine delete constantly fail with invalid memory address
Seen in https://ci.vmware.run/vmware/vic/6045 and as a follow on from #2817 

Build https://ci.vmware.run/vmware/vic/6013 left `VCH-6013-4771` and `drunk_englebart-9f1ce9...` behind.

For some reason, all of the `vic-machine delete` operations that occur against that host attempt to delete `drunk_englebart`.
1. They **must not** try to do so as that VM does **not** belong to them - that they are suggests strongly that the SearchIndex is not being used correctly or has a bug.
2. Even if they were to do so, they should not be getting a nil pointer.

```
[34mINFO[0m[2016-10-19T18:09:37Z] Connect to docker:                           
[34mINFO[0m[2016-10-19T18:09:37Z] docker -H dhcp-192-168-31-221.ci.drone.local:2376 --tlsverify --tlscacert="./VCH-6053-1693/ca.pem" --tlscert="./VCH-6053-1693/cert.pem" --tlskey="./VCH-6053-1693/key.pem" info 
[34mINFO[0m[2016-10-19T18:09:37Z] Installer completed successfully             
[34mINFO[0m[2016-10-19T18:09:48Z] ### Removing VCH ####                        
[34mINFO[0m[2016-10-19T18:09:48Z]                                              
[34mINFO[0m[2016-10-19T18:09:48Z] VCH ID: VirtualMachine:2279                  
[34mINFO[0m[2016-10-19T18:09:48Z] Removing VMs                                 
[34mINFO[0m[2016-10-19T18:09:48Z] Removing image stores                        
[34mINFO[0m[2016-10-19T18:09:54Z] Removing volume stores                       
[34mINFO[0m[2016-10-19T18:09:54Z] Deleting volume store "default" on Datastore "datastore1" at path "test" 
[34mINFO[0m[2016-10-19T18:09:54Z] Removing appliance VM network devices        
[34mINFO[0m[2016-10-19T18:09:55Z] Bridge network was not created during VCH deployment, leaving it there 
[34mINFO[0m[2016-10-19T18:09:55Z] Removing Resource Pool "VCH-6053-1693"       
[34mINFO[0m[2016-10-19T18:09:55Z] Completed successfully                       
[34mINFO[0m[2016-10-19T18:09:56Z] ### Removing VCH ####                        
[34mINFO[0m[2016-10-19T18:09:57Z]                                              
[34mINFO[0m[2016-10-19T18:09:57Z] VCH ID: VirtualMachine:1906                  
[34mINFO[0m[2016-10-19T18:09:57Z] Removing VMs                                 
[34mINFO[0m[2016-10-19T18:09:57Z] Delete will attempt to remove datastore files for VM "drunk_engelbart-9f1ce9ea3dd4f8402d5049999af91256c143b0e55cca9f319efa3171a0b4d86e" 
[31mERRO[0m[2016-10-19T18:09:57Z] --------------------                         
[31mERRO[0m[2016-10-19T18:09:57Z] vic-machine-linux failed: runtime error: invalid memory address or nil pointer dereference
```

### PR DESCRIPTION
**Pull request by emlin**
Fixes #2818 
For another kind of invalid state vm, vsphere might return empty vm.Config property, so govmomi will panic for NPE. This is fixed in #2977 
This PR did following changes to fix this kind of failure:
* Override govmomi vm.Properties method in vm.go, and fix the vm if that's in invalid state, cause this function is not enclosed by waitForResult method.
* Fix waitForResult method, to handle non invalid state error, if vm is already in invalid state. This might include RPC send error.
* Update urfave/cli vendor code, cause it does not hide all error stack in latest version.

### CODE REVIEW

File: pkg/vsphere/vm/vm.go [hunk 1]
```diff
@@ -512,23 +525,70 @@ func (vm *VirtualMachine) needsFix(err error) bool {
...
+func (vm *VirtualMachine) Properties(ctx context.Context, r types.ManagedObjectReference, ps []string, o *mo.VirtualMachine) error {
+	log.Debugf("get vm properties %s of vm %s", ps, r)
+	contains := false
+	for i := range ps {
+		if ps[i] == summary {
+			contains = true
+			break
+		}
+	}
+	var newps []string
```
Comment (hmahmood) [inline pkg/vsphere/vm/vm.go]: You can just do (no need for newps)
```go
if !contains {
  ps = append(ps, connectionStatus)
}
```

File: pkg/vsphere/vm/vm.go [hunk 2]
```diff
@@ -512,23 +525,70 @@ func (vm *VirtualMachine) needsFix(err error) bool {
...
+	if !contains {
+		newps = append(ps, connectionStatus)
```
Comment (hmahmood) [inline pkg/vsphere/vm/vm.go]: You are checking for `summary` above, but then appending on `connectionStatus` here? Also, the constant names are less intuitive than the actual strings; makes the code a little less readable imo.

File: pkg/vsphere/vm/vm.go (hunk 1 above)
Comment (emlin) [inline pkg/vsphere/vm/vm.go]: this is because I need to double check properties, and the next time, I don't need to add new properties. So I kept the old variable.

File: vendor/manifest [hunk 3]
```diff
@@ -888,6 +888,14 @@
 			"branch": "v1"
 		},
 		{
+			"importpath": "gopkg.in/urfave/cli.v1",
+			"repository": "https://gopkg.in/urfave/cli.v1",
```
Comment (hmahmood) [inline vendor/manifest]: Where are we using this?

File: pkg/vsphere/vm/vm.go (hunk 2 above)
Comment (emlin) [inline pkg/vsphere/vm/vm.go]: any suggestion on the name?

File: vendor/manifest (hunk 3 above)
Comment (emlin) [inline vendor/manifest]: I searched the urfave/cli code, itself has this dependency, so I assume I cannot remove this directory simply.

Comment (dougm) [inline vendor/manifest]: Looks like we should be using "gopkg.in/urfave/cli.v1" as the import path in our own code to avoid the duplicate vendoring of this package.  If the NPE fix doesn't depend on updating this dependency, maybe the vendor update + import path change could be done in a separate PR?

File: pkg/vsphere/vm/vm.go [hunk 4]
```diff
@@ -458,18 +471,18 @@ func (vm *VirtualMachine) registerVM(ctx context.Context, path, name string,
...
+func (vm *VirtualMachine) fixVM(ctx context.Context) error {
 	log.Debugf("Fix invalid state VM: %s", vm.Reference())
 	folders, err := vm.Session.Datacenter.Folders(ctx)
 	if err != nil {
 		log.Errorf("Unable to get vm folder: %s", err)
 		return err
 	}
 
-	properties := []string{"config.files", "summary.config", "summary.runtime", "resourcePool", "parentVApp"}
+	properties := []string{"summary.config", "summary.runtime", "resourcePool", "parentVApp"}
```
Comment (dougm) [inline pkg/vsphere/vm/vm.go]: While you're in there, looks like we only use Runtime.Host here, maybe limit that to "summary.runtime.host".

File: vendor/manifest (hunk 3 above)
Comment (emlin) [inline vendor/manifest]: Not directly related, just to improve the capability to print out NPE. I can separate it.

File: pkg/vsphere/vm/vm.go (hunk 2 above)
Comment (hmahmood) [inline pkg/vsphere/vm/vm.go]: I would not use the constants.

File: pkg/vsphere/vm/vm.go (hunk 1 above)
Comment (hickeng) [inline pkg/vsphere/vm/vm.go]: Do we actually need to check? What happens if we append "summary.runtime.connectionState" every time, irrespective of whether it's present already?

File: pkg/vsphere/vm/vm_test.go [hunk 5]
```diff
@@ -190,6 +191,13 @@ func TestVM(t *testing.T) {
 		t.Errorf("Failed to find fixed vm: %s", err)
 	}
 	assert.Equal(t, vm.Reference(), newVM.Reference())
+
+	// VM properties
+	var ovm mo.VirtualMachine
```
Comment (hickeng) [inline pkg/vsphere/vm/vm_test.go]: This is exactly the sort of test where we should be using vcsim to return InvalidState - @dougm is there an easy way to do this fault injection?

Comment (emlin) [inline pkg/vsphere/vm/vm_test.go]: @dougm the registervm methods are folder method or vApp method, how to inject the folder or vApp in simulator?

File: pkg/vsphere/vm/vm.go (hunk 1 above)
Comment (emlin) [inline pkg/vsphere/vm/vm.go]: It doesn't matter to query duplicated properties, but as we're trying to make minimum properties query each time, it will help to reduce the array length.
And I think this array length is really short based on our current coding practice, I assume it doesn't hurt to loop that array.

File: pkg/vsphere/vm/vm_test.go (hunk 5 above)
Comment (dougm) [inline pkg/vsphere/vm/vm_test.go]: Added Register/Unregister: https://github.com/vmware/vic/pull/3068

**Comment by emlin** [comment]
Changed fixed vm condition in WaitForResult for #2958

File: pkg/vsphere/vm/vm_test.go [hunk 6]
```diff
@@ -436,3 +446,145 @@ func TestBfsSnapshotTree(t *testing.T) {
...
+	// Test the success path
+	var o mo.VirtualMachine
+	err = vmm.Properties(ctx, vmo.Reference(), []string{"config", "summary", "resourcePool", "parentVApp"}, &o)
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	//	// Inject invalid connection state to vm
+	ref := simulator.Map.Get(vmo.Reference()).(*simulator.VirtualMachine)
+	ref.Summary.Config.VmPathName = "[LocalDS_0] ha-host_VM0/ha-host_VM0.vmx"
```
Comment (dougm) [inline pkg/vsphere/vm/vm_test.go]: Looks like we need to set that field in vcsim.  You can also use this for now, rather than the hardcoded string:
`ref.Config.Files.VmPathName`

**Comment by dougm** [comment]
lgtm

File: pkg/vsphere/vm/vm_test.go (hunk 6 above)
Comment (emlin) [inline pkg/vsphere/vm/vm_test.go]: good

**Comment by emlin** [comment]
lgtm
