### PR TITLE
Sync cache after out-of-band container removal

### LINKED ISSUE #1640: portlayer error code for "already deleted or not completely created" and personality handling
I was compelled to delete some container VMs directly due to out-of-disk issues - this resulted in an inconsistent state between VC, portlayer and personality.

```
vagrant@devbox:~$ docker -H 192.168.78.216:2376 --tls create --net=front-tier --link=cat:enemy --name=dog -it busybox
8808d6cea58596780070a2504d7ea67f51d0c79909dbdf1a39f5ed779990ce7c
vagrant@devbox:~$ docker -H 192.168.78.216:2376 --tls network connect back-tier dog
vagrant@devbox:~$ docker -H 192.168.78.216:2376 --tls start -ai dog
Error response from daemon: server error from portlayer : Operation failed: Insufficient resources. - (&{{} %!s(*types.InsufficientResourcesFault=&{{{<nil> [{{} msg.vmk.status.VMK_NO_RESOURCES [] Out of resources}]}}}) Insufficient resources.})

# <deleted dog VM here>

vagrant@devbox:~$ docker -H 192.168.78.216:2376 --tls start -ai dog
Error: No such container: dog
vagrant@devbox:~$ docker -H 192.168.78.216:2376 --tls create --net=front-tier --link=cat:enemy --name=dog -it busybox
Error response from daemon: Conflict. The name "dog" is already in use by container 8808d6cea58596780070a2504d7ea67f51d0c79909dbdf1a39f5ed779990ce7c. You have to remove (or rename) that container to be able to re use that name.
vagrant@devbox:~$ docker -H 192.168.78.216:2376 --tls start -ai dog
Error: No such container: dog
vagrant@devbox:~$ docker -H 192.168.78.216:2376 --tls rm dog
Error response from daemon: server error from portlayer : [DELETE /containers/{id}][500] containerRemoveInternalServerError
vagrant@devbox:~$ docker -H 192.168.78.216:2376 --tls rm dog
Error response from daemon: server error from portlayer : [DELETE /containers/{id}][500] containerRemoveInternalServerError
vagrant@devbox:~$ docker -H 192.168.78.216:2376 --tls create --net=front-tier --link=cat:enemy --name=dog -it busybox
Error response from daemon: Conflict. The name "dog" is already in use by container 8808d6cea58596780070a2504d7ea67f51d0c79909dbdf1a39f5ed779990ce7c. You have to remove (or rename) that container to be able to re use that name.
```

As can be seen I tried several times to see if repeated invocation would result in different behaviour, but it does not.

The port layer is reporting:
```
time="2016-07-17T19:41:44Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerInfoHandler] Containers.GetContainerInfoHandler" 
time="2016-07-17T19:41:44Z" level=debug msg="GetContainerInfoHandler Error: ServerFaultCode: The object has already been deleted or has not been completely created" 
time="2016-07-17T19:41:44Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerInfoHandler] [3.097715ms] Containers.GetContainerInfoHandler" 
```

and personality:
```
time="2016-07-17T19:42:04Z" level=debug msg="[BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerRm] ContainerRm" 
time="2016-07-17T19:42:04Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerRm] [3.689814ms] ContainerRm" 
time="2016-07-17T19:42:04Z" level=error msg="Handler for DELETE /v1.23/containers/dog returned error: server error from portlayer : [DELETE /containers/{id}][500] containerRemoveInternalServerError " 
```

In this case the port-layer should return _410 Gone_ or _404_ and the personality should recognise a 410/404 and remove any entries from it's cache.

There should also be a vcsim test added for this scenario

[logs (2).tar.gz](https://github.com/vmware/vic/files/380828/logs.2.tar.gz)

### PR DESCRIPTION
**Pull request by jzt**
This syncs the persona cache when it is learned that a container has been removed by an out-of-band process, such as VC.

Fixes #1640

### CODE REVIEW

**Comment by dougm** [comment]
lgtm

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

File: lib/apiservers/engine/backends/container.go [hunk 1]
```diff
@@ -411,7 +419,8 @@ func (c *Container) ContainerRm(name string, config *types.ContainerRmConfig) er
 	if err != nil {
 		switch err := err.(type) {
 		case *containers.ContainerRemoveNotFound:
-			return derr.NewRequestNotFoundError(fmt.Errorf("No such container: %s", name))
+			cache.ContainerCache().DeleteContainer(name)
+			return derr.NewRequestNotFoundError(fmt.Errorf("No such container: %s", paramName))
```
Comment (hickeng) [inline lib/apiservers/engine/backends/container.go]: Doesn't need to be for this PR, but we should really move "No such container" and similar strings that are repeated in many locations into the message catalogue.

File: lib/apiservers/portlayer/restapi/handlers/containers_handlers.go [hunk 2]
```diff
@@ -217,14 +217,21 @@ func (handler *ContainersHandlersImpl) CommitHandler(params containers.CommitPar
...
 	cID := exec.ParseID(params.ID)
 	h := exec.GetContainer(cID)
 	if h == nil {
 		return containers.NewContainerRemoveNotFound()
 	}
 
-	err := h.Container.Remove(context.Background(), handler.handlerCtx.Session)
+	// make sure the container exists - it may still be cached but it may have
+	// been removed out-of-band on the backend
+	_, err := exec.ContainerInfo(context.Background(), handler.handlerCtx.Session, cID)
```
Comment (hickeng) [inline lib/apiservers/portlayer/restapi/handlers/containers_handlers.go]: Is this necessary or can we check the return from Remove for NotFound? There's always going to be a timing hole here in between checking it exists, calling remove and the remove actually being dispatched.

Comment (jzt) [inline lib/apiservers/portlayer/restapi/handlers/containers_handlers.go]: Fixed!

**Comment by jzt** [comment]
I will merge this once local integration tests are finished running.

**Comment by caglar10ur** [comment]
oh so next year :trollface:

**Comment by jzt** [comment]
♻️
