### PR TITLE
[specific ci=1-04-Docker-Create] Add default (empty) HostConfig if it is nil when validating ContainerCreateConfig

### LINKED ISSUE #2557: NetworkMode overwrites NetworkingConfig and cannot be omitted
I am trying to create a network via docker remote API on VIC and also attach some containers to this network during the network creation. In docker, there are two ways to achieve this: the old one is specifying the name of the network as a value for the **NetworkMode** property and the new one is providing a **NetworkingConfig**. These are also available on VIC, but there are a few major differences from traditional docker:
- If **NetworkingConfig** is provided, **NetworkMode** cannot be ommited on VIC. This is not the case on Docker
- If **NetworkMode** is provided along with **NetworkingConfig**, **NetworkMode** will overwrite the provided configuration if its value differes from a network name. This means that if I specify `NetworkMode: bridge`, it doesn't matter what networks I will specify in the **NetworkingConfig**, they will be ignored and the container will be attached to the **bridge** network only
- Providing `NetworkMode: null` is the same as providing `NetworkMode: bridge`

**VIC Version:** Jfrog bintray build 5316

**Code on Docker**

``` bash
# Create a network
curl --unix-socket /var/run/docker.sock  -H "Content-Type: application/json" -d '{"Name": "alp-network"}' https:/networks/create
# {"Id":"ac7ffb0ce6dd980f283917e0fa5d362c07fb7a85b48cef303274af9f7bd1196e","Warning":""}

# Create a container. Provide only NetworkMode
curl --unix-socket /var/run/docker.sock  -H "Content-Type: application/json" -d '{"Image": "alpine", "Cmd": ["ping", "127.0.0.1"], "NetworkMode": "alp-network"}' http:/containers/create?name=test-alp-1
# {"Id":"35eba84af142580fb7ba0b61e8e09e5e8d98f44953ccf6429467509dd6c2c54c","Warnings":null}

# Create a container. Specify only NetworkingConfig
curl --unix-socket /var/run/docker.sock  -H "Content-Type: application/json" -d '{"Image": "alpine", "Cmd": ["ping", "127.0.0.1"], "NetworkingConfig": {"EndpointsConfig": {"alp-network": {} } } }' http:/containers/create?name=test-alp-2
# {"Id":"dcd6d8283a3ebc011a1ae82563723143f5b78faafeaf9c7b0702bdcc94231c7a","Warnings":null}

# Create a container. Specify both properties. NetworkMode is the name of the network
curl --unix-socket /var/run/docker.sock  -H "Content-Type: application/json" -d '{"Image": "alpine", "Cmd": ["ping", "127.0.0.1"], "NetworkMode": "alp-network", "NetworkingConfig": {"EndpointsConfig": {"alp-network": {} } } }' http:/containers/create?name=test-alp-3
# {"Id":"f3ef93d4229b7514b07dc7da20bab1653dae0b9b24bfb7707ab644d15782562e","Warnings":null}

# Create a container. Specify both properties. NetworMode is bridge
curl --unix-socket /var/run/docker.sock  -H "Content-Type: application/json" -d '{"Image": "alpine", "Cmd": ["ping", "127.0.0.1"], "NetworkMode": "bridge", "NetworkingConfig": {"EndpointsConfig": {"alp-network": {} } } }' https:/containers/create?name=alp-4
# {"Id":"1b1a163eb303ba476aecce876c02c8798b73ebdc9f890032c8b3a991ef8ef01f","Warnings":null}

# Start all the containers with successive docker start commands
```

**Code on VIC**

``` bash
# Create a network:
curl --insecure --cert cert.pem --key key.pem -H "Content-Type: application/json" -d '{"Name": "alp-network"}' https://$IP:2376/networks/create
# {"Id":"7951d04936d187053bafa9bed70a1a2ca235dfcfbfd1a458f2d94156a5f0695c","Warning":""}

# Create a container. Provide only NetworkMode
curl --insecure --cert cert.pem --key key.pem -H "Content-Type: application/json" -d '{"Image": "alpine", "Cmd": ["ping", "127.0.0.1"], "NetworkMode": "alp-network"}' https://$IP:2376/containers/create?name=alp-1
# {"Id":"23c23adf83a0230be2219994c26b387b7e110584a229060cbe6a95283611572a","Warnings":null}

# Create a container. Specify only NetworkingConfig
curl --insecure --cert cert.pem --key key.pem -H "Content-Type: application/json" -d '{"Image": "alpine", "Cmd": ["ping", "127.0.0.1"], "NetworkingConfig": {"EndpointsConfig": {"alp-network": {} } } }' https://$IP:2376/containers/create?name=alp-2
# Bad request error from portlayer: invalid config

# Create a container. Specify both properties. NetworkMode is the name of the network
curl --insecure --cert cert.pem --key key.pem -H "Content-Type: application/json" -d '{"Image": "alpine", "Cmd": ["ping", "127.0.0.1"], "NetworkMode": "alp-network", "NetworkingConfig": {"EndpointsConfig": {"alp-network": {} } } }' https://$IP:2376/containers/create?name=alp-3
# {"Id":"0aa7c2fc2a687d70e2e8e0debd929004c75827fd6a702a28d4d172d68b82b253","Warnings":null}

# Create a container. Specify both properties. NetworMode is bridge
curl --insecure --cert cert.pem --key key.pem -H "Content-Type: application/json" -d '{"Image": "alpine", "Cmd": ["ping", "127.0.0.1"], "NetworkMode": "bridge", "NetworkingConfig": {"EndpointsConfig": {"alp-network": {} } } }' https://$IP:2376/containers/create?name=alp-4
# {"Id":"4a4dbc11ab1b9f6ba3bbcae7b7851438b9b6c682a9a52c594920143183305c16","Warnings":null}

# Start all the containers with successive docker start commands
```

**Expected behavior:**
4 containers, created, then started, all of them connected to the created `alp-network`. This is the output of the `docker network inspect` command on Docker host:

``` bash
docker network inspect alp-network
[
    {
        "Name": "alp-network",
        "Id": "ac7ffb0ce6dd980f283917e0fa5d362c07fb7a85b48cef303274af9f7bd1196e",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "1b1a163eb303ba476aecce876c02c8798b73ebdc9f890032c8b3a991ef8ef01f": {
                "Name": "alp-4",
                "EndpointID": "93cb10f3bd2a825a913a37c0f0f6f7fff86f2371e10c95d6d603bcb1b8780bb8",
                "MacAddress": "02:42:ac:12:00:05",
                "IPv4Address": "172.18.0.5/16",
                "IPv6Address": ""
            },
            "35eba84af142580fb7ba0b61e8e09e5e8d98f44953ccf6429467509dd6c2c54c": {
                "Name": "test-alp-1",
                "EndpointID": "0645749ac7a4ddfc92b437826a500996797a380fbdc573c596a91f6d689736df",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "dcd6d8283a3ebc011a1ae82563723143f5b78faafeaf9c7b0702bdcc94231c7a": {
                "Name": "test-alp-2",
                "EndpointID": "b849ae57568544621382ad701aed3309c54e7f08937a531770058f0b88dea591",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "f3ef93d4229b7514b07dc7da20bab1653dae0b9b24bfb7707ab644d15782562e": {
                "Name": "test-alp-3",
                "EndpointID": "01ecc716d49ecc7a9b3192c871c790f110538f9cd85265f033f34f616d255985",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

**Actual behavior:**
Only three containers are created (alp-2 creation failed), only two of them are connected to the created network, the last one is connected to bridge:

``` bash
# alp-network:
 docker --tls network inspect alp-network
[
    {
        "Name": "alp-network",
        "Id": "7951d04936d187053bafa9bed70a1a2ca235dfcfbfd1a458f2d94156a5f0695c",
        "Scope": "",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "0aa7c2fc2a687d70e2e8e0debd929004c75827fd6a702a28d4d172d68b82b253": {
                "Name": "alp-3",
                "EndpointID": "0aa7c2fc2a687d70e2e8e0debd929004c75827fd6a702a28d4d172d68b82b253",
                "MacAddress": "",
                "IPv4Address": "172.17.0.3/16",
                "IPv6Address": ""
            },
            "682534adcef9444730f2eb6d24e3ca4c34267f5a612be93db5ae7a4118856e08": {
                "Name": "alp-1",
                "EndpointID": "682534adcef9444730f2eb6d24e3ca4c34267f5a612be93db5ae7a4118856e08",
                "MacAddress": "",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            },
        },
        "Options": {},
        "Labels": {}
    }
]

# bridge network
docker --tls network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "f8bcd3c67f4741106b30462c3b4c026adf984d9f42e55c6c980f68fb85f2b727",
        "Scope": "",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.16.0.0/16",
                    "Gateway": "172.16.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "4a4dbc11ab1b9f6ba3bbcae7b7851438b9b6c682a9a52c594920143183305c16": {
                "Name": "alp-4",
                "EndpointID": "4a4dbc11ab1b9f6ba3bbcae7b7851438b9b6c682a9a52c594920143183305c16",
                "MacAddress": "",
                "IPv4Address": "172.16.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

### PR DESCRIPTION
**Pull request by chengwang86**
This is needed when the client request is sent via docker rest api call without specifying HostConfig in the form data. See examples in #2557. 

Fixes #2557 and #3709.

### CODE REVIEW

File: lib/apiservers/engine/backends/container.go [hunk 1]
```diff
@@ -1405,41 +1406,43 @@ func validateCreateConfig(config *types.ContainerCreateConfig) error {
...
 			}
+
+			start, end, _ := nat.ParsePortRangeToInt(pb.HostPort)
+			if start != end {
+				return InternalServerError("host port ranges are not supported for port bindings")
+			}
 		}
 	}
 
+	if config.Config == nil {
```
Comment (vburenin) [inline lib/apiservers/engine/backends/container.go]: Would it make sense to run this check at the beginning of this method?

Comment (chengwang86) [inline lib/apiservers/engine/backends/container.go]: I can do the check at the beginning, but I find that all the subsequent checks for config.Config.XXX are right below the current line. So I thought it might be better to move "if config.Config == nil" and "if config.Config.XXX" closer to each other.

Comment (anchal-agrawal) [inline lib/apiservers/engine/backends/container.go]: I concur with @vburenin's suggestion - it's nice to error out early and avoid unnecessary computation in the error case.

**Comment by sflxn** [comment]
lgtm.  Please squash the commits before merging.

File: tests/test-cases/Group1-Docker-Commands/1-04-Docker-Create.robot [hunk 2]
```diff
@@ -162,3 +162,8 @@ Create a container with custom amount of memory in Bytes
     ${rc}  ${output}=  Run Keyword If  '%{HOST_TYPE}' == 'ESXi'  Run And Return Rc And Output  govc vm.info ${id} |awk '/Memory:/ {print $2}'
     Run Keyword If  '%{HOST_TYPE}' == 'ESXi'  Should Be Equal As Integers  ${rc}  0
     Run Keyword If  '%{HOST_TYPE}' == 'ESXi'  Should Contain  ${output}  2048MB
+
+Create a container using rest api call without HostConfig in the form data
+    ${output}=  Run  curl -sk --cert %{DOCKER_CERT_PATH}/cert.pem --key %{DOCKER_CERT_PATH}/key.pem -H "Content-Type: application/json" -d '{"Image": "busybox", "Cmd": ["ping", "127.0.0.1"], "NetworkMode": "bridge"}' https://%{VCH-IP}:2376/containers/create
+    Log To Console  ${output}
```
Comment (mhagen-vmware) [inline tests/test-cases/Group1-Docker-Commands/1-04-Docker-Create.robot]: We don't want to log this to console.  Just use   Log  ${output}
