### PR TITLE
Return an invalid login to login page

### LINKED ISSUE #3564: Not friendly authentication error screen
# Actual
Entering wrong credentials ended up with this screen on vic-admin page.

image

# Expected

User should be returned to a login page.

### PR DESCRIPTION
**Pull request by sgairo**
Fixes #3564 
failedlogin

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
@sgairo Can you post a mockup of the failed login page?

File: cmd/vicadmin/server.go [hunk 1]
```diff
@@ -265,6 +266,7 @@ func (s *server) Authenticated(link string, handler func(http.ResponseWriter, *h
 // renders the page for login and handles authorization requests
 func (s *server) loginPage(res http.ResponseWriter, req *http.Request) {
 	defer trace.End(trace.Begin(""))
+	var invalidLoginMessage = ""
```
Comment (anchal-agrawal) [inline cmd/vicadmin/server.go]:
```go
var invalidLoginMessage string
```
or
```go
invalidLoginMessage := ""
```

are canonical ways.
