### PR TITLE
Blend dynamic and static hostfile entries and fix DHCP config

### LINKED ISSUE #6515: Assigning container network IP via DHCP causes /etc/hosts customisation to revert
VIC Engine - vic_1.2.1-rc2, vic_1.2.1

User statement: As a customer of VIC, I would like to set custom entries in /etc/hosts due to application expectations.

Details: Current versions do not implement run --add-host. However, this is tweaked using a workaround; refer https://github.com/vmware/vic/issues/4195#issuecomment-285645969. You may also refer #5833 .

Issue Description: This worked fine so long as the VCH was built with --cnr <range>. However, switching to DHCP fails this immediately. /etc/hosts are reverted to original within few seconds of editing.

Easily reproducible. Refer screenshot.

image

@hickeng

### PR DESCRIPTION
**Pull request by hickeng**
* Allow a user to construct a base /etc/hosts for a container and have those entries blended
with entries generated by tether.
* Update the base set of addresses with some common entries and supports multiple occurrences of a hostname if split across IPv4 and IPv6 addresses.
* Retry DHCP lease renewal on error
* Add iptables rule for DHCP when needed
* Populate `docker ps` output with correct IP address to reflect ports published via container network

TODO:
- [ ] public/private IP transition which breaks from alias set - this is not actually needed at this time so skipping
- [x] complete unit tests
- [x] add robot test
- [x] consider when we should display IP addresses for container-network other than with -p - for the moment I've decided not to provide it in other scenarios; the only one that's really applicable is Open firewall and there we'd have to somehow omit the ports.

Additional work for the port forwarding:
- associate forwarded ports with an external scope network irrespective of network connect ordering (see #5776) so long as network is configured with Published or Open trust levels. Not going to be in this PR.

Fixes #6515

### CODE REVIEW

File: lib/etcconf/hosts.go [hunk 1]
```diff
@@ -163,31 +208,110 @@ func (h *hosts) SetHost(hostname string, ip net.IP) {
...
+
+	if hentry != nil {
+		// existing entry with no changes
+		if bytes.Equal(hentry.IP, ip) {
+			h.dirty = false
+			return
+		}
+
+		// existing hostname with a new address - change address for all assocated hostnames
+		hentry.setAddress(ip)
```
Comment (hmahmood) [inline lib/etcconf/hosts.go]: Why not just remove the host from the entry instead since it is associated with a different IP?

Comment (hickeng) [reply lib/etcconf/hosts.go]: because someone may have entered an extra host alias for this entry.
For example if you have the following entry:
```
10.118.20.236 container-network.localnet my-custom-alias-for-app
```
and the DHCP lease changes, then you can either:
a. edit the IP address (what this change does)
b. create a new entry and move _some_ of the hosts

So our choices are:
```
# edit the IP
10.118.22.33 container-network.localnet my-custom-alias-for-app
```
or
```
# split the entry
10.118.20.236 my-custom-alias-for-app
10.118.22.33 container-network.localnet
```

In the latter case we've likely broken some assumptions and quite possibly are still referencing an address that no longer belongs to that container.

File: tests/resources/VCH-Util.robot [hunk 2]
```diff
@@ -190,11 +190,11 @@ Install VIC Appliance To Test Server
...
+    ${output}=  Run Keyword Unless  ${certs}  Run  ${vic-machine} create --debug ${debug} --name=%{VCH-NAME} --target=%{TEST_URL}%{TEST_DATACENTER} --thumbprint=%{TEST_THUMBPRINT} --user=%{TEST_USERNAME} --image-store=%{TEST_DATASTORE} --appliance-iso=${appliance-iso} --bootstrap-iso=${bootstrap-iso} --password=%{TEST_PASSWORD} --force=true --bridge-network=%{BRIDGE_NETWORK} --public-network=%{PUBLIC_NETWORK} --compute-resource=%{TEST_RESOURCE} --timeout %{TEST_TIMEOUT} --insecure-registry harbor.ci.drone.local --volume-store=%{TEST_DATASTORE}/%{VCH-NAME}-VOL:${vol} --container-network=%{PUBLIC_NETWORK}:public --no-tlsverify ${additional-args}
```
Comment (mhagen-vmware) [inline tests/resources/VCH-Util.robot]: IDK if we want to specify container network as the default for all of our tests?  Is this really the recommended operation for all of our users now?

File: tests/test-cases/Group0-Bugs/6515.robot [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+    ${rc}  ${output}=  Run And Return Rc And Output  docker %{VCH-PARAMS} cp ${CURDIR}/6515.resource ${id}:/etc/hosts
+    Should Be Equal As Integers  ${rc}  0
+
+    ${rc}=  Run And Return Rc  docker %{VCH-PARAMS} start ${name}
+    Should Be Equal As Integers  ${rc}  0
+
+    ${rc}  ${hosts}=  Run And Return Rc And Output  docker %{VCH-PARAMS} exec ${id} cat /etc/hosts
+    Should Be Equal As Integers  ${rc}  0
+    Log  ${hosts}
+    Should Contain  ${hosts}  robot-test-alias
```
Comment (mhagen-vmware) [inline tests/test-cases/Group0-Bugs/6515.robot]: Can we throw in a docker restart and cat /etc/hosts again as well?

File: tests/resources/VCH-Util.robot (hunk 2 above)
Comment (hickeng) [reply tests/resources/VCH-Util.robot]: Using a container network has _always_ been the recommended mechanism for exposing services. Port forwarding via the endpointVM is purely for docker compatibility.
I figure that adding a container network to our default install at least makes it easier to write tests that reflect that usage.
