### PR TITLE
Nat for udp

### LINKED ISSUE #8573: UDP port cannot be exposed
#### Summary

Creating DNSCrypt-proxy container. Connect by Bridge network. 
Use DNS client with containerized dnscrypt-proxy server.

Need to expose ports 8053/TCP and 8053/UDP. From VIC HTTP interface cannot choose protocol at all. Only Port number can be entered. When port number is entered and container started one can see that only TCP port is exposed.

#### Environment information

Container: dnscrypt-proxy.

##### vSphere and vCenter Server version

ESXI 6.7U1 HP
VCenter 6.7U1
##### VIC version

vic-v1.5.3-7511-ba6b1644.ova
Have tested on 1.5.2 - same effect.
#### Details

Used Dockerfile
`FROM golang:1.11-alpine3.8 as build`

`ENV RELEASE_TAG 2.0.17`
`RUN apk --no-cache add git && \`
`    git clone https://github.com/jedisct1/dnscrypt-proxy /go/src/github.com/jedisct1/ && \`
`    cd /go/src/github.com/jedisct1/dnscrypt-proxy && \`
`    git checkout tags/${RELEASE_TAG} && \`
`    CGO_ENABLED=0 GOOS=linux go install -a -ldflags '-s -w -extldflags "-static"' -v ./...`

`FROM alpine:3.8`

`RUN apk --no-cache add ca-certificates`
`COPY --from=build /go/bin/dnscrypt-proxy /usr/local/bin/dnscrypt-proxy`
`ADD config /config`

`EXPOSE 53/udp`
`EXPOSE 53/tcp`

`CMD ["dnscrypt-proxy", "-config", "/config/dnscrypt-proxy.toml"]`

##### Steps to reproduce
Create container dnscrypt-proxy.
Connect to Brudge network.
Expose configured UDP and TCP ports.
Use VCH address and exposed port to resolv something.

##### Actual behavior

DNS doesn't work on UDP. Work like a charm on TCP.

##### Expected behavior
Resolving must work on exposed UDP port

#### Logs 
[menv@methone ~]$ dig google.com @192.168.160.86 -p 8053

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7 <<>> google.com @192.168.160.86 -p 8053
;; global options: +cmd
;; connection timed out; no servers could be reached

[menv@methone ~]$ dig google.com @192.168.160.86 -p 8053 +tcp

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7 <<>> google.com @192.168.160.86 -p 8053 +tcp
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6782
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1452
; OPT=12: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.) (.)
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             2       IN      A       172.217.20.46

;; Query time: 116 msec
;; SERVER: 192.168.160.86#8053(192.168.160.86)
;; WHEN: Tue Jul 23 23:42:12 MSK 2019
;; MSG SIZE  rcvd: 128

#### Troubleshooting attempted

- [ ] Searched [GitHub][issues] for existing issues. (Mention any similar issues under "See also", above.)
- [ ] Searched the [documentation][docs] for relevant troubleshooting guidance.
- [ ] Searched for a relevant [VMware KB article][kb].

[issues]:https://github.com/vmware/vic/issues
[docs]:https://vmware.github.io/vic-product/#documentation
[kb]:https://kb.vmware.com/s/global-search/%40uri#t=Knowledge&sort=relevancy&f:@commonproduct=[vSphere%20Integrated%20Containers]

### PR DESCRIPTION
**Pull request by yuyangbj**
Fixes #8573 
[specific ci=1-10-Docker-PS]

### CODE REVIEW

File: lib/apiservers/engine/backends/portmap/portmap.go [hunk 1]
```diff
@@ -82,10 +88,23 @@ func (p *portMapper) isPortAvailable(proto string, ip net.IP, port int) bool {
 		}
 	}()
 
-	if err != nil {
+	if err != nil && proto == "tcp" {
 		return true
 	}
 
+	if proto == "udp" {
```
Comment (wjun) [inline lib/apiservers/engine/backends/portmap/portmap.go]: It looks net.Dail cannot detect if a udp port is in use by checking the error?
