### PR TITLE
Remove user credentials from vicadmin.log upon failed login

### LINKED ISSUE #3550: Correct vicadmin.log from showing user/pass information in log

### PR DESCRIPTION
**Pull request by sgairo**
Fixes #3550 
Logs client ip upon failed authentication and client ip with user information upon successful authentication.

### CODE REVIEW

File: cmd/vicadmin/server.go [hunk 1]
```diff
@@ -287,12 +287,13 @@ func (s *server) loginPage(res http.ResponseWriter, req *http.Request) {
...
 			// something went wrong or we could not authenticate
-			log.Warnf("User %s from %s failed to authenticate at %s", userconfig.User, req.RemoteAddr, time.Now())
+			log.Warnf("%s failed to authenticate at %s", req.RemoteAddr, time.Now())
 			http.Error(res, "Authentication failed due to incorrect credential(s)", http.StatusUnauthorized)
 			return
 		}
 
-		// successful login above; user is authenticated
+		// successful login above; user is authenticated, reported for audit purposed
+		log.Infof("User %s from %s was successfully to authenticated at %s", userconfig.User, req.RemoteAddr, time.Now())
```
Comment (anchal-agrawal) [inline cmd/vicadmin/server.go]: `userconfig.User` contains the username and password from the HTML form and we shouldn't be logging it this way, specially on a successful login.

Comment (sgairo) [inline cmd/vicadmin/server.go]: Fixed :)
