### PR TITLE
Verify license present in nightly env

### LINKED ISSUE #5438: nightly test failed to create cluster - License not available to perform the operation
Seen in nightly test vsphere 6.0

5-3-ELM:
```
Running command 'govc cluster.create cls 2>&1'.
${out} = govc: ServerFaultCode: License not available to perform the operation.
```
[5-3-Enhanced-Linked-Mode.zip](https://github.com/vmware/vic/files/1066664/5-3-Enhanced-Linked-Mode.zip)

### PR DESCRIPTION
**Pull request by andrewtchin**
Fixes #5438

Waits up to 1 min for the license to show up correctly on vCenter and ESXi in nightly tests.

### CODE REVIEW

**Comment by AngieCris** [comment]
what is the possible root cause of the `SecurityError` from govc license check? Is it that the license doesn't come up yet, or the ESX host disconnected, or sth else?

**Comment by andrewtchin** [comment]
@AngieCris This is a permission error https://vdc-download.vmware.com/vmwb-repository/dcr-public/6b586ed2-655c-49d9-9029-bc416323cb22/fa0b429a-a695-4c11-b7d2-2cbc284049dc/doc/vmodl.fault.SecurityError.html
I suspect, but am not sure that since we only see this in ELM tests that there's something with syncing the state that may take a while, so I added the retries for 1 minute.

File: lib/install/validate/config.go [hunk 1]
```diff
@@ -384,6 +384,7 @@ func (v *Validator) ManagementNetAllowed(ctx context.Context, mgmtIP net.IPNet,
 		TargetIP: mgmtIP}
 }
 
+// CheckLicense checks license features on the Validator's target
```
Comment (anchal-agrawal) [inline lib/install/validate/config.go]: Thanks for doing this.
