### PR TITLE
Delete old VCH

### LINKED ISSUE #2719: vic-machine: unable to delete old VCH versions
**Expected behavior:**
`vic-machine delete --force` deletes the VCH that it knows is there

**Actual behavior:**

```
INFO[2016-10-13T17:26:48Z] ### Removing VCH ####
INFO[2016-10-13T17:26:48Z]
INFO[2016-10-13T17:26:48Z] VCH ID: VirtualMachine:367
INFO[2016-10-13T17:26:48Z] Removing VMs
INFO[2016-10-13T17:26:48Z] Specify --force to force delete
INFO[2016-10-13T17:26:48Z] Collecting ha-host hostd.log
ERRO[2016-10-13T17:26:48Z] Cannot find compute resources from configuration, please delete VCH manually
ERRO[2016-10-13T17:26:48Z] --------------------
ERRO[2016-10-13T17:26:48Z] vic-machine-linux failed: delete failed
```

We can determine the compute resource from the path of the VCH VM. We can check if there are any VMs in that compute resource that do not have a VIC version & ID in them and fail in that scenario.
We really should delete VCHs that we can identify if `--force` is specified, even if the compute resource key has changed.

### PR DESCRIPTION
**Pull request by emlin**
Fixes #2719
If vic-machine identified the vm is one VCH instance, will delete the container VMs and VCH instance itself. Even the guestinfo configuration is changed, and some of configuration cannot be identified.
The problem is that if there is custom image store, or volume store configured, but vic-machine cannot read those configuration back, those resources will not be cleaned up.

### CODE REVIEW

File: cmd/vic-machine/delete/delete.go [hunk 1]
```diff
@@ -138,6 +139,17 @@ func (d *Uninstall) Run(cli *cli.Context) (err error) {
...
+
+	// compare vch version and vic-machine version
+	installerBuild := version.GetBuild()
+	if vchConfig.Version == nil || !installerBuild.Equal(vchConfig.Version) {
+		if !d.Data.Force {
+			log.Errorf("VCH version %q is different with installer version %s. Specify --force to force delete", vchConfig.Version.ShortVersion(), installerBuild.ShortVersion())
+			return errors.New("delete failed")
+		}
+
+		log.Warnf("VCH version %q is different with installer version %s. Force delete will try best to delete everything found.", vchConfig.Version.ShortVersion(), installerBuild.ShortVersion())
```
Comment (mlh78750) [inline cmd/vic-machine/delete/delete.go]: Change warning text to: Force delete will attempt to remove everything related to the installed VCH.

Comment (emlin) [inline cmd/vic-machine/delete/delete.go]: 👍

File: cmd/vic-machine/delete/delete.go [hunk 2]
```diff
@@ -138,6 +139,17 @@ func (d *Uninstall) Run(cli *cli.Context) (err error) {
 		log.Error(err)
 		return errors.New("delete failed")
 	}
+
+	// compare vch version and vic-machine version
+	installerBuild := version.GetBuild()
+	if vchConfig.Version == nil || !installerBuild.Equal(vchConfig.Version) {
+		if !d.Data.Force {
+			log.Errorf("VCH version %q is different with installer version %s. Specify --force to force delete", vchConfig.Version.ShortVersion(), installerBuild.ShortVersion())
```
Comment (andrewtchin) [inline cmd/vic-machine/delete/delete.go]: different than installer version

File: cmd/vic-machine/delete/delete.go [hunk 3]
```diff
@@ -138,6 +139,17 @@ func (d *Uninstall) Run(cli *cli.Context) (err error) {
...
+			return errors.New("delete failed")
+		}
+
+		log.Warnf("VCH version %q is different with installer version %s. Force delete will attempt to remove everything related to the installed VCH", vchConfig.Version.ShortVersion(), installerBuild.ShortVersion())
```
Comment (andrewtchin) [inline cmd/vic-machine/delete/delete.go]: same

File: lib/install/management/delete.go [hunk 4]
```diff
@@ -79,46 +79,94 @@ func (d *Dispatcher) DeleteVCH(conf *config.VirtualContainerHostConfigSpec) erro
...
-	var children []*vm.VirtualMachine
 
 	if len(conf.ComputeResources) == 0 {
-		err = errors.Errorf("Cannot find compute resources from configuration, please delete VCH manually")
-		return err
+		if !d.force {
+			err = errors.Errorf("Cannot find compute resources from configuration")
+			return nil, err
+		}
+		log.Warnf("Cannot find compute resources from configuration, try to delete under parent resource pool")
```
Comment (andrewtchin) [inline lib/install/management/delete.go]: attempting to delete

File: lib/install/management/delete.go [hunk 5]
```diff
@@ -79,46 +79,94 @@ func (d *Dispatcher) DeleteVCH(conf *config.VirtualContainerHostConfigSpec) erro
...
+}
 
+func (d *Dispatcher) getImageDatastore(vmm *vm.VirtualMachine, conf *config.VirtualContainerHostConfigSpec) (*object.Datastore, error) {
+	var err error
+	if len(conf.ImageStores) == 0 {
+		if !d.force {
+			err = errors.Errorf("Cannot find image stores from configuration")
+			return nil, err
+		}
+		log.Warnf("Cannot find image stores from configuration, try to delete from vm datastore")
```
Comment (andrewtchin) [inline lib/install/management/delete.go]: same

**Comment by andrewtchin** [comment]
lgtm

File: lib/install/management/resource_pool.go [hunk 6]
```diff
@@ -108,21 +107,22 @@ func (d *Dispatcher) destroyResourcePoolIfEmpty(conf *config.VirtualContainerHos
 
 	log.Infof("Removing Resource Pool %q", conf.Name)
 
-	rpRef := conf.ComputeResources[len(conf.ComputeResources)-1]
-	rp := compute.NewResourcePool(d.ctx, d.session, rpRef)
-
+	if d.parentResourcepool == nil {
+		log.Warnf("Do not find parent VCH resource pool")
```
Comment (anchal-agrawal) [inline lib/install/management/resource_pool.go]: Minor - `"Did not find..."`

File: tests/test-cases/Group12-VCH-BC/12-01-Delete.robot [hunk 7]
```diff
@@ -0,0 +1,97 @@
...
+    \   Run Keyword If  '${status}' == 'PASS'  Set Suite Variable  ${ext-ip}  @{output}[${idx}]
+
+*** Test Cases ***
+Delete VCH with new vic-machine
+    Log To Console  \nRunning docker pull busybox...
+    ${rc}  ${output}=  Run And Return Rc And Output  docker ${params} pull busybox
+    Log  ${output}
+    Should Be Equal As Integers  ${rc}  0
+    Should Not Contain  ${output}  Error
+    ${name}=  Generate Random String  15
```
Comment (anchal-agrawal) [inline tests/test-cases/Group12-VCH-BC/12-01-Delete.robot]: TIL 👍

**Comment by anchal-agrawal** [comment]
LGTM

**Comment by emlin** [comment]
.
