### PR TITLE
Make installer wait for portlayer to initialize

### LINKED ISSUE #1109: Failed to ping portlayer: Get http://127.0.0.1:8080/_ping: dial tcp 127.0.0.1:8080: getsockopt: connection refused
Seeing this error periodically, not sure how to reliably cause this problem.  It seems transitory and immediately after seeing this error, I can run the docker command again and not see this error.

Might be a race condition with how quickly my scripts make a docker request after deploying a new VCH?

### PR DESCRIPTION
**Pull request by anchal-agrawal**
* Adds logic to make the installer wait for the portlayer to start serving requests
* Removes `sleep` in the integration tests
* Adds an integration test for `vic-machine create --no-tls`

Fixes #1109

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
To ensure that the portlayer is serving before the installer exits, this implementation issues a `docker info` in the installer and checks the response. The request is retried 10 times with a sleep of 1 second in between. If the portlayer isn't serving after 10 tries, the installer logs a warning and continues with the installation.

ping @hmahmood @emlin @mhagen-vmware @jzt

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

File: lib/install/management/appliance.go [hunk 1]
```diff
@@ -581,6 +586,58 @@ func (d *Dispatcher) waitForKey(key string) {
...
+	}
+
+	return false
+}
+
+// waitForApplianceInit checks if the appliance is live by issuing `docker info` to it
+func waitForApplianceInit(hostIP, port string) bool {
+	dockerInfoURL := "https://" + hostIP + ":" + port + "/info"
+	tr := &http.Transport{
+		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
```
Comment (andrewtchin) [inline lib/install/management/appliance.go]: should this have a TODO to be configurable for when we support user supplied certs?

**Comment by andrewtchin** [comment]
there's and additional robot test added yesterday that needs the issue check removed in `https://github.com/vmware/vic/blob/master/tests/test-cases/Group6-VIC-Machine/6-5-Create-Validation.robot`

**Comment by andrewtchin** [comment]
lgtm

File: lib/install/management/appliance.go [hunk 2]
```diff
@@ -581,6 +586,58 @@ func (d *Dispatcher) waitForKey(key string) {
...
+			return status[1] == "RUNNING"
+		}
+	}
+
+	return false
+}
+
+// waitForApplianceInit checks if the appliance is live by issuing `docker info` to it
+func waitForApplianceInit(hostIP, port string) bool {
+	dockerInfoURL := "https://" + hostIP + ":" + port + "/info"
```
Comment (emlin) [inline lib/install/management/appliance.go]: suggest: fmt.Sprintf("https://%s:%s/info", hostIP, port)

File: lib/install/management/appliance.go [hunk 3]
```diff
@@ -611,6 +668,12 @@ func (d *Dispatcher) makeSureApplianceRuns(conf *config.VirtualContainerHostConf
 	if !ip.IsUnspecifiedIP(conf.ExecutorConfig.Networks["client"].Assigned.IP) {
 		d.HostIP = conf.ExecutorConfig.Networks["client"].Assigned.IP.String()
 		log.Debug("Obtained IP address for client interface: %q", d.HostIP)
+
+		// wait till the appliance is fully initialized
+		initSuccess := waitForApplianceInit(d.HostIP, d.DockerPort)
```
Comment (emlin) [inline lib/install/management/appliance.go]: There are other codes to retrieve components status. It's fine to keep current logic, but need to move your code to the end of the method.
And return error if service is unreachable.

File: lib/install/management/appliance.go (hunk 1 above)
Comment (gigawhitlocks) [inline lib/install/management/appliance.go]: Isn't there a cert that matches the docker endpoint available in the `VirtualContainerHostConfigSpec`?

Comment (anchal-agrawal) [inline lib/install/management/appliance.go]: Yes, I see a `HostCertificate` there. Let me try that out.

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by anchal-agrawal** [comment]
Addressed comments. Thanks @emlin @andrewtchin @gigawhitlocks!

**Comment by anchal-agrawal** [comment]
Updated go and rebased.

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by anchal-agrawal** [comment]
There's an integration test in #1982 that depends on this PR.

**Comment by emlin** [comment]
lgtm 👍

File: lib/install/management/appliance.go [hunk 4]
```diff
@@ -652,5 +721,11 @@ func (d *Dispatcher) makeSureApplianceRuns(conf *config.VirtualContainerHostConf
 		return errors.New("timed out waiting for IP address information from appliance")
 	}
 
-	return fmt.Errorf("could not obtain IP address information from appliance: %s", updateErr)
+	// wait till the appliance is fully initialized
```
Comment (hickeng) [inline lib/install/management/appliance.go]: I'd prefer it if this were called after `makeSureApplianceRuns` rather than here. If needed we can change the names to:
```
ensureApplianceInitializes
ensureComponentsInitialize
```

Calling it here means we've a large error handling block in the middle of the function rather than a clean separation between success and failure paths.

Comment (anchal-agrawal) [inline lib/install/management/appliance.go]: Fixed, thank you!

**Comment by anchal-agrawal** [comment]
♻️

**Comment by anchal-agrawal** [comment]
Another ♻️

**Comment by anchal-agrawal** [comment]
Another ♻️
