### PR TITLE
Don't write to closed log file

### LINKED ISSUE #1326: vic-machine Bad FD for create log
15599b2

vic-machine create has a (new within the last day) undesired error message at the end of output `Failed to write to log, write create.log: bad file descriptor`

This happens both when `create.log` does not exist and when already present before running `vic-machine create`. The log file has the expected contents after running the command.

This does not happen when the installer completes successfully.

```
⇒  bin/vic-machine-linux create --target=skinner.eng.vmware.com --user=Administrator@vsphere.local --image-datastore Datastoreasdf --bridge-network vch-test --name chin-vic-102 --compute-resource asdf
INFO[2016-07-01T09:40:54-07:00] ### Installing VCH ####                      
INFO[2016-07-01T09:40:54-07:00] Generating certificate/key pair - private key in ./chin-vic-102-key.pem 
INFO[2016-07-01T09:40:55-07:00] Validating supplied configuration            
INFO[2016-07-01T09:40:55-07:00] Suggesting valid values for --compute-resource based on /Datacenter/host/asdf/Resources 
ERRO[2016-07-01T09:40:56-07:00] Unable to list pools for /Datacenter/host/asdf: resource pool '/Datacenter/host/asdf/*' not found 
INFO[2016-07-01T09:40:56-07:00]   Austin                                     
INFO[2016-07-01T09:40:56-07:00]   JoshCluster                                
INFO[2016-07-01T09:40:56-07:00] Datastoreasdf                                
ERRO[2016-07-01T09:40:56-07:00] Datastore for images is nil                  
ERRO[2016-07-01T09:40:56-07:00] Firewall check SKIPPED                       
ERRO[2016-07-01T09:40:56-07:00]   datastore not set                          
ERRO[2016-07-01T09:40:56-07:00]   cluster not set                            
ERRO[2016-07-01T09:40:56-07:00] License check SKIPPED                        
ERRO[2016-07-01T09:40:56-07:00]   datastore not set                          
ERRO[2016-07-01T09:40:56-07:00]   cluster not set                            
ERRO[2016-07-01T09:40:56-07:00] DRS check SKIPPED                            
ERRO[2016-07-01T09:40:56-07:00]   datastore not set                          
ERRO[2016-07-01T09:40:56-07:00]   cluster not set                            
ERRO[2016-07-01T09:40:56-07:00] Compatibility check SKIPPED                  
ERRO[2016-07-01T09:40:56-07:00]   datastore not set                          
ERRO[2016-07-01T09:40:56-07:00]   cluster not set                            
ERRO[2016-07-01T09:40:56-07:00] --------------------                         
ERRO[2016-07-01T09:40:56-07:00] resource pool '/Datacenter/host/asdf/Resources' not found 
ERRO[2016-07-01T09:40:56-07:00] datastore 'Datastoreasdf' not found          
ERRO[2016-07-01T09:40:56-07:00] Firewall check SKIPPED                       
ERRO[2016-07-01T09:40:56-07:00] License check SKIPPED                        
ERRO[2016-07-01T09:40:56-07:00] DRS check SKIPPED                            
ERRO[2016-07-01T09:40:56-07:00] Compatibility check SKIPPED                  
ERRO[2016-07-01T09:40:56-07:00] Creation cannot continue: configuration validation failed 
ERRO[2016-07-01T09:40:56-07:00] vic-machine-linux failed: validation of configuration failed 
Failed to write to log, write create.log: bad file descriptor
```

### PR DESCRIPTION
**Pull request by andrewtchin**
Changed log call to print and made sure we log errors that were previously returned while we still have the log file open.

Fixes #1326

```
INFO[2016-07-05T12:59:44-07:00] ### Installing VCH ####                      
INFO[2016-07-05T12:59:44-07:00] Generating certificate/key pair - private key in ./chin-vic-105-key.pem 
INFO[2016-07-05T12:59:45-07:00] Validating supplied configuration            
INFO[2016-07-05T12:59:45-07:00] Suggesting valid values for --compute-resource based on * 
INFO[2016-07-05T12:59:46-07:00]   Austin                                     
INFO[2016-07-05T12:59:46-07:00]   JoshCluster                                
INFO[2016-07-05T12:59:46-07:00] Datastore                                    
ERRO[2016-07-05T12:59:46-07:00] Firewall check SKIPPED                       
ERRO[2016-07-05T12:59:46-07:00]   cluster not set                            
ERRO[2016-07-05T12:59:46-07:00] License check SKIPPED                        
ERRO[2016-07-05T12:59:46-07:00]   cluster not set                            
ERRO[2016-07-05T12:59:46-07:00] DRS check SKIPPED                            
ERRO[2016-07-05T12:59:46-07:00]   cluster not set                            
ERRO[2016-07-05T12:59:46-07:00] Compatibility check SKIPPED                  
ERRO[2016-07-05T12:59:46-07:00]   cluster not set                            
ERRO[2016-07-05T12:59:46-07:00] --------------------                         
ERRO[2016-07-05T12:59:46-07:00] No unambiguous default compute resource available: --compute-resource must be specified 
ERRO[2016-07-05T12:59:46-07:00] Firewall check SKIPPED                       
ERRO[2016-07-05T12:59:46-07:00] License check SKIPPED                        
ERRO[2016-07-05T12:59:46-07:00] DRS check SKIPPED                            
ERRO[2016-07-05T12:59:46-07:00] Compatibility check SKIPPED                  
ERRO[2016-07-05T12:59:46-07:00] Create cannot continue: configuration validation failed 
--------------------
vic-machine-linux failed: validation of configuration failed
```

```
INFO[2016-07-05T13:00:09-07:00] ### Removing VCH ####                        
INFO[2016-07-05T13:00:10-07:00] Suggesting valid values for --compute-resource based on * 
INFO[2016-07-05T13:00:10-07:00]   Austin                                     
INFO[2016-07-05T13:00:10-07:00]   JoshCluster                                
ERRO[2016-07-05T13:00:10-07:00] Failed to get Virtual Container Host docker-appliance 
ERRO[2016-07-05T13:00:10-07:00] No unambiguous default compute resource available: --compute-resource must be specified 
--------------------
vic-machine-linux failed: delete failed
```

```
INFO[2016-07-05T13:01:37-07:00] ### Inspecting VCH ####                      
INFO[2016-07-05T13:01:38-07:00] Suggesting valid values for --compute-resource based on * 
INFO[2016-07-05T13:01:38-07:00]   Austin                                     
INFO[2016-07-05T13:01:38-07:00]   JoshCluster                                
ERRO[2016-07-05T13:01:38-07:00] Failed to get Virtual Container Host docker-appliance 
ERRO[2016-07-05T13:01:38-07:00] No unambiguous default compute resource available: --compute-resource must be specified 
--------------------
vic-machine-linux failed: inspect failed
```

### CODE REVIEW

**Comment by emlin** [comment]
lgtm

File: cmd/vic-machine/delete/delete.go [hunk 1]
```diff
@@ -115,36 +115,39 @@ func (d *Uninstall) Run(cli *cli.Context) error {
...
+		log.Error(err)
+		return errors.New("delete failed")
 	}
 	vchConfig, err := executor.GetVCHConfig(vch)
 	if err != nil {
-		log.Errorf("Failed to get Virtual Container Host configuration")
-		return err
+		log.Error("Failed to get Virtual Container Host configuration")
+		log.Error(err)
+		return errors.New("delete failed")
```
Comment (gigawhitlocks) [inline cmd/vic-machine/delete/delete.go]: On these errors, we should include all of the textual information in the error that's returned, because it gets concatenated together with other errors further down (up?) the stack for increasing contextual information. So instead of doing `log.Error(message` and then `return errors` you should collapse them into a single returned error I do believe

**Comment by gigawhitlocks** [comment]
lgtm

**Comment by andrewtchin** [comment]
♻️
