### PR TITLE
Handle early container poweroff state change in docker start

### LINKED ISSUE #3604: Failure in docker run ps password check test
From build: https://ci.vmware.run/vmware/vic/7554

from docker personality:
```
time=2017-01-09T22:37:33.806656986Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).Wait:570] [3m0.013033481s] b88eff2a68524b112d47848f61930e48dd75c001d09da43038d9d4b27cb9681c 
time=2017-01-09T22:37:33.815305972Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerWait:834] [3m0.021742897s] name(b88eff2a68524b112d47848f61930e48dd75c001d09da43038d9d4b27cb9681c):timeout(-1s) 
time="2017-01-09T22:37:33Z" level=error msg="Handler for POST /v1.21/containers/b88eff2a68524b112d47848f61930e48dd75c001d09da43038d9d4b27cb9681c/wait returned error: Server error from portlayer: ContainerWaitHandler(b88eff2a68524b112d47848f61930e48dd75c001d09da43038d9d4b27cb9681c) Error: context deadline exceeded"
```

From portlayer, it looks like we got stuck for about 3 minutes here:
```
time=2017-01-09T22:34:33.792143808Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.Commit:35] b88eff2a68524b112d47848f61930e48dd75c001d09da43038d9d4b27cb9681c 
time="2017-01-09T22:34:33Z" level=debug msg="ChangeVersion is 2017-01-09T22:34:23.554362Z" 
time=2017-01-09T22:34:33.793663858Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).ContainerWaitHandler:357] b88eff2a68524b112d47848f61930e48dd75c001d09da43038d9d4b27cb9681c:-1 
time=2017-01-09T22:34:34.032834021Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/portlayer/exec.(*Container).RefreshFromHandle:307] e696112e9f2c4fea725f37dbd3efc733 
time="2017-01-09T22:34:34Z" level=debug msg="Current ChangeVersion: 2017-01-09T22:34:23.554362Z" 
time=2017-01-09T22:34:34.037653792Z level=debug msg=[ END ] [github.com/vmware/vic/lib/portlayer/exec.(*Container).RefreshFromHandle:307] [4.819271ms] e696112e9f2c4fea725f37dbd3efc733 
time=2017-01-09T22:34:34.037660407Z level=debug msg=[ END ] [github.com/vmware/vic/lib/portlayer/exec.Commit:35] [245.516092ms] b88eff2a68524b112d47848f61930e48dd75c001d09da43038d9d4b27cb9681c 
time=2017-01-09T22:37:33.794068385Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).ContainerWaitHandler:357] [3m0.000387528s] b88eff2a68524b112d47848f61930e48dd75c001d09da43038d9d4b27cb9681c:-1 
```

But from vmware.log, it looks like the container finished on time as expected:
```
2017-01-09T22:34:34.266Z| vmx| I120: Flushing VMX VMDB connections
2017-01-09T22:34:34.266Z| vmx| I120: VigorTransport_ServerCloseClient: Closing transport 32263650 (err = 0)
2017-01-09T22:34:34.266Z| vmx| I120: VigorTransport_ServerDestroy: server destroyed.
2017-01-09T22:34:34.270Z| vmx| I120: VMX exit (0).
2017-01-09T22:34:34.270Z| vmx| I120: AIOMGR-S : stat o=5 r=15 w=0 i=0 br=245760 bw=0
2017-01-09T22:34:34.270Z| vmx| I120: OBJLIB-LIB: ObjLib cleanup done.
2017-01-09T22:34:34.270Z| vmx| W110: VMX has left the building: 0.
```

[integration_logs_7554_0e85c97314d461ba869ab55ab8b894fb11c994c4.zip](https://github.com/vmware/vic/files/711925/integration_logs_7554_0e85c97314d461ba869ab55ab8b894fb11c994c4.zip)

### PR DESCRIPTION
**Pull request by anchal-agrawal**
This change alters container start logic to check the container's current power state before setting it to `Running`. If the state is already set to `Stopped` by event handling due to the container's process exiting before we set the state to `Running`, we now skip the change to `Running`.

Fixes #3604

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
Missed the copyright header change in the first commit. I'll push the change afterwards to avoid triggering another [full ci] build.

**Comment by emlin** [comment]
> Missed the copyright header change in the first commit. I'll push the change afterwards to avoid triggering another [full ci] build.

I would suggest to rerun test few times, as it is a race condition issue, which might not be reproduced in your previous run. 😄

**Comment by emlin** [comment]
@caglar10ur you're right, here should be locked similar to what containerWait

File: lib/portlayer/exec/container.go [hunk 1]
```diff
@@ -340,12 +339,27 @@ func (c *Container) start(ctx context.Context) error {
...
 
-	finalState = StateRunning
+	c.m.Lock()
+	defer c.m.Unlock()
 
-	return err
+	// Obtain the current state and set the final state to Running only if it's Starting.
+	// The current state is already Stopped if the container's process has exited or
+	// a poweredoff event has been processed.
+	currentState := c.state
```
Comment (vburenin) [inline lib/portlayer/exec/container.go]:
```
if c.state == StateStarting {
    c.updateState(StateRunning)
} 
c.updateState will not change state if it is the same state as the current one.
```

File: lib/portlayer/exec/container.go [hunk 2]
```diff
@@ -340,12 +339,27 @@ func (c *Container) start(ctx context.Context) error {
...
+	if currentState == StateStarting {
+		finalState = StateRunning
+	} else {
+		log.Infof("current state of container %s is %v", c.ExecConfig.ID, currentState)
```
Comment (vburenin) [inline lib/portlayer/exec/container.go]: I see no benefits from this log statement on info level as well as even on debug level.

Comment (anchal-agrawal) [inline lib/portlayer/exec/container.go]: I put this in because it would be helpful to log the current state since we skip a state change to `Running` here. You're right though, since we'd have already logged the existing state earlier. I'll remove this log.

File: lib/portlayer/exec/container.go (hunk 1 above)
Comment (anchal-agrawal) [inline lib/portlayer/exec/container.go]: Fixed.

**Comment by anchal-agrawal** [comment]
@caglar10ur please review the latest changes, thanks!

File: lib/portlayer/exec/container.go [hunk 3]
```diff
@@ -234,6 +234,17 @@ func (c *Container) updateState(s State) State {
...
 
+// transitionState changes the container state to finalState if the current state is initialState.
+func (c *Container) transitionState(initialState, finalState State) {
+	c.m.Lock()
+	defer c.m.Unlock()
+
+	if c.state == initialState {
+		c.state = finalState
+		log.Debugf("Set container %s state: %s", c.ExecConfig.ID, finalState)
+	}
```
Comment (caglar10ur) [inline lib/portlayer/exec/container.go]: could you please add another debug line for the else clause so that we could see why this function did nothing

Comment (caglar10ur) [inline lib/portlayer/exec/container.go]: Also I think this function should return an error to the caller so that caller can know whether transition succeeded or not.

File: lib/portlayer/exec/container.go [hunk 4]
```diff
@@ -326,10 +337,8 @@ func (c *Container) start(ctx context.Context) error {
 	if c.vm == nil {
 		return fmt.Errorf("vm not set")
 	}
-	// get existing state and set to starting
-	// if there's a failure we'll revert to existing
-	finalState := c.updateState(StateStarting)
-	defer func() { c.updateState(finalState) }()
+	// Set state to Starting
+	c.updateState(StateStarting)
```
Comment (caglar10ur) [inline lib/portlayer/exec/container.go]: isn't this still racy? Why we are not using new transitionState here with stateStopped as the initial state?

File: lib/portlayer/exec/container.go (hunk 3 above)
Comment (anchal-agrawal) [inline lib/portlayer/exec/container.go]: Sounds good.

File: lib/portlayer/exec/container.go (hunk 4 above)
Comment (anchal-agrawal) [inline lib/portlayer/exec/container.go]: Yes, it's been racy before this change as well. However, I'm not sure if we can decide on one initial state here - on a `run -it busybox`, the initial state here is `Created`. It could be `Stopped` if the container is stopped.

Comment (anchal-agrawal) [inline lib/portlayer/exec/container.go]: We can use `SetState` here instead of `updateState` to get rid of the race here.

Comment (caglar10ur) [inline lib/portlayer/exec/container.go]: Good point, I think you can leave it as is

File: lib/portlayer/exec/container.go (hunk 3 above)
Comment (anchal-agrawal) [inline lib/portlayer/exec/container.go]: Fixed!

File: lib/portlayer/exec/container.go (hunk 4 above)
Comment (anchal-agrawal) [inline lib/portlayer/exec/container.go]: Updated to use `SetState`, which grabs a lock.
