### PR TITLE
Fix IPAM calculation error

### LINKED ISSUE #6516: VCH IPAM calculating the container network range wrongly.
VIC Engine - vic_1.2.1-rc2, vic_1.2.1

User statement: As a customer of VIC, I would like to use DHCP, where multiple VCH may share same CNW subnet; IP addresses being managed by DHCP server. 

Details: Please note #6515 is causing issues that forces continued use of CNR.

Issue Description: However, any CNR range specified with x-**127** (as below) would result in a /25 subnet as the IPRange inside VCH IPAM without regard to the starting octet specified.

```
--cnr 10.92.159.0-24_1159_uat_vic_cnw:10.92.159.5-127 OR
--cnr 10.92.159.0-24_1159_uat_vic_cnw:10.92.159.16-10.92.159.127
```

result; refer screenshot.
image

@hickeng

### PR DESCRIPTION
**Pull request by yuyangbj**
When we specified the ip range for container network, and the network inspect
always show the wrong cidr using docker cmd to get information.

Fixes #6516

### CODE REVIEW

File: lib/apiservers/portlayer/restapi/handlers/scopes_handlers.go [hunk 1]
```diff
@@ -366,7 +367,9 @@ func toScopeConfig(scope *network.Scope) *models.ScopeConfig {
 		pools = append(pools, p.String())
 	}
 
-	sc.IPAM = pools
```
Comment (YanzhaoLi) [inline lib/apiservers/portlayer/restapi/handlers/scopes_handlers.go]: Is this change necessary? If so, how about sc.IPAM = append(sc.IPAM, pools...)

Comment (yuyangbj) [reply lib/apiservers/portlayer/restapi/handlers/scopes_handlers.go]: Good catch! Thanks!
