### PR TITLE
[specific ci=1-07-Docker-Stop] Fixed docker stop after upgrade to API 1.25

### LINKED ISSUE #3976: Docker stop is broken with client version 1.13.1
`docker stop` does not work & errors out on current build on `master` with latest docker client.

**VIC version:**

This is happening on `master`, all commits starting with commit `4d2e9a3dee3acf32f144f857153b7c506581ab66` found via manual testing + `git bisect`

```
❯ docker -H 192.168.218.149:2376 --tls info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: v0.8.0-0-bd30cd6
Storage Driver: vSphere Integrated Containers v0.8.0-0-bd30cd6 Backend Engine
VolumeStores: default
vSphere Integrated Containers v0.8.0-0-bd30cd6 Backend Engine: RUNNING
 VCH CPU limit: 2942 MHz
 VCH memory limit: 857 MiB
 VCH CPU usage: 144 MHz
 VCH memory usage: 1.104 GiB
 VMware Product: VMware ESXi
 VMware OS: vmnix-x86
 VMware OS version: 6.0.0
Plugins: 
 Volume: 
 Network: bridge
Swarm: inactive
Operating System: vmnix-x86
OSType: vmnix-x86
Architecture: x86_64
CPUs: 2942
Total Memory: 857 MiB
Name: ian-vch
ID: vSphere Integrated Containers
Docker Root Dir: 
Debug Mode (client): false
Debug Mode (server): false
Registry: registry-1.docker.io
Experimental: false
Live Restore Enabled: false

```

**Deployment details:**
Tested on my local esx

What was the vic-machine create command used to deploy the VCH?
```/home/ian/go/src/github.com/vmware/vic/bin/vic-machine-linux create --target 192.168.218.147 --user root --image-store=datastore1 --password xxxxx --name ian-vch --image-store=datastore1/images --volume-store=datastore1/volumes:default --force --no-tlsverify ```

**Steps to reproduce:**

Do above install, and run the following with the following docker client version or the latest (this bug is reproducible with latest docker client as well)
```
~
❯ docker --version
Docker version 1.13.1, build 092cba3

~
❯ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:41:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:41:33 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Actual behavior:**
```
❯ docker -H 192.168.218.149:2376 --tls stop $(docker -H 192.168.218.149:2376 --tls run -itd busybox top)
Unable to find image 'busybox:latest' locally
Pulling from library/busybox
4b0bc1c4050b: Pulling fs layer
a3ed95caeb02: Pulling fs layer
a3ed95caeb02: Verifying Checksum
a3ed95caeb02: Download complete
4b0bc1c4050b: Verifying Checksum
4b0bc1c4050b: Download complete
4b0bc1c4050b: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:348432dd709c2cd6ca42e56c2a0d157f611c50c908e14c9bfc1e9cb0ed234871
Status: Downloaded newer image for library/busybox:latest
error during connect: Post https://192.168.218.149:2376/v1.23/containers/dbf1eeb18d0b1a4d55c86e950416e32b484bfbe2037f5f28ee1739bb8b387e1a/stop: EOF
```

**Expected behavior:**

Run the container & stop it,  verifiable via `docker ps`

**Logs:**

Looks like there's a panic in the personality:
```
Feb 16 2017 01:46:52.609Z INFO  Launching docker personality pprof server on 127.0.0.1:6062
Feb 16 2017 01:46:52.845Z INFO  Waiting for portlayer to come up
Feb 16 2017 01:46:54.847Z INFO  Portlayer is up and responding to pings
Feb 16 2017 01:46:54.847Z INFO  Refreshing repository cache
Feb 16 2017 01:46:54.847Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.NewRepositoryCache:131]
Feb 16 2017 01:46:54.847Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Get:49] repositories
Feb 16 2017 01:46:54.847Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.InitializeLayerCache:68]
Feb 16 2017 01:46:54.847Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Get:49] layers
Feb 16 2017 01:46:54.848Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.InitializeImageCache:84]
Feb 16 2017 01:46:54.848Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Get:49] images
Feb 16 2017 01:46:54.849Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Get:49] [1.78176ms] repositories
Feb 16 2017 01:46:54.849Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.NewRepositoryCache:131] [1.908666ms] 
Feb 16 2017 01:46:54.849Z INFO  Repository cache updated successfully
Feb 16 2017 01:46:54.849Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Get:49] [1.631707ms] images
Feb 16 2017 01:46:54.849Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.InitializeImageCache:84] [1.680276ms] 
Feb 16 2017 01:46:54.849Z INFO  Image cache initialized successfully
Feb 16 2017 01:46:54.849Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Get:49] [2.07278ms] layers
Feb 16 2017 01:46:54.849Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.InitializeLayerCache:68] [2.094829ms] 
Feb 16 2017 01:46:54.849Z INFO  Layer cache initialized successfully
Feb 16 2017 01:46:54.850Z INFO  Container cache updated successfully
Feb 16 2017 01:46:54.850Z INFO  Creating image store
Feb 16 2017 01:46:55.534Z INFO  Image store created successfully
Feb 16 2017 01:46:55.534Z INFO  TLS enabled
Feb 16 2017 01:46:55.535Z INFO  Listener created for HTTP on 192.168.218.149//tcp
Feb 16 2017 01:46:55.544Z INFO  API listen on 192.168.218.149:2376
Feb 16 2017 01:46:55.792Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*System).SystemInfo:76] SystemInfo
Feb 16 2017 01:46:55.792Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*SystemProxy).ContainerCount:80] ContainerCount
Feb 16 2017 01:46:55.792Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*SystemProxy).ContainerCount:80] [457.12µs] ContainerCount
Feb 16 2017 01:46:55.792Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).GetImages:121]
Feb 16 2017 01:46:55.792Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).GetImages:121] [44.053µs] 
Feb 16 2017 01:46:55.793Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*SystemProxy).PingPortlayer:56] PingPortlayer
Feb 16 2017 01:46:55.793Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*SystemProxy).PingPortlayer:56] [224.372µs] PingPortlayer
Feb 16 2017 01:46:55.793Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*SystemProxy).VCHInfo:109] VCHInfo
Feb 16 2017 01:46:55.807Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*SystemProxy).VCHInfo:109] [14.156593ms] VCHInfo
Feb 16 2017 01:46:55.807Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*System).SystemInfo:76] [15.470762ms] SystemInfo
Feb 16 2017 01:48:30.564Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate:258]
Feb 16 2017 01:48:30.564Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Get:147]
Feb 16 2017 01:48:30.564Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).getImageByNamed:199]
Feb 16 2017 01:48:30.564Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Get:329]
Feb 16 2017 01:48:30.564Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Get:329] [33.908µs] 
Feb 16 2017 01:48:30.564Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).getImageByNamed:199] [166.746µs] 
Feb 16 2017 01:48:30.564Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Get:147] [320.121µs] 
Feb 16 2017 01:48:30.564Z ERROR ContainerCreate: image busybox error: No such image: busybox:latest
Feb 16 2017 01:48:30.564Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate:258] [611.853µs] 
Feb 16 2017 01:48:30.564Z ERROR Handler for POST /v1.23/containers/create returned error: No such image: busybox:latest
Feb 16 2017 01:48:30.566Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*System).SystemInfo:76] SystemInfo
Feb 16 2017 01:48:30.566Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*SystemProxy).ContainerCount:80] ContainerCount
Feb 16 2017 01:48:30.567Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*SystemProxy).ContainerCount:80] [1.288385ms] ContainerCount
Feb 16 2017 01:48:30.567Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).GetImages:121]
Feb 16 2017 01:48:30.567Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).GetImages:121] [4.849µs] 
Feb 16 2017 01:48:30.567Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*SystemProxy).PingPortlayer:56] PingPortlayer
Feb 16 2017 01:48:30.567Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*SystemProxy).PingPortlayer:56] [195.667µs] PingPortlayer
Feb 16 2017 01:48:30.567Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*SystemProxy).VCHInfo:109] VCHInfo
Feb 16 2017 01:48:30.581Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*SystemProxy).VCHInfo:109] [13.770965ms] VCHInfo
Feb 16 2017 01:48:30.581Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*System).SystemInfo:76] [15.778051ms] SystemInfo
Feb 16 2017 01:48:30.583Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Image).PullImage:296]
Feb 16 2017 01:48:30.583Z INFO  PullImage: reference: busybox:latest, 127.0.0.1:2377, portlayer: "127.0.0.1:2377"
Feb 16 2017 01:48:30.583Z INFO  Using UUID (564def6f-b1e5-c6cf-fa8a-51421654afaa) for imagestore name
Feb 16 2017 01:48:30.583Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.PingPortLayer:40] 127.0.0.1:2377
Feb 16 2017 01:48:30.584Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.PingPortLayer:40] [960.217µs] 127.0.0.1:2377
Feb 16 2017 01:48:30.584Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.LearnRegistryURL:68] registry-1.docker.io
Feb 16 2017 01:48:30.584Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Head:351] https://registry-1.docker.io/v2/
Feb 16 2017 01:48:30.876Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Head:351] [291.632902ms] https://registry-1.docker.io/v2/
Feb 16 2017 01:48:30.876Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.LearnRegistryURL:68] [291.857478ms] registry-1.docker.io
Feb 16 2017 01:48:30.876Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.LearnAuthURL:112] library/busybox/latest
Feb 16 2017 01:48:30.876Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Head:351] https://registry-1.docker.io/v2/library/busybox/manifests/latest
Feb 16 2017 01:48:31.118Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Head:351] [241.833934ms] https://registry-1.docker.io/v2/library/busybox/manifests/latest
Feb 16 2017 01:48:31.118Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.LearnAuthURL:112] [242.047405ms] library/busybox/latest
Feb 16 2017 01:48:31.118Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.FetchToken:155] https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io
Feb 16 2017 01:48:31.118Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).FetchAuthToken:197] https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io
Feb 16 2017 01:48:31.119Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Fetch:123] https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io
Feb 16 2017 01:48:31.382Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Fetch:123] [263.366242ms] https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io
Feb 16 2017 01:48:31.382Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).FetchAuthToken:197] [263.763487ms] https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io
Feb 16 2017 01:48:31.382Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.FetchToken:155] [263.859473ms] https://auth.docker.io/token?scope=repository%3Alibrary%2Fbusybox%3Apull&service=registry.docker.io
Feb 16 2017 01:48:31.383Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.FetchImageManifest:314] library/busybox/latest
Feb 16 2017 01:48:31.383Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Fetch:123] https://registry-1.docker.io/v2/library/busybox/manifests/latest
Feb 16 2017 01:48:31.794Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Fetch:123] [411.096261ms] https://registry-1.docker.io/v2/library/busybox/manifests/latest
Feb 16 2017 01:48:31.795Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.FetchImageManifest:314] [411.807885ms] library/busybox/latest
Feb 16 2017 01:48:31.795Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.(*LCache).Get:125]
Feb 16 2017 01:48:31.795Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.(*LCache).Get:125] [12.7µs] 
Feb 16 2017 01:48:31.795Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.(*LCache).Get:125]
Feb 16 2017 01:48:31.795Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.(*LCache).Get:125] [8.897µs] 
Feb 16 2017 01:48:31.795Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.(*LayerDownloader).DownloadLayers:107]
Feb 16 2017 01:48:31.795Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.(*LCache).Get:125]
Feb 16 2017 01:48:31.795Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.(*LCache).Get:125] [4.754µs] 
Feb 16 2017 01:48:31.795Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.(*LCache).Add:96]
Feb 16 2017 01:48:31.795Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.(*LCache).Add:96] [13.258µs] 
Feb 16 2017 01:48:31.795Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.(*LCache).Get:125]
Feb 16 2017 01:48:31.795Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.(*LCache).Get:125] [4.87µs] 
Feb 16 2017 01:48:31.796Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.(*LCache).Add:96]
Feb 16 2017 01:48:31.796Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.(*LCache).Add:96] [13.314µs] 
Feb 16 2017 01:48:31.796Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.FetchImageBlob:179] library/busybox/sha256:4b0bc1c4050b03c95ef2a8e36e25feac42fd31283e8c30b3ee5df6b043155d3c
Feb 16 2017 01:48:31.796Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Fetch:123] https://registry-1.docker.io/v2/library/busybox/blobs/sha256:4b0bc1c4050b03c95ef2a8e36e25feac42fd31283e8c30b3ee5df6b043155d3c
Feb 16 2017 01:48:31.797Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.FetchImageBlob:179] library/busybox/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Feb 16 2017 01:48:31.797Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Fetch:123] https://registry-1.docker.io/v2/library/busybox/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Feb 16 2017 01:48:32.382Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Fetch:123] [584.923036ms] https://registry-1.docker.io/v2/library/busybox/blobs/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Feb 16 2017 01:48:32.382Z INFO  diffID for layer c40e708042c6a113e5827705cf9ace0377fae60cf9ae7a80ea8502d6460d87c6: sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
Feb 16 2017 01:48:32.382Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.FetchImageBlob:179] [585.427307ms] library/busybox/sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Feb 16 2017 01:48:32.597Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Fetch:123] [800.405996ms] https://registry-1.docker.io/v2/library/busybox/blobs/sha256:4b0bc1c4050b03c95ef2a8e36e25feac42fd31283e8c30b3ee5df6b043155d3c
Feb 16 2017 01:48:32.646Z INFO  diffID for layer 8243b36f9bd41166cc1fd0a66bab2200bc7bc108f2aa5a301e35ab7bfbc5f8b3: sha256:38ac8d0f5bb30c8b742ad97a328b77870afaec92b33faf7e121161bc78a3fec8
Feb 16 2017 01:48:32.646Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.FetchImageBlob:179] [850.163902ms] library/busybox/sha256:4b0bc1c4050b03c95ef2a8e36e25feac42fd31283e8c30b3ee5df6b043155d3c
Feb 16 2017 01:48:32.646Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.(*ImageC).WriteImageBlob:295] 8243b36f9bd41166cc1fd0a66bab2200bc7bc108f2aa5a301e35ab7bfbc5f8b3
Feb 16 2017 01:48:32.646Z INFO  Path: /tmp/https/registry-1.docker.io/v2/library/busybox/latest/8243b36f9bd41166cc1fd0a66bab2200bc7bc108f2aa5a301e35ab7bfbc5f8b3/8243b36f9bd41166cc1fd0a66bab2200bc7bc108f2aa5a301e35ab7bfbc5f8b3.targ
Feb 16 2017 01:48:32.646Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.WriteImage:82] 8243b36f9bd41166cc1fd0a66bab2200bc7bc108f2aa5a301e35ab7bfbc5f8b3
Feb 16 2017 01:48:33.118Z INFO  Created an image &models.Image{ID:"8243b36f9bd41166cc1fd0a66bab2200bc7bc108f2aa5a301e35ab7bfbc5f8b3", Metadata:map[string]string{"metaData":"{\"id\":\"8243b36f9bd41166cc1fd0a66bab2200bc7bc108f2aa5a301e35ab7bfbc5f8b3\",\"created\":\"2017-01-13T22:13:53.949637331Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c #(nop) ADD file:707e63805c0be1a22662851e9149b8929fb94fd3bd6a6ebe75c8d69d580d8bcb in / \"]}}"}, Parent:"http://ian-vch/storage/images/564def6f-b1e5-c6cf-fa8a-51421654afaa/scratch", SelfLink:"http://ian-vch/storage/images/564def6f-b1e5-c6cf-fa8a-51421654afaa/8243b36f9bd41166cc1fd0a66bab2200bc7bc108f2aa5a301e35ab7bfbc5f8b3", Store:"http://ian-vch/storage/images/564def6f-b1e5-c6cf-fa8a-51421654afaa"}
Feb 16 2017 01:48:33.118Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.WriteImage:82] [471.407918ms] 8243b36f9bd41166cc1fd0a66bab2200bc7bc108f2aa5a301e35ab7bfbc5f8b3
Feb 16 2017 01:48:33.118Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.(*ImageC).WriteImageBlob:295] [471.493439ms] 8243b36f9bd41166cc1fd0a66bab2200bc7bc108f2aa5a301e35ab7bfbc5f8b3
Feb 16 2017 01:48:33.118Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.(*LCache).Commit:114]
Feb 16 2017 01:48:33.118Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.(*LCache).Save:139]
Feb 16 2017 01:48:33.118Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Put:70] layers
Feb 16 2017 01:48:33.159Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Put:70] [40.803834ms] layers
Feb 16 2017 01:48:33.159Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.(*LCache).Save:139] [41.014727ms] 
Feb 16 2017 01:48:33.159Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.(*LCache).Commit:114] [41.024288ms] 
Feb 16 2017 01:48:33.159Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).GetImageID:317] c40e708042c6a113e5827705cf9ace0377fae60cf9ae7a80ea8502d6460d87c6
Feb 16 2017 01:48:33.159Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).GetImageID:317] [5.044µs] c40e708042c6a113e5827705cf9ace0377fae60cf9ae7a80ea8502d6460d87c6
Feb 16 2017 01:48:33.159Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Get:147]
Feb 16 2017 01:48:33.159Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Get:147] [51.553µs] 
Feb 16 2017 01:48:33.159Z INFO  Image ID: sha256:7968321274dc6b6171697c33df7815310468e694ac5be0ec03ff053bb135e768
Feb 16 2017 01:48:33.159Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Add:217]
Feb 16 2017 01:48:33.160Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Add:217] [24.449µs] 
Feb 16 2017 01:48:33.160Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Save:272]
Feb 16 2017 01:48:33.160Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Put:70] images
Feb 16 2017 01:48:33.197Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Put:70] [37.597309ms] images
Feb 16 2017 01:48:33.197Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Save:272] [37.745628ms] 
Feb 16 2017 01:48:33.197Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).AddReference:185]
Feb 16 2017 01:48:33.197Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Save:167]
Feb 16 2017 01:48:33.197Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Put:70] repositories
Feb 16 2017 01:48:33.230Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Put:70] [32.45112ms] repositories
Feb 16 2017 01:48:33.230Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Save:167] [32.550459ms] 
Feb 16 2017 01:48:33.230Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).AddReference:185] [32.568167ms] 
Feb 16 2017 01:48:33.230Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.(*ImageC).WriteImageBlob:295] c40e708042c6a113e5827705cf9ace0377fae60cf9ae7a80ea8502d6460d87c6
Feb 16 2017 01:48:33.230Z INFO  Path: /tmp/https/registry-1.docker.io/v2/library/busybox/latest/c40e708042c6a113e5827705cf9ace0377fae60cf9ae7a80ea8502d6460d87c6/c40e708042c6a113e5827705cf9ace0377fae60cf9ae7a80ea8502d6460d87c6.targ
Feb 16 2017 01:48:33.230Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.WriteImage:82] c40e708042c6a113e5827705cf9ace0377fae60cf9ae7a80ea8502d6460d87c6
Feb 16 2017 01:48:33.628Z INFO  Created an image &models.Image{ID:"c40e708042c6a113e5827705cf9ace0377fae60cf9ae7a80ea8502d6460d87c6", Metadata:map[string]string{"metaData":"{\"architecture\":\"amd64\",\"config\":{\"Hostname\":\"4cfe65ad68c6\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"sh\"],\"Image\":\"sha256:1dccd5cbb1206eda5c8a84f03ef6332d5fa49fe80399fa6448a4eb77eeaa9e3f\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"container\":\"092f3197c0e5034bbf0ef61b9c3829402b50c20907ff6a7c2e06f218fb17c267\",\"container_config\":{\"Hostname\":\"4cfe65ad68c6\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) \",\"CMD [\\\"sh\\\"]\"],\"Image\":\"sha256:1dccd5cbb1206eda5c8a84f03ef6332d5fa49fe80399fa6448a4eb77eeaa9e3f\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"created\":\"2017-01-13T22:13:54.401355854Z\",\"docker_version\":\"1.12.3\",\"id\":\"c40e708042c6a113e5827705cf9ace0377fae60cf9ae7a80ea8502d6460d87c6\",\"os\":\"linux\",\"parent\":\"8243b36f9bd41166cc1fd0a66bab2200bc7bc108f2aa5a301e35ab7bfbc5f8b3\",\"throwaway\":true}"}, Parent:"http://ian-vch/storage/images/564def6f-b1e5-c6cf-fa8a-51421654afaa/8243b36f9bd41166cc1fd0a66bab2200bc7bc108f2aa5a301e35ab7bfbc5f8b3", SelfLink:"http://ian-vch/storage/images/564def6f-b1e5-c6cf-fa8a-51421654afaa/c40e708042c6a113e5827705cf9ace0377fae60cf9ae7a80ea8502d6460d87c6", Store:"http://ian-vch/storage/images/564def6f-b1e5-c6cf-fa8a-51421654afaa"}
Feb 16 2017 01:48:33.628Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.WriteImage:82] [397.823513ms] c40e708042c6a113e5827705cf9ace0377fae60cf9ae7a80ea8502d6460d87c6
Feb 16 2017 01:48:33.628Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.(*ImageC).WriteImageBlob:295] [398.036034ms] c40e708042c6a113e5827705cf9ace0377fae60cf9ae7a80ea8502d6460d87c6
Feb 16 2017 01:48:33.628Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.(*LCache).Commit:114]
Feb 16 2017 01:48:33.628Z DEBUG [BEGIN] [github.com/vmware/vic/lib/imagec.(*LCache).Save:139]
Feb 16 2017 01:48:33.628Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Put:70] layers
Feb 16 2017 01:48:33.670Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/kv.Put:70] [42.381394ms] layers
Feb 16 2017 01:48:33.670Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.(*LCache).Save:139] [42.45112ms] 
Feb 16 2017 01:48:33.670Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.(*LCache).Commit:114] [42.460973ms] 
Feb 16 2017 01:48:33.671Z DEBUG [ END ] [github.com/vmware/vic/lib/imagec.(*LayerDownloader).DownloadLayers:107] [1.875769744s] 
Feb 16 2017 01:48:33.671Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Image).PullImage:296] [3.087726526s] 
Feb 16 2017 01:48:33.672Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate:258]
Feb 16 2017 01:48:33.672Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Get:147]
Feb 16 2017 01:48:33.672Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).getImageByNamed:199]
Feb 16 2017 01:48:33.672Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Get:329]
Feb 16 2017 01:48:33.672Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Get:329] [20.316µs] 
Feb 16 2017 01:48:33.672Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Tags:349]
Feb 16 2017 01:48:33.672Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Tags:349] [11.957µs] 
Feb 16 2017 01:48:33.672Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Digests:364]
Feb 16 2017 01:48:33.672Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Digests:364] [43.415µs] 
Feb 16 2017 01:48:33.672Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).getImageByNamed:199] [159.903µs] 
Feb 16 2017 01:48:33.672Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Tags:349]
Feb 16 2017 01:48:33.672Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Tags:349] [13.775µs] 
Feb 16 2017 01:48:33.672Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Digests:364]
Feb 16 2017 01:48:33.672Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*repoCache).Digests:364] [44.332µs] 
Feb 16 2017 01:48:33.672Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Get:147] [294.808µs] 
Feb 16 2017 01:48:33.672Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.validateCreateConfig:1481] Container.validateCreateConfig
Feb 16 2017 01:48:33.672Z INFO  Container CPU count: 2
Feb 16 2017 01:48:33.672Z INFO  Container memory: 2048 MB
Feb 16 2017 01:48:33.673Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.validateCreateConfig:1481] [401.931µs] Container.validateCreateConfig
Feb 16 2017 01:48:33.673Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).containerCreate:316] Container.containerCreate
Feb 16 2017 01:48:33.673Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).CreateContainerHandle:165] c40e708042c6a113e5827705cf9ace0377fae60cf9ae7a80ea8502d6460d87c6
Feb 16 2017 01:48:33.688Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).CreateContainerHandle:165] [14.933374ms] c40e708042c6a113e5827705cf9ace0377fae60cf9ae7a80ea8502d6460d87c6
Feb 16 2017 01:48:33.688Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).AddContainerToScope:206] 931e0f9cfe82d8473d4967b9bedc7fe5
Feb 16 2017 01:48:33.689Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).AddContainerToScope:206] [653.32µs] 931e0f9cfe82d8473d4967b9bedc7fe5
Feb 16 2017 01:48:33.689Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).AddInteractionToContainer:367] 931e0f9cfe82d8473d4967b9bedc7fe5
Feb 16 2017 01:48:33.689Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).AddInteractionToContainer:367] [533.956µs] 931e0f9cfe82d8473d4967b9bedc7fe5
Feb 16 2017 01:48:33.689Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).AddLoggingToContainer:340] 931e0f9cfe82d8473d4967b9bedc7fe5
Feb 16 2017 01:48:33.690Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).AddLoggingToContainer:340] [418.642µs] 931e0f9cfe82d8473d4967b9bedc7fe5
Feb 16 2017 01:48:33.690Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).AddVolumesToContainer:250] 931e0f9cfe82d8473d4967b9bedc7fe5
Feb 16 2017 01:48:33.690Z INFO  Specified Volumes : []string(nil)
Feb 16 2017 01:48:33.690Z INFO  anonymous Volumes : []string{}
Feb 16 2017 01:48:33.690Z INFO  Finalized Volume list : []backends.volumeFields{}
Feb 16 2017 01:48:33.690Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).AddVolumesToContainer:250] [36.76µs] 931e0f9cfe82d8473d4967b9bedc7fe5
Feb 16 2017 01:48:33.690Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).CommitContainerHandle:393] 931e0f9cfe82d8473d4967b9bedc7fe5
Feb 16 2017 01:48:33.809Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).CommitContainerHandle:393] [118.961747ms] 931e0f9cfe82d8473d4967b9bedc7fe5
Feb 16 2017 01:48:33.809Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).containerCreate:316] [135.719645ms] Container.containerCreate
Feb 16 2017 01:48:33.809Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerCreate:258] [136.535165ms] 
Feb 16 2017 01:48:33.817Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStart:537] dbf1eeb18d0b1a4d55c86e950416e32b484bfbe2037f5f28ee1739bb8b387e1a
Feb 16 2017 01:48:33.817Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/retry.Do:38]
Feb 16 2017 01:48:42.604Z DEBUG [ END ] [github.com/vmware/vic/pkg/retry.Do:38] [8.787577293s] 
Feb 16 2017 01:48:42.604Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStart:537] [8.787718629s] dbf1eeb18d0b1a4d55c86e950416e32b484bfbe2037f5f28ee1739bb8b387e1a
Feb 16 2017 01:48:42.648Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStop:901] dbf1eeb18d0b1a4d55c86e950416e32b484bfbe2037f5f28ee1739bb8b387e1a
Feb 16 2017 01:48:42.648Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/retry.Do:38]
Feb 16 2017 01:48:42.648Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).Stop:464] dbf1eeb18d0b1a4d55c86e950416e32b484bfbe2037f5f28ee1739bb8b387e1a
Feb 16 2017 01:48:42.661Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).IsRunning:541]
Feb 16 2017 01:48:42.675Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Get:147]
Feb 16 2017 01:48:42.675Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).getImageByDigest:188]
Feb 16 2017 01:48:42.676Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).getImageByDigest:188] [16.315µs] 
Feb 16 2017 01:48:42.676Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends/cache.(*ICache).Get:147] [83.28µs] 
Feb 16 2017 01:48:42.676Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).IsRunning:541] [14.335699ms] 
Feb 16 2017 01:48:42.677Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).Stop:464] [29.188331ms] dbf1eeb18d0b1a4d55c86e950416e32b484bfbe2037f5f28ee1739bb8b387e1a
Feb 16 2017 01:48:42.677Z DEBUG [ END ] [github.com/vmware/vic/pkg/retry.Do:38] [29.218087ms] 
Feb 16 2017 01:48:42.677Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStop:901] [29.310846ms] dbf1eeb18d0b1a4d55c86e950416e32b484bfbe2037f5f28ee1739bb8b387e1a
2017-02-16 01:48:42.677481 I | http: panic serving 192.168.218.148:36354: runtime error: invalid memory address or nil pointer dereference
goroutine 124 [running]:
net/http.(*conn).serve.func1(0xc4205d3a80)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x19cb980, 0xc42000e060)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/lib/apiservers/engine/backends.(*ContainerProxy).Stop(0xc420367530, 0xc420ccb080, 0xc4205ccef7, 0x40, 0x0, 0xed036fb01, 0x0, 0x0)
	/go/src/github.com/vmware/vic/lib/apiservers/engine/backends/container_proxy.go:527 +0x453
github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStop.func1(0xc4204fd938, 0x2d1da20)
	/go/src/github.com/vmware/vic/lib/apiservers/engine/backends/container.go:910 +0x5e
github.com/vmware/vic/pkg/retry.Do(0xc420c0ae70, 0x1e445f0, 0x0, 0x0)
	/go/src/github.com/vmware/vic/pkg/retry/retry.go:54 +0x163
github.com/vmware/vic/lib/apiservers/engine/backends.(*Container).ContainerStop(0xc420358380, 0xc4205ccef7, 0x40, 0x0, 0x0, 0x0)
	/go/src/github.com/vmware/vic/lib/apiservers/engine/backends/container.go:912 +0x156
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container.(*containerRouter).postContainersStop(0xc4201b7fc0, 0x7f73f2ca6ac0, 0xc420c0ad80, 0x2ccd620, 0xc420bcf790, 0xc4200bb860, 0xc420c0acc0, 0x0, 0x0)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container/container_routes.go:181 +0xe6
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container.postContainersStop)-fm(0x7f73f2ca6ac0, 0xc420c0ad80, 0x2ccd620, 0xc420bcf790, 0xc4200bb860, 0xc420c0acc0, 0x7f73f2ca6ac0, 0xc420c0ad80)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/container/container.go:61 +0x69
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x2ccd620, 0xc420bcf790, 0xc4200bb860)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/server.go:139 +0x22c
net/http.HandlerFunc.ServeHTTP(0xc42043d5c0, 0x2ccd620, 0xc420bcf790, 0xc4200bb860)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4205ff310, 0x2ccd620, 0xc420bcf790, 0xc4200bb860)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc4201a5830, 0x2ccd620, 0xc420bcf790, 0xc4200bb860)
	/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router_swapper.go:29 +0x70
net/http.serverHandler.ServeHTTP(0xc42059a280, 0x2ccd620, 0xc420bcf790, 0xc4200bb860)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4205d3a80, 0x2ccf4a0, 0xc420c80e40)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

### PR DESCRIPTION
**Pull request by sflxn**
The function signature changed but we didn't check for nil.
It's now properly handling the stop timeout the same way
that docker does.

Resolves #3976

### CODE REVIEW

File: lib/apiservers/engine/backends/container.go [hunk 1]
```diff
@@ -906,6 +908,16 @@ func (c *Container) ContainerStop(name string, seconds *int) error {
...
+	if seconds == nil {
+		var timeout int
+		if vc.Config.StopTimeout != nil {
+			timeout = *vc.Config.StopTimeout
+		} else {
+			timeout = DefaultStopTimeout
+		}
+		seconds = &timeout
+	}
+
```
Comment (caglar10ur) [inline lib/apiservers/engine/backends/container.go]:
```
	if seconds == nil {
 		timeout := DefaultStopTimeout
 		if vc.Config.StopTimeout != nil {
 			timeout = *vc.Config.StopTimeout 			
 		}
 		seconds = &timeout
 	}
```

**Comment by gigawhitlocks** [comment]
One thing though: this definitely needs a regression test as mentioned by the tag in the issue

**Comment by mdubya66** [comment]
agreed, this needs a regression test with this merge

**Comment by sflxn** [comment]
The regression test is to switch over to the docker 1.13 client in our CI.

**Comment by mdubya66** [comment]
as discussed in slack let's provide a specific test for version 1.13 for this test case.

File: lib/apiservers/engine/backends/container.go (hunk 1 above)
Comment (sflxn) [inline lib/apiservers/engine/backends/container.go]: :) I considered this.  Being a C guy, I figured one less assignment was more efficient but fine.
