### PR TITLE
Fix broken portlets

### LINKED ISSUE #4111: VIC UI Portlets are broken
After merging the recent PRs portlets are broken in the VM Summary tab view. This is because the Angular app could not parse the Object ID properly from the parent frame. 

**Actual behavior:**
image

**Expected behavior:**
Portlets should be displayed correctly

### PR DESCRIPTION
**Pull request by jooskim**
This PR fixes #4111 by passing the Object ID from `app-routing.component.ts` to the `DataPropertyService` via `SummaryPortletComponent`. It no longer depends on platform API.

### CODE REVIEW

File: ui/vic-ui-h5c/vic/src/vic-app/src/app/summary-portlet/summary-portlet.component.ts [hunk 1]
```diff
@@ -77,7 +77,12 @@ export class VicSummaryPortletComponent implements
 
     ngAfterViewInit() {
         setTimeout(() => {
-            this.service.fetchVmInfo(VM_PROPERTIES_TO_EXTRACT, this.stubType);
+            // set up objectId in data property service
+            this.route.params.subscribe((params: any) => {
+                this.service.setObjectId(params.id);
+                this.service.fetchVmInfo(VM_PROPERTIES_TO_EXTRACT, this.stubType);
+                console.log(`objectId set to ${params.id}`);
```
Comment (jak-atx) [inline ui/vic-ui-h5c/vic/src/vic-app/src/app/summary-portlet/summary-portlet.component.ts]: Do you need to keep this here? If it's only for debugging let's remove.

Comment (jooskim) [inline ui/vic-ui-h5c/vic/src/vic-app/src/app/summary-portlet/summary-portlet.component.ts]: All `console.log` statements get removed during the production build process. Those are quite useful when testing with the dev build mode which doesn't remove them.

Comment (jooskim) [inline ui/vic-ui-h5c/vic/src/vic-app/src/app/summary-portlet/summary-portlet.component.ts]: Do you think we should still remove them for the sake of cleanness?
