### PR TITLE
vic-machine will not include VCH memory with snapshot

### LINKED ISSUE #7083: Failed upgrades create multiple snapshots
VIC Engine - v1.2.1-13858-c3db65f > v1.3.0-**15556**-473375a

User statement: As a customer of VIC, I would like to have upgrade and reversion to be seamless. Upgrade process could also check if there's an existing Snapshot (due to earlier failure) before creating a new one of the same name.

time="2018-01-11T18:28:25+08:00" level=info msg="Rolling back upgrade"
time="2018-01-11T18:28:25+08:00" level=info msg="Reverting to snapshot reconfigure for **15556**"
time="2018-01-11T18:28:40+08:00" level=error msg="Failed to revert appliance to snapshot: Failed to roll back upgrade: \"reconfigure for 15556\" resolves to 2 snapshots."

if upgrade is successful, vic-machine could optionally prompt to delete the snapshot taken.

### PR DESCRIPTION
**Pull request by cgtexmex**
vic-machine takes a snapshot of the current appliance when facilitating
a configure or upgrade.  It does not need to snap the current appliance
memory.  This change will increase the performance of configure and
upgrade.

[specific ci=Group11-Upgrade --suite 6-16-Config]

Fixes: #6264, Fixes #7083

### CODE REVIEW

**Comment by zjs** [comment]
Do we have a test case that verifies that the issue described in https://github.com/vmware/vic/issues/6264#issuecomment-329669435 no longer occurs? I don't _see_ a test that performs that workflow in Group 6, but those tests aren't well organized so it's possible I'm missing it.

**Comment by cgtexmex** [comment]
@zjs I'm looking into #6264 (thanks @hickeng )..so I'll let you know.  If it takes to long I'll be punting this as it's not a requirement of ROBO, but would help with ROBO testing, etc..

**Comment by cgtexmex** [comment]
The CI test failed because the appliance VM is not poweredOn -- when you take a snap w/o memory it restores in poweredOff state.  I'll change the rollback func to now start the rolled back appliance.

**Comment by cgtexmex** [comment]
@zjs in a failed upgrade..(like the one caused by the test w/a 1s timeout)..we would never delete the created snapshot because this [func](https://github.com/vmware/vic/blob/master/lib/install/management/configure.go#L106)  returns the VCH Appliance reference and not the snapshot reference.  I'll correct that..

**Comment by cgtexmex** [comment]
Test failed again for same reason -- the VCH hadn't powered on yet -- will need to update the test to wait, etc..

**Comment by cgtexmex** [comment]
nudge @zjs @hickeng @mhagen-vmware

File: lib/install/management/configure.go [hunk 1]
```diff
@@ -258,21 +258,25 @@ func (d *Dispatcher) deleteSnapshotByRef(snapshot *types.ManagedObjectReference,
 	return nil
 }
 
-// tryCreateSnapshot try to create upgrade snapshot. It will check if upgrade snapshot already exists. If exists, return error.
-// if succeed, return snapshot refID
-func (d *Dispatcher) tryCreateSnapshot(name, desc string) (*types.ManagedObjectReference, error) {
+// createSnapshot will create a snapshot of the VCH Appliance
+func (d *Dispatcher) createSnapshot(name, desc string) (*types.ManagedObjectReference, error) {
```
Comment (anchal-agrawal) [inline lib/install/management/configure.go]: Nice function name change 👍

File: lib/install/management/configure.go [hunk 2]
```diff
@@ -258,21 +258,25 @@ func (d *Dispatcher) deleteSnapshotByRef(snapshot *types.ManagedObjectReference,
...
-		return d.appliance.CreateSnapshot(ctx, name, desc, true, false)
+		return d.appliance.CreateSnapshot(ctx, name, desc, false, false)
 	})
 	if err != nil {
 		return nil, errors.Errorf("Failed to create upgrade snapshot %q: %s.", name, err)
 	}
-	return info.Entity, nil
+	snap, ok := info.Result.(types.ManagedObjectReference)
+	if !ok {
+		// TODO: what to do in this situation..
```
Comment (anchal-agrawal) [inline lib/install/management/configure.go]: What should we do here? Also, is there a difference b/w `info.Entity` and `info.Result`?

Comment (anchal-agrawal) [reply lib/install/management/configure.go]: > Also, is there a difference b/w info.Entity and info.Result?

Oh I see, I think it's because https://github.com/vmware/vic/pull/7574#issuecomment-375498998

Comment (matthewavery) [inline lib/install/management/configure.go]: my 0.02$ here is that we have to fail the attempt to configure/upgrade(I saw this in the configure function, but I am not 100% familiar with the call path). I am surprised we do not attempt the snapshot first in that function. Since we would want the ability to rollback first and foremost. I might be misunderstanding some of the complexity to what is happening in the configure function, but it seems like we should abort if we are not at the very least able to guarantee a return to the old state of the VCH.

Comment (matthewavery) [reply lib/install/management/configure.go]: I might not understand what has happened here as well. Is it possible to get an empty result object on a successful snapshot creation?

Comment (cgtexmex) [reply lib/install/management/configure.go]: `info.Entity` is the object acted on (vm in this case) -- `info.Result` is what resulted..so in this case the snapshot --- my _assumption_ is that if this would not work....it would have failed earlier during the task...

Comment (cgtexmex) [reply lib/install/management/configure.go]: we do snap before the upgrade...so if the snap fails we will fail the upgrade / configure

Comment (cgtexmex) [reply lib/install/management/configure.go]: So to put it another way...if there was no valid result then we wouldn't even make it here...

Comment (anchal-agrawal) [reply lib/install/management/configure.go]: Agreed. Perhaps the type check isn't needed, because the `info.Result` should be a moref if `CreateSnapshot` returned no error.

Comment (cgtexmex) [reply lib/install/management/configure.go]: it's a cast not a check -- it returns as `AnyType` and we have to cast to the a moref -- if this fails we should return an error so that we fail the upgrade...again I doubt we'd ever hit it..but as soon as I say that...we'll hit it...so I'll push an update in a minute

Comment (matthewavery) [reply lib/install/management/configure.go]: understood, I was looking at the `Configure` function and I was just noticing that we upload the ISOs(potentially) before we take the snapshot. Not related to this PR, it just seemed out of order.

Comment (anchal-agrawal) [reply lib/install/management/configure.go]: Haha, thanks for explaining!
