### PR TITLE
[specific ci=Group1-Docker-Commands]return device in use message if two containers using same volumes

### LINKED ISSUE #5571: Handle failure to lock vmdk during container start
**VIC version:**
dev - 732f8779ba924a582464b5c6c9317da0bae7f445

**Deployment details:**
Generic VCH with default volume store configured

```
vic-machine-linux create --target=https://192.168.78.128 --image-store=datastore1/localtls/images --compute-resource= --name=localtls --container-network=VMExternal:external --volume-store=datastore1/volumes:default --volume-store=datastore1/other-volumes:others --public-network-ip=192.168.78.127/24 --public-network-gateway=192.168.78.2 --dns-server=10.132.71.1 --dns-server=10.132.71.2 --thumbprint= --debug=2
```

**Steps to reproduce:**
```
$ docker volume create
f6cbafbf-0b8e-4368-af3d-035e0c409217
$ docker run -dit -v f6cbafbf-0b8e-4368-af3d-035e0c409217:/var/tmp busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
27144aa8f1b9: Pull complete
a3ed95caeb02: Pull complete
Digest: sha256:be3c11fdba7cfe299214e46edc642e09514dbb9bbefcd0d3836c05a1e0cd0642
Status: Downloaded newer image for library/busybox:latest
eeea17a4de4ff93410c885dba2ba6073daa2cb5fc4d06d4aa50e9b55c13c0922
$ docker run -dit -v f6cbafbf-0b8e-4368-af3d-035e0c409217:/var/tmp busybox
8f534a02bffa167b0fb229b7a9659d6ebc3f246d50af335387f4d45d638a241a
docker: Error response from daemon: Server error from portlayer: File system specific implementation of LookupAndOpen[file] failed.
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                     PORTS               NAMES
8f534a02bffa        busybox             "sh"                5 hours ago         Starting                                       wonderful_goldberg
eeea17a4de4f        busybox             "sh"                5 hours ago         Exited (143) 5 hours ago                       clever_goldwasser
```

**Actual behavior:**
ContainerVM fails to start
docker ps lists container as `Starting` indefinitely

**Expected behavior:**
ContainerVM fails to start
docker ps lists container as `Stopped` to reflect it's power state (off)

### PR DESCRIPTION
**Pull request by emlin**
fixes #5571

This PR will return the locked device information in error message, and set stopped status if VM powered on task failed directly

### CODE REVIEW

**Comment by jialin-li** [comment]
lgtm

File: lib/portlayer/exec/container.go [hunk 1]
```diff
@@ -351,6 +362,28 @@ func (c *Container) start(ctx context.Context) error {
...
+		// change state to stopped because start task failed
+		c.SetState(StateStopped)
+
+		// check if locked disk error
+		devices := disk.LockedDisks(err)
+		if len(devices) > 0 {
+			for i := range devices {
+				// get device id from datastore file path
+				// FIXME: find a reasonable way to get device ID from datastore path in exec
+				devices[i] = strings.TrimSuffix(path.Base(devices[i]), ".vmdk")
```
Comment (chengwang86) [inline lib/portlayer/exec/container.go]: Do all the devices have the same suffix of vmdk?

Comment (emlin) [inline lib/portlayer/exec/container.go]: hmm.. good question. Might not, but if that's file locked issue, in our case, most likely it's vmdk file attached to multiple VMs.
I didn't see other scenario for that. 

But no matter how, this is just the best effort we can do right now to get the device ID instead of device path, cause the device path does not mean anything for end user. 
If there's any other file conflict happened, it would be better to keep the file suffix, I think
