### PR TITLE
Fix vch imagestore deletion

### LINKED ISSUE #8613: Can not remove the custom image store folder when deleting vch in the vsphere7.0
test build:
vc: 15423980
esxi: 15423978

image

This does not happen within vsphere 67U3.
This issue easy to reproduce. Steps is as following
1. we use vic-machine-linux to create VCH 
bin/vic-machine-linux create --name=VCH-21277-2535 --target=10.199.17.15 --thumbprint=B4:C6:4F:BB:2B:46:E4:49:AB:5F:2E:2E:DF:CE:D9:75:9E:25:8F:6B --user=administrator@vsphere.local **--image-store datastore1/vic-machine-test-images** --appliance-iso=bin/appliance.iso --bootstrap-iso=bin/bootstrap.iso --password=Alfred!23 --force=true --bridge-network=VCH-21277-122 --public-network=vm-network --compute-resource=/dc1/host/cls --timeout 3m --tls-cname=*.eng.vmware.com --insecure-registry wdc-harbor-ci.eng.vmware.com 2>&1
2. delete the VCH and finding in the datadstore, the folder vic-machine-test-images still exists.
the output of vic-machine-linux delete is as below
_time="2020-01-21T14:12:57Z" level=info msg="### Removing VCH ####" 
time="2020-01-21T14:12:58Z" level=info msg="Validating target" 
time="2020-01-21T14:12:58Z" level=info 
time="2020-01-21T14:12:58Z" level=info msg="VCH ID: VirtualMachine:vm-1218" 
time="2020-01-21T14:12:58Z" level=info msg="Removing VMs" 
time="2020-01-21T14:12:58Z" level=info msg="Removing image stores" 
time="2020-01-21T14:12:59Z" level=info msg="Removing volume stores" 
time="2020-01-21T14:12:59Z" level=info msg="Removing appliance VM network devices" 
time="2020-01-21T14:13:24Z" level=error msg="vic/pkg/trace.(*Operation).Err: Shut down endpointVM error: context deadline exceeded\nvic/lib/install/management.(*Dispatcher).powerOffVM:162 Shut down endpointVM\nvic/cmd/vic-machine/delete.(*Uninstall).Run:92 vic-machine-linux\nvic/cmd/vic-machine/common.NewOperation:27 vic-machine-linux" 
time="2020-01-21T14:13:24Z" level=warning msg="Guest shutdown timed out, resorting to power off - sessions may be left open: Post https://10.199.17.15/sdk: context deadline exceeded" 
time="2020-01-21T14:13:24Z" level=error msg="unexpected fault on task retry: &types.InvalidPowerState{InvalidState:types.InvalidState{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}, RequestedState:\"poweredOn\", ExistingState:\"poweredOff\"}" 
time="2020-01-21T14:13:25Z" level=info msg="Removing Resource Pool \"VCH-21277-2535\"" 
time="2020-01-21T14:13:25Z" level=info msg=---------- 
time="2020-01-21T14:13:25Z" level=info msg="If firewall changes were made for VIC during install, they were not reverted during delete" 
time="2020-01-21T14:13:25Z" level=info msg="To modify firewall rules see vic-machine update firewall --help" 
time="2020-01-21T14:13:25Z" level=info msg=---------- 
time="2020-01-21T14:13:25Z" level=info msg="Completed successfully"_

### PR DESCRIPTION
**Pull request by wjun**
In VC 7.0, datastore path changes, so we need to
add a new condition.

[specific ci=Group1-Docker-Commands]

Fixes #8613

### CODE REVIEW

File: lib/install/management/store_files.go [hunk 1]
```diff
@@ -88,13 +88,13 @@ func (d *Dispatcher) deleteImages(conf *config.VirtualContainerHostConfigSpec, v
 			continue
 		}
 
-		if len(children) == 1 { // when image store path is given, we need to delete VIC dir too when it is empty.
+		if len(children) == 1 || len(children) == 0 { // when image store path is given, we need to delete VIC dir too when it is empty.
```
Comment (YanzhaoLi) [inline lib/install/management/store_files.go]: Not familiar with these code. What does `|| len(children) == 0 ` mean?

Comment (yuyangbj) [reply lib/install/management/store_files.go]: i think it is empty dir

Comment (YanzhaoLi) [reply lib/install/management/store_files.go]: > i think it is empty dir

So in vc7.0, `len(children) == 0 or 1`  means empty dir, while in vc6.x only `len(children) == 1` means empty dir
