### PR TITLE
[skip ci][harbor] Add notary port, move common to ephemeral storage, fix makefile

### LINKED ISSUE #4354: Notary DB startup has a race condition
When `notary-db` starts up enters in a race condition with `harbor-log`, this is being tracked upstream as vmware/harbor#1738

### LINKED ISSUE #4373: Harbor UI and Jobservice can't connect to MySQL
This issue tracks the problem upstream on vmware/harbor#1771

### PR DESCRIPTION
**Pull request by frapposelli**
Fixes #4354
Fixes #4373

### CODE REVIEW

File: installer/scripts/build-bundle.sh [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+# exit on failure and configure debug, include util functions
+set -e && [ -n "$DEBUG" ] && set -x
+DIR=$(dirname $(readlink -f "$0"))
+
+function usage() {
+echo "Usage: $0 -o outputfile -b bin_dir" 1>&2
```
Comment (dougm) [inline installer/scripts/build-bundle.sh]: forgot to run `bashfmt` ?

File: installer/scripts/build-bundle.sh [hunk 2]
```diff
@@ -0,0 +1,61 @@
+#!/bin/bash
+# Copyright 2016 VMware, Inc. All Rights Reserved.
```
Comment (anchal-agrawal) [inline installer/scripts/build-bundle.sh]: Do we mean `2017`?

**Comment by frapposelli** [comment]
thanks folks, appreciate the after hours review 😄
