### PR TITLE
Fixing pointer serialization/deserialization

### LINKED ISSUE #1853: extraconfig package pointer serialization/deserialization is not symmetric
When serializing a `nil` pointer, the extraconfig package will skip writing its key to guestinfo. However, when deserializing the corresponding pointer, if the key does not exist in guestinfo, extraconfig will still allocate an object to assign to the pointer.

### PR DESCRIPTION
**Pull request by hmahmood**
Fixes #1853 

Not required for 0.5.0

### CODE REVIEW

**Comment by caglar10ur** [comment]
LGTM, @hickeng you might want to take a look at this PR

File: pkg/vsphere/extraconfig/decode.go [hunk 1]
```diff
@@ -334,7 +331,7 @@ func decodeMap(src DataSource, dest reflect.Value, prefix string, depth recursio
 	mapkeys, err := src(prefix)
 	if mapkeys == "" || err != nil {
 		log.Debugf("No value found in data source for maps keys \"%s\"", prefix)
-		return this
+		return reflect.ValueOf(nil)
```
Comment (hickeng) [inline pkg/vsphere/extraconfig/decode.go]: This requires every reference to a map element, pointer or otherwise, to check for nil. I'd prefer to have an empty map returned. If you must absolutely have a nil pointer in the case of a pointer to a map, then check for map size explicitly.

Comment (hmahmood) [inline pkg/vsphere/extraconfig/decode.go]: This is returned from an unexported function, and I tried to make all of the `decodeX` functions follow the same pattern, i.e. return reflect.ValueOf(nil) in case of error. Returning a nil map would disrupt this pattern, since we can't return for every type that we decode in case of error.

I will add some tests for the error cases.

Comment (hickeng) [inline pkg/vsphere/extraconfig/decode.go]: That precise issue is why I hadn't implemented the nil pointer logic yet. Perhaps we can add a boolean field to decode that denotes whether it's hung from a pointer or not. That would allow us to control on a type by type basis whether you get zero value or nil pointer.

**Comment by hmahmood** [comment]
@caglar10ur @hickeng can you guys take a look at this again please? Thanks.

File: pkg/vsphere/extraconfig/store.go [hunk 2]
```diff
@@ -43,7 +42,7 @@ func (t *MapStore) Get(key string) (string, error) {
 
 	val, ok := t.store[key]
 	if !ok {
-		return "", os.ErrNotExist
+		return "", ErrKeyNotFound
```
Comment (caglar10ur) [inline pkg/vsphere/extraconfig/store.go]: Do we have any callers type asserting for os.ErrNotExist?

**Comment by caglar10ur** [comment]
Overall LGTM, https://github.com/vmware/vic/pull/1854/files#r74861264 is the only comment I have

File: pkg/vsphere/extraconfig/store.go (hunk 2 above)
Comment (hmahmood) [inline pkg/vsphere/extraconfig/store.go]: I made an attempt to find all callers and fix them. Don't think I missed any in our source at least.

**Comment by hickeng** [comment]
Thanks! LGTM

**Comment by hmahmood** [comment]
:recycle:
