### PR TITLE
Fixes panic during container create on VC using resource pool

### LINKED ISSUE #2460: Unable to create containers on VC when using a resource pool
If you install vic to a vsphere cluster and specify the use of a resource pool instead of a vApp container create will fail.  

```
time="2016-09-23T20:31:44Z" level=debug msg="[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler] [299.385µs] Containers.CommitHandler" 
2016/09/23 20:31:44 http: panic serving 192.168.175.183:44192: runtime error: invalid memory address or nil pointer dereference
goroutine 74 [running]:
net/http.(*conn).serve.func1(0xc420884c80)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xe18080, 0xc42000e050)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/vendor/github.com/vmware/govmomi/object.VirtualApp.CreateChildVM_Task(0x0, 0x1986620, 0xc42000e468, 0x0, 0x0, 0xc4204461e0, 0x50, 0x0, 0x0, 0xc42079ea20, ...)
	/Users/cgreenwood/CNA/go/src/github.com/vmware/vic/vendor/github.com/vmware/govmomi/object/virtual_app.go:39 +0x54
github.com/vmware/vic/lib/portlayer/exec.(*Container).Commit.func2(0x1986620, 0xc42000e468, 0xc420192ed0, 0x1, 0x1, 0xc42032a6f0)
	/Users/cgreenwood/CNA/go/src/github.com/vmware/vic/lib/portlayer/exec/container.go:152 +0x90
github.com/vmware/vic/pkg/vsphere/tasks.WaitForResult(0x1986620, 0xc42000e468, 0xc4201930b8, 0xd, 0x12e7701, 0x3c)
	/Users/cgreenwood/CNA/go/src/github.com/vmware/vic/pkg/vsphere/tasks/waiter.go:64 +0x63
github.com/vmware/vic/lib/portlayer/exec.(*Container).Commit(0xc420154c80, 0x1986620, 0xc42000e468, 0xc420410050, 0xc42078a360, 0x0, 0x0, 0x0)
	/Users/cgreenwood/CNA/go/src/github.com/vmware/vic/lib/portlayer/exec/container.go:153 +0x9d4
github.com/vmware/vic/lib/portlayer/exec.(*Handle).Commit(0xc42078a360, 0x7f65d5721d68, 0xc42000e468, 0xc420410050, 0x0, 0x67, 0xecf778830)
	/Users/cgreenwood/CNA/go/src/github.com/vmware/vic/lib/portlayer/exec/handle.go:167 +0x2a2
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler(0xc42042a050, 0xc42087ce10, 0xc4204805d0, 0x20, 0x0, 0x0, 0x0)
	/Users/cgreenwood/CNA/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/containers_handlers.go:216 +0x15f
github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).CommitHandler-fm(0xc42087ce10, 0xc4204805d0, 0x20, 0x0, 0x30003c420193a01, 0xc42057aa20)
	/Users/cgreenwood/CNA/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers/containers_handlers.go:55 +0x52
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers.CommitHandlerFunc.Handle(0xc420310620, 0xc42087ce10, 0xc4204805d0, 0x20, 0x0, 0x0, 0x0)
	/Users/cgreenwood/CNA/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers/commit.go:17 +0x4e
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers.(*Commit).ServeHTTP(0xc4205ae120, 0x1985a60, 0xc4206a6000, 0xc42087ce10)
	/Users/cgreenwood/CNA/go/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers/commit.go:49 +0x1c7
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1(0x1985a60, 0xc4206a6000, 0xc42087ce10)
	/Users/cgreenwood/CNA/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23 +0x69
net/http.HandlerFunc.ServeHTTP(0xc4204180f0, 0x1985a60, 0xc4206a6000, 0xc42087ce10)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1(0x1985a60, 0xc4206a6000, 0xc42087ce10)
	/Users/cgreenwood/CNA/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:78 +0x555
net/http.HandlerFunc.ServeHTTP(0xc4205a5900, 0x1985a60, 0xc4206a6000, 0xc42087ce10)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1(0x1985a60, 0xc4206a6000, 0xc42087ce10)
	/Users/cgreenwood/CNA/go/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36 +0x7b
net/http.HandlerFunc.ServeHTTP(0xc420614ba0, 0x1985a60, 0xc4206a6000, 0xc42087ce10)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc420884c00, 0x1985a60, 0xc4206a6000, 0xc42087ce10)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420884c80, 0x19865e0, 0xc4205a5c00)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

### PR DESCRIPTION
**Pull request by cgtexmex**
If you install vic to a vSphere cluster and specify the use of a resource pool instead of a vApp container create will fail.

fixes #2460

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
lgtm

**Comment by andrewtchin** [comment]
lgtm

File: lib/portlayer/exec/container.go [hunk 1]
```diff
@@ -146,7 +146,7 @@ func (c *Container) Commit(ctx context.Context, sess *session.Session, h *Handle
 		var res *types.TaskInfo
 		var err error
 
-		if sess.IsVC() && Config.VirtualApp != nil {
+		if sess.IsVC() && Config.VirtualApp.ResourcePool != nil {
```
Comment (hmahmood) [inline lib/portlayer/exec/container.go]: Is VirttualApp always not nil?
