### PR TITLE
Fix already bound error on container restart

### LINKED ISSUE #1086: Restarting a stopped container fails with "already bound"
Once a container has stopped due to exit of the main container process (as opposed to via an explicit stop command), restarting that container will fail with "already bound". Container can still be started successfully directly via UI or govc.
To work around this call stop on the container - this will return an error currently, but will allow a subsequent start operation to succeed:

work around:
```
vagrant@devbox:~/vic/bin$ docker -H 192.168.78.245:2376 --tls start -ai eb35c2e622f53d172a6ab41576b3de0493b7eb5dfe20e0121b142ab13fa87a6c
Error response from daemon: container eb35c2e622f53d172a6ab41576b3de0493b7eb5dfe20e0121b142ab13fa87a6c already bound
vagrant@devbox:~/vic/bin$ docker -H 192.168.78.245:2376 --tls stop eb35c2e622f53d172a6ab41576b3de0493b7eb5dfe20e0121b142ab13fa87a6c
Error response from daemon: server error from portlayer
Error: failed to stop containers: [eb35c2e622f53d172a6ab41576b3de0493b7eb5dfe20e0121b142ab13fa87a6c]
vagrant@devbox:~/vic/bin$ docker -H 192.168.78.245:2376 --tls start  eb35c2e622f53d172a6ab41576b3de0493b7eb5dfe20e0121b142ab13fa87a6c
vagrant@devbox:~/vic/bin$
vagrant@devbox:~/vic/bin$ docker -H 192.168.78.245:2376 --tls attach eb35c2e622f53d172a6ab41576b3de0493b7eb5dfe20e0121b142ab13fa87a6c
/ # 
``` 

Error case:
```
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(restart)] $Z create -it golang
b372c1a48391f2379582803a16cd5666936e9e96d3f0aa102f1101c6ce225d07
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(restart)] $Z start b372c1a48391f2379582803a16cd5666936e9e96d3f0aa102f1101c6ce225d07
b372c1a48391f2379582803a16cd5666936e9e96d3f0aa102f1101c6ce225d07
[vagrant@devbox:/opt/go/src/github.com/vmware/vic(restart)] $Z attach b372c1a48391f2379582803a16cd5666936e9e96d3f0aa102f1101c6ce225d07
root@b372c1a48391:/go#
root@b372c1a48391:/go# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  4.4  0.0   4336   680 tty1     Ss+  18:37   0:01 /bin/sh /.tether/tether
[...]root       209  1.4  0.7 225916 14792 tty1     Sl+  18:37   0:00 /.tether/tether-bin
root       214  0.0  0.1  20248  3200 pts/0    Ss   18:37   0:00 /bin/bash
root       219  0.0  0.0  17500  2052 pts/0    R+   18:37   0:00 ps aux
root@b372c1a48391:/go# exit

[vagrant@devbox:/opt/go/src/github.com/vmware/vic(restart)] $Z start b372c1a48391f2379582803a16cd5666936e9e96d3f0aa102f1101c6ce225d07
Error response from daemon: container b372c1a48391f2379582803a16cd5666936e9e96d3f0aa102f1101c6ce225d07 already bound
Error: failed to start containers: b372c1a48391f2379582803a16cd5666936e9e96d3f0aa102f1101c6ce225d07
```

started to observe after https://github.com/vmware/vic/pull/1029

### PR DESCRIPTION
**Pull request by andrewtchin**
Fixes #1086 

```
chin@ubuntu:~/go/src/github.com/vmware/vic|1086/already-bound 
⇒  docker -H 192.168.218.141:2376 --tls create -it golang
Unable to find image 'golang:latest' locally
Pulling from library/golang
a79803310595: Pull complete 
8ad8b3f87b37: Pull complete 
a3ed95caeb02: Pull complete 
751fe39c4d34: Pull complete 
ae3b77eefc06: Pull complete 
92c7f8737c98: Pull complete 
bf37bbda794c: Pull complete 
6e9d2df2553b: Pull complete 
Digest: sha256:ddf30fb99905cf90292825504d453289ccbc3f6b0ff4e087c1c4d0e487ee3314
Status: Downloaded newer image for library/golang:latest
da897d227c6c18209abbb66c15702d78db6fc8bdea02ae61b3e3d104d1cff351
chin@ubuntu:~/go/src/github.com/vmware/vic|1086/already-bound 
⇒  docker -H 192.168.218.141:2376 --tls start da         
da
chin@ubuntu:~/go/src/github.com/vmware/vic|1086/already-bound 
⇒  docker -H 192.168.218.141:2376 --tls ps -a      
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
da897d227c6c        golang              "/bin/bash"         4 months ago        Running                                 determined_bhaskara
chin@ubuntu:~/go/src/github.com/vmware/vic|1086/already-bound 
⇒  docker -H 192.168.218.141:2376 --tls attach da
root@da897d227c6c:/go# 
root@da897d227c6c:/go# ls
bin  src
root@da897d227c6c:/go# exit%                                                                                                                                                                                                                                                                                                                                                                                                      chin@ubuntu:~/go/src/github.com/vmware/vic|1086/already-bound 
⇒  docker -H 192.168.218.141:2376 --tls ps -a    
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
da897d227c6c        golang              "/bin/bash"         4 months ago        Exited (0)                              determined_bhaskara
chin@ubuntu:~/go/src/github.com/vmware/vic|1086/already-bound 
⇒  docker -H 192.168.218.141:2376 --tls start da   
da
chin@ubuntu:~/go/src/github.com/vmware/vic|1086/already-bound 
⇒  docker -H 192.168.218.141:2376 --tls ps -a      
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
da897d227c6c        golang              "/bin/bash"         4 months ago        Running                                 determined_bhaskara
chin@ubuntu:~/go/src/github.com/vmware/vic|1086/already-bound 
⇒  docker -H 192.168.218.141:2376 --tls attach da
root@da897d227c6c:/go# 
root@da897d227c6c:/go# ls
bin  src
root@da897d227c6c:/go# exit
exit
```

passed local regression tests

### CODE REVIEW

File: lib/portlayer/network/network.go [hunk 1]
```diff
@@ -117,9 +119,26 @@ func Init(ctx context.Context, sess *session.Session, source extraconfig.DataSou
...
+// eventCallback processes events
+func eventCallback(ie events.Event) {
+	switch ie.String() {
+	case events.ContainerPoweredOff:
+		handle := exec.GetContainer(uid.Parse(ie.Reference()))
+		if handle == nil {
+			log.Errorf("Container %s not found - unable to UnbindContainer", ie.Reference())
+			return
+		}
+		DefaultContext.UnbindContainer(handle)
```
Comment (jzt) [inline lib/portlayer/network/network.go]: Not checking for error here?

File: lib/portlayer/network/network.go [hunk 2]
```diff
@@ -117,9 +119,26 @@ func Init(ctx context.Context, sess *session.Session, source extraconfig.DataSou
 		}
 	})
 
+	// subscribe to the event stream for Vm events
+	exec.Config.EventManager.Subscribe(events.NewEventType(events.ContainerEvent{}).Topic(), "network", eventCallback)
```
Comment (hmahmood) [inline lib/portlayer/network/network.go]: This subscription should be per context

File: lib/portlayer/network/network.go (hunk 1 above)
Comment (andrewtchin) [inline lib/portlayer/network/network.go]: fixed

File: lib/portlayer/network/network.go (hunk 2 above)
Comment (andrewtchin) [inline lib/portlayer/network/network.go]: fixed

**Comment by jzt** [comment]
LGTM

**Comment by hmahmood** [comment]
lgtm

File: lib/portlayer/network/context.go [hunk 3]
```diff
@@ -113,6 +114,9 @@ func NewContext(bridgePool net.IPNet, bridgeMask net.IPMask, config *Configurati
 		}
 	}
 
+	// subscribe to the event stream for Vm events
+	exec.Config.EventManager.Subscribe(events.NewEventType(events.ContainerEvent{}).Topic(), "network", ctx.handleEvent)
```
Comment (cgtexmex) [inline lib/portlayer/network/context.go]: This is created on a per-context basis which implies we could have more than one context per VCH?  If so, the second arg to subscribe needs to be unique per context -- otherwise only the latest context would receive the callback.

Comment (andrewtchin) [inline lib/portlayer/network/context.go]: fixed

**Comment by cgtexmex** [comment]
lgtm

**Comment by andrewtchin** [comment]
♻️  lgtm

**Comment by andrewtchin** [comment]
♻️ lgtm
