### PR TITLE
[specific ci=6-16-Config] Ensure volume stores use '/' on windows

### LINKED ISSUE #6041: vic-machine-windows is replacing backslashes with %5C in volume store paths
**Details:**
If I run `vic-machine-windows create` with the `--volume-store` option, I cannot perform any `vic-machine-windows configure` operations on that VCH without hitting errors about not being able to find the volume store.  

If I deploy a VCH without a volume store, I can run all `vic-machine-windows configure` commands without problems, except if I specify `--volume-store`. If I run `vic-machine-windows configure --volume-store` to add a volume store, the `configure` command succeeds, but I get the same behaviour as described above if I attempt any further `configure` operations.

If I run `vic-machine-windows inspect config` on a VCH that has a volume store (volume store added by either `create` or `configure`), the path to the volume store shows up with `%5C` wherever there should be backslashes. 

**VIC version:**

`vic-machine-windows.exe version v1.1.0-rc3-13153-02b4c0a`

**Deployment details:**

Create VCH without a volume store:

`$ vic-machine-windows create --target 'Administrator@vsphere.local:password@10.153.199.2 --thumbprint FD:38:47:57:88:D9:AC:BE:69:1A:E9:2F:FA:C4:62:BD:82:69:48:FB --bridge-network vic-bridge --no-tls --name volstore-test`

VCH deployment succeeds.

**Steps to reproduce:**

Add a volume store to the VCH:

```
$ vic-machine-windows configure --target 'Administrator@vsphere.local:password'@10.153.199.2 --thumbprint FD:38:47:57:88:D9:AC:BE:69:1A:E9:2F:FA:C4:62:BD:82:69:48:FB --id vm-250 --volume-store datastore1/volstore-test-volstore:default
Aug 15 2017 12:41:47.545+02:00 INFO  ### Configuring VCH ####
Aug 15 2017 12:41:53.425+02:00 INFO  Validating target
Aug 15 2017 12:41:56.875+02:00 WARN  Disabling 82dde229-0679-4f3c-b436-44bf1d9ce101 vpxd.log collection (ServerFaultCode: A specified parameter was not correct: key)
Aug 15 2017 12:41:57.809+02:00 INFO
Aug 15 2017 12:41:57.810+02:00 INFO  VCH ID: VirtualMachine:vm-250
Aug 15 2017 12:41:59.545+02:00 INFO  Creating directory [datastore1] volstore-test
Aug 15 2017 12:41:59.821+02:00 INFO  Datastore path is [datastore1] volstore-test
Aug 15 2017 12:42:05.437+02:00 INFO  No certificate regeneration requested. No new certificates provided. Certificates left unchanged.
Aug 15 2017 12:42:05.437+02:00 INFO  Validating supplied configuration
Aug 15 2017 12:42:14.039+02:00 INFO  vDS configuration OK on "vic-bridge"
Aug 15 2017 12:42:16.376+02:00 INFO  Firewall status: ENABLED on "/dc1/host/10.153.199.206/10.153.199.206"
Aug 15 2017 12:42:16.962+02:00 INFO  Firewall configuration OK on hosts:
Aug 15 2017 12:42:16.962+02:00 INFO     "/dc1/host/10.153.199.206/10.153.199.206"
Aug 15 2017 12:42:18.690+02:00 INFO  License check OK on hosts:
Aug 15 2017 12:42:18.691+02:00 INFO    "/dc1/host/10.153.199.206/10.153.199.206"
Aug 15 2017 12:42:18.691+02:00 INFO  DRS check SKIPPED - target is standalone host
Aug 15 2017 12:42:55.597+02:00 INFO  Creating directory [datastore1] volstore-test-volstore
Aug 15 2017 12:42:55.960+02:00 INFO  Datastore path is [datastore1] volstore-test-volstore
Aug 15 2017 12:42:56.299+02:00 INFO  Setting VM configuration
Aug 15 2017 12:43:00.005+02:00 INFO  Waiting for IP information
Aug 15 2017 12:43:01.137+02:00 INFO  Waiting for major appliance components to launch
Aug 15 2017 12:43:24.285+02:00 INFO  Obtained IP address for client interface: "10.153.199.204"
Aug 15 2017 12:43:24.285+02:00 INFO  Checking VCH connectivity with vSphere target
Aug 15 2017 12:43:26.144+02:00 INFO  vSphere API Test: https://10.153.199.2 vSphere API target responds as expected
Aug 15 2017 12:43:27.738+02:00 INFO  Completed successfully
```

Any attempt to run another `vic-machine configure` operation on the VCH fails:

```
$ vic-machine-windows configure --target 'Administrator@vsphere.local:password'@10.153.199.2 --thumbprint FD:38:47:57:88:D9:AC:BE:69:1A:E9:2F:FA:C4:62:BD:82:69:48:FB --id vm-250 --cpu 1024
Aug 15 2017 12:46:28.568+02:00 INFO  ### Configuring VCH ####
Aug 15 2017 12:46:34.692+02:00 INFO  Validating target
Aug 15 2017 12:46:38.292+02:00 WARN  Disabling 82dde229-0679-4f3c-b436-44bf1d9ce101 vpxd.log collection (ServerFaultCode: A specified parameter was not correct: key)
Aug 15 2017 12:46:38.614+02:00 INFO
Aug 15 2017 12:46:38.614+02:00 INFO  VCH ID: VirtualMachine:vm-250
Aug 15 2017 12:46:40.359+02:00 INFO  Creating directory [datastore1] volstore-test
Aug 15 2017 12:46:40.638+02:00 INFO  Datastore path is [datastore1] volstore-test
Aug 15 2017 12:46:45.969+02:00 INFO  No certificate regeneration requested. No new certificates provided. Certificates left unchanged.
Aug 15 2017 12:46:45.970+02:00 INFO  Validating supplied configuration
Aug 15 2017 12:46:51.156+02:00 INFO  Suggesting valid values for --volume-store based on "datastore1\\volstore-test-volstore:default"
Aug 15 2017 12:46:51.731+02:00 INFO  Suggested values for --volume-store:
Aug 15 2017 12:46:51.732+02:00 INFO    "datastore1:default"
Aug 15 2017 12:46:54.842+02:00 INFO  vDS configuration OK on "vic-bridge"
Aug 15 2017 12:46:57.065+02:00 INFO  Firewall status: ENABLED on "/dc1/host/10.153.199.206/10.153.199.206"
Aug 15 2017 12:46:57.639+02:00 INFO  Firewall configuration OK on hosts:
Aug 15 2017 12:46:57.639+02:00 INFO     "/dc1/host/10.153.199.206/10.153.199.206"
Aug 15 2017 12:46:59.579+02:00 INFO  License check OK on hosts:
Aug 15 2017 12:46:59.580+02:00 INFO    "/dc1/host/10.153.199.206/10.153.199.206"
Aug 15 2017 12:46:59.580+02:00 INFO  DRS check SKIPPED - target is standalone host
Aug 15 2017 12:47:02.674+02:00 ERROR --------------------
Aug 15 2017 12:47:02.674+02:00 ERROR datastore 'datastore1\volstore-test-volstore' not found
Aug 15 2017 12:47:02.674+02:00 ERROR Configuring cannot continue: configuration validation failed
Aug 15 2017 12:47:02.943+02:00 ERROR --------------------
Aug 15 2017 12:47:02.943+02:00 ERROR vic-machine-windows.exe configure failed: validation of configuration failed
```

Inspect the new configuration of the VCH:

```
$ vic-machine-windows inspect config --target 'Administrator@vsphere.local:password'@10.153.199.2 --thumbprint FD:38:47:57:88:D9:AC:BE:69:1A:E9:2F:FA:C4:62:BD:82:69:48:FB --id vm-250
Aug 15 2017 12:48:46.607+02:00 INFO  ### Inspecting VCH ####
Aug 15 2017 12:48:52.628+02:00 INFO  Validating target
Aug 15 2017 12:48:56.081+02:00 WARN  Disabling 82dde229-0679-4f3c-b436-44bf1d9ce101 vpxd.log collection (ServerFaultCode: A specified parameter was not correct: key)
Aug 15 2017 12:48:59.583+02:00 INFO
Aug 15 2017 12:48:59.583+02:00 INFO  Target VCH created with the following options:

        --target=https://10.153.199.2
        --thumbprint=FD:38:47:57:88:D9:AC:BE:69:1A:E9:2F:FA:C4:62:BD:82:69:48:FB
        --name=volstore-test
        --compute-resource=/dc1/host/10.153.199.206/Resources
        --ops-user=Administrator@vsphere.local
        --image-store=ds://datastore1
        --volume-store=ds://datastore1%5Cvolstore-test-volstore:default
        --bridge-network=vic-bridge

```

**Actual behavior:**

The characters `%5C` appear in the volume store paths in place of backslashes.

**Expected behavior:**

The volume store path should include backslashes.

**Logs:**

[logs.zip](https://github.com/vmware/vic/files/1224826/logs.zip)

### PR DESCRIPTION
**Pull request by jonathanibers**
Fixes #6041

### CODE REVIEW

File: lib/install/validate/config_to_data.go [hunk 1]
```diff
@@ -23,7 +23,7 @@ import (
 	log "github.com/Sirupsen/logrus"
 	"github.com/docker/go-units"
 
-	"path/filepath"
+	"path"
```
Comment (anchal-agrawal) [inline lib/install/validate/config_to_data.go]: Go imports should have three groups - see https://github.com/vmware/vic/pull/5865#discussion_r130988908.

**Comment by anchal-agrawal** [comment]
Couple nits:

* Remove `(#6041)` from the PR title and commit message - when the PR is merged, Github automatically appends the PR number to the commit message.
* Since this is a nuanced fix, adding more details about the change in the commit message body would be good to have. See https://chris.beams.io/posts/git-commit.
