### PR TITLE
Remove full datastore path from vm spec attribute VmPathName

### LINKED ISSUE #1888: docker create fails on 6.5_RC1 VC
build 3538

installed 6.5b3 VC and two 6.5b3 hosts. 

Installed to VC with 

`./vic-machine-darwin create --target 10.161.245.177 --image-datastore datastore1 --name vic-demo --user Administrator@vsphere.local --password 'Admin!23'  --compute-resource /ha-datacenter/host/10.160.97.176/Resources --bridge-network bridge --external-network vm-network`

Then tried create:

$ docker -H 10.162.13.107:2376 --tls create busybox
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
a3ed95caeb02: Pull complete
8ddc19f16526: Pull complete
Digest: sha256:65ce39ce3eb0997074a460adfb568d0b9f0f6a4392d97b6035630c9d7bf92402
Status: Downloaded newer image for library/busybox:latest
Error: No such image: busybox

This also leaves files on the host that are marked as "deletable=false" and are unable to be deleted via API.

### PR DESCRIPTION
**Pull request by cgtexmex**
Removes the full datastore path from VmPathName in
the VM Spec.  Will now ALWAYS be [datastore name] -- i.e.
[datastore1]

fixes #1888

### CODE REVIEW

File: lib/spec/spec.go [hunk 1]
```diff
@@ -109,10 +109,6 @@ func NewVirtualMachineConfigSpec(ctx context.Context, session *session.Session,
 	config.VMFullName = fullName
 
 	VMPathName := config.VMPathName
```
Comment (dougm) [inline lib/spec/spec.go]: You could get rid of that var too and just use `config.VMPathName` below.

**Comment by dougm** [comment]
lgtm

**Comment by fdawg4l** [comment]
lgtm

**Comment by cgtexmex** [comment]
rebase -- removed unneeded variable

**Comment by hickeng** [comment]
LGTM - however I don't recall why we were doing this in the first place, so @fdawg4l is the authoritative source.

**Comment by dougm** [comment]
@hickeng it was the old trick to avoid creating a vm with the same name, avoiding the foo_1.vmx, foo_2.vmx, etc., renames.  I recall discovering this via source opengrok in the enatai/dcp days, but not finding any related docs.  Also recall sharing it with you in the early bonneville days, in the old kitchen, while you were on the couch enjoying a bowl of soup you crafted from canned V8 juice.
```
commit cb475c33d6fac2e12a1eb4e2d9050405a38da96a
Author: Doug MacEachern <dougm@vmware.com>
Date:   Fri Jan 9 10:55:12 2015 -0800

    Handle VM create/delete races

    Fixes enatai/dcp#157

    Change-Id: I4acf0ba951d30afc012e93d1ded4c963b563b42e

diff --git a/go/src/dcp/provisioning/esx/client.go b/go/src/dcp/provisioning/esx/client.go
index 41b85c2..370f21e 100644
--- a/go/src/dcp/provisioning/esx/client.go
+++ b/go/src/dcp/provisioning/esx/client.go
...
@@ -368,9 +359,13 @@ func (c *Client) CreateVM() (*govmomi.VirtualMachine, error) {
                return nil, err
        }

+       name := c.state.ID
+       // Use a full path to the config file to avoid creating a VM with the same name
+       cfgPath := fmt.Sprintf("[%s] %s/%s.vmx", ds.Name(), name, name)
+
        spec := types.VirtualMachineConfigSpec{
-               Name:  c.state.ID,
-               Files: &types.VirtualMachineFileInfo{VmPathName: fmt.Sprintf("[%s]", ds.Name())},
+               Name:  name,
+               Files: &types.VirtualMachineFileInfo{VmPathName: cfgPath},
```

**Comment by caglar10ur** [comment]
```
bowl of soup you crafted from canned V8 juice
```

need to open a p0 issue for this :) LGTM

**Comment by cgtexmex** [comment]
rebase
