### PR TITLE
Concurrent copy

### LINKED ISSUE #5742: Docker cp fails on concurrent copy for offline container
When two cp requests to an offline container are targeted at the same volume or r/w layer, one request would successfully attached the vmdk, and return from portlayer. When the second request comes in, the vmdk is already attached and mounted to the VCH, but the current logic failover to online and assumes the owner is a container VM. This is a problem because if the VCH starts a guest tool connection to itself, ref counting for mount is not updated. The vmdk will be unmounted whenever the first request finishes, and can cause the second copy operation to fail in the middle.

Acceptance:
- [ ] many (>20) concurrent copyTo operations to the same offline container succeed
- [ ] detection for images/volumes/containers for the case where the online Owner identified _is_ the applianceVM and appropriate retry logic (unsure how to test this).

### PR DESCRIPTION
**Pull request by hickeng**
Updates to disk reference counting to handle concurrent attach case.
Currently exploits personality bug to get back end concurrency via: 
```
for i in {1..50};do docker cp bin/foo.txt offline:/; docker cp bin/bar offline:/;done
```

Does not yet handle accidental detection of the endpointVM as the online owner.

Towards: #5742

### CODE REVIEW

File: lib/portlayer/storage/vsphere/export.go [hunk 1]
```diff
@@ -130,13 +131,19 @@ func (i *ImageStore) Export(op trace.Operation, id, ancestor string, spec *archi
 	// this allows us to assume it's an image
 	r, err := i.NewDataSource(op, ancestor)
 	if err != nil {
+		op.Debugf("Unable to get datasource for ancester: %s", err)
```
Comment (caglar10ur) [inline lib/portlayer/storage/vsphere/export.go]: Based on the TV advertisement that I keep seeing, I'm sure http://www.ancestor.com/ will help you there :P

File: pkg/vsphere/disk/disk_manager.go [hunk 2]
```diff
@@ -384,15 +413,14 @@ func (m *Manager) Detach(op trace.Operation, config *VirtualDiskConfig) error {
...
+
 	select {
 	case <-m.maxAttached:
 	default:
 	}
 
-	if err = d.setDetached(op, m.Disks); err != nil {
-		op.Errorf(err.Error())
-	}
-
```
Comment (caglar10ur) [inline pkg/vsphere/disk/disk_manager.go]: good catch.

**Comment by matthewavery** [comment]
@hickeng there is now a feature branch for docker-cp for the final merges of funtionality. I will be sure to rebase above this to show that we are safe from this.

File: lib/portlayer/storage/vsphere/container.go [hunk 3]
```diff
@@ -231,7 +236,7 @@ func (c *ContainerStore) Export(op trace.Operation, id, ancestor string, spec *a
 	}
 
 	if ancestor == "" {
-		op.Infof("No ancester specified so following basic export path")
+		op.Infof("No ancestorr specified so following basic export path")
```
Comment (jzt) [inline lib/portlayer/storage/vsphere/container.go]: out of the frying pan an into the fire :)

`s/ancestorr/ancestor`

File: lib/portlayer/storage/vsphere/export.go [hunk 4]
```diff
@@ -156,7 +163,10 @@ func (i *ImageStore) Export(op trace.Operation, id, ancestor string, spec *archi
 		return nil, err
 	}
 
-	return tar, nil
+	return &storage.ProxyReadCloser{
```
Comment (jzt) [inline lib/portlayer/storage/vsphere/export.go]: Side question: are we still using the CleanupReader? If not, we could probably remove the file if it hasn't been already.

File: lib/portlayer/storage/vsphere/container.go (hunk 3 above)
Comment (hickeng) [inline lib/portlayer/storage/vsphere/container.go]: just how did I manage that?

File: lib/portlayer/storage/vsphere/export.go (hunk 4 above)
Comment (hickeng) [inline lib/portlayer/storage/vsphere/export.go]: It's gone. I'm not actually sure why CleanupReader wasn't getting typed as an io.Closer but the very slightly different `ProxyCloser` I tried worked, so I switched.
