### PR TITLE
Add DHCP client to tether. Fix other DHCP issues.

### LINKED ISSUE #747: Milestone: container dhcp support
When attaching containers to a mapped vSphere network, one of the likely IPAM mechanisms available to us is DHCP. This comes with two requirements:

1. dhcp client in bootstrap (perhaps https://github.com/d2g/dhcp4client)
2. reporting of the assigned address (perhaps https://github.com/davecheney/mdns/, or simple update to guestinfo)

There is no need to expose the external mapped network IP via the normal container name resolution as it's fundamentally outside of that managed environment.

#745 is related but is not directly required.

### LINKED ISSUE #1214: Basic address acquisition
This covers basic address acquisition from a DHCP server.
This does not cover renew and release operations.

### PR DESCRIPTION
**Pull request by hmahmood**
Fixes #1214 
Fixes #747

### CODE REVIEW

File: cmd/tether/ops.go [hunk 1]
```diff
@@ -36,9 +42,17 @@ func (t *operations) Setup() error {
 }
 
 func (t *operations) Cleanup() error {
+	if err := t.BaseOperations.Cleanup(); err != nil {
```
Comment (hickeng) [inline cmd/tether/ops.go]: `return t.BaseOperations.Cleanup()`
but I don't think you need this at all if `t` is embedding `BaseOperations`

File: cmd/tether/ops.go [hunk 2]
```diff
@@ -36,9 +42,17 @@ func (t *operations) Setup() error {
...
+		return err
+	}
+
 	return nil
 }
 
+func (t *operations) Apply(endpoint *metadata.NetworkEndpoint) error {
```
Comment (hickeng) [inline cmd/tether/ops.go]: Same as above

File: cmd/vch-init/ops.go [hunk 3]
```diff
@@ -52,6 +58,10 @@ func (t *operations) Setup() error {
 }
 
 func (t *operations) Cleanup() error {
+	if err := t.BaseOperations.Cleanup(); err != nil {
```
Comment (hickeng) [inline cmd/vch-init/ops.go]: same comments as for cmd/tether/ops.go

File: lib/metadata/network_interface.go [hunk 4]
```diff
@@ -59,3 +59,7 @@ type ContainerNetwork struct {
 	// The IP ranges for this network
 	Pools []ip.Range `vic:"0.1" scope:"read-only" key:"pools"`
 }
+
+func (e *NetworkEndpoint) IsDynamic() bool {
```
Comment (hickeng) [inline lib/metadata/network_interface.go]: Is this materially different from IsUnspecified?

File: lib/tether/net_linux_test.go [hunk 5]
```diff
@@ -69,7 +69,7 @@ func TestSetIpAddress(t *testing.T) {
 						Name: "bridge",
 					},
 					Default: true,
-					Gateway: gwIP,
+					Gateway: *gwIP,
```
Comment (hickeng) [inline lib/tether/net_linux_test.go]: found this myself - no idea how this got committed as I always run the package tests directly as well as make test when making tether changes.

**Comment by hickeng** [comment]
@hmahmood Took a look through this - probably easiest to talk through it with you tomorrow.

File: isos/bootstrap/bootstrap [hunk 6]
```diff
@@ -58,24 +58,9 @@ if mount -t ext4 /dev/disk/by-label/containerfs ${MOUNTPOINT}; then
...
-
-    echo "Setting IP addr to " \$addr > /dev/ttyS1
-    echo "Setting route to" \$gateway > /dev/ttyS1
-
-    ip addr add \$addr dev eth1
-    ip link set dev eth1 up
-    ip route add default via \$gateway dev eth1
-fi
-
 /.tether/tether-bin
```
Comment (caglar10ur) [inline isos/bootstrap/bootstrap]: I think we can drop this wrapper and start using binary as is

File: lib/dhcp/client.go [hunk 7]
```diff
@@ -0,0 +1,174 @@
...
+import (
+	"fmt"
+	"net"
+	"sync"
+	"syscall"
+	"time"
+
+	log "github.com/Sirupsen/logrus"
+	"github.com/d2g/dhcp4"
+	"github.com/d2g/dhcp4client"
```
Comment (caglar10ur) [inline lib/dhcp/client.go]: Not that I've any experience with them but we have https://github.com/vmware/godhcpv4

File: lib/tether/ops_linux.go [hunk 8]
```diff
@@ -442,20 +438,115 @@ func apply(t Netlink, endpoint *metadata.NetworkEndpoint) error {
 			}
 			log.Infof("Added nameserver: %s", server.String())
 		}
-	} else {
+	} else if !ip.IsUnspecifiedIP(endpoint.Network.Gateway.IP) {
```
Comment (caglar10ur) [inline lib/tether/ops_linux.go]: Who wins here? Our internal DNS or dhcp provided one?

**Comment by caglar10ur** [comment]
Great work, some nitpicks but overall LGTM

File: lib/tether/ops_linux.go (hunk 8 above)
Comment (hmahmood) [inline lib/tether/ops_linux.go]: For endpoints connected to the bridge network, it will be our internal DNS (i.e. vch). For DHCP endpoints, which should never be the same as the bridge endpoint, it most likely will not go into this branch as we will use the DNS entries from the DHCP server.

**Comment by hmahmood** [comment]
There is a problem with this PR: the dhcp loop does not update endpoints when renewing the dhcp lease. I will fix this, but it will require adding more robust resolv.conf and hosts handling. I will add basic implementations of these.

File: isos/bootstrap/bootstrap [hunk 9]
```diff
@@ -33,14 +33,10 @@ if mount -t ext4 /dev/disk/by-label/containerfs ${MOUNTPOINT}; then
...
-        touch ${MOUNTPOINT}/.tether-init/resolv.conf ${MOUNTPOINT}/.tether-init/resolv.conf
+        touch ${MOUNTPOINT}/etc/hostname
         touch ${MOUNTPOINT}/etc/hosts
-        echo "127.0.0.1 localhost localhost.localdomain" > ${MOUNTPOINT}/.tether-init/hosts
-
-        mount --bind ${MOUNTPOINT}/.tether-init/hostname ${MOUNTPOINT}/etc/hostname
-        mount --bind ${MOUNTPOINT}/.tether-init/resolv.conf ${MOUNTPOINT}/etc/resolv.conf
-        mount --bind ${MOUNTPOINT}/.tether-init/hosts ${MOUNTPOINT}/etc/hosts
+        touch ${MOUNTPOINT}/etc/resolv.conf
+        echo "127.0.0.1 localhost localhost.localdomain" > ${MOUNTPOINT}/etc/hosts
```
Comment (caglar10ur) [inline isos/bootstrap/bootstrap]: Should we add ipv6 defaults here? My ubuntu box has following defaults

```
127.0.0.1       localhost

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

File: isos/bootstrap/bootstrap (hunk 6 above)
Comment (caglar10ur) [inline isos/bootstrap/bootstrap]: Now that we have lib/etcconf/hosts.go, I think prefer tether writing the default config files and then dropping this shell wrapper and calling the binary directly.

File: lib/dhcp/client.go [hunk 10]
```diff
@@ -0,0 +1,175 @@
...
+
+// The default timeout for the client
+const defaultTimeout = 10 * time.Second
+
+// NewClient creates a new DHCP client. Note the returned object is not thread-safe.
+func NewClient() (Client, error) {
+	return &client{timeout: defaultTimeout}, nil
+}
+
+func (c *client) SetTimeout(t time.Duration) error {
```
Comment (caglar10ur) [inline lib/dhcp/client.go]: Why we are returning error here? I think we can just drop that and return nothing

File: lib/dhcp/packet.go [hunk 11]
```diff
@@ -0,0 +1,104 @@
...
+
+	var dns []net.IP
+	for i := 0; i < len(b); i += 4 {
+		dns = append(dns, net.IP(b[i:i+4]))
+	}
+
+	return dns
+}
+
+func (p *Packet) ServerIP() net.IP {
```
Comment (caglar10ur) [inline lib/dhcp/packet.go]: Needs a comment - exported function

File: lib/metadata/network_interface.go [hunk 12]
```diff
@@ -33,7 +33,7 @@ type NetworkEndpoint struct {
 	Static *net.IPNet `vic:"0.1" scope:"read-only" key:"staticip"`
 
 	// Actual IP address assigned
-	Assigned net.IP `vic:"0.1" scope:"read-write" key:"ip"`
+	Assigned net.IPNet `vic:"0.1" scope:"read-write" key:"ip"`
```
Comment (caglar10ur) [inline lib/metadata/network_interface.go]: should we change the key to ipnet as well?

Comment (hmahmood) [inline lib/metadata/network_interface.go]: I think ip is fine, matches `staticip` above.

File: isos/bootstrap/bootstrap (hunk 9 above)
Comment (hmahmood) [inline isos/bootstrap/bootstrap]: i will add those entries.

File: isos/bootstrap/bootstrap (hunk 6 above)
Comment (hmahmood) [inline isos/bootstrap/bootstrap]: I will drop the wrapper. However, I am not sure what happens if we boot with an empty hosts file. So I more inclined to have a default there.

File: lib/tether/config.go [hunk 13]
```diff
@@ -88,3 +89,32 @@ type SessionConfig struct {
...
+	// The network in which this information should be interpreted. This is embedded directly rather than
+	// as a pointer so that we can ensure the data is consistent
+	Network metadata.ContainerNetwork `vic:"0.1" scope:"read-only" key:"network"`
+
+	// DHCP runtime info
+	DHCP *DHCPInfo `vic:"0.1" scope:"read-only" recurse:"depth=0"`
+}
+
+func (e *NetworkEndpoint) IsDynamic() bool {
+	return len(e.Static.IP) == 0
```
Comment (caglar10ur) [inline lib/tether/config.go]: ```return e.Static.IPIsUnspecifiedIP()``` maybe?

**Comment by caglar10ur** [comment]
Have some minor questions but overall LGTM

File: cmd/vic-init/ops.go [hunk 14]
```diff
@@ -42,7 +42,12 @@ type operations struct {
 	tether.BaseOperations
 }
 
-func (t *operations) Setup() error {
+func (t *operations) Setup(sink tether.ConfigSink) error {
+	if err := t.BaseOperations.Setup(sink); err != nil {
+		return err
+	}
+
+	// TODO: enabled for initial dev debugging only
```
Comment (hickeng) [inline cmd/vic-init/ops.go]: No longer just for dev debugging - now it's restricted to loopback it's there for vicadmin to gather as part of diagnostic logs.

File: isos/bootstrap/bootstrap [hunk 15]
```diff
@@ -32,15 +32,9 @@ if mount -t ext4 /dev/disk/by-label/containerfs ${MOUNTPOINT}; then
         mkdir -p ${MOUNTPOINT}/dev ${MOUNTPOINT}/proc ${MOUNTPOINT}/sys ${MOUNTPOINT}/etc
         # ln -sf /proc/mounts ${MOUNTPOINT}/etc/mtab
 
-        # ensure both the source and destination files exist for bind mounting
-        touch ${MOUNTPOINT}/etc/hostname ${MOUNTPOINT}/.tether-init/hostname
-        touch ${MOUNTPOINT}/.tether-init/resolv.conf ${MOUNTPOINT}/.tether-init/resolv.conf
+        touch ${MOUNTPOINT}/etc/hostname
         touch ${MOUNTPOINT}/etc/hosts
-        echo "127.0.0.1 localhost localhost.localdomain" > ${MOUNTPOINT}/.tether-init/hosts
```
Comment (hickeng) [inline isos/bootstrap/bootstrap]: Even if there are no network endpoints defined, we still want the loopback entry in hosts.

File: lib/install/validate/validator.go [hunk 16]
```diff
@@ -327,27 +328,12 @@ func (v *Validator) network(ctx context.Context, input *data.Data, conf *metadat
...
-		}
-	}
-
 	bridgeNet := &metadata.NetworkEndpoint{
 		Common: metadata.Common{
 			Name: "bridge",
 			ID:   endpointMoref,
 		},
-		Static: &gateway,
+		Static: &net.IPNet{IP: net.IPv4zero}, // static but managed externally
```
Comment (hickeng) [inline lib/install/validate/validator.go]: nice

File: lib/portlayer/network/context.go [hunk 17]
```diff
@@ -912,6 +953,24 @@ func (c *Context) DeleteScope(name string) error {
 		return fmt.Errorf("scope has bound endpoints")
 	}
 
+	// remove gateway ip from bridge interface
+	link, err := getBridgeLink()
```
Comment (hickeng) [inline lib/portlayer/network/context.go]: Should we stash this somewhere on initialization? It seems like something that should be done during portlayer init and likely a fatal failure (without it we cannot do name resolution for containers or port forwarding).

File: lib/tether/config.go [hunk 18]
```diff
@@ -88,3 +89,32 @@ type SessionConfig struct {
...
+
+	// Actual IP address assigned
+	Assigned net.IPNet `vic:"0.1" scope:"read-write" key:"ip"`
+
+	// The network in which this information should be interpreted. This is embedded directly rather than
+	// as a pointer so that we can ensure the data is consistent
+	Network metadata.ContainerNetwork `vic:"0.1" scope:"read-only" key:"network"`
+
+	// DHCP runtime info
+	DHCP *DHCPInfo `vic:"0.1" scope:"read-only" recurse:"depth=0"`
```
Comment (hickeng) [inline lib/tether/config.go]: Are you intending that this be serialized so we can preserve DHCP info across reboots? If so then it needs to be read-write and present before the VM is powered on (i.e. in the lib/metadata structures). If not then we can simply omit the annotation and it won't get serialized in guestinfo as it is read-only by default.

Comment (hmahmood) [inline lib/tether/config.go]: Actually I don't want to serialize it at all. Without the annotation I was getting was not DHCP == nil, which I need in the code.

File: isos/bootstrap/bootstrap (hunk 15 above)
Comment (hmahmood) [inline isos/bootstrap/bootstrap]: The loopback entries are now done in BaseOperations.Setup as per @caglar10ur suggestion.

File: lib/tether/ops_linux.go [hunk 19]
```diff
@@ -539,3 +643,61 @@ func (t *BaseOperations) Fork() error {
...
+	for _, e := range entries {
+		h.SetHost(e.hostname, e.addr)
+	}
+
+	if err = h.Save(); err != nil {
+		return err
+	}
+
+	// start with empty resolv.conf
+	os.Remove("/etc/resolv.conf")
```
Comment (hickeng) [inline lib/tether/ops_linux.go]: Pull this path from the const in lib/etcconf?

File: lib/tether/ops_linux.go [hunk 20]
```diff
@@ -539,3 +643,61 @@ func (t *BaseOperations) Fork() error {
...
+
+	rc := etcconf.NewResolvConf("")
+	if err = rc.Load(); err != nil {
```
Comment (hickeng) [inline lib/tether/ops_linux.go]: Why do we call load having just deleted the source file?

**Comment by hickeng** [comment]
LGTM
minor comments and questions - built it but not yet done any testing with it. Would like to sit down with you next time I'm in Austin or before if necessary and spend a day going over tether restructure to make this an easier integration.

**Comment by hmahmood** [comment]
Poke

**Comment by hmahmood** [comment]
Poke
