### PR TITLE
Handle nil vSphere host fw info during install

### LINKED ISSUE #6049: vic-machine panic when deploying to bart for longevity testing
```
Aug 16 2017 10:26:48.071-05:00 INFO  ### Installing VCH ####
Aug 16 2017 10:26:48.071-05:00 WARN  Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
Aug 16 2017 10:26:48.071-05:00 DEBUG client network: IP {<nil> <nil>} gateway <nil> dest: []
Aug 16 2017 10:26:48.071-05:00 DEBUG public network: IP {10.17.109.6 ffffff00} gateway 10.17.109.253 dest: []
Aug 16 2017 10:26:48.071-05:00 DEBUG management network: IP {<nil> <nil>} gateway <nil> dest: []
Aug 16 2017 10:26:48.071-05:00 DEBUG VCH DNS servers: [10.118.81.1]
Aug 16 2017 10:26:48.071-05:00 INFO  Using public-network-ip as cname where needed - use --tls-cname to override: 10.17.109.6/24
Aug 16 2017 10:26:48.072-05:00 INFO  Loaded server certificate VCH-0-1927/server-cert.pem
Aug 16 2017 10:26:48.072-05:00 DEBUG Not generating server or client certs, nothing for generateCertificates to do
Aug 16 2017 10:26:48.072-05:00 WARN  Configuring without TLS verify - certificate-based authentication disabled
Aug 16 2017 10:26:48.072-05:00 DEBUG --target=https://bart.eng.vmware.com
Aug 16 2017 10:26:48.072-05:00 DEBUG --user=<censored>
Aug 16 2017 10:26:48.072-05:00 DEBUG --password=<censored>
Aug 16 2017 10:26:48.072-05:00 DEBUG --thumbprint=48:EE:3F:A7:F1:E8:42:BA:28:7D:38:66:31:C6:5E:D3:81:68:47:2F
Aug 16 2017 10:26:48.072-05:00 DEBUG --name=VCH-0-1927
Aug 16 2017 10:26:48.072-05:00 DEBUG --compute-resource=cls
Aug 16 2017 10:26:48.072-05:00 DEBUG --image-store=vsanDatastore
Aug 16 2017 10:26:48.072-05:00 DEBUG --volume-store=vsanDatastore/VCH-0-1927-VOL:default
Aug 16 2017 10:26:48.072-05:00 DEBUG --dns-server=10.118.81.1
Aug 16 2017 10:26:48.072-05:00 DEBUG --bridge-network=bridge
Aug 16 2017 10:26:48.072-05:00 DEBUG --public-network=vm-network
Aug 16 2017 10:26:48.072-05:00 DEBUG --public-network-gateway=10.17.109.253
Aug 16 2017 10:26:48.072-05:00 DEBUG --public-network-ip=10.17.109.6/24
Aug 16 2017 10:26:48.072-05:00 DEBUG --no-tlsverify=true
Aug 16 2017 10:26:48.072-05:00 DEBUG --insecure-registry=harbor.ci.drone.local
Aug 16 2017 10:26:48.072-05:00 DEBUG --appliance-iso=bin/appliance.iso
Aug 16 2017 10:26:48.072-05:00 DEBUG --bootstrap-iso=bin/bootstrap.iso
Aug 16 2017 10:26:48.072-05:00 DEBUG --force=true
Aug 16 2017 10:26:48.072-05:00 DEBUG --timeout=3m0s
Aug 16 2017 10:26:48.072-05:00 DEBUG --debug=1
Aug 16 2017 10:26:48.072-05:00 DEBUG Creating VMOMI session with thumbprint 48:EE:3F:A7:F1:E8:42:BA:28:7D:38:66:31:C6:5E:D3:81:68:47:2F
Aug 16 2017 10:26:48.289-05:00 DEBUG Session Environment Info: 
Aug 16 2017 10:26:48.289-05:00 DEBUG vSphere resource cache populating...
Aug 16 2017 10:26:48.294-05:00 DEBUG Cached dc: 
Aug 16 2017 10:26:48.298-05:00 DEBUG Cached cluster: 
Aug 16 2017 10:26:48.328-05:00 DEBUG Cached pool: 
Aug 16 2017 10:26:48.330-05:00 DEBUG Cached folders: 
Aug 16 2017 10:26:48.330-05:00 DEBUG Error count populating vSphere cache: (1)
Aug 16 2017 10:26:48.330-05:00 DEBUG new validator Session.Populate: Failure finding ds (): default datastore resolves to multiple instances, please specify
Aug 16 2017 10:26:48.330-05:00 INFO  Validating supplied configuration
Aug 16 2017 10:26:48.330-05:00 DEBUG Setting scratch image size to 8000000 KB in VCHConfig
Aug 16 2017 10:26:48.676-05:00 DEBUG No path element specified for image store - will use default
Aug 16 2017 10:26:48.683-05:00 INFO  Configuring static IP for additional networks using port group "vm-network"
Aug 16 2017 10:26:48.683-05:00 DEBUG Setting static IP for "public" on port group "vm-network"
Aug 16 2017 10:26:48.687-05:00 DEBUG Setting static IP for "client" on port group "vm-network"
Aug 16 2017 10:26:48.690-05:00 DEBUG Setting static IP for "management" on port group "vm-network"
Aug 16 2017 10:26:48.696-05:00 DEBUG Network configuration:
Aug 16 2017 10:26:48.696-05:00 DEBUG 	Network: client NetworkEndpoint: &{{  client } true 10.17.109.6/24 {<nil> <nil>}  []}
Aug 16 2017 10:26:48.696-05:00 DEBUG 	Network: management NetworkEndpoint: &{{   } true 10.17.109.6/24 {<nil> <nil>}  []}
Aug 16 2017 10:26:48.697-05:00 DEBUG 	Network: bridge NetworkEndpoint: &{{ DistributedVirtualPortgroup:dvportgroup-33 bridge } true <nil> {<nil> <nil>}  []}
Aug 16 2017 10:26:48.697-05:00 DEBUG 	Network: public NetworkEndpoint: &{{  public } true 10.17.109.6/24 {<nil> <nil>}  []}
Aug 16 2017 10:26:48.701-05:00 INFO  vDS configuration OK on "bridge"
Aug 16 2017 10:26:48.702-05:00 DEBUG Checking firewall with management network IP {10.17.109.6 ffffff00}
Aug 16 2017 10:26:48.733-05:00 INFO  Firewall status: DISABLED on "/stress-datacenter/host/cls/homer.eng.vmware.com"
Aug 16 2017 10:26:48.738-05:00 DEBUG fw misconfigured with fw disabled "/stress-datacenter/host/cls/homer.eng.vmware.com"
Aug 16 2017 10:26:48.753-05:00 INFO  Firewall status: DISABLED on "/stress-datacenter/host/cls/milhouse.eng.vmware.com"
Aug 16 2017 10:26:48.761-05:00 DEBUG fw misconfigured with fw disabled "/stress-datacenter/host/cls/milhouse.eng.vmware.com"
Aug 16 2017 10:26:48.785-05:00 INFO  Firewall status: DISABLED on "/stress-datacenter/host/cls/nelson.eng.vmware.com"
Aug 16 2017 10:26:48.795-05:00 DEBUG fw misconfigured with fw disabled "/stress-datacenter/host/cls/nelson.eng.vmware.com"
Aug 16 2017 10:26:48.810-05:00 INFO  Firewall status: DISABLED on "/stress-datacenter/host/cls/ralph.eng.vmware.com"
Aug 16 2017 10:26:48.814-05:00 ERROR --------------------
Aug 16 2017 10:26:48.815-05:00 ERROR vic-machine-linux failed, please check log file vic-machine.log for details
goroutine 1 [running]:
runtime/debug.Stack(0xf9db24, 0x2f, 0xc420368770)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
main.main.func1(0xc420154b60, 0xc42000e290)
	/go/src/github.com/vmware/vic/cmd/vic-machine/main.go:151 +0x17d
panic(0xd79980, 0x1845f40)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/vmware/vic/lib/install/validate.(*Validator).ManagementNetAllowed(0xc420080480, 0x185afc0, 0xc420014450, 0xc4201fc290, 0x10, 0x10, 0xc4201fc2a0, 0x4, 0x4, 0xc420024bc0, ...)
	/go/src/github.com/vmware/vic/lib/install/validate/config.go:311 +0x2bf
github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewallForTether(0xc420080480, 0x185afc0, 0xc420014450, 0xc4201fc290, 0x10, 0x10, 0xc4201fc2a0, 0x4, 0x4, 0x0, ...)
	/go/src/github.com/vmware/vic/lib/install/validate/config.go:126 +0x515
github.com/vmware/vic/lib/install/validate.(*Validator).CheckFirewall(0xc420080480, 0x185afc0, 0xc420014450, 0xc42006dc00)
	/go/src/github.com/vmware/vic/lib/install/validate/config.go:87 +0x1ff
github.com/vmware/vic/lib/install/validate.(*Validator).Validate(0xc420080480, 0x185afc0, 0xc420014450, 0xc4201ccc00, 0x0, 0x0, 0x0)
	/go/src/github.com/vmware/vic/lib/install/validate/validator.go:307 +0x27b
github.com/vmware/vic/cmd/vic-machine/create.(*Create).Run(0xc4201aad80, 0xc4201fa280, 0x0, 0x0)
	/go/src/github.com/vmware/vic/cmd/vic-machine/create/create.go:720 +0x2de
github.com/vmware/vic/cmd/vic-machine/create.(*Create).Run-fm(0xc4201fa280, 0x0, 0xc4201fa280)
	/go/src/github.com/vmware/vic/cmd/vic-machine/main.go:62 +0x34
github.com/vmware/vic/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xd2db60, 0xc4201b7b40, 0xc4201fa280, 0xc420069300, 0x0)
	/go/src/github.com/vmware/vic/vendor/gopkg.in/urfave/cli.v1/app.go:485 +0xd4
github.com/vmware/vic/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xf612b1, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf6335e, 0xa, 0x0, ...)
	/go/src/github.com/vmware/vic/vendor/gopkg.in/urfave/cli.v1/command.go:193 +0xb72
github.com/vmware/vic/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420154b60, 0xc4200101c0, 0x1c, 0x1c, 0x0, 0x0)
	/go/src/github.com/vmware/vic/vendor/gopkg.in/urfave/cli.v1/app.go:250 +0x7d0
main.main()
	/go/src/github.com/vmware/vic/cmd/vic-machine/main.go:156 +0x220c
```

### PR DESCRIPTION
**Pull request by cgtexmex**
Gracefully handle a nil host firewall info object.

Fixes #6049

### CODE REVIEW

File: lib/install/validate/config.go [hunk 1]
```diff
@@ -156,6 +164,16 @@ func (v *Validator) CheckFirewallForTether(ctx context.Context, mgmtIP net.IPNet
 					status.MisconfiguredDisabled = append(status.MisconfiguredDisabled, host.InventoryPath)
 					log.Warn(err)
 				}
+			case *FirewallConfigUnavailableError:
+				if firewallEnabled {
+					log.Debugf("fw configuration unavailable %q", host.InventoryPath)
```
Comment (anchal-agrawal) [inline lib/install/validate/config.go]: Nit - `fw` can be ambiguous in the logs.

**Comment by emlin** [comment]
I'm good with it as long as the the issue does not happen for all hosts with SSH disabled. 😄

**Comment by cgtexmex** [comment]
@emlin it doesn't appear to be related to SSH...it's a property collector call that's being executed and apparently nothing was returned.  I've been unable to recreate that scenario...
