### PR TITLE
Show correct output while pulling fake image (#757)

### LINKED ISSUE #757: Incorrect output when attempting to pull a non-existant image
Docker:

```
vagrant@devbox ~/g/s/g/v/vic ❯❯❯ docker pull ibm/os2warp
Using default tag: latest
Pulling repository docker.io/ibm/os2warp
Error: image ibm/os2warp not found
```

VIC:

```
vagrant@devbox /U/z/g/s/g/v/vic ❯❯❯ docker $DOCKER_OPTS pull ibm/os2warp
Using default tag: latest
Error response from daemon: exit status 1
```

### PR DESCRIPTION
**Pull request by anchal-agrawal**
* Fixes output while pulling a non-existent image

Vanilla docker:
```
$ sudo docker pull foo/bar
Using default tag: latest
Pulling repository docker.io/foo/bar
Error: image foo/bar not found
```

VIC:
```
$ docker -H <host> --tls pull foo/bar
Using default tag: latest
latest: Pulling from foo/bar
Error: image foo/bar not found
```
* Enables related integration test for `docker pull`

Fixes #757

### CODE REVIEW

File: cmd/imagec/imagec.go [hunk 1]
```diff
@@ -694,18 +694,22 @@ func main() {
...
 	// HACK: Required to learn the name of the vmdk from given reference
 	// Used by docker personality until metadata support lands
 	if !options.resolv {
 		progress.Message(po, options.tag, "Pulling from "+options.image)
 	}
 
+	// Get the manifest
+	manifest, err := FetchImageManifest(options)
+	if err != nil {
+		if strings.Contains(err.Error(), "image not found") {
```
Comment (caglar10ur) [inline cmd/imagec/imagec.go]: this is ugly :) Why don't you just return the desired error message from the above function in the first place?

Comment (anchal-agrawal) [inline cmd/imagec/imagec.go]: Thanks for your input! I figured I didn't have the image name in `fetcher.go`, that's why I propagate `"image not found"` and add the name in `imagec.go`.

I believe the image name would be in the `url` struct there, so let me see if I can parse it out.

Comment (caglar10ur) [inline cmd/imagec/imagec.go]: options.image should be the image name in FetchImageManifest since we are passing the whole struct to it

Comment (caglar10ur) [inline cmd/imagec/imagec.go]: Hmm I see what you are saying now, it's fetch function that returning the error not FetchImageManifest

Comment (caglar10ur) [inline cmd/imagec/imagec.go]: One other possibility is starting to return typed errors and use assertion instead of parsing the error message itself but that could be more involved

I'll create an issue for that.

LGTM

Comment (caglar10ur) [inline cmd/imagec/imagec.go]: https://github.com/vmware/vic/issues/1710 is created to track that work

Comment (matthewavery) [inline cmd/imagec/imagec.go]: lgtm :sheep: :it:

**Comment by matthewavery** [comment]
lgtm :sheep:  :it:

**Comment by caglar10ur** [comment]
LGTM :sheep: :it: (

**Comment by anchal-agrawal** [comment]
Triggered another build, it had failed while downloading test logs.
