### PR TITLE
vic-machine uses default datastore if not specified

### LINKED ISSUE #1206: vic-machine should default to datastore if only one exists.
**VIC Version:**
https://bintray.com/vmware/vic-repo/download_file?file_path=vic_2151.tar.gz

ESX version
VMware-VMvisor-Installer-6.0.0-3634798.x86_64 installed with all defaults in Fusion. 

**Expected behavior:**
With only 1 datastore we should default to using it without failing, if more than 1 then present the options.

**Actual behavior:**
(mwilliamson) dubs:~/Downloads/vic 3 $ ./vic-machine-darwin create --target 172.16.127.129 --user root --password 'virtualized'
--image-datastore Image datastore name must be specified

### PR DESCRIPTION
**Pull request by andrewtchin**
Fixes #1206 

vC:
```
⇒  bin/vic-machine-linux create --target 10.17.109.115/dc1  --name chin-vic-18 --user administrator@vsphere.local --password password --compute-resource cluster1/chin  --bridge-network vch-test
INFO[2016-08-12T13:50:02-07:00] ### Installing VCH ####                      
INFO[2016-08-12T13:50:02-07:00] Generating certificate/key pair - private key in ./chin-vic-18-key.pem 
INFO[2016-08-12T13:50:03-07:00] Validating supplied configuration            
INFO[2016-08-12T13:50:03-07:00] Using default datastore: vsanDatastore  
INFO[2016-08-12T13:50:04-07:00] vDS configuration OK on "vch-test"           
INFO[2016-08-12T13:50:04-07:00] Firewall status: ENABLED on "/dc1/host/cluster1/10.17.109.74" 
INFO[2016-08-12T13:50:05-07:00] Firewall status: ENABLED on "/dc1/host/cluster1/10.17.109.76" 
INFO[2016-08-12T13:50:05-07:00] Firewall status: ENABLED on "/dc1/host/cluster1/10.17.109.169" 
INFO[2016-08-12T13:50:05-07:00] Firewall configuration OK on hosts:          
INFO[2016-08-12T13:50:05-07:00]   "/dc1/host/cluster1/10.17.109.74"          
INFO[2016-08-12T13:50:05-07:00]   "/dc1/host/cluster1/10.17.109.76"          
INFO[2016-08-12T13:50:05-07:00]   "/dc1/host/cluster1/10.17.109.169"         
INFO[2016-08-12T13:50:06-07:00] License check OK on hosts:                   
INFO[2016-08-12T13:50:06-07:00]   "/dc1/host/cluster1/10.17.109.74"          
INFO[2016-08-12T13:50:06-07:00]   "/dc1/host/cluster1/10.17.109.76"          
INFO[2016-08-12T13:50:06-07:00]   "/dc1/host/cluster1/10.17.109.169"         
INFO[2016-08-12T13:50:06-07:00] DRS check OK on:                             
INFO[2016-08-12T13:50:06-07:00]   "/dc1/host/cluster1/Resources/chin"        
INFO[2016-08-12T13:50:07-07:00] Creating virtual app "chin-vic-18"           
INFO[2016-08-12T13:50:07-07:00] Creating appliance on target                 
INFO[2016-08-12T13:50:07-07:00] Network role "client" is sharing NIC with "external" 
INFO[2016-08-12T13:50:07-07:00] Network role "management" is sharing NIC with "external" 
INFO[2016-08-12T13:50:24-07:00] Uploading images for container               
INFO[2016-08-12T13:50:24-07:00] "/home/chin/go/src/github.com/vmware/vic/bin/bootstrap.iso" 
INFO[2016-08-12T13:50:24-07:00] "/home/chin/go/src/github.com/vmware/vic/bin/appliance.iso" 
INFO[2016-08-12T13:51:01-07:00] Registering VCH as a vSphere extension       
INFO[2016-08-12T13:51:14-07:00] Waiting for IP information                   
INFO[2016-08-12T13:51:50-07:00] Waiting for major appliance components to launch 
INFO[2016-08-12T13:51:51-07:00] Initialization of appliance successful       
INFO[2016-08-12T13:51:51-07:00]                                              
INFO[2016-08-12T13:51:51-07:00] vic-admin portal:                            
INFO[2016-08-12T13:51:51-07:00] https://10.17.109.140:2378                   
INFO[2016-08-12T13:51:51-07:00]                                              
INFO[2016-08-12T13:51:51-07:00] DOCKER_HOST=10.17.109.140:2376               
INFO[2016-08-12T13:51:51-07:00]                                              
INFO[2016-08-12T13:51:51-07:00] Connect to docker:                           
INFO[2016-08-12T13:51:51-07:00] docker -H 10.17.109.140:2376 --tls info      
INFO[2016-08-12T13:51:51-07:00] Installer completed successfully  
```

ESX:
```
⇒  bin/vic-machine-linux create --target 192.168.218.177 --name chin-vic-110 --user root --password password 
INFO[2016-08-12T13:52:21-07:00] ### Installing VCH ####                      
INFO[2016-08-12T13:52:21-07:00] Generating certificate/key pair - private key in ./chin-vic-110-key.pem 
INFO[2016-08-12T13:52:22-07:00] Validating supplied configuration            
INFO[2016-08-12T13:52:22-07:00] Using default datastore: datastore1     
INFO[2016-08-12T13:52:22-07:00] Firewall status: DISABLED on "/ha-datacenter/host/localhost.localdomain/localhost.localdomain" 
INFO[2016-08-12T13:52:22-07:00] Firewall configuration OK on hosts:          
INFO[2016-08-12T13:52:22-07:00]   "/ha-datacenter/host/localhost.localdomain/localhost.localdomain" 
WARN[2016-08-12T13:52:22-07:00] Evaluation license detected. VIC may not function if evaluation expires or insufficient license is later assigned. 
INFO[2016-08-12T13:52:22-07:00] License check OK                             
INFO[2016-08-12T13:52:22-07:00] DRS check SKIPPED - target is standalone host 
INFO[2016-08-12T13:52:22-07:00] Creating Resource Pool "chin-vic-110"        
INFO[2016-08-12T13:52:22-07:00] Creating VirtualSwitch                       
INFO[2016-08-12T13:52:22-07:00] Creating Portgroup                           
INFO[2016-08-12T13:52:23-07:00] Creating appliance on target                 
INFO[2016-08-12T13:52:23-07:00] Network role "client" is sharing NIC with "external" 
INFO[2016-08-12T13:52:23-07:00] Network role "management" is sharing NIC with "external" 
INFO[2016-08-12T13:52:23-07:00] Uploading images for container               
INFO[2016-08-12T13:52:23-07:00] "/home/chin/go/src/github.com/vmware/vic/bin/bootstrap.iso" 
INFO[2016-08-12T13:52:23-07:00] "/home/chin/go/src/github.com/vmware/vic/bin/appliance.iso" 
INFO[2016-08-12T13:52:27-07:00] Waiting for IP information                   
INFO[2016-08-12T13:52:38-07:00] Waiting for major appliance components to launch 
INFO[2016-08-12T13:52:38-07:00] Initialization of appliance successful       
INFO[2016-08-12T13:52:38-07:00]                                              
INFO[2016-08-12T13:52:38-07:00] vic-admin portal:                            
INFO[2016-08-12T13:52:38-07:00] https://192.168.218.136:2378                 
INFO[2016-08-12T13:52:38-07:00]                                              
INFO[2016-08-12T13:52:38-07:00] DOCKER_HOST=192.168.218.136:2376             
INFO[2016-08-12T13:52:38-07:00]                                              
INFO[2016-08-12T13:52:38-07:00] Connect to docker:                           
INFO[2016-08-12T13:52:38-07:00] docker -H 192.168.218.136:2376 --tls info    
INFO[2016-08-12T13:52:38-07:00] Installer completed successfully 
```

Multiple DS present:
```
⇒  bin/vic-machine-linux create --target 192.168.218.177 --name chin-vic-110 --user root --password password                                                                       
INFO[2016-08-12T13:57:43-07:00] ### Installing VCH ####                      
INFO[2016-08-12T13:57:43-07:00] Generating certificate/key pair - private key in ./chin-vic-110-key.pem 
INFO[2016-08-12T13:57:43-07:00] Validating supplied configuration            
INFO[2016-08-12T13:57:43-07:00] Suggesting valid values for --image-store based on "*" 
INFO[2016-08-12T13:57:43-07:00] Suggested values for --image-store:          
INFO[2016-08-12T13:57:43-07:00]   "datastore1"                               
INFO[2016-08-12T13:57:43-07:00]   "ds2"                                      
ERRO[2016-08-12T13:57:43-07:00] Firewall check SKIPPED                       
ERRO[2016-08-12T13:57:43-07:00]   datastore not set                          
ERRO[2016-08-12T13:57:43-07:00] License check SKIPPED                        
ERRO[2016-08-12T13:57:43-07:00]   datastore not set                          
ERRO[2016-08-12T13:57:43-07:00] DRS check SKIPPED                            
ERRO[2016-08-12T13:57:43-07:00]   datastore not set                          
ERRO[2016-08-12T13:57:43-07:00] Compatibility check SKIPPED                  
ERRO[2016-08-12T13:57:43-07:00]   datastore not set                          
ERRO[2016-08-12T13:57:43-07:00] --------------------                         
ERRO[2016-08-12T13:57:43-07:00] datastore hostname empty                     
ERRO[2016-08-12T13:57:43-07:00] Firewall check SKIPPED                       
ERRO[2016-08-12T13:57:43-07:00] License check SKIPPED                        
ERRO[2016-08-12T13:57:43-07:00] DRS check SKIPPED                            
ERRO[2016-08-12T13:57:43-07:00] Compatibility check SKIPPED                  
ERRO[2016-08-12T13:57:43-07:00] Create cannot continue: configuration validation failed 
ERRO[2016-08-12T13:57:43-07:00] --------------------                         
ERRO[2016-08-12T13:57:43-07:00] vic-machine-linux failed: validation of configuration failed

```

### CODE REVIEW

File: lib/install/validate/storage.go [hunk 1]
```diff
@@ -92,9 +92,17 @@ func (v *Validator) DatastoreHelper(ctx context.Context, path string, label stri
...
-		v.suggestDatastore("*", label, flag)
-		return nil, nil, errors.New("datastore hostname empty")
+		// see if we can find a default datastore
+		store, err := v.Session.Finder.DatastoreOrDefault(ctx, "*")
+		if err == nil {
+			dsURL.Host = store.Name()
+			log.Infof("Using default datastore: %s", dsURL.Host)
+		} else {
+			v.suggestDatastore("*", label, flag)
+			return nil, nil, errors.New("datastore hostname empty")
```
Comment (caglar10ur) [inline lib/install/validate/storage.go]: s/hostname/name/g

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

File: lib/install/validate/storage.go [hunk 2]
```diff
@@ -92,9 +92,17 @@ func (v *Validator) DatastoreHelper(ctx context.Context, path string, label stri
 			dsURL.Path = ""
 		}
 	}
+
 	if dsURL.Host == "" {
-		v.suggestDatastore("*", label, flag)
-		return nil, nil, errors.New("datastore hostname empty")
+		// see if we can find a default datastore
+		store, err := v.Session.Finder.DatastoreOrDefault(ctx, "*")
+		if err == nil {
```
Comment (hmahmood) [inline lib/install/validate/storage.go]: Looks nicer: :-)
```go
if err != nil {
  v.suggestDatastore("*", label, flag)
   return nil, nil, errors.New("datastore hostname empty")
}

dsURL.Host = store.Name()
log.Infof("Using default datastore: %s", dsURL.Host)
```

File: tests/test-cases/Group6-VIC-Machine/6-5-Create-Validation.robot [hunk 3]
```diff
@@ -29,3 +29,24 @@ Suggest resources - Invalid target path
...
+
+    Log To Console  \nInstalling VCH to test server...
+    ${output}=  Run  bin/vic-machine-linux create --name=${vch-name} --target=%{TEST_URL} --user=%{TEST_USERNAME} --password=%{TEST_PASSWORD}
+    Log To Console  ${output}
+    Should Contain  ${output}  Using default datastore
+    Should Contain  ${output}  Installer completed successfully
+    Get Docker Params  ${output}  ${true}
+    Log To Console  Installer completed successfully: ${vch-name}...
+    Sleep  10 seconds
+    ${status}=  Get State Of Github Issue  1109
```
Comment (hmahmood) [inline tests/test-cases/Group6-VIC-Machine/6-5-Create-Validation.robot]: What does 1109 have to do with this test?

File: tests/test-cases/Group6-VIC-Machine/6-5-Create-Validation.robot [hunk 4]
```diff
@@ -29,3 +29,24 @@ Suggest resources - Invalid target path
     ${output}=  Run  bin/vic-machine-linux create --name=${vch-name} --target=%{TEST_URL}/MUCH/DATACENTER --user=%{TEST_USERNAME} --image-store=%{TEST_DATASTORE} --password=%{TEST_PASSWORD}
     Should Contain  ${output}  Suggested datacenters:
     Should Contain  ${output}  vic-machine-linux failed
+
+Default image datastore
+    Log To Console  \nRunning vic-machine create - default image datastore
```
Comment (hmahmood) [inline tests/test-cases/Group6-VIC-Machine/6-5-Create-Validation.robot]: Do we test if we can't find a datastore to use? The `else` case in the code above?

File: lib/install/validate/storage.go (hunk 1 above)
Comment (fdawg4l) [inline lib/install/validate/storage.go]: s/hostname//g

**Comment by fdawg4l** [comment]
LGTM

File: tests/test-cases/Group6-VIC-Machine/6-5-Create-Validation.robot (hunk 3 above)
Comment (andrewtchin) [inline tests/test-cases/Group6-VIC-Machine/6-5-Create-Validation.robot]: this is a timing issue that can cause the test case to fail if we don't sleep. for most of the other integration tests this issue check is in the `Install VIC Appliance To Test Server` keyword

File: tests/test-cases/Group6-VIC-Machine/6-5-Create-Validation.robot (hunk 4 above)
Comment (andrewtchin) [inline tests/test-cases/Group6-VIC-Machine/6-5-Create-Validation.robot]: not right now since we don't have a way to change datastores in our test env

File: lib/install/validate/storage.go (hunk 2 above)
Comment (andrewtchin) [inline lib/install/validate/storage.go]: lol nice

**Comment by hmahmood** [comment]
lgtm

**Comment by andrewtchin** [comment]
♻️

File: tests/test-cases/Group6-VIC-Machine/6-5-Create-Validation.robot [hunk 5]
```diff
@@ -29,3 +29,25 @@ Suggest resources - Invalid target path
...
+    Set Test Environment Variables  ${true}  default  network  'VM Network'
+    # Attempt to cleanup old/canceled tests
+    Run Keyword And Ignore Error  Cleanup Dangling VMs On Test Server
+    Run Keyword And Ignore Error  Cleanup Datastore On Test Server
+    Set Test VCH Name
+
+    Log To Console  \nInstalling VCH to test server...
+    ${output}=  Run  bin/vic-machine-linux create --name=${vch-name} --target=%{TEST_URL} --user=%{TEST_USERNAME} --password=%{TEST_PASSWORD}
+    Log To Console  ${output}
```
Comment (mhagen-vmware) [inline tests/test-cases/Group6-VIC-Machine/6-5-Create-Validation.robot]: Can we get rid of this line?
