### PR TITLE
Fix docker run/run -i and run -t truncation

### LINKED ISSUE #2660: docker run -itd busybox dmesg hangs and truncates
End's mid log message:
[    0.114184] TCP bind hash table entries: 16384 (order: 6, 262144 bytes)
[    0.114198] TCP: Hash tables configured (established 16384 bind 16384)
[    0.114209] UDP hash table entries: 1024 (order: 3, 32768 bytes)
[    0.114212] UDP-L

Docker, prints all and returns.

Attaching to the container just hangs, and doing a log on the container just prints the same output.  This also happens when directly attaching with run -it.

This is running on our new hardware VC cluster.

### PR DESCRIPTION
**Pull request by caglar10ur**
We now control Std{in|out|err}Pipe's directly and copy between them and dio

This PR also;

- Adds OpenStdin bool to the SessionConfig to indicate whether we should be opening stdin or not
- Sets the serial lines speed to 115200.
- Various cleanups

Fixes #2660

### CODE REVIEW

File: cmd/tether/attach_linux.go [hunk 1]
```diff
@@ -33,6 +33,48 @@ import (
...
+
+	// copy it as the future
+	future := current.termios
+
+	// unset 9600 bps
+	future.Cflag &^= syscall.B9600
+	// set them to 115200 bps
+	future.Cflag |= syscall.B115200
+	future.Ispeed = syscall.B115200
+	future.Ospeed = syscall.B115200
```
Comment (vburenin) [inline cmd/tether/attach_linux.go]: Have you tested this speed? I tried to change speed of serial ports and didn't notice any changes. Direct write/read into serial port device handles around 60KB/s

File: lib/tether/tether.go [hunk 2]
```diff
@@ -442,24 +445,26 @@ func (t *tether) Register(name string, extension Extension) {
...
 	if session.wait != nil {
+		log.Debugf("Waiting on session.wait")
 		session.wait.Wait()
+		log.Debugf("Wait on session.wait completed")
 	}
 
-	// reader must be closed before calling wait, and this must interrupt the underlying Read
-	// or Wait will not return.
+	log.Debugf("Calling wait on cmd")
+	log.Errorf("Wait returned %s", session.Cmd.Wait())
```
Comment (vburenin) [inline lib/tether/tether.go]: is it an error?

File: lib/tether/tether_linux.go [hunk 3]
```diff
@@ -35,6 +34,10 @@ const (
 	//https://github.com/golang/go/blob/master/src/syscall/zerrors_linux_arm64.go#L919
 	SetChildSubreaper = 0x24
 	pidFilePath       = "var/run"
+
+	// in sync with lib/apiservers/portlayer/handlers/interaction_handler.go
+	// 115200 bps is 14.4 KB/s so use that
+	ioCopyBufferSize = 14 * 1024
```
Comment (vburenin) [inline lib/tether/tether_linux.go]: Real speed is faster, it is around 60KB.

File: cmd/tether/attach_linux.go (hunk 1 above)
Comment (caglar10ur) [inline cmd/tether/attach_linux.go]: This is just setting the correct value on the linux side, I don't think there is a speed limit on the ESXi side. By the way how did you test it?

File: lib/tether/tether.go (hunk 2 above)
Comment (caglar10ur) [inline lib/tether/tether.go]: Ahh, leftover. Taking care of

File: lib/tether/tether_linux.go (hunk 3 above)
Comment (caglar10ur) [inline lib/tether/tether_linux.go]: see ^ above

File: cmd/tether/attach_linux.go (hunk 1 above)
Comment (vburenin) [inline cmd/tether/attach_linux.go]: there were two ways.
1. I measured transfer speed between two points by implementing my own read/write wrapper - it is not precise, however I was getting speeds like 30-50KB/s for terminal sessions while running midnight commander or vmware/powercli - these are doing massive data updates on screen.
2. dd if=/dev/zere of=/.tether/<serial_port>

File: lib/tether/tether.go [hunk 4]
```diff
@@ -339,6 +340,8 @@ func (t *tether) processSessions() error {
 					err:  t.launch(session),
 				}
 			}(session)
+
+			session.Unlock()
```
Comment (hmahmood) [inline lib/tether/tether.go]: You have this inside the `if {...}` clause only. If this clause is skipped, you will deadlock at the start of the loop when you try to lock again.

File: lib/tether/tether.go [hunk 5]
```diff
@@ -442,24 +445,33 @@ func (t *tether) Register(name string, extension Extension) {
...
+	}
 
 	// close down the outputs
-	session.Outwriter.Close()
+	log.Debugf("Calling close on writers")
+	if err := session.Outwriter.Close(); err != nil {
+		log.Warnf("Close for Outwriter returned %s", err)
+	}
 	session.Errwriter.Close()
+	if err := session.Errwriter.Close(); err != nil {
```
Comment (hmahmood) [inline lib/tether/tether.go]: Calling `session.Errwriter.Close()` twice?

File: lib/tether/tether_linux.go [hunk 6]
```diff
@@ -213,29 +216,104 @@ func lookPath(file string, env []string, dir string) (string, error) {
...
+
+	if session.OpenStdin {
 		go func() {
-			_, gerr := io.Copy(session.Pty, session.Reader)
-			log.Debugf("PTY stdin copy: %s", gerr)
+			_, gerr := io.CopyBuffer(session.StdinPipe, session.Reader, make([]byte, ioCopyBufferSize))
+			log.Debugf("Reader stdin returned: %s", gerr)
+
+			if gerr == nil {
+				if cerr := session.StdinPipe.Close(); cerr != nil {
```
Comment (hmahmood) [inline lib/tether/tether_linux.go]: Do you need to close this? Documentation for Cmd.StdinPipe() stays it will closed when Cmd.Wait() returns.

File: lib/tether/tether.go (hunk 4 above)
Comment (caglar10ur) [inline lib/tether/tether.go]: ah good catch! Fixed

File: lib/tether/tether.go (hunk 5 above)
Comment (caglar10ur) [inline lib/tether/tether.go]: Fixed

File: lib/tether/tether_linux.go (hunk 6 above)
Comment (caglar10ur) [inline lib/tether/tether_linux.go]: that's for the other case (if the command being run will not exit until standard input is closed, the caller must close the pipe.)

Comment (hmahmood) [inline lib/tether/tether_linux.go]: Is that the case here? i.e. we have to close this here for the command to exit? I thought we called Cmd.Wait() somewhere in the tether.

File: lib/portlayer/network/network.go [hunk 7]
```diff
@@ -20,6 +20,8 @@ import (
 
 	log "github.com/Sirupsen/logrus"
 
+	"golang.org/x/net/context"
```
Comment (hmahmood) [inline lib/portlayer/network/network.go]: Are we moving back to this from just `"context"`

Comment (caglar10ur) [inline lib/portlayer/network/network.go]: hmm nope, this was the result of goimports but while at it I'll move them to context

File: lib/tether/tether_linux.go (hunk 6 above)
Comment (caglar10ur) [inline lib/tether/tether_linux.go]: We do call it in the childReaper but for that the command need to exit, tee for example won't exit unless you close the stdin

**Comment by hmahmood** [comment]
lgtm

**Comment by vburenin** [comment]
LGTM

File: lib/apiservers/engine/backends/container_proxy.go [hunk 8]
```diff
@@ -1242,7 +1245,9 @@ func containerConfigFromContainerInfo(vc *viccontainer.VicContainer, info *model
 		container.Tty = *info.ContainerConfig.Tty // Attach standard streams to a tty, including stdin if it is not closed.
 	}
 	// They are not coming from PL so set them to true unconditionally
```
Comment (hickeng) [inline lib/apiservers/engine/backends/container_proxy.go]: comment is now incorrect

File: lib/tether/tether.go [hunk 9]
```diff
@@ -442,24 +445,33 @@ func (t *tether) Register(name string, extension Extension) {
...
-	session.Lock()
-	defer session.Unlock()
+	log.Debugf("Waiting on session.wait")
+	session.wait.Wait()
+	log.Debugf("Wait on session.wait completed")
 
-	if session.wait != nil {
-		session.wait.Wait()
+	log.Debugf("Calling wait on cmd")
+	if err := session.Cmd.Wait(); err != nil {
```
Comment (hickeng) [inline lib/tether/tether.go]: I assume that we no longer need to close the Reader first?

File: lib/tether/tether.go [hunk 10]
```diff
@@ -442,24 +445,33 @@ func (t *tether) Register(name string, extension Extension) {
 func (t *tether) handleSessionExit(session *SessionConfig) {
```
Comment (hickeng) [inline lib/tether/tether.go]: comment that the caller needs to hold the session lock

File: lib/tether/tether_linux.go [hunk 11]
```diff
@@ -213,29 +216,104 @@ func lookPath(file string, env []string, dir string) (string, error) {
...
+	}
 
-		// TODO: do we need to ensure all reads have completed before calling Wait on the process?
-		// it frees up all resources - does that mean it frees the output buffers?
-		go func() {
-			_, gerr := io.Copy(session.Outwriter, session.Pty)
-			log.Debugf("PTY stdout copy: %s", gerr)
+	session.wait.Add(1)
+	go func() {
+		_, gerr := io.CopyBuffer(session.Outwriter, session.Pty, make([]byte, ioCopyBufferSize))
```
Comment (hickeng) [inline lib/tether/tether_linux.go]: Most performant option would be to implement ReadFrom in MutliWriter.

File: lib/tether/tether_linux.go [hunk 12]
```diff
@@ -213,29 +216,104 @@ func lookPath(file string, env []string, dir string) (string, error) {
...
+	}
+
+	if session.OpenStdin {
 		go func() {
-			_, gerr := io.Copy(session.Pty, session.Reader)
-			log.Debugf("PTY stdin copy: %s", gerr)
+			_, gerr := io.CopyBuffer(session.StdinPipe, session.Reader, make([]byte, ioCopyBufferSize))
+			log.Debugf("Reader stdin returned: %s", gerr)
+
+			if gerr == nil {
```
Comment (hickeng) [inline lib/tether/tether_linux.go]: Do we need to close this if the err is non-nil as well?

File: lib/tether/tether_linux.go [hunk 13]
```diff
@@ -213,29 +216,104 @@ func lookPath(file string, env []string, dir string) (string, error) {
...
+	// Add 2 for Std{out|err}
+	session.wait.Add(2)
+	go func() {
+		_, gerr := io.CopyBuffer(session.Outwriter, session.StdoutPipe, make([]byte, ioCopyBufferSize))
+		log.Debugf("Writer goroutine for stdout returned: %s", gerr)
+
+		if session.StdinPipe != nil {
+			log.Debugf("(stdout): Writing zero byte to stdin pipe")
+			n, werr := session.StdinPipe.Write([]byte{})
+			if n == 0 && werr != nil && werr.Error() == "write |1: bad file descriptor" {
```
Comment (hickeng) [inline lib/tether/tether_linux.go]: What is the intent here? I would have thought that if Write is returning bad file descriptor, then the stdin Copy routine would have exited and we could close there.
If we need to close here, why are we not closing in all conditions, and only on bad file descriptor error?

File: tests/manual-test-cases/Group17-ManualTTY/17-1-TTY-Tests.robot [hunk 14]
```diff
@@ -32,4 +32,28 @@ Docker run -it command that doesn't stop
     ${out}=  Run  docker ${params} logs ${containerID}
     Should Contain  ${out}  Mem:
     Should Contain  ${out}  CPU:
-    Should Contain  ${out}  Load average:
\ No newline at end of file
+    Should Contain  ${out}  Load average:
+
+Docker run with -i
+    ${rc}  ${output}=  Run And Return Rc And Output  docker ${params} run -i busybox dmesg
```
Comment (hickeng) [inline tests/manual-test-cases/Group17-ManualTTY/17-1-TTY-Tests.robot]: can we use the following or similar - relying on dmesg output stability make break us in the future:
`run -i busybox /bin/ash -c "dmesg;echo complete"`

File: cmd/vic-machine/create/create.go [hunk 15]
```diff
@@ -42,7 +42,7 @@ import (
 
 	"crypto/x509"
 
-	"golang.org/x/net/context"
+	"context"
```
Comment (anchal-agrawal) [inline cmd/vic-machine/create/create.go]: Should we move `context` to the first group of imports?

File: cmd/vic-machine/debug/debug.go [hunk 16]
```diff
@@ -29,7 +30,7 @@ import (
 	"github.com/vmware/vic/pkg/version"
 	"github.com/vmware/vic/pkg/vsphere/vm"
 
-	"golang.org/x/net/context"
+	"context"
```
Comment (anchal-agrawal) [inline cmd/vic-machine/debug/debug.go]: ditto

File: lib/apiservers/engine/backends/container_proxy.go (hunk 8 above)
Comment (caglar10ur) [inline lib/apiservers/engine/backends/container_proxy.go]: still true for the next line so moved there

File: lib/tether/tether.go (hunk 9 above)
Comment (caglar10ur) [inline lib/tether/tether.go]: nope

File: lib/tether/tether.go (hunk 10 above)
Comment (caglar10ur) [inline lib/tether/tether.go]: done

File: lib/tether/tether_linux.go (hunk 12 above)
Comment (caglar10ur) [inline lib/tether/tether_linux.go]: err means StdinPipe is closed so we should be fine there

File: tests/manual-test-cases/Group17-ManualTTY/17-1-TTY-Tests.robot (hunk 14 above)
Comment (caglar10ur) [inline tests/manual-test-cases/Group17-ManualTTY/17-1-TTY-Tests.robot]: done

File: cmd/vic-machine/create/create.go (hunk 15 above)
Comment (caglar10ur) [inline cmd/vic-machine/create/create.go]: done

File: lib/tether/tether_linux.go (hunk 13 above)
Comment (caglar10ur) [inline lib/tether/tether_linux.go]: This is a left over from pipe work (#3017) shouldn't affect this.

**Comment by caglar10ur** [comment]
♻️

**Comment by caglar10ur** [comment]
[squashed the commits as I'm still not sure whether github squash & merge works or not]

**Comment by caglar10ur** [comment]
♻️
