### PR TITLE
[full ci] Fix multiple data races reported by race detector

### LINKED ISSUE #2647: [tether] serverConn needs to protected by a lock
```
goroutine 12 [running]:
panic(0x8a3640, 0xc42000c050)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.(*attachServerSSH).run.func1(0xc420136088)
        /opt/go/src/github.com/vmware/vic/cmd/tether/attach.go:216 +0xa8
main.(*attachServerSSH).run(0xc420059ec0, 0x0, 0x0)
        /opt/go/src/github.com/vmware/vic/cmd/tether/attach.go:313 +0x175b
created by main.(*attachServerSSH).start
        /opt/go/src/github.com/vmware/vic/cmd/tether/attach.go:144 +0x334
```

### PR DESCRIPTION
**Pull request by caglar10ur**
- attachServerSSH uses sync/atomic to get/set enabled value as there was
a race between stop and run

- underlying *net.Conn is now protected by its own mutex as there was a
race between stop and run

- *ssh.ServerConn is now protected by its own mutex as we are sending
it to channel mux (as a part of the cleanup function)

- incoming signals channel in tether is now accompanied by another
channel called done. Its whole purpose is to stop the reaper loop after we
close the incoming channel. Without this we keep reading from it.

Fixes #2647, #2646 and #2330

### CODE REVIEW

File: cmd/tether/attach.go [hunk 1]
```diff
@@ -87,6 +92,21 @@ func (t *attachServerSSH) Reload(config *tether.ExecutorConfig) error {
 	return nil
 }
 
+// Enabled sets the enabled to true
+func (t *attachServerSSH) Enabled() {
+	atomic.StoreInt32(&t.enabled, 1)
```
Comment (hmahmood) [inline cmd/tether/attach.go]: Do we need this given that you grab the attachServerSSH lock when you change enabled in start() and stop() below?

Comment (hmahmood) [inline cmd/tether/attach.go]: You need this for the IsReload() call in run() ... nvm.

File: cmd/tether/attach.go [hunk 2]
```diff
@@ -200,21 +239,28 @@ func (t *attachServerSSH) run() error {
...
 		defer func() {
 			log.Debugf("cleanup on connection")
 
-			if serverConn != nil {
+			serverConn.Lock()
+			if serverConn.ServerConn != nil {
 				log.Debugf("closing underlying connection")
 				serverConn.Close()
 			}
+			serverConn.Lock()
```
Comment (hmahmood) [inline cmd/tether/attach.go]: `Unlock()`? I would use `defer` here.

Comment (caglar10ur) [inline cmd/tether/attach.go]: Done

File: cmd/tether/attach.go [hunk 3]
```diff
@@ -150,46 +170,65 @@ func (t *attachServerSSH) start() error {
...
+		serverConn.Lock()
+		established = serverConn.ServerConn != nil
+		serverConn.Unlock()
 		// keep waiting for the connection to establish
-		for serverConn == nil {
+		for !established {
+			log.Debugf("Trying to establish a connection")
 			// tests are passing their own connections so do not create connections when testing is set
 			if !t.testing {
+				t.conn.Lock()
```
Comment (caglar10ur) [inline cmd/tether/attach.go]: Done

File: lib/tether/tether.go [hunk 4]
```diff
@@ -65,6 +65,7 @@ type tether struct {
 	sink extraconfig.DataSink
 
 	incoming chan os.Signal
+	done     chan bool
```
Comment (hmahmood) [inline lib/tether/tether.go]: If you just want to signal stop, use `chan struct{}`, and then close the channel when you want to signal.

**Comment by caglar10ur** [comment]
@hmahmood refactoring the code showed another race between the Close and the Backchannel, would be glad if you could review again

File: lib/tether/tether_linux.go [hunk 5]
```diff
@@ -126,10 +136,17 @@ func (t *tether) childReaper() error {
...
+	// Ordering is important otherwise we may one goroutine closing, and the other goroutine is trying to write afterwards
+	log.Debugf("Removing the signal notifier")
 	signal.Reset(syscall.SIGCHLD)
+
+	log.Debugf("Closing the channel done to reaper")
 	close(t.incoming)
+
+	log.Debugf("Sending true to the done channel")
+	// just closing the channel is not going to stop the iteration over the channel so signal it as well
+	t.done <- true
```
Comment (caglar10ur) [inline lib/tether/tether_linux.go]: We weren't now we are :)

File: cmd/tether/attach.go (hunk 3 above)
Comment (caglar10ur) [inline cmd/tether/attach.go]: Done

Comment (caglar10ur) [inline cmd/tether/attach.go]: Found another issue and was fixing that, pushed couple of min. ago

File: pkg/serial/handshake.go [hunk 6]
```diff
@@ -162,9 +162,26 @@ func HandshakeClient(ctx context.Context, conn net.Conn, debug bool) error {
...
+			n, err := conn.Read(b)
+			c <- ioret{n, err}
+			close(c)
+		}()
+
+		select {
+		case ret := <-c:
+			return ret.n, ret.err
+		case <-ctx.Done():
+			return 0, ctx.Err()
```
Comment (caglar10ur) [inline pkg/serial/handshake.go]: SetReadDeadline doesn't work on serial (rawconn doesn't implement them) and I don't know any other way to cancel a read

File: cmd/tether/attach.go [hunk 7]
```diff
@@ -150,68 +178,102 @@ func (t *attachServerSSH) start() error {
 func (t *attachServerSSH) stop() {
 	defer trace.End(trace.Begin("stop attach server"))
 
-	if t == nil || !t.enabled {
+	if t == nil || !t.IsEnabled() {
```
Comment (fdawg4l) [inline cmd/tether/attach.go]: Think this is worth a `Debugf`?

File: cmd/tether/attach.go [hunk 8]
```diff
@@ -150,68 +178,102 @@ func (t *attachServerSSH) start() error {
...
+			log.Debugf("Trying to establish a connection")
 			// tests are passing their own connections so do not create connections when testing is set
-			if !t.testing {
-				// close the connection if required
-				if t.conn != nil {
-					(*t.conn).Close()
+
+			establishFn := func() error {
+				t.conn.Lock()
+				defer t.conn.Unlock()
```
Comment (fdawg4l) [inline cmd/tether/attach.go]: `for` loop with a `defer Unlock`.  You'll pile these `defer`s up if you don't exit the loop, right?

File: cmd/tether/attach.go [hunk 9]
```diff
@@ -51,11 +52,18 @@ type attachServerSSH struct {
 	m sync.Mutex
 
 	// conn is held directly as it's how we stop the attach server
-	conn      *net.Conn
+	conn struct {
+		sync.Mutex
```
Comment (fdawg4l) [inline cmd/tether/attach.go]: Reading the code, I think i understand the lock contract: Enabled, conn lock, and Disabled, con unlock. I think :-). Can you add a (big honking) comment about the lock order?

File: lib/tether/tether_linux.go [hunk 10]
```diff
@@ -68,9 +68,11 @@ func (t *tether) childReaper() error {
 
 	go func() {
 		var status syscall.WaitStatus
-
 		flag := syscall.WNOHANG | syscall.WUNTRACED | syscall.WCONTINUED
+
 		for range t.incoming {
+			log.Debugf("Woke up because of a received SIGCHLD")
```
Comment (hickeng) [inline lib/tether/tether_linux.go]: This message and "Inspecting children with status change" will always proc together - redundant

File: cmd/tether/attach.go (hunk 7 above)
Comment (caglar10ur) [inline cmd/tether/attach.go]: Done (pushed as a new commit)

File: lib/tether/tether_linux.go [hunk 11]
```diff
@@ -126,10 +137,16 @@ func (t *tether) childReaper() error {
 func (t *tether) stopReaper() {
```
Comment (hickeng) [inline lib/tether/tether_linux.go]: can you confirm that we don't call this until all directly launched children have exited?

File: cmd/tether/attach.go [hunk 12]
```diff
@@ -140,78 +171,121 @@ func (t *attachServerSSH) start() error {
...
+	t.Disabled()
 
-	if conn != nil {
-		(*conn).Close()
+	log.Debugf("Canceling the context")
+	t.cancel()
+
+	log.Debugf("Acquiring the connection lock")
+	t.conn.Lock()
+	if t.conn.conn != nil {
```
Comment (fdawg4l) [inline cmd/tether/attach.go]: Looks like in `Start()`, Enabled is set, then `t.conn.Lock()` is acquired, and `t.conn.conn` is assigned in `run()`.  But here, we set disabled, acquire the `conn` lock , then do this check.  Is it possible Start() will set enabled, then in another routine we call `stop`, set disabled, acquire the `conn.Lock`, find this nil before `run()` has a chance to assign, fall out of `stop`, and run now has a dangling `conn`?

File: lib/tether/tether_linux.go [hunk 13]
```diff
@@ -126,10 +137,16 @@ func (t *tether) childReaper() error {
...
 	defer trace.End(trace.Begin("Shutting down child reaping"))
 
-	// stop child reaping
-	log.Info("Shutting down reaper")
+	// Ordering is important otherwise we may one goroutine closing, and the other goroutine is trying to write afterwards
+	log.Debugf("Removing the signal notifier")
 	signal.Reset(syscall.SIGCHLD)
+
+	log.Debugf("Closing the channel done to reaper")
```
Comment (hickeng) [inline lib/tether/tether_linux.go]: Closing the reapers signal channel

File: lib/tether/tether_linux.go [hunk 14]
```diff
@@ -126,10 +137,16 @@ func (t *tether) childReaper() error {
...
 	close(t.incoming)
+
+	log.Debugf("Sending true to the done channel")
+	// just closing the channel is not going to stop the iteration over the channel so signal it as well
```
Comment (hickeng) [inline lib/tether/tether_linux.go]: shouldn't `done` be closed first if incoming potentially has queued elements? It's the most immediate way of stopping reaping from continuing.
Of course calling code shouldn't be assuming reaping has stopped until this call returns, but...

File: cmd/tether/attach.go (hunk 9 above)
Comment (caglar10ur) [inline cmd/tether/attach.go]: Yep, will do. It's a litte bit mess right now as we communicate by sharing memory :/

File: cmd/tether/attach.go (hunk 12 above)
Comment (hickeng) [inline cmd/tether/attach.go]: @fdawg4l there is an error path starting at line 250 that I think would result in this.

File: cmd/tether/attach.go [hunk 15]
```diff
@@ -140,78 +171,121 @@ func (t *attachServerSSH) start() error {
...
-			// wait for backchannel to establish
-			err = backchannel(context.Background(), conn)
-			if err != nil {
-				detail := fmt.Errorf("failed to establish backchannel: %s", err)
-				log.Error(detail)
-				continue
-			}
+				// create the SSH server
+				serverConn.Lock()
+				defer serverConn.Unlock()
```
Comment (fdawg4l) [inline cmd/tether/attach.go]: Ok, this _isn't_ in an anon func :-)

Here, can we Lock, defer the unlock, and come back around again and possibly deadlock ourselves?  Likewise the `defer` may never run, right?

File: cmd/tether/attach.go (hunk 12 above)
Comment (caglar10ur) [inline cmd/tether/attach.go]: Correct me if I'm wrong but what you are saying is only valid (I think) if you are calling stop and start concurrently, right? Those are not exported, instead we have Start and Stop which syncronized via mutex so this shouldn't be a problem outside of this package. And if you are calling start/stop within the package then I think correct answer could be "deal with it" :)

File: cmd/tether/attach.go (hunk 15 above)
Comment (hmahmood) [inline cmd/tether/attach.go]: Closing brace for anon func on line 278 :-)

**Comment by hmahmood** [comment]
lgtm

File: cmd/tether/attach.go (hunk 15 above)
Comment (caglar10ur) [inline cmd/tether/attach.go]: The diff is making it hard to see, they are all in the same function. Looking at it directly could help maybe https://github.com/caglar10ur/vic/blob/tether/cmd/tether/attach.go#L239

File: cmd/tether/attach.go (hunk 12 above)
Comment (fdawg4l) [inline cmd/tether/attach.go]: Sounds good :-)

File: cmd/tether/attach.go (hunk 15 above)
Comment (fdawg4l) [inline cmd/tether/attach.go]: AHHh...  Dammit :-) #imissgerrit.  Thanks!

**Comment by fdawg4l** [comment]
lgtm

File: pkg/serial/handshake.go (hunk 6 above)
Comment (hickeng) [inline pkg/serial/handshake.go]: Implementing rawconn.SetReadDeadline might be easier to parse and is consistent with expected net.Conn behaviour.
I'd actually prefer conn.SetReadDeadline(ctx) but it doesn't match the interface

File: cmd/tether/attach.go [hunk 16]
```diff
@@ -150,68 +178,102 @@ func (t *attachServerSSH) start() error {
...
-		for serverConn == nil {
+		for !established && t.IsEnabled() {
+			log.Debugf("Trying to establish a connection")
 			// tests are passing their own connections so do not create connections when testing is set
-			if !t.testing {
-				// close the connection if required
-				if t.conn != nil {
-					(*t.conn).Close()
+
+			establishFn := func() error {
```
Comment (caglar10ur) [inline cmd/tether/attach.go]: I think err is more idiomatic here as in reality that function ends up with an error so I prefer this way unless you really want bool there :)

File: cmd/tether/attach_linux.go [hunk 17]
```diff
@@ -106,13 +106,15 @@ func (t *attachServerSSH) Start() error {
 		return detail
 	}
 
-	t.conn, err = rawConnectionFromSerial()
+	t.conn.Lock()
+	defer t.conn.Unlock()
+
+	t.conn.conn, err = rawConnectionFromSerial()
```
Comment (caglar10ur) [inline cmd/tether/attach_linux.go]: Nope, just a leftover removing

File: lib/tether/tether_linux.go (hunk 10 above)
Comment (caglar10ur) [inline lib/tether/tether_linux.go]: Done

File: lib/tether/tether_linux.go (hunk 13 above)
Comment (caglar10ur) [inline lib/tether/tether_linux.go]: Eheeh not sure what I was trying to say :) Done

File: lib/tether/tether_linux.go (hunk 14 above)
Comment (caglar10ur) [inline lib/tether/tether_linux.go]: Done

File: cmd/tether/attach_linux.go (hunk 17 above)
Comment (caglar10ur) [inline cmd/tether/attach_linux.go]: Done

File: lib/tether/tether_linux.go (hunk 11 above)
Comment (caglar10ur) [inline lib/tether/tether_linux.go]: We do, Start calls the cleanup on its way out and cleanup is the only place where we call this function.

**Comment by caglar10ur** [comment]
rawconn wasn't closing the channel, fixed that too with https://github.com/vmware/vic/pull/2702/commits/0f02d5d4f8bb92d3750750a88870d1a43af06009

File: pkg/serial/handshake.go (hunk 6 above)
Comment (caglar10ur) [inline pkg/serial/handshake.go]: unless I miss something it's more involved though as only way to cancel the read in rawconn is sending an error over error channel. So we can create a context with deadline in SetReadLine and write timeout err to that channel but that also means that a successful read needs to cancel the context.

To be clear, do you prefer SetReadDeadline to be implemented for this PR or are you OK postponing it to some other day?

**Comment by caglar10ur** [comment]
@hmahmood @hickeng see https://github.com/vmware/vic/pull/2702/commits/03190baf04de59eea95e47db6ae95cc9837eb461 we are not interrupting the read by closing the underlying conn

**Comment by caglar10ur** [comment]
♻️

**Comment by caglar10ur** [comment]
♻️

**Comment by caglar10ur** [comment]
♻️

File: cmd/tether/attach.go [hunk 18]
```diff
@@ -140,26 +179,82 @@ func (t *attachServerSSH) start() error {
...
+		err := fmt.Errorf("attach server is not enabled")
+		log.Error(err)
+		return err
+	}
+
+	log.Debugf("Setting enabled to false")
+	t.Disabled()
+
+	// This context is used by backchannel and we need to cancel it before
+	// trying to obtain the following lock so that backchannel releases it.
```
Comment (hickeng) [inline cmd/tether/attach.go]: It's not that backchannel holds this lock, but that this lock is held by backchannel's caller and not released until backchannel returns.

File: cmd/tether/attach.go [hunk 19]
```diff
@@ -140,26 +179,82 @@ func (t *attachServerSSH) start() error {
...
+	log.Debugf("Canceling the context")
+	t.cancel()
 
-	if conn != nil {
-		(*conn).Close()
+	log.Debugf("Acquiring the connection lock")
+	t.conn.Lock()
+	if t.conn.conn != nil {
+		log.Debugf("Closing the connection")
+		(*t.conn.conn).Close()
```
Comment (hickeng) [inline cmd/tether/attach.go]: This _should_ be returning "Close called again on rawconn - squashing" or similar. Close should already have been called as a result of t.cancel().

File: cmd/tether/attach.go [hunk 20]
```diff
@@ -140,26 +179,82 @@ func (t *attachServerSSH) start() error {
...
+
+	// This needs to tick *faster* than the ticker in connection.go on the
+	// portlayer side.  The PL sends the first syn and if this isn't waiting,
+	// alignment will take a few rounds (or it may never happen).
+	ticker := time.NewTicker(10 * time.Millisecond)
+	defer ticker.Stop()
+
+	ch := make(chan struct{}, 1)
+
+	go func() {
```
Comment (hickeng) [inline cmd/tether/attach.go]: this deserves a comment as to why it cannot go in the same select as HandshakeServer

File: cmd/tether/attach.go [hunk 21]
```diff
@@ -140,26 +179,82 @@ func (t *attachServerSSH) start() error {
...
+		select {
+		case <-ctx.Done():
+			(*conn).Close()
+			close(ch)
```
Comment (hickeng) [inline cmd/tether/attach.go]: `close(ch)` before `(*conn).Close()`
Otherwise HandshakeServer may return and re-enter before `ch` is closed.

Also - **I'm not sure what happens if you call read on a closed rawconn**

File: cmd/tether/attach.go (hunk 18 above)
Comment (caglar10ur) [inline cmd/tether/attach.go]: Done

File: cmd/tether/attach.go (hunk 19 above)
Comment (caglar10ur) [inline cmd/tether/attach.go]: Done

**Comment by hickeng** [comment]
LGTM now we've got the backchannel interrupt sorted out.

**Comment by caglar10ur** [comment]
♻️
