### PR TITLE
Increase timeout up to 10 seconds and decrease amount of data.

### LINKED ISSUE #2963: TestHandshakeServerLotsOfTrashOnTheLine fails due to timeout.
Loaded system may require much longer time to transfer the data. 
Reducing amount of data in order of magnitude as well as increasing timeout to 10 seconds should help.

### PR DESCRIPTION
**Pull request by vburenin**
Increase timeout up to 10 seconds and decreased amount of data many times to avoid timeouts on a loaded system.
Fixes #2963

### CODE REVIEW

**Comment by jzt** [comment]
LGTM

**Comment by vburenin** [comment]
LGTM

File: pkg/serial/handshake_test.go [hunk 1]
```diff
@@ -129,14 +129,14 @@ func TestHandshakeServerNormalCaseScenario(t *testing.T) {
 
 func TestHandshakeServerLotsOfTrashOnTheLine(t *testing.T) {
 	log.SetLevel(log.InfoLevel)
-	clientConn, serverConn := NewFakeConnection(time.Second * 3)
+	clientConn, serverConn := NewFakeConnection(time.Second * 10)
```
Comment (hickeng) [inline pkg/serial/handshake_test.go]: If we're playing with test timeouts like this, I think we should be using infinite timeout and letting the Go test timeout kill it.
