### PR TITLE
[specific ci=1-02-Docker-Pull] Fix docker pull on artifactory

### LINKED ISSUE #6738: Image pull from artifactory fails: Failed to obtain OAuth endpoint: https://vic-docker-local.artifactory.eng.vmware.com/v2/busybox/manifests/1 returned an unexpected response: Unexpected http code: 403
After successful login to artifcatory repo, image pull fails:
```
Nov  9 2017 14:58:46.410Z INFO  PullImage: reference: vic-docker-local.artifactory.eng.vmware.com/busybox:1, 127.0.0.1:2377, portlayer: "127.0.0.1:2377"
Nov  9 2017 14:58:46.410Z INFO  Using UUID (564d1c2f-2a64-983b-1ec9-4185f86f38c7) for imagestore name
Nov  9 2017 14:58:46.410Z DEBUG Running with portlayer
Nov  9 2017 14:58:46.410Z DEBUG [BEGIN]  [vic/lib/imagec.PingPortLayer:40] 127.0.0.1:2377
Nov  9 2017 14:58:46.411Z DEBUG [ END ]  [vic/lib/imagec.PingPortLayer:40] [385.047µs] 127.0.0.1:2377
Nov  9 2017 14:58:46.411Z DEBUG [BEGIN]  [vic/lib/imagec.LearnRegistryURL:75] vic-docker-local.artifactory.eng.vmware.com
Nov  9 2017 14:58:46.411Z DEBUG Trying https scheme for &imagec.Options{Reference:(*reference.taggedRef)(0xc420653e60), Registry:"vic-docker-local.artifactory.eng.vmware.com", Image:"busybox", Tag:"1", Destination:"/tmp", Host:"127.0.0.1:2377", Storename:"564d1c2f-2a64-983b-1ec9-4185f86f38c7", Username:"vic-deployer", Password:"vmware!123", Token:(*fetcher.Token)(nil), Timeout:3600000000000, Outstream:(*ioutils.WriteFlusher)(0xc42059fa40), InsecureSkipVerify:false, InsecureAllowHTTP:true, ImageManifestSchema1:(*imagec.Manifest)(nil), ImageManifestSchema2:(*schema2.DeserializedManifest)(nil), ManifestDigest:"", RegistryCAs:(*x509.CertPool)(0xc4207daf30), Standalone:false, ImageStore:""}
Nov  9 2017 14:58:46.411Z DEBUG URL: https://vic-docker-local.artifactory.eng.vmware.com/v2/
Nov  9 2017 14:58:46.550Z DEBUG [ END ]  [vic/lib/imagec.LearnRegistryURL:75] [138.852068ms] vic-docker-local.artifactory.eng.vmware.com
Nov  9 2017 14:58:46.550Z DEBUG [BEGIN]  [vic/lib/imagec.LearnAuthURL:100] vic-docker-local.artifactory.eng.vmware.com/busybox:1
Nov  9 2017 14:58:46.550Z DEBUG URL: https://vic-docker-local.artifactory.eng.vmware.com/v2/busybox/manifests/1
Nov  9 2017 14:58:46.587Z DEBUG [ END ]  [vic/lib/imagec.LearnAuthURL:100] [37.614669ms] vic-docker-local.artifactory.eng.vmware.com/busybox:1
Nov  9 2017 14:58:46.587Z INFO  https://vic-docker-local.artifactory.eng.vmware.com/v2/busybox/manifests/1 returned an unexpected response: Unexpected http code: 403, URL: https://vic-docker-local.artifactory.eng.vmware.com/v2/busybox/manifests/1
Nov  9 2017 14:58:46.587Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.(*Image).PullImage:322] [226.636362ms] 
Nov  9 2017 14:58:46.587Z ERROR Handler for POST /v1.21/images/create returned error: Failed to obtain OAuth endpoint: https://vic-docker-local.artifactory.eng.vmware.com/v2/busybox/manifests/1 returned an unexpected response: Unexpected http code: 403, URL: https://vic-docker-local.artifactory.eng.vmware.com/v2/busybox/manifests/1
```

[21-2-Artifactory-VCH-0-7754-container-logs.zip](https://github.com/vmware/vic/files/1458276/21-2-Artifactory-VCH-0-7754-container-logs.zip)

### PR DESCRIPTION
**Pull request by sflxn**
Artifactory responds with HTTP 403 when attempting initial query
to look up bearer realm.  We use an URL that includes manifest and
repo.  That works on most registries, and appears to be correct
according to the docker OAuth spec.

Now, if the URL we use does not work, we attempt another query
with just the registry URL.  This works well with Artifactory.  It
is also the same URL we use for docker login.

Fixes #6738

### CODE REVIEW

**Comment by sgairo** [comment]
This looks good, should there be a test added, or an issue opened to add a test when time is permitting?

**Comment by mhagen-vmware** [comment]
@sgairo https://github.com/vmware/vic/pull/6734

**Comment by sgairo** [comment]
Oh gotcha, great!

**Comment by sflxn** [comment]
Found two problems.  The first is pulling from GCR.  The second is the error message from pulling a private repo from Artifactory without signing in first.

They're fixed now.

File: lib/imagec/docker.go [hunk 1]
```diff
@@ -118,9 +120,20 @@ func LearnAuthURL(options Options) (*url.URL, error) {
...
+	log.Debugf("Pinging %s", manifestURL.String())
+	hdr, err := fetcher.Ping(manifestURL)
 	if err == nil && fetcher.IsStatusUnauthorized() {
-		return fetcher.ExtractOAuthURL(hdr.Get("www-authenticate"), url)
+		return fetcher.ExtractOAuthURL(hdr.Get("www-authenticate"), nil)
+	}
+
+	if !fetcher.IsStatusOK() {
+		// Try with just the registry url.  This works better with some registries (e.g.
+		// Artifcatory)
```
Comment (anchal-agrawal) [inline lib/imagec/docker.go]: s/Artifcatory/Artifactory

File: pkg/fetcher/fetcher.go [hunk 2]
```diff
@@ -453,7 +453,12 @@ func (u *URLFetcher) buildRegistryErrMsg(url *url.URL, respBody io.ReadCloser) s
 		return errMsg
 	}
 
-	errMsg += fmt.Sprintf(", Message: %s", errDetail)
+	if strings.Contains(errDetail, "does not have permission") {
```
Comment (anchal-agrawal) [inline pkg/fetcher/fetcher.go]: Is there a better way to look for this error type other than comparing the error string? Do all registries return the same error string?

Comment (sflxn) [reply pkg/fetcher/fetcher.go]: There is, but that's a much bigger task then will fit into the time allowed for this release.  The returned json from the registry is,

 {"errors":[{"code":"UNAUTHORIZED","message":"The client does not have permission for manifest","detail":{"manifest":"busybox/latest/manifest.json"}}]}

Comment (anchal-agrawal) [reply pkg/fetcher/fetcher.go]: That's fair - could we write up an issue for it? I'll leave that to you since you have the most knowledge about the implementation of this piece.
