### PR TITLE
Fix logging for restartable sessions

### LINKED ISSUE #5682: Restart-able sessions are not initializing their Session logs
vic-init relaunched the session when a service fails. Currently we stop logging when that happens. Instead we should keep writing to service's log file as expected.

### PR DESCRIPTION
**Pull request by caglar10ur**
```
... install VCH ...
...   vic-ssh   ...
root@ [ ~ ]# ps aux | grep port-layer
root       278  4.2  2.0 250696 42808 ?        Sl   22:41   0:00 /sbin/port-layer-server --host=localhost --port=2377
root@ [ ~ ]# kill -9 278
root@ [ ~ ]# ps aux | grep port-layer
root       291  1.0  1.8 238932 38344 ?        Sl   22:41   0:00 /sbin/docker-engine-server -port=2375 -port-layer-port=2377
root@ [ ~ ]# grep Serving /var/log/vic/port-layer.log
Jul 10 2017 22:41:17.337Z INFO  Serving port layer at http://127.0.0.1:2377
Jul 10 2017 22:41:46.726Z INFO  Serving port layer at http://127.0.0.1:2377
root@ [ ~ ]#
```

Fixes #5682

### CODE REVIEW

File: lib/tether/tether.go [hunk 1]
```diff
@@ -649,6 +607,42 @@ func (t *tether) handleSessionExit(session *SessionConfig) {
...
+	}
+	session.Outwriter = stdout
+	session.Errwriter = stderr
+	session.Reader = dio.MultiReader()
+
+	if session.Diagnostics.SysLogConfig != nil {
+		cfg := session.Diagnostics.SysLogConfig
+		var w syslog.Writer
+		if writer == nil {
+			writer, err = syslog.Dial(cfg.Network, cfg.RAddr, syslog.Info|syslog.Daemon, fmt.Sprintf("%s", t.config.ID[:shortLen]))
```
Comment (hmahmood) [inline lib/tether/tether.go]: Hm... this is going to create one syslog connection per session, while before the syslog connection was being shared between all the sessions. Any way to keep that behavior?

Comment (caglar10ur) [inline lib/tether/tether.go]: Grrr I was planning to move  var writer syslog.Writer into tether struct to keep that behavior but looks like I forgot that, changing now

Comment (caglar10ur) [inline lib/tether/tether.go]: Done, pushed a new commit to do that
