### PR TITLE
Check for null struct fields when converting images

### LINKED ISSUE #913: [docker-server] runtime error: invalid memory address or nil pointer dereference
docker-engine-server crashes with following on my system. The trace points to convertV1ImageToDockerImage function call. 
```
2016/05/31 17:12:17 http: panic serving 192.168.218.141:33002: runtime error: invalid memory address or nil pointer dereference
goroutine 37 [running]:
net/http.(*conn).serve.func1(0xc820f59b80)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0xebe780, 0xc820010070)
	/usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/vmware/vic/lib/apiservers/engine/backends.(*Image).Images(0xc820493680, 0x0, 0x0, 0x0, 0x0, 0x1271700, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/go/src/github.com/vmware/vic/lib/apiservers/engine/backends/image.go:104 +0x709
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/image.(*imageRouter).getImagesJSON(0xc820634cc0, 0x7fe8493d8400, 0xc820f70600, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540, 0xc820f70570, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/image/image_routes.go:313 +0x1a7
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/image.(*imageRouter).(github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/image.getImagesJSON)-fm(0x7fe8493d8400, 0xc820f70600, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540, 0xc820f70570, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router/image/image.go:29 +0x74
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.NewVersionMiddleware.func1.1(0x7fe8493d8400, 0xc820f70600, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540, 0xc820f70570, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/version.go:42 +0xa43
github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware.NewUserAgentMiddleware.func1.1(0x7fe8493d8348, 0xc8200113e8, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540, 0xc820f70570, 0x0, 0x0)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/middleware/user_agent.go:32 +0x491
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x7fe8493d4218, 0xc821074000, 0xc820f2c540)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/server.go:132 +0x138
net/http.HandlerFunc.ServeHTTP(0xc82063c160, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/vmware/vic/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc820632fa0, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/gorilla/mux/mux.go:103 +0x270
github.com/vmware/vic/vendor/github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc8207deab0, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540)
	/opt/go/src/github.com/vmware/vic/vendor/github.com/docker/docker/api/server/router_swapper.go:29 +0x72
net/http.serverHandler.ServeHTTP(0xc82062c200, 0x7fe8493d4218, 0xc821074000, 0xc820f2c540)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820f59b80)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

### PR DESCRIPTION
**Pull request by jzt**
Note: The output of `docker images` will remain incorrect until #387 is refactored to use the image metadata work that is currently in progress (see #423). @mhagen-vmware if that output is breaking a test, I'd just skip it for now.

Fixes #913

### CODE REVIEW

File: lib/apiservers/engine/backends/image.go [hunk 1]
```diff
@@ -236,13 +236,19 @@ func resolveImageSize(v1Map map[string]*v1.V1Image, resolved map[string]int64, i
 }
 
 func convertV1ImageToDockerImage(v1Image *v1.V1Image) *types.Image {
+	var labels map[string]string
+	if v1Image.Config != nil && v1Image.Config.Labels != nil {
+		labels = v1Image.Config.Labels
+	} else {
+		labels = make(map[string]string)
```
Comment (caglar10ur) [inline lib/apiservers/engine/backends/image.go]: does it have to be an empty map? If not how about using nil there?

Comment (caglar10ur) [inline lib/apiservers/engine/backends/image.go]: Or removing the else statement 

```
var labels map[string]string
if v1Image.Config != nil && v1Image.Config.Labels != nil {
		labels = v1Image.Config.Labels
 }
```

Comment (jzt) [inline lib/apiservers/engine/backends/image.go]: @caglar10ur fixed, I was being paranoid.

**Comment by hmahmood** [comment]
lgtm

**Comment by andrewtchin** [comment]
lgtm
