### PR TITLE
fixes VSAN container log names, and fixes the missing container debug missing from the log bundles

### LINKED ISSUE #2195: vicadmin doesn't include both log directories for a container on VSAN
On the datastore for a vsan deployment we have two directories linking to the same files:
a2f2c557-b44c-fbda-cc0e-0200051150c9
kickass_dijkstr-0806e51820ded115e3cda453ee7c1d17816ad6cbd9a5e33f0e0c3bda9f242a77

In vicadmin it looks like we only grabbed the non-friendly named directory with it's logs:
```
'-rw-r----- 0/0            1537 2016-08-30 15:13 proc-mounts
-rw-r----- 0/0             204 2016-08-30 15:13 free
-rw-r----- 0/0             519 2016-08-30 15:13 ip-link
-rw-r----- 0/0           11527 2016-08-30 15:13 portlayer/concise
-rw-r----- 0/0         2477305 2016-08-30 15:13 portlayer/heap
-rw-r----- 0/0         1517021 2016-08-30 15:13 vicadm/heap
-rw-r----- 0/0            5634 2016-08-30 15:13 docker/concise
-rw-r----- 0/0          132517 2016-08-30 15:13 var/log/vic/init.log
-rw-r----- 0/0          185694 2016-08-30 15:13 30e8c557-9cdc-1563-7308-020022ac0aee/vmware.log
-rw-r----- 0/0              62 2016-08-30 15:13 uptime
-rw-r----- 0/0            1325 2016-08-30 15:13 lsmod
-rw-r----- 0/0              68 2016-08-30 15:13 disk-by-label
-rw-r----- 0/0           69680 2016-08-30 15:13 var/log/vic/port-layer.log
-rw-r----- 0/0          225486 2016-08-30 15:13 abe8c557-2d84-a9d9-b26d-02002296868f/vmware.log
-rw-r----- 0/0          158987 2016-08-30 15:13 hostd/HostSystem:host-33 @ /vcqaDC/host/cls/10.162.32.198
-rw-r----- 0/0           76223 2016-08-30 15:13 vpxd:vpxd.log
-rw-r----- 0/0          181201 2016-08-30 15:13 hostd/HostSystem:host-21 @ /vcqaDC/host/cls/10.162.33.141
-rw-r----- 0/0             381 2016-08-30 15:13 df
-rw-r----- 0/0            1263 2016-08-30 15:13 ip-addr
-rw-r----- 0/0             265 2016-08-30 15:13 proc-self-fd
-rw-r----- 0/0           13060 2016-08-30 15:13 var/log/vic/imagec.log
-rw-r----- 0/0            8356 2016-08-30 15:13 vicadm/concise
-rw-r----- 0/0              41 2016-08-30 15:13 vicadm/block
-rw-r----- 0/0            7529 2016-08-30 15:13 docker/verbose
-rw-r----- 0/0             178 2016-08-30 15:13 ip-route
-rw-r----- 0/0              82 2016-08-30 15:13 disk-by-path
-rw-r----- 0/0            4658 2016-08-30 15:13 docker/heap
-rw-r----- 0/0              41 2016-08-30 15:13 docker/block
-rw-r----- 0/0           20257 2016-08-30 15:13 portlayer/verbose
-rw-r----- 0/0           11344 2016-08-30 15:13 var/log/vic/docker-personality.log
-rw-r----- 0/0           20957 2016-08-30 15:13 vicadm/verbose
-rw-r----- 0/0           29055 2016-08-30 15:13 var/log/vic/vicadmin.log
-rw-r----- 0/0           76506 2016-08-30 15:13 hostd/HostSystem:host-27 @ /vcqaDC/host/cls/10.162.56.173
-rw-r----- 0/0          100370 2016-08-30 15:13 hostd/HostSystem:host-15 @ /vcqaDC/host/cls/10.162.34.242
-rw-r----- 0/0            2454 2016-08-30 15:13 netstat
-rw-r----- 0/0              41 2016-08-30 15:13 portlayer/block' does not contain 'cc0c350a6fb3416634ab7ef65a055c5592725c0c7d12e1055250cb2e0ba6371f/vmware.log'
```

We either need to just grab both or at least the friendlier named directory otherwise the user doesn't have any good way of figuring out the container logs for the container they want.

### LINKED ISSUE #2457: Debug logs missing from vicadmin logs
the debug logs for containers are not being fetched. This must be fixed for proper debugging in some scenarios.

### PR DESCRIPTION
**Pull request by matthewavery**
Fixes #2195
Fixes #2457

Also this is a slight refactor to make the file operations a little more apparent. There may be future refactors as needed.

### CODE REVIEW

File: cmd/vicadmin/vicadm.go [hunk 1]
```diff
@@ -315,33 +333,36 @@ func findDatastoreLogs(c *session.Session) (map[string]entryReader, error) {
...
 
 		// generate the full paths to collect
 		for _, file := range vmFiles {
 			// replace the VM token in file name with the VM name
-			processed := strings.Replace(file, string(vchconfig.VM), path.Base(vmpath.Path), -1)
-			rpath := fmt.Sprintf("%s/%s", vmpath.Path, processed)
-			readers[rpath] = datastoreReader{
+			vmHashName := strings.Split(logfile.VMName, "-")
+			processed := strings.Replace(file, string(vchconfig.VM), vmHashName[1], -1)
+			wpath := fmt.Sprintf("log write path: %s/%s", logfile.VMName, processed)
```
Comment (andrewtchin) [inline cmd/vicadmin/vicadm.go]: is there a reason to have `log write path:` here? it looks like its just used as the key on L360

File: cmd/vicadmin/vicadm.go [hunk 2]
```diff
@@ -315,33 +333,36 @@ func findDatastoreLogs(c *session.Session) (map[string]entryReader, error) {
...
+			rpath := fmt.Sprintf("log read path: %s/%s", logfile.URL.Path, processed)
```
Comment (dougm) [inline cmd/vicadmin/vicadm.go]: Don't see how this can work with the "log read path: " prefix.  `datastoreReader.path` is used by datastoreReader.open in the GET request.  We can revisit the other name issues above, but this looks like it has to be fixed.

Comment (andrewtchin) [inline cmd/vicadmin/vicadm.go]: same here i don't know where `path` it's used, but i wouldnt expect it to have `log read path: ` in it

File: cmd/vicadmin/vicadm.go [hunk 3]
```diff
@@ -315,33 +333,36 @@ func findDatastoreLogs(c *session.Session) (map[string]entryReader, error) {
...
 			continue
 		}
 
 		// generate the full paths to collect
 		for _, file := range vmFiles {
 			// replace the VM token in file name with the VM name
-			processed := strings.Replace(file, string(vchconfig.VM), path.Base(vmpath.Path), -1)
-			rpath := fmt.Sprintf("%s/%s", vmpath.Path, processed)
-			readers[rpath] = datastoreReader{
+			vmHashName := strings.Split(logfile.VMName, "-")
```
Comment (dougm) [inline cmd/vicadmin/vicadm.go]: What happens if someone names their vm with a "-" character in it?

File: cmd/vicadmin/vicadm.go [hunk 4]
```diff
@@ -290,21 +294,35 @@ func listVMPaths(ctx context.Context, s *session.Session) ([]url.URL, error) {
...
 	for _, child := range children {
 		path, err := child.DSPath(ctx)
+
 		if err != nil {
 			log.Errorf("Unable to get datastore path for child VM %s: %s", child.Reference(), err)
 			// we need to get as many logs as possible
 			continue
 		}
 
+		logname, err := child.Name(ctx)
```
Comment (dougm) [inline cmd/vicadmin/vicadm.go]: Note that if a VM is renamed, the path to .debug does not change.

**Comment by dougm** [comment]
Also, the git commit message: https://github.com/vmware/vic/blob/master/CONTRIBUTING.md#format-of-the-commit-message

File: cmd/vicadmin/vicadm.go (hunk 1 above)
Comment (matthewavery) [inline cmd/vicadmin/vicadm.go]: Yes, I added that because prevously it was unclear that the key to that map was the write path. I did it as a readability improvement.

Comment (matthewavery) [inline cmd/vicadmin/vicadm.go]: oh woops. I see what you are saying I added that to the wrong place with the last commit :( disregard previous comment.

File: cmd/vicadmin/vicadm.go (hunk 4 above)
Comment (matthewavery) [inline cmd/vicadmin/vicadm.go]: Yes we have had previous issues with vm renaming as well. Should that be covered in this pr?

File: cmd/vicadmin/vicadm.go (hunk 3 above)
Comment (matthewavery) [inline cmd/vicadmin/vicadm.go]: what would you suggest for this? I was thinking about that as well and it is kind of hard to tell what that ending hash is. it is perfectly legal for someone to give their containerVM a hash for a name and then we will give it one as well.

Comment (matthewavery) [inline cmd/vicadmin/vicadm.go]: I really think we should change the name of the `*.debug` file tbh. it should be something similar to the `vmware.log` file where we do not rely on the hash or naming of anything for the log.

**Comment by matthewavery** [comment]
Yeah I need to fix the PR header. The commits in this will get fixed when I squash and merge after lgtms and a green unit test run. I usually do not squash until the very end.

**Comment by dougm** [comment]
lgtm - looks like this'll get us .debug logs in CI now

We can revisit the naming later.  But yes, if we had a fixed log name, such as "tether.log", we can use VirtualMachine.Config.Files.LogDirectory to get the path to that file, and avoid having to parse/replace/etc to figure out the path.

**Comment by andrewtchin** [comment]
lgtm
