### PR TITLE
Correct log routes in vic-admin

### LINKED ISSUE #5729: Problem curl'ing port layer log
I've observed two issues in this build (#5700): https://ci.vcna.io/vmware/vic/12327

1. Group0-Bugs.5343
2. Group9-VIC-Admin.9-02-VICAdmin-CertAuth

Both of these relate to not finding expected content in the port layer log. The second provides a really good hint at why the first failed:

```
Get Portlayer Log                                                     | FAIL |
'<!DOCTYPE html>
<html itemscope="" itemtype="http://schema.org/Organization" lang="en-US">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>VIC: VCH-12327-8972</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <link rel="stylesheet" href="css/clarity-ui.min.css">
    <link rel="stylesheet" href="css/fontello.css">
    <link rel="stylesheet" href="css/style.css">
  </head>
    [ Message content over the limit has been removed. ]
                  <div class="sixty"><a href="/logs/init.log">Initialization & watchdog</a></div>
                  <div class="forty"><a href="/logs/tail/init.log">Live Log</a></div>
                </div>
                <div class="row">
                  <div class="sixty"><a href="/logs/vicadmin.log">Admin Server</a></div>
                  <div class="forty"><a href="/logs/tail/vicadmin.log">Live Log</a></div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  </body>
</html>' does not contain 'Launching portlayer server'
```

It looks like we've got the index page instead of the portlayer log. Took a look at vicadmin log, but didn't see an obvious cause, however I'm unfamiliar with normal for that log. Did wonder why there's so many Authenticated blocks in a row when we start.

Most likely unrelated is why we're not gathering profile data on any of the pprof endpoints:
```
Jul 16 2017 00:24:18.899Z DEBUG [BEGIN] [main.urlReader.open:292] http://127.0.0.1:6060/debug/pprof/profile
Jul 16 2017 00:24:20.899Z DEBUG [ END ] [main.urlReader.open:292] [2.000216475s] http://127.0.0.1:6060/debug/pprof/profile
Jul 16 2017 00:24:20.899Z WARN  error reading vic-init/profile(http://127.0.0.1:6060/debug/pprof/profile): Get http://127.0.0.1:6060/debug/pprof/profile: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

### PR DESCRIPTION
**Pull request by morris-jason**
Fixes #5729 and fixes broken log rotation functionality.

### CODE REVIEW

**Comment by gigawhitlocks** [comment]
Looks good, but can you run the VicAdmin CI suite before you merge?

**Comment by vburenin** [comment]
as we discussed offline, this PR is not solving the root cause of the problem, in fact it makes it impossible to export rotated logs. There is a different place to look at that should completely eliminate the issue.

**Comment by morris-jason** [comment]
@vburenin I've reworked to include rotated logs.

File: cmd/vicadmin/logs.go [hunk 1]
```diff
@@ -104,31 +105,58 @@ func (r dlogReader) open() (entry, error) {
 // cross process synchronization.
 func logFiles() []string {
 	defer trace.End(trace.Begin(""))
+
```
Comment (morris-jason) [inline cmd/vicadmin/logs.go]: Look at the raw file, this is a bad diff.

File: cmd/vicadmin/server.go [hunk 2]
```diff
@@ -262,7 +263,7 @@ func (s *server) Authenticated(link string, handler func(http.ResponseWriter, *h
 		log.Infof("User with a valid auth cookie at %s is authenticated.", connectingAddr[0])
 		handler(w, r)
 	}
-	s.mux.Handle(link, gorillacontext.ClearHandler(http.HandlerFunc(authHandler)))
+	s.Handle(link, http.HandlerFunc(authHandler))
```
Comment (morris-jason) [inline cmd/vicadmin/server.go]: @gigawhitlocks Is this ok, using the custom Handle? Seemed fine in tests.

File: cmd/vicadmin/logs.go [hunk 3]
```diff
@@ -131,6 +134,72 @@ func logFiles() []string {
...
+	}
+
+	// write file contents to w
+	for _, fileName := range names {
+		file, err := os.Open(fileName)
+		if err != nil {
+			log.Errorf("error opening file %s: %s", fileName, err.Error())
+			continue
+		}
+		var r io.ReadCloser = file
```
Comment (vburenin) [inline cmd/vicadmin/logs.go]: not sure assigning it to interface makes sense, just use file as it is.

File: cmd/vicadmin/logs.go [hunk 4]
```diff
@@ -131,6 +134,72 @@ func logFiles() []string {
...
+		if strings.HasSuffix(fileName, "gz") {
+			r, err = gzip.NewReader(file)
+			if err != nil {
+				log.Errorf("error opening gzipped file %s: %s", fileName, err.Error())
+				continue
+			}
+		}
+		defer r.Close()
```
Comment (vburenin) [inline cmd/vicadmin/logs.go]: close this explicitly at the end no need defer in the loop, it may lead to resource exhaustion due to too many files are open.

File: cmd/vicadmin/logs.go (hunk 3 above)
Comment (morris-jason) [inline cmd/vicadmin/logs.go]: Added comment. Reassigning r to a gzip reader if needed.

File: cmd/vicadmin/logs.go (hunk 4 above)
Comment (morris-jason) [inline cmd/vicadmin/logs.go]: Done.

File: cmd/vicadmin/server.go (hunk 2 above)
Comment (gigawhitlocks) [inline cmd/vicadmin/server.go]: Uhm, I think you still need to nest the `ClearHandler` because it clears out context related to the session at the end of the request, as I recall.. docs are here http://www.gorillatoolkit.org/pkg/context

Unfortunately I don't remember exactly what the side effect of not using it is, but I believe it amounts to leaking something we don't want to leak.

Comment (morris-jason) [inline cmd/vicadmin/server.go]: https://github.com/vmware/vic/blob/master/cmd/vicadmin/server.go#L161
s.Handle will make a call to ClearHandler with the httlHandler.

Comment (gigawhitlocks) [inline cmd/vicadmin/server.go]: good stuff
