### PR TITLE
Diagnostic improvements to vicadmin [full ci]

### LINKED ISSUE #2811: vicadmin fails to return data if connection to vsphere fails
If the [session.Connect call](https://github.com/vmware/vic/blob/master/cmd/vicadmin/vicadm.go#L391) fails then the Validator [created here](https://github.com/vmware/vic/blob/master/cmd/vicadmin/server.go#L272) is invalid (the session is nil) and there are multiple panics.

If altering [the creation of the validator](https://github.com/vmware/vic/blob/master/lib/vicadmin/validate.go#L80) to check for validity of the session and return `nil, fmt.Errorf("invalid session")` then nothing is rendered.

This failure to connect could be:
- incorrect thumbprint
- network outage
- firewall config issue
- vsphere credentials have changed
- ... (multitude of options)

Adding this to the backlog for GA as it significantly impacts our ability to diagnose some of the most common connectivity issues.

### LINKED ISSUE #3082: vic-admin should work even it can't speak to vsphere.
When the customer hit #3081 the port layer would just quit when it couldn't connect to the target. tether/vic-init would restart it and it would just quit again. During this time you could connect to vic-admin but it never returned any data. When the rest of the system is not working we need vic-admin the most. See also #3079.

### LINKED ISSUE #3086: vic-admin: add endpointVM system time to vic-admin pages
We should add the endpoint VM system time to the vic-admin pages, including the login page.
This is specifically useful in the case of clock-skew causing certificate validation errors as per #2670 

@stuclem when added this should be mentioned in the troubleshooting related to clock-skew

### PR DESCRIPTION
**Pull request by anchal-agrawal**
The vicadmin page doesn't function correctly if we don't have a vSphere session connection. This PR makes several changes to aid debugging.

Fixes #2811 
Fixes #3086 
Fixes #3082
Towards #3083

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
Here are some mockups.

Login page:

login page

Dashboard (healthy):

normal homepage

File: cmd/vicadmin/server.go [hunk 1]
```diff
@@ -266,7 +274,7 @@ func (s *server) loginPage(res http.ResponseWriter, req *http.Request) {
 		if err != nil || usersession == nil {
 			// something went wrong or we could not authenticate
 			log.Warnf("User %s from %s failed to authenticated at %s", user, req.RemoteAddr, time.Now())
-			http.Error(res, "Authentication failed due to incorrect credential(s)", 400)
+			http.Error(res, "Authentication failed due to incorrect credential(s)", http.StatusBadRequest)
```
Comment (anchal-agrawal) [inline cmd/vicadmin/server.go]: I changed this to `http.StatusBadRequest` solely to remove the hardcoded value. Would using `http.StatusUnauthorized` be more appropriate?

File: lib/vicadmin/validate.go [hunk 2]
```diff
@@ -55,6 +54,9 @@ type Validator struct {
 	DockerPort       string
 	VCHStatus        template.HTML
 	VCHIssues        template.HTML
+	VCHReachable     bool
+	VCHUnreachable   bool
```
Comment (anchal-agrawal) [inline lib/vicadmin/validate.go]: `VCHUnreachable` is redundant. 

I tried using an `else` block [here](https://github.com/vmware/vic/pull/3106/files#diff-7372f4b2bbd435e1a9f6b78eeb5f04f0R105) to show the error string under the log bundle link, but the template couldn't be parsed. I'll modify the template logic to get rid of `VCHUnreachable` if we can.

**Comment by anchal-agrawal** [comment]
@stuclem Once this is merged, please update `doc/user_doc/vic_admin/vicadmin_status_ref.md` to reflect the change from `Network Connectivity` to `Registry and Internet Connectivity`. We might need more changes to that doc to explain the error scenario in the picture above.

File: cmd/vicadmin/server.go [hunk 3]
```diff
@@ -266,7 +275,7 @@ func (s *server) loginPage(res http.ResponseWriter, req *http.Request) {
 		if err != nil || usersession == nil {
 			// something went wrong or we could not authenticate
 			log.Warnf("User %s from %s failed to authenticated at %s", user, req.RemoteAddr, time.Now())
```
Comment (gigawhitlocks) [inline cmd/vicadmin/server.go]: "failed to authenticated" if you could fix that typo pls

File: lib/vicadmin/validate.go (hunk 2 above)
Comment (gigawhitlocks) [inline lib/vicadmin/validate.go]: @sgairo can you help w/ this?

File: lib/vicadmin/validate.go [hunk 4]
```diff
@@ -71,46 +73,64 @@ func NewValidator(ctx context.Context, vch *config.VirtualContainerHostConfigSpe
...
+
+		v.LicenseStatus = BadStatus
+		v.LicenseIssues = template.HTML("")
 	} else {
-		v.FirewallStatus = BadStatus
-		for _, err := range firewallIssues {
-			v.FirewallIssues = template.HTML(fmt.Sprintf("%s<span class=\"error-message\">%s</span>\n", v.FirewallIssues, err))
+
+		v.VCHReachable = true
+		v.VCHUnreachable = false
```
Comment (gigawhitlocks) [inline lib/vicadmin/validate.go]: yeah this hurts, see if you can figure out how to use an `else` in the template as you mentioned before.. or even `if` and then `if not` somehow :\

Comment (anchal-agrawal) [inline lib/vicadmin/validate.go]: Agreed, it's painful. Working on it.

**Comment by gigawhitlocks** [comment]
Minor nits, otherwise LGTM

File: lib/vicadmin/validate.go (hunk 2 above)
Comment (anchal-agrawal) [inline lib/vicadmin/validate.go]: Fixed. Turns out the template doesn't like html comments between `{{if}}` and `{{else}}`.

File: cmd/vicadmin/server.go [hunk 5]
```diff
@@ -314,16 +323,15 @@ func (s *server) loginPage(res http.ResponseWriter, req *http.Request) {
...
 	}
 
-	// Render login page (shows up on non-POST requests):
-	sess, err := client(&rootConfig)
-	if err != nil {
-		log.Errorf("Could not render login page due to vSphere connection error: %s", err.Error())
-		http.Error(res, genericErrorMessage, http.StatusInternalServerError)
-		return
+	// Render login page (shows up on non-POST requests)
+	hostName, _ := os.Hostname()
```
Comment (caglar10ur) [inline cmd/vicadmin/server.go]: do not ignore err here

File: cmd/vicadmin/server.go (hunk 1 above)
Comment (caglar10ur) [inline cmd/vicadmin/server.go]: StatusUnauthorized

File: cmd/vicadmin/server.go [hunk 6]
```diff
@@ -499,12 +507,41 @@ func (s *server) tailFiles(res http.ResponseWriter, req *http.Request, names []s
...
+			displayErrStr = "unable to obtain a vim client"
+		case session.UserPassLoginError:
+			displayErrStr = "unable to log in with username and password"
+		default:
+			displayErrStr = err.Error()
+		}
+	}
+
+	return displayErrStr
+}
```
Comment (caglar10ur) [inline cmd/vicadmin/server.go]: why do you need displayErrStr? Return directly within the switch statement eg; ```return fmt.Sprintf("SDK URL could not be parsed: %s", err.Err)```

File: cmd/vicadmin/server.go [hunk 7]
```diff
@@ -499,12 +507,41 @@ func (s *server) tailFiles(res http.ResponseWriter, req *http.Request, names []s
...
 	ctx := context.Background()
 	sess, err := s.getSessionFromRequest(req)
 	v := vicadmin.NewValidator(ctx, &vchConfig, sess)
 
+	if sess == nil {
+		// We're unable to connect to vSphere, so display an error message
+		displayErrStr := deriveDisplayError(err)
+		v.VCHIssues = template.HTML(fmt.Sprintf(
+			"<span class=\"error-message\">%s Error: %s</span>\n",
+			v.Hostname+VCHUnreachableMsg, displayErrStr))
```
Comment (caglar10ur) [inline cmd/vicadmin/server.go]: year is 2016, I think it's safe to say that we can have longer lines now :) I suggest making this a single line

File: pkg/vsphere/session/errors.go [hunk 8]
```diff
@@ -0,0 +1,47 @@
...
+//
+// Unless required by applicable law or agreed to in writing, software
+// distributed under the License is distributed on an "AS IS" BASIS,
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+package session
+
+import "fmt"
```
Comment (caglar10ur) [inline pkg/vsphere/session/errors.go]: if they are session specific then you don't need to export them otherwise I suggest putting them in errors pkg

File: cmd/vicadmin/server.go (hunk 6 above)
Comment (anchal-agrawal) [inline cmd/vicadmin/server.go]: I thought it would be cleaner to assign `displayErrStr` and return once at the end of the func, rather than putting several `return`s.

File: cmd/vicadmin/server.go (hunk 1 above)
Comment (anchal-agrawal) [inline cmd/vicadmin/server.go]: Fixed.

File: cmd/vicadmin/server.go (hunk 5 above)
Comment (anchal-agrawal) [inline cmd/vicadmin/server.go]: If the error is non-nil, `hostName` would be an empty string, which is what we'd want to display if we can't find the hostname. Please let me know if you have suggestions.

File: cmd/vicadmin/server.go (hunk 6 above)
Comment (caglar10ur) [inline cmd/vicadmin/server.go]: IMHO - it's more confusing this way. You are hiding the fact that you are returning an empty string when err == nil

```
func deriveDisplayError(err error) string {
	if err != nil {
		switch err := err.(type) {
		case session.SDKURLError:
			return fmt.Sprintf("SDK URL could not be parsed: %s", err.Err)
 		case session.SoapClientError:
 			return "unable to obtain a vim client"
 		case session.UserPassLoginError:
 			return "unable to log in with username and password"
 		default:
 			return err.Error()
 		}
 	}
 
 	return ""
 }
```

Comment (anchal-agrawal) [inline cmd/vicadmin/server.go]: Sounds good, thanks! I'll make the change.

File: pkg/vsphere/session/errors.go (hunk 8 above)
Comment (anchal-agrawal) [inline pkg/vsphere/session/errors.go]: We need exported errors to access them outside the `session` pkg in `cmd/vicadmin/server.go`. Since these errors are session-specific, I put them in the `session` pkg. Should we move them to `pkg/errors` anyway?

File: cmd/vicadmin/server.go (hunk 7 above)
Comment (anchal-agrawal) [inline cmd/vicadmin/server.go]: I feel this improves readability by separating the html arg from the other args.

File: pkg/vsphere/session/errors.go (hunk 8 above)
Comment (caglar10ur) [inline pkg/vsphere/session/errors.go]: Hmm missed the server.go part. Now sure, I guess they can stay and we can move it if another user shows up in the future

**Comment by caglar10ur** [comment]
LGTM

File: cmd/vicadmin/server.go (hunk 5 above)
Comment (anchal-agrawal) [inline cmd/vicadmin/server.go]: Thought about this some more. I'll change this so `hostName = "VCH"` when we get an error. It would be better to display "VCH Login" just "Login". Thanks @caglar10ur!

File: pkg/vsphere/session/errors.go [hunk 9]
```diff
@@ -0,0 +1,47 @@
...
+
+// SDKURLError is returned when the soap SDK URL cannot be parsed
+type SDKURLError struct {
+	Service string
+	Err     error
```
Comment (anchal-agrawal) [inline pkg/vsphere/session/errors.go]: I've been running into issues with the way `fmt.Sprintf` handles anonymous `error` fields as arguments. I'll defer this change for now and look for the exact problem.

**Comment by anchal-agrawal** [comment]
🏁
