### PR TITLE
Workaround a streaming panic in logs [full ci]

### LINKED ISSUE #3261: panic in generated code during `docker logs`
This presented in the following CI test: https://ci.vmware.run/vmware/vic/7124
Logs: https://console.cloud.google.com/m/cloudstorage/b/vic-ci-logs/o/integration_logs_7124_dcd7d2ec1e794f2b65112de8c514e4c39f9674c9.zip?authuser=1

The expected output was not seen by the docker client, but was in the container log on disk.
```
==============================================================================
Test-Cases.Group1-Docker-Commands.1-07-Docker-Stop :: Test 1-07 - Docker Stop 
==============================================================================

TEST_URL=192.168.31.8

Installing VCH to test server...
Installer completed successfully: VCH-7124-8900
Stop an already stopped container                                     | PASS |
------------------------------------------------------------------------------
Basic docker container stop                                           | PASS |
------------------------------------------------------------------------------
Stop a container with SIGKILL using default grace period              | PASS |
------------------------------------------------------------------------------
Stop a container with SIGKILL using specific stop signal              | PASS |
------------------------------------------------------------------------------
Stop a container with SIGKILL using specific grace period             | FAIL |
'' does not contain 'StopSignalHUP'
```

In the portlayer log we have a panic:
```
time=2016-11-20T16:01:09.067935766Z level=debug msg=[ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerLogsHandler:336] [70.399µs] 4a8b138affcce24660732dcf47fb540e8b72a4e8270f3218e9f5dc7df284500b 
2016/11/20 16:01:09 http: panic serving 192.168.31.234:36466: runtime error: invalid memory address or nil pointer dereference
goroutine 182 [running]:
net/http.(*conn).serve.func1(0xc4203f9780)
	/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0xe7ffe0, 0xc420016040)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers.(*GetContainerLogsNotFound).WriteResponse(0xc42041cb98, 0x1a333e0, 0xc4206a4f70, 0x0, 0x0)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers/get_container_logs_responses.go:82 +0x5a
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.(*Context).Respond(0xc4208148c0, 0x1a333e0, 0xc4206a4f70, 0xc4204a1770, 0xc42057f1c0, 0x1, 0x1, 0xc420123340, 0xeb2e40, 0xc42041cb98)
	/drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/context.go:392 +0x424
github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers.(*GetContainerLogs).ServeHTTP(0xc420137e20, 0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
	/drone/src/github.com/vmware/vic/lib/apiservers/portlayer/restapi/operations/containers/get_container_logs.go:53 +0x313
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1(0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
	/drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23 +0x69
net/http.HandlerFunc.ServeHTTP(0xc420592b80, 0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1(0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
	/drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:78 +0x555
net/http.HandlerFunc.ServeHTTP(0xc420885200, 0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
	/usr/local/go/src/net/http/server.go:1726 +0x44
github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1(0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
	/drone/src/github.com/vmware/vic/vendor/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36 +0x7b
net/http.HandlerFunc.ServeHTTP(0xc4205ecda0, 0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc420458600, 0x1a333e0, 0xc4206a4f70, 0xc4204a1770)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc4203f9780, 0x1a33f60, 0xc420236fc0)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

### PR DESCRIPTION
**Pull request by sflxn**
This works around a race condition in streaming support between
us and swagger when returning errors.  Long term, we need to
change the pattern we use for logging to adopt an explicit close
from the client side, telling the server side to close.

Resolves #3261

### CODE REVIEW

**Comment by hickeng** [comment]
Ah, this seems vaguely familiar.
@vburenin  you also seemed to have an idea as to what this was - please review

File: lib/apiservers/portlayer/restapi/handlers/containers_handlers.go [hunk 1]
```diff
@@ -355,7 +355,7 @@ func (handler *ContainersHandlersImpl) GetContainerLogsHandler(params containers
 
 	reader, err := container.LogReader(context.Background(), tail, follow)
 	if err != nil {
-		return containers.NewGetContainerLogsInternalServerError().WithPayload(&models.Error{Message: err.Error()})
+		return containers.NewGetContainerLogsInternalServerError().WithPayload()
```
Comment (sflxn) [inline lib/apiservers/portlayer/restapi/handlers/containers_handlers.go]: Added a comment.  Also removed the WithPayload().

**Comment by caglar10ur** [comment]
I believe we also don't return an error from SetStdin because of this

**Comment by caglar10ur** [comment]
LGTM

**Comment by vburenin** [comment]
unfortunately this is not the fix :-(

**Comment by mdubya66** [comment]
@sflxn recognizes that, it's a workaround

**Comment by mdubya66** [comment]
lgtm

**Comment by sflxn** [comment]
Just removed the error payload for the ContainerNotFound case.  It resolves a narrow case where user curl the portlayer server from within the VCH with a non-existent container.

**Comment by vburenin** [comment]
LGTM

**Comment by vburenin** [comment]
Unfortunately,  this will trigger another error that user will see:
➜  vic git:(master) ✗ docker logs bf3ca248066d
Error running logs job: Server error from portlayer: Unknown error from the interaction port layer: ByteStreamConsumer can only deal with io.Writer
