### PR TITLE
Remove image store if scratch creation fails on create image store [full ci]

### LINKED ISSUE #3273: VM_STATE_GUEST_OPERATION state preventing PL startup on VCH
Seen in CI job [7144](https://ci.vmware.run/vmware/vic/7144).

[integration_logs_7144_3fab0b09236b25886f990078cbc5d8467c8233f0.zip](https://github.com/vmware/vic/files/605157/integration_logs_7144_3fab0b09236b25886f990078cbc5d8467c8233f0.zip). See `Test-Cases.Group1-Docker-Commands.1-27-Docker-Login-VCH-7144-6364-container-logs.zip`.

PL
```
107 time=2016-11-21T16:12:36.926064118Z level=debug msg=[BEGIN] [github.com/vmware/vic/pkg/vsphere/disk.(*Manager).CreateAndAttach:85] [datastore1] VCH-7144-6364/VIC/564dd448-4352-7e99-788b-8eb0cada27f0/images/scratch/scratch.vmdk·
108 time=2016-11-21T16:12:36.926079070Z level=info msg=op=253.4 (delta:561.892719ms): Create/attach vmdk [datastore1] VCH-7144-6364/VIC/564dd448-4352-7e99-788b-8eb0cada27f0/images/scratch/scratch.vmdk from parent··
109 time=2016-11-21T16:12:36.930286914Z level=debug msg=op=253.4 (delta:566.097473ms): Attach reconfigure task=Task:haTask-13120-vim.VirtualMachine.reconfigure-4801534·
110 time="2016-11-21T16:12:36Z" level=debug msg="unexpected fault on task retry : &types.InvalidState{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}"·
111 time="2016-11-21T16:12:36Z" level=debug msg="Do not fix non invalid state error"·
112 time=2016-11-21T16:12:36.968518190Z level=error msg=op=253.4 (delta:604.330139ms): vmdk storage driver failed to attach disk: The operation is not allowed in the current state.·
```

hostd
```
 928 2016-11-21T16:12:36.348Z info hostd[7B880B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/577bad39-46bacc3a-720b-0050569c9c22/VCH-7144-6364/VCH-7144-6364.vmx opID=ee59e803 user=root] State Transition (VM_STATE_ON -> VM_STATE_GUEST_OPERATION)

...

 948 2016-11-21T16:12:37.435Z info hostd[77281B70] [Originator@6876 sub=Vimsvc.TaskManager opID=ee59e819 user=root] Task Created : haTask-13120-vim.VirtualMachine.reconfigure-4801534
 949 2016-11-21T16:12:37.436Z error hostd[77281B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/577bad39-46bacc3a-720b-0050569c9c22/VCH-7144-6364/VCH-7144-6364.vmx opID=ee59e819 user=root] Invalid transition requested (VM_STATE_GUEST_OPERATION -> VM_STATE_RECONFIGURING): Invalid state
 950 2016-11-21T16:12:37.436Z warning hostd[77281B70] [Originator@6876 sub=Vmsvc.vm:/vmfs/volumes/577bad39-46bacc3a-720b-0050569c9c22/VCH-7144-6364/VCH-7144-6364.vmx opID=ee59e819 user=root] Failed to start Reconfiguring: vim.fault.InvalidState
 951 2016-11-21T16:12:37.436Z info hostd[77281B70] [Originator@6876 sub=Default opID=ee59e819 user=root] AdapterServer caught exception: vim.fault.InvalidState
 952 2016-11-21T16:12:37.436Z info hostd[77281B70] [Originator@6876 sub=Vimsvc.TaskManager opID=ee59e819 user=root] Task Completed : haTask-13120-vim.VirtualMachine.reconfigure-4801534 Status error
```

We're trying to bring up the PL, create the image-store scratch disk by asking vsphere to `RECONFIGURE` the VCH, but fail.  We fail because the VCH state is in `VM_STATE_GUEST_OPERATION`.

### PR DESCRIPTION
**Pull request by fdawg4l**
Fixes #3273 

Creation of an image store should be itempotent.

* Also migrated log calls to op.Info/op.Debug/op.Error calls so we can
  track op IDs.

### CODE REVIEW

**Comment by fdawg4l** [comment]
I can't repro the initial issue locally so I'm going to put this through CI repeatedly.

**Comment by fdawg4l** [comment]
Of the 3 runs I kicked off, 1 failed with what looks like unrelated test failures.

b7196
Test-Cases.Group1-Docker-Commands.1-05-Docker-Start- doesnt look related to invalid state.
```

18:09:32.617	INFO	Running command 'docker -H dhcp-192-168-31-155.ci.drone.local:2376 --tls start 0091c3ae3e357e599e4c32040fea2230a9b2ace9e1d5845155ca1910317d745f 2>&1'.	
18:12:36.999	INFO	${rc} = 1	
18:12:36.999	INFO	${output} = Error response from daemon: Server error from portlayer: unable to wait for process launch status: context deadline exceeded
Error: failed to start containers: 0091c3ae3e357e599e4c32040fea2230a9b2ace9...
```
Don't know what this is about but its well past the invalid state area.



Test-Cases.Group1-Docker-Commands.1-08-Docker-Logs.Docker logs with follow and tail
```
18:24:23.034	INFO	Running command 'docker -H dhcp-192-168-31-223.ci.drone.local:2376 --tls logs --tail=5 --follow 237339fe10990b28dc46b05a067961587f0efae853c2b03bab505577924b362a 2>&1'.	
18:24:26.751	INFO	${rc} = 0	
18:24:26.752	INFO	${output} = 16
17
18
19
20

```
Reports it got 5 lines back instead of 15.  I can't tell if its a test issue or what because the invocation for follow was 5 lines.  So why it's expecting 15 is beyond me.

File: lib/apiservers/portlayer/restapi/handlers/storage_handlers_test.go [hunk 1]
```diff
@@ -142,6 +142,10 @@ func (c *MockDataStore) CreateImageStore(op trace.Operation, storeName string) (
 	return u, nil
 }
 
+func (c *MockDataStore) DeleteImageStore(op trace.Operation, storeName string) error {
```
Comment (vburenin) [inline lib/apiservers/portlayer/restapi/handlers/storage_handlers_test.go]: FYI: this mock object is a very good candidate to be generated rather than implemented.

**Comment by vburenin** [comment]
LGTM - not sure how it can fix the problem, but code looks good in general.

**Comment by matthewavery** [comment]
LGTM

File: lib/portlayer/storage/image_cache.go [hunk 2]
```diff
@@ -171,6 +169,12 @@ func (c *NameLookupCache) CreateImageStore(op trace.Operation, storeName string)
 	// Create the root image
 	scratch, err := c.DataStore.WriteImage(op, &Image{Store: store}, Scratch.ID, nil, "", nil)
 	if err != nil {
+		// if we failed here, remove the image store
+		op.Infof("Removing failed image store %s", storeName)
+		if e := c.DataStore.DeleteImageStore(op, storeName); e != nil {
+			op.Errorf("image store cleanup failed: %s", e.Error())
```
Comment (emlin) [inline lib/portlayer/storage/image_cache.go]: This is what I want to ask as well. If eventually we didn't attach and also failed to delete the imagestore, is it possible to know that imagestore is invalid in next time imagestore creation?

Comment (fdawg4l) [inline lib/portlayer/storage/image_cache.go]: The only scenario in which this will fail legitimately is because it has images in there.  And we dont enter this path if there are images in that directory.

The other path is simply calls to the datastore failing.  THere's really nothing we can do about that since they aren't tasks or bound by some `state` being true.  VSAN is the most tempermental about this stuff and it's pretty OK nuking empty dirs but we'll see if we need a retry around all of the datastore calls soon enough.

**Comment by fdawg4l** [comment]
.

**Comment by fdawg4l** [comment]
.
