### PR TITLE
VCH name input validation

### LINKED ISSUE #3552: Failed to create VCH with error
**VIC version:**

vic_0.8.0-7315-c8ac999

**Deployment details:**
Deploying on ESX 6.0

What was the vic-machine create command used to deploy the VCH?
```
vic>vic-machine-windows create --target 10.112.81.203 --user root --password "ca$hc0w" --no-tlsverify --force --name 'vch1'
INFO[2017-01-03T15:43:58+05:30] ### Installing VCH ####
WARN[2017-01-03T15:43:58+05:30] Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
INFO[2017-01-03T15:43:58+05:30] Loaded server certificate 'vch1'\server-cert.pem
WARN[2017-01-03T15:43:58+05:30] Configuring without TLS verify - certificate-based authentication disabled
INFO[2017-01-03T15:43:58+05:30] Validating supplied configuration
INFO[2017-01-03T15:43:58+05:30] Using default datastore: datastore1 (4)
INFO[2017-01-03T15:43:58+05:30] Firewall status: DISABLED on "/ha-datacenter/host/blr-3rd-2-dhcp458.eng.vmware.com/blr-3rd-2-dhcp458.eng.vmware.com"
WARN[2017-01-03T15:43:58+05:30] Firewall configuration will be incorrect if firewall is reenabled on hosts:
WARN[2017-01-03T15:43:58+05:30]         "/ha-datacenter/host/blr-3rd-2-dhcp458.eng.vmware.com/blr-3rd-2-dhcp458.eng.vmware.com"
INFO[2017-01-03T15:43:58+05:30] Firewall must permit dst 2377/tcp outbound to VCH management interface if firewall is reenabled
INFO[2017-01-03T15:43:58+05:30] License check OK
INFO[2017-01-03T15:43:58+05:30] DRS check SKIPPED - target is standalone host
INFO[2017-01-03T15:43:58+05:30]
INFO[2017-01-03T15:43:58+05:30] Creating Resource Pool "'vch1'"
INFO[2017-01-03T15:43:58+05:30] Creating VirtualSwitch
INFO[2017-01-03T15:43:58+05:30] Creating Portgroup
INFO[2017-01-03T15:43:58+05:30] Creating appliance on target
INFO[2017-01-03T15:43:58+05:30] Network role "management" is sharing NIC with "client"
INFO[2017-01-03T15:43:58+05:30] Network role "public" is sharing NIC with "client"
INFO[2017-01-03T15:43:59+05:30] Uploading images for container
INFO[2017-01-03T15:43:59+05:30]         "bootstrap.iso"
INFO[2017-01-03T15:43:59+05:30]         "appliance.iso"
INFO[2017-01-03T15:44:03+05:30] Waiting for IP information
INFO[2017-01-03T15:44:18+05:30] Waiting for major appliance components to launch
INFO[2017-01-03T15:44:18+05:30] Checking VCH connectivity with vSphere target
INFO[2017-01-03T15:44:18+05:30] vSphere API Test: https://10.112.81.203 vSphere API target responds as expected
INFO[2017-01-03T15:46:58+05:30] Collecting ha-host hostd.log
ERRO[2017-01-03T15:46:58+05:30] Failed to collect ha-host hostd.log: Post https://10.112.81.203/sdk: net/http: request canceled while waiting for connection
WARN[2017-01-03T15:46:58+05:30] No log data for ha-host hostd.log
ERRO[2017-01-03T15:46:58+05:30] --------------------
ERRO[2017-01-03T15:46:58+05:30] vic-machine-windows failed: Create timed out: if slow connection, increase timeout with --timeout
```
**Steps to reproduce:**

**Actual behavior:**

**Expected behavior:**

**Logs:**

* If you can access the VCH Admin portal, please download and attach the log bundle(s). See https://vmware.github.io/vic/assets/files/html/vic_admin/log_bundles.html for details.
* If the VCH Admin portal is inaccessible, you can enable SSH to the VCH endpoint VM to obtain logs manually. See https://vmware.github.io/vic/assets/files/html/vic_admin/vch_ssh_access.html for details. The VCH logs will be under /var/log/vic/ on the VM.

**Additional details as necessary:**

### PR DESCRIPTION
**Pull request by andrewtchin**
Fixes #3552

Prevent certain characters from being used in the VCH name
Allows `-_ ()`

```
⇒  bin/vic-machine-linux create -t 'root:password@192.168.218.129'  --thumbprint DC:5F:3C:3B:57:37:25:A0:84:C8:4E:31:48:00:C0:14:62:D9:95:E2 --public-network-ip 192.168.218.200/24 --public-network-gateway 192.168.218.2 --name "'chin'"
Feb  8 2017 12:20:51.763-08:00 INFO  ### Installing VCH ####
Feb  8 2017 12:20:51.763-08:00 ERROR --------------------
Feb  8 2017 12:20:51.763-08:00 ERROR vic-machine-linux create failed: --name contains unsupported characters: invalid characters in "'chin'"

```

Previously this would create a VCH named `'chin'`, but that caused problems.

### CODE REVIEW

File: cmd/vic-machine/common/utils.go [hunk 1]
```diff
@@ -31,3 +34,15 @@ func LogErrorIfAny(clic *cli.Context, err error) error {
...
+// CheckUnsupportedChars returns an error if string contains special characters
+// https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2046088
+func CheckUnsupportedChars(s string) error {
+	st := []byte(s)
+	re := regexp.MustCompile(`%|&|\*|\$|#|@|!|\\|/|:|\?|"|<|>|;|'|\|`)
+
+	if v := re.FindIndex(st); v == nil {
+		return nil
+	}
+	return fmt.Errorf("invalid characters in %q", s)
```
Comment (emlin) [inline cmd/vic-machine/common/utils.go]: Will that be better to use unsupported character, instead of invalid?
In addition, it will be better to list all unsupported character here. So user knows what's wrong easily.

File: cmd/vic-machine/create/create.go [hunk 2]
```diff
@@ -499,14 +499,19 @@ func (c *Create) processParams() error {
 		return err
 	}
 
-	if c.BridgeNetworkName == "" {
-		c.BridgeNetworkName = c.DisplayName
+	// prevent usage of special characters for certain user provided values
+	if err := common.CheckUnsupportedChars(c.DisplayName); err != nil {
```
Comment (emlin) [inline cmd/vic-machine/create/create.go]: I think image store and volume store contains path name, and is not checked in vic-machine. It will be ideal to add check for them as well.
thanks

**Comment by matthewavery** [comment]
lgtm

File: cmd/vic-machine/common/utils.go [hunk 3]
```diff
@@ -31,3 +34,27 @@ func LogErrorIfAny(clic *cli.Context, err error) error {
...
+// https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2046088
+func CheckUnsupportedChars(s string) error {
+	re := regexp.MustCompile(`%|&|\*|\$|#|@|!|\\|/|:|\?|"|<|>|;|'|\|`)
+	return checkUnsupportedChars(s, re)
+}
+
+// CheckUnsupportedCharsDatastore returns an error if a path string contains special characters
+// Same as CheckUnsupportedChars but allows / and :
+func CheckUnsupportedCharsDatastore(s string) error {
+	re := regexp.MustCompile(`%|&|\*|\$|#|@|!|\\|\?|"|<|>|;|'|\|`)
```
Comment (emlin) [inline cmd/vic-machine/common/utils.go]: Please define constants for the two regex, and add comment for their difference, to make it easy to understand and update

File: cmd/vic-machine/common/utils.go [hunk 4]
```diff
@@ -31,3 +40,24 @@ func LogErrorIfAny(clic *cli.Context, err error) error {
...
+}
+
+// CheckUnsupportedCharsDatastore returns an error if a datastore string contains special characters
+func CheckUnsupportedCharsDatastore(s string) error {
+	re := regexp.MustCompile(unsuppCharsDatastoreRegex)
+	return checkUnsupportedChars(s, re)
+}
+
+func checkUnsupportedChars(s string, re *regexp.Regexp) error {
+	st := []byte(s)
```
Comment (vburenin) [inline cmd/vic-machine/common/utils.go]: I wonder if vSphere supports unicode in path names? if so, since you are looking for special characters in a byte array, you may find many if "not allowed" due to how UTF-8 works.

File: cmd/vic-machine/common/utils.go [hunk 5]
```diff
@@ -31,3 +40,24 @@ func LogErrorIfAny(clic *cli.Context, err error) error {
 	log.Errorf("%s %s failed: %s\n", clic.App.Name, clic.Command.Name, errors.ErrorStack(err))
 	return cli.NewExitError("", 1)
 }
+
+// CheckUnsupportedChars returns an error if string contains special characters
+func CheckUnsupportedChars(s string) error {
+	re := regexp.MustCompile(unsuppCharsRegex)
```
Comment (vburenin) [inline cmd/vic-machine/common/utils.go]: Try always compile regex on module level. So, everything fails immediately.

File: cmd/vic-machine/common/utils_test.go [hunk 6]
```diff
@@ -0,0 +1,113 @@
...
+		valid bool
+	}{
+		{"anjunabeats", true},
+		{"tony-1", true},
+		{"paavo_1", true},
+		{"jono(1)", true},
+		{"oceanlab (1)", true},
+		{"waawn/", true},
+		{"tristate:", true},
+		{"test%", false},
```
Comment (vburenin) [inline cmd/vic-machine/common/utils_test.go]: try some unicode in this test.

Comment (vburenin) [inline cmd/vic-machine/common/utils_test.go]: Actually, try to pass unicode from CLI also.

File: cmd/vic-machine/create/create.go [hunk 7]
```diff
@@ -499,14 +499,19 @@ func (c *Create) processParams() error {
...
+		return cli.NewExitError(fmt.Sprintf("--name contains unsupported characters: %s", err), 1)
```
Comment (vburenin) [inline cmd/vic-machine/create/create.go]: I think referring by a parameter name to a problem is good, but feels clunky. Try to rephrase it like "<something> (--name value) contains not allowed characters. Allowed characters are: a-zA-Z, :, ..." Include full set of them, as a user I would love it.

File: cmd/vic-machine/create/create.go [hunk 8]
```diff
@@ -543,6 +548,10 @@ func (c *Create) processParams() error {
 		return err
 	}
 
+	if err := common.CheckUnsupportedCharsDatastore(c.ImageDatastorePath); err != nil {
+		return cli.NewExitError(fmt.Sprintf("--image-store contains unsupported characters: %s", err), 1)
```
Comment (vburenin) [inline cmd/vic-machine/create/create.go]: Same thing.

File: cmd/vic-machine/create/create.go [hunk 9]
```diff
@@ -868,6 +877,9 @@ func (c *Create) processVolumeStores() error {
 	defer trace.End(trace.Begin(""))
 	c.VolumeLocations = make(map[string]string)
 	for _, arg := range c.volumeStores {
+		if err := common.CheckUnsupportedCharsDatastore(arg); err != nil {
+			return fmt.Errorf("--volume-store contains unsupported characters: %s", err)
```
Comment (vburenin) [inline cmd/vic-machine/create/create.go]: same thing.

File: cmd/vic-machine/common/utils.go [hunk 10]
```diff
@@ -15,13 +15,25 @@
...
 	"github.com/vmware/vic/pkg/errors"
 )
 
+// https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2046088
+const unsuppCharsRegex = `%|&|\*|\$|#|@|!|\\|/|:|\?|"|<|>|;|'|\|`
+
+// Same as unsuppCharsRegex but allows / and : for datastore paths
+const unsuppCharsDatastoreRegex = `%|&|\*|\$|#|@|!|\\|\?|"|<|>|;|'|\|`
+
+var reUnsupp *regexp.Regexp = regexp.MustCompile(unsuppCharsRegex)
```
Comment (vburenin) [inline cmd/vic-machine/common/utils.go]: no need to specify a type here.
