### PR TITLE
init session logging earlier

### LINKED ISSUE #6004: docker exec causes cde in portlayer and panic in tether
**VIC version:**
x.y.z / master / commit ID

6.5U1 ESXi host running in fusion 

```
(mwilliamson) ib-aus-office-130:~/Downloads/vic $ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 1
Server Version: v1.1.0-rc3-13153-02b4c0a
Storage Driver: vSphere Integrated Containers v1.1.0-rc3-13153-02b4c0a Backend Engine
VolumeStores: default
vSphere Integrated Containers v1.1.0-rc3-13153-02b4c0a Backend Engine: RUNNING
 VCH CPU limit: 2942 MHz
 VCH memory limit: 1.255 GiB
 VCH CPU usage: 120 MHz
 VCH memory usage: 1.47 GiB
 VMware Product: VMware ESXi
 VMware OS: vmnix-x86
 VMware OS version: 6.5.0
 Registry Whitelist Mode: disabled.  All registry access allowed.
Plugins:
 Volume: vsphere
 Network: bridge
Swarm: inactive
Operating System: vmnix-x86
OSType: vmnix-x86
Architecture: x86_64
CPUs: 2942
Total Memory: 1.255 GiB
ID: vSphere Integrated Containers
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 0
 Goroutines: 21
 System Time: 2017-08-14T16:00:45.243586071Z
 EventsListeners: 0
Registry: registry.hub.docker.com
Experimental: false
Live Restore Enabled: false
```
**Deployment details:**
What was the vic-machine create command used to deploy the VCH?

```
(mwilliamson) ib-aus-office-130:~/Downloads/vic $ ./vic-machine-darwin upgrade --target 172.16.127.223 --user root --password password  --name virtual-container-host --thumbprint 24:E9:16:3A:49:91:3E:C4:DD:FE:AA:67:1A:66:9F:2D:DF:A8:6F:88
Aug 14 2017 10:59:00.349-05:00 INFO  ### Upgrading VCH ####
Aug 14 2017 10:59:00.669-05:00 INFO  Validating target
Aug 14 2017 10:59:00.784-05:00 WARN  Disabling ha-host hostd.log collection (ServerFaultCode: Cannot complete the operation due to an incorrect request to the server.)
Aug 14 2017 10:59:00.784-05:00 INFO
Aug 14 2017 10:59:00.784-05:00 INFO  VCH ID: VirtualMachine:1
Aug 14 2017 10:59:01.088-05:00 INFO  Creating directory [datastore1] virtual-container-host
Aug 14 2017 10:59:01.102-05:00 INFO  datastore root [datastore1] virtual-container-host already exists
Aug 14 2017 10:59:01.102-05:00 INFO  Datastore path is [datastore1] virtual-container-host
Aug 14 2017 10:59:01.160-05:00 INFO  Uploading images for container
Aug 14 2017 10:59:01.161-05:00 INFO  	"appliance.iso"
Aug 14 2017 10:59:01.161-05:00 INFO  	"bootstrap.iso"
Aug 14 2017 10:59:17.836-05:00 INFO  Switching appliance iso to [datastore1] virtual-container-host/V1.1.0-RC3-13153-02B4C0A-appliance.iso
Aug 14 2017 10:59:17.871-05:00 INFO  Setting VM configuration
Aug 14 2017 10:59:18.715-05:00 INFO  Waiting for IP information
Aug 14 2017 10:59:18.739-05:00 INFO  Waiting for major appliance components to launch
Aug 14 2017 10:59:33.990-05:00 INFO  Obtained IP address for client interface: "172.16.127.224"
Aug 14 2017 10:59:33.990-05:00 INFO  Checking VCH connectivity with vSphere target
Aug 14 2017 10:59:34.706-05:00 INFO  vSphere API Test: https://172.16.127.223 vSphere API target responds as expected
Aug 14 2017 10:59:49.218-05:00 INFO  Deleting upgrade snapshot "reconfigure for 13058"
Aug 14 2017 10:59:49.363-05:00 INFO  Completed successfully
```

**Steps to reproduce:**
1. Upgrade VCH to latest build 13153 
2. Enable ssh login on VCH and verified date and time
3. Start busybox container on VCH 
4. Copy a simple file to /tmp on the container
5. verify the file is there using ls -l
6. try to remove the file from the busybox container
7. Portlayer error. 
8. try to ls -l the file again, different portlayer error

**Actual behavior:**
```
(mwilliamson) ib-aus-office-130:~/Downloads/vic $ docker run -d busybox
7c7b64bb5f1abc7fd7dc2714cb3b991af88040ed5a99567c0f2f4e1ab8fdaa11

(mwilliamson) ib-aus-office-130:~/Downloads/vic $
(mwilliamson) ib-aus-office-130:~/Downloads/vic $ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
(mwilliamson) ib-aus-office-130:~/Downloads/vic $ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                     PORTS               NAMES
7c7b64bb5f1a        busybox             "sh"                14 seconds ago      Exited (0) 7 seconds ago                       jolly_cray
a69b4649f40c        busybox             "sh"                24 seconds ago      Created                                        focused_engelbart
(mwilliamson) ib-aus-office-130:~/Downloads/vic $ docker run -dit busybox
2f6216110cbc4507f09fc5eb3590f00bbb08cd45d8fd3b4dda557d8341a2e27a
(mwilliamson) ib-aus-office-130:~/Downloads/vic $ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
2f6216110cbc        busybox             "sh"                12 seconds ago      Up 14 seconds                           heuristic_perlman
(mwilliamson) ib-aus-office-130:~/Downloads/vic $ echo "this is a test" > /tmp/tf
(mwilliamson) ib-aus-office-130:~/Downloads/vic $ docker cp /tmp/tf 2:/tmp
(mwilliamson) ib-aus-office-130:~/Downloads/vic $ docker exec 2 ls -l /tmp
total 4
-rw-r--r--    1 root     root            15 Aug 14 16:04 tf
(mwilliamson) ib-aus-office-130:~/Downloads/vic $ docker exec 2 rm /tmp/tf
Server error from portlayer: [GET /interaction/{id}/stderr][404] containerGetStderrNotFound
(mwilliamson) ib-aus-office-130:~/Downloads/vic $ docker exec 2 ls -l /tmp
No such interaction connection for container: b1c28b8e2d56ce2e25023f68e4835a0b01b74fe128a0c36b0e3677b2ad52f452
(mwilliamson) ib-aus-office-130:~/Downloads/vic $ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
2f6216110cbc        busybox             "sh"                3 minutes ago       Up 3 minutes                            heuristic_perlman
(mwilliamson) ib-aus-office-130:~/Downloads/vic $ docker exec 2 ls -l /tmp
Server error from portlayer: [GET /interaction/{id}/stderr][404] containerGetStderrNotFound
```

**Expected behavior:**
able to perform cp and exec operations without failure from portlayer

**Logs:**
[container-logs.zip](https://github.com/vmware/vic/files/1222797/container-logs.zip)

* If you can access the VCH Admin portal, please download and attach the log bundle(s). See https://vmware.github.io/vic/assets/files/html/vic_admin/log_bundles.html for details.
* If the VCH Admin portal is inaccessible, you can enable SSH to the VCH endpoint VM to obtain logs manually. See https://vmware.github.io/vic/assets/files/html/vic_admin/vch_ssh_access.html for details. The VCH logs will be under /var/log/vic/ on the VM.

**Additional details as necessary:**

### PR DESCRIPTION
**Pull request by emlin**
This PR fixes #6004 and second issue in #5819

### CODE REVIEW

File: lib/tether/tether.go [hunk 1]
```diff
@@ -424,6 +430,20 @@ func (t *tether) processSessions() error {
 					extraconfig.EncodeWithPrefix(t.sink, session, extraconfig.CalculateKeys(t.config, fmt.Sprintf("%s.%s", session.extraconfigKey, id), "")[0])
 					log.Warnf("Re-launching process for session %s (count: %d)", id, session.Diagnostics.ResurrectionCount)
 					session.Cmd = *restartableCmd(&session.Cmd)
+
```
Comment (caglar10ur) [inline lib/tether/tether.go]: This is wrong and will break tether. 

You should not launch the session by yourself like this and instead only call loggingLocked and let the next block to handle launching them in parallel.

File: lib/tether/tether.go [hunk 2]
```diff
@@ -731,12 +751,6 @@ func (t *tether) launch(session *SessionConfig) error {
 		session.Cmd.SysProcAttr = user
 	}
 
-	err = t.loggingLocked(session)
```
Comment (caglar10ur) [inline lib/tether/tether.go]: instead of removing this and adding above, I believe you could simply do following here;

```go
if session.Diagnostics.ResurrectionCount > 0 {
    err = t.loggingLocked(session)
....
}
```

File: lib/tether/tether.go (hunk 1 above)
Comment (emlin) [inline lib/tether/tether.go]: copied too many code.

File: lib/tether/tether.go (hunk 2 above)
Comment (emlin) [inline lib/tether/tether.go]: okay
