### PR TITLE
Fix regression for VC upgrade [specific ci=Group11-Upgrade]

### LINKED ISSUE #6771: vic-machine upgrade failure on vCenter: unable to locate VCH
**VIC version:**

master

**Deployment details:**

```
# VIC 1.2.1 binaries
$ ./vic-machine-linux create --target <> --user <> --password <> --name VCH-1 --compute-resource cls --public-network=vm-network --bridge-network=bridge --image-store=datastore1 --volume-store=datastore1/test:default --force --no-tlsverify --debug 1
```

**Steps to reproduce:**

```
# master
$ ./vic-machine-linux upgrade --target <> --user <> --password <> --name=VCH-1 --compute-resource cls --debug 1 --force 
```

**Actual behavior:**
```
Nov 15 2017 10:19:12.111-08:00 DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).CheckImagesFiles:76]
Nov 15 2017 10:19:12.111-08:00 DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).checkImageVersion:164]
Nov 15 2017 10:19:12.111-08:00 DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).GetImageVersion:132]
Nov 15 2017 10:19:12.111-08:00 DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).GetImageVersion:132] [30.308µs] 
Nov 15 2017 10:19:12.111-08:00 DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:190]
Nov 15 2017 10:19:12.111-08:00 DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:190] [4.83µs] 
Nov 15 2017 10:19:12.111-08:00 DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:190]
Nov 15 2017 10:19:12.111-08:00 DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:190] [4.219µs] 
Nov 15 2017 10:19:12.111-08:00 DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).checkImageVersion:164] [71.545µs] 
Nov 15 2017 10:19:12.111-08:00 DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).checkImageVersion:164]
Nov 15 2017 10:19:12.111-08:00 DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).GetImageVersion:132]
Nov 15 2017 10:19:12.111-08:00 DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).GetImageVersion:132] [11.902µs] 
Nov 15 2017 10:19:12.111-08:00 DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:190]
Nov 15 2017 10:19:12.111-08:00 DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:190] [4.38µs] 
Nov 15 2017 10:19:12.111-08:00 DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:190]
Nov 15 2017 10:19:12.111-08:00 DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).getNoCommitHashVersion:190] [4.327µs] 
Nov 15 2017 10:19:12.111-08:00 DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).checkImageVersion:164] [47.99µs] 
Nov 15 2017 10:19:12.111-08:00 DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/common.(*Images).CheckImagesFiles:76] [231.014µs] 
Nov 15 2017 10:19:12.111-08:00 INFO  ### Upgrading VCH ####
Nov 15 2017 10:19:12.111-08:00 DEBUG [BEGIN] [github.com/vmware/vic/lib/install/validate.NewValidator:86]
Nov 15 2017 10:19:12.380-08:00 DEBUG Accepting host "10.161.57.152" thumbprint D1:10:39:E1:DD:F1:25:EE:25:35:3D:50:DC:3A:B1:CF:74:A0:F9:70
Nov 15 2017 10:19:12.380-08:00 DEBUG Creating VMOMI session with thumbprint D1:10:39:E1:DD:F1:25:EE:25:35:3D:50:DC:3A:B1:CF:74:A0:F9:70
Nov 15 2017 10:19:12.653-08:00 DEBUG Session Environment Info: 
Nov 15 2017 10:19:12.653-08:00 DEBUG vSphere resource cache populating...
Nov 15 2017 10:19:12.752-08:00 DEBUG Cached dc: 
Nov 15 2017 10:19:12.906-08:00 DEBUG Cached cluster: 
Nov 15 2017 10:19:13.306-08:00 DEBUG Cached pool: 
Nov 15 2017 10:19:13.356-08:00 DEBUG Cached folders: 
Nov 15 2017 10:19:13.356-08:00 DEBUG Error count populating vSphere cache: (1)
Nov 15 2017 10:19:13.356-08:00 DEBUG new validator Session.Populate: Failure finding ds (): default datastore resolves to multiple instances, please specify
Nov 15 2017 10:19:13.356-08:00 DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.NewValidator:86] [1.245385038s] 
Nov 15 2017 10:19:13.356-08:00 DEBUG [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).ValidateTarget:326]
Nov 15 2017 10:19:13.356-08:00 INFO  Validating target
Nov 15 2017 10:19:13.357-08:00 DEBUG [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).target:398]
Nov 15 2017 10:19:13.357-08:00 DEBUG [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).managedbyVC:405]
Nov 15 2017 10:19:13.357-08:00 DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).managedbyVC:405] [70.236µs] 
Nov 15 2017 10:19:13.357-08:00 DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).target:398] [213.264µs] 
Nov 15 2017 10:19:13.357-08:00 DEBUG [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).ListIssues:266]
Nov 15 2017 10:19:13.357-08:00 DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).ListIssues:266] [37.636µs] 
Nov 15 2017 10:19:13.357-08:00 DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).ValidateTarget:326] [561.197µs] 
Nov 15 2017 10:19:13.357-08:00 DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.NewDispatcher:81]
Nov 15 2017 10:19:13.357-08:00 DEBUG [ END ] [github.com/vmware/vic/lib/install/management.NewDispatcher:81] [12.55µs] 
Nov 15 2017 10:19:13.357-08:00 DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).NewVCHFromComputePath:93] path "", name "VCH-1"
Nov 15 2017 10:19:13.357-08:00 DEBUG [BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).ResourcePoolHelper:61]
Nov 15 2017 10:19:13.357-08:00 DEBUG Using default resource pool for compute resource: "/ha-datacenter/host/cls/Resources"
Nov 15 2017 10:19:13.357-08:00 DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).ResourcePoolHelper:61] [38.375µs] 
Nov 15 2017 10:19:13.661-08:00 ERROR Failed to get VCH resource pool "/ha-datacenter/host/cls/Resources/VCH-1": resource pool '/ha-datacenter/host/cls/Resources/VCH-1' not found
Nov 15 2017 10:19:13.661-08:00 DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).NewVCHFromComputePath:93] [304.139899ms] path "", name "VCH-1"
Nov 15 2017 10:19:13.661-08:00 ERROR Failed to get Virtual Container Host VCH-1
Nov 15 2017 10:19:13.661-08:00 ERROR resource pool '/ha-datacenter/host/cls/Resources/VCH-1' not found
Nov 15 2017 10:19:13.712-08:00 ERROR --------------------
Nov 15 2017 10:19:13.712-08:00 ERROR vic-machine-linux upgrade failed: upgrade failed
```

**Expected behavior:**

Upgrade should be able to find the VCH and proceed with the operation.

**Additional details as necessary:**

I suspect the regression to be due to this change: https://github.com/vmware/vic/pull/6572/files#diff-6a167380a66d015ed8093337bcbaa6f9R102

The following scenario fails as well:

```
# VIC 1.2.1 binaries
$ ./vic-machine-linux create --target <> --user <> --password <> --name VCH-1 --compute-resource cls --public-network=vm-network --bridge-network=bridge --image-store=datastore1 --volume-store=datastore1/test:default --force --no-tlsverify --debug 1

# master
$ ./vic-machine-linux delete --target <> --user <> --password <> --name VCH-1 --compute-resource cls --force
Nov 15 2017 12:11:03.733-08:00 INFO  ### Removing VCH ####
Nov 15 2017 12:11:05.009-08:00 INFO  Validating target
Nov 15 2017 12:11:05.709-08:00 ERROR Failed to get VCH resource pool "/ha-datacenter/host/cls/Resources/VCH-0-1014": resource pool '/ha-datacenter/host/cls/Resources/VCH-0-1014' not found
Nov 15 2017 12:11:05.709-08:00 ERROR Failed to get Virtual Container Host VCH-0-1014
Nov 15 2017 12:11:05.709-08:00 ERROR resource pool '/ha-datacenter/host/cls/Resources/VCH-0-1014' not found
Nov 15 2017 12:11:05.764-08:00 ERROR --------------------
Nov 15 2017 12:11:05.764-08:00 ERROR vic-machine-linux delete failed: delete failed
```

### PR DESCRIPTION
**Pull request by jzt**
This reverts a change that caused an upgrade regression due to removal of vApp checking.

Fixes #6771, thanks @anchal-agrawal

### CODE REVIEW

**Comment by jzt** [comment]
Refreshing to run a Group11-Upgrade test.

File: lib/install/management/virtual_app.go [hunk 1]
```diff
@@ -0,0 +1,101 @@
+// Copyright 2016 VMware, Inc. All Rights Reserved.
```
Comment (sgairo) [inline lib/install/management/virtual_app.go]: 👀  🤔

Comment (matthewavery) [reply lib/install/management/virtual_app.go]: Thanks license-bot!

Comment (jzt) [reply lib/install/management/virtual_app.go]: This is actually a revert, so its not a new file containing changes from 2017 :)

Comment (sgairo) [reply lib/install/management/virtual_app.go]: coolio, I figured it wasn't wrong because I remember having it, but also wasn't sure why it seemed to be new.
