### PR TITLE
Fix for #649

### LINKED ISSUE #649: vic-machine validation: invalid resource pool path is not reported correctly
for example, specify -compute-resource with "/ha-datacenter/host/localhost.eng.vmware.com", installation will succeed, but port-layer-server is not started for failed to find this resource pool.

the correct resource pool should be like "/ha-datacenter/host/localhost.eng.vmware.com/Resources"

### PR DESCRIPTION
**Pull request by gigawhitlocks**
Fixes #649 
Also renames two typo'd variables, ExternalNetworkName and ExternalNetworkPath from ExtenalNetwork(Path/Name) respectively. Did this in a separate commit for clarity in code review.

Integration test run results: http://smithers.eng.vmware.com:8080/job/ian_tests_his_fork/3/console
(also tested manually)

### CODE REVIEW

**Comment by andrewtchin** [comment]
👍

File: install/management/appliance.go [hunk 1]
```diff
@@ -170,9 +170,9 @@ func (d *Dispatcher) createApplianceSpec(conf *configuration.Configuration) (*ty
 			&types.OptionValue{Key: "guestinfo.vch/components", Value: "/sbin/docker-engine-server /sbin/port-layer-server /sbin/vicadmin"},
 			&types.OptionValue{Key: "guestinfo.vch/sbin/imagec", Value: "-debug -logfile=/var/log/vic/imagec.log -insecure"},
 			&types.OptionValue{Key: "guestinfo.vch/sbin/port-layer-server",
-				Value: fmt.Sprintf("--host=localhost --port=8080 --insecure --sdk=%s --datacenter=%s --cluster=%s --pool=%s/%s --datastore=%s --network=%s --vch=%s",
-					conf.TargetPath, conf.DatacenterName, conf.ClusterPath, conf.ResourcePoolPath, conf.DisplayName,
-					conf.ImageStorePath, conf.ExtenalNetworkPath, conf.DisplayName)},
+				Value: fmt.Sprintf("--host=localhost --port=8080 --insecure --sdk=%s --datacenter=%s --cluster=%s --pool=%s --datastore=%s --network=%s --vch=%s",
+					conf.TargetPath, conf.DatacenterName, conf.ClusterPath, d.vchPoolPath,
```
Comment (hmahmood) [inline install/management/appliance.go]: I think the bug is referring to ClusterPath, and you have not changed anything about that?

**Comment by hmahmood** [comment]
The code here: https://github.com/vmware/vic/blob/master/cmd/vic-machine/install.go#L178 needs to be fixed to handle the case where /Resources is not present in the cluster path. This should probably be added if it is missing, or we should validate if the pool path is correct or not (i.e. query VC/ESX).

**Comment by gigawhitlocks** [comment]
@hmahmood the validation happens here https://github.com/vmware/vic/blob/master/install/management/resource_pool.go#L35

This change uses the validated path. The bug previously was that the installer should BAIL when this is not found and it was not doing that -- now it does:
```
ian@ubuntu:~/bin$ ./vic-machine -target=skinner.eng.vmware.com -user=administrator@vsphere.local -passwd=ca\$hc0w -image-store=Datastore -appliance-iso=./appliance.iso -bootstrap-iso=./bootstrap.iso -bridge-network=hasan-test -force=true -generate-cert=true -name=ian-vch -compute-resource=/Datacenter
INFO[2016-05-11T17:11:13-05:00] ### Installing VCH ####                      
INFO[2016-05-11T17:11:13-05:00] Generating certificate/key pair - private key in ./ian-vch-key.pem 
INFO[2016-05-11T17:11:14-05:00] Validating supplied configuration            
ERRO[2016-05-11T17:11:15-05:00] Failed to create session: Failure finding cluster (/Datacenter): compute resource '/Datacenter' not found
Failure finding pool (/Datacenter): resource pool '/Datacenter' not found 
FATA[2016-05-11T17:11:15-05:00] Validating supplied configuration failed. Exiting... 
```


Since it's using govmomi's `find` it is also slightly less finicky in specifying the path, so if you specify e.g. `-compute-resource=/ha-datacenter/host/localhost.localdomain/Resources` or `-compute-resource=/ha-datacenter/host/localhost.localdomain/` both will succeed and install to the same place (and port-layer-server works). If you omit localhost.localdomain, vsphere isnt smart enough to add Resources to the path, so that fails and you get an error like the one shown above.

**Comment by hmahmood** [comment]
LGTM
