### PR TITLE
Copy existing volume data to mounts [full ci]

### LINKED ISSUE #3482: Volumes clobber underlying files
When volumes are mounted in the container they clobber the underlying files instead of copying them like docker does:
https://docs.docker.com/engine/tutorials/dockervolumes/

> Volumes are initialized when a container is created. If the container’s base image contains data at the specified mount point, that existing data is copied into the new volume upon volume initialization. (Note that this does not apply when mounting a host directory.)

Steps to reproduce:
Build & run container from the following dockerfile, `/etc/example/nowyouseeme` should exist.
Works correctly on Docker 1.10.3, does not work on VIC.
```
FROM debian:jessie

RUN mkdir -p /etc/example/nowyouseeme

VOLUME ["/etc/example"]

ENTRYPOINT ["/bin/bash"]
```

### PR DESCRIPTION
**Pull request by jakedsouza**
**Issue:**
  A containers base image data is **not** copied when a volume is mounted, if the containers base image contains data at the mount point. 

**Fix:**
  After mounting the volumes, copy the underlying base image files to the mount point. 
 
Changes - 
1. After all volumes are mounted, call `populateVolumes` 
2. For each mountpoint, `bind mount` the underlying *parent directory* to a tmp directory `/.bind` 
3. Copy the base image data to the mounted volume 
4. Cleanup the temp directory 
5. Add a markfile `.mountscopied` in the root so that we don't perform the operation again 
6. Introduce `CopyMode` field in MountSpec. Which defines whether to copy the data or not. 
   Currently it always copies once.  

Fixes #3482

### CODE REVIEW

File: lib/tether/tether.go [hunk 1]
```diff
@@ -42,11 +44,16 @@ import (
...
+	// MaxDeathRecords The maximum number of records to keep for restarting processes
 	MaxDeathRecords = 5
 
 	// the length of a truncated ID for use as hostname
 	shortLen = 12
+
+	// temp directory to copy existing data to mounts
+	bindDir = "/.bind"
+	// markfile to avoid re-copying existing data to mounts
+	mountsCopied = "/.mountscopied"
```
Comment (fdawg4l) [inline lib/tether/tether.go]: I'm not sure this is worth implementing since we're using the same path for shared volumes.  In which case container1 and container2 and both mount the same volume (`someVol`), and both will race on copying their contents to it.

Rather, lets remove this check and always copy the dirents in the underlying mount point (the bind mount) as long as they are newer or do not exist.

Comment (jakedsouza) [inline lib/tether/tether.go]: I think we should not copy multiple times. 

As per docker's implementation, this operation is performed only once when the container is created. 

Also it looks like docker copies *ALL* the data and not the new and non-existent ones.   

https://github.com/vmware/vic/blob/master/vendor/github.com/docker/docker/container/container_unix.go#L379-L397

File: lib/tether/ops_linux.go [hunk 2]
```diff
@@ -699,6 +700,56 @@ func (t *BaseOperations) MountTarget(ctx context.Context, source url.URL, target
...
+
+	source = filepath.Clean(source)
+
+	log.Debugf("creating directory %s", bindDir)
+	if err := os.MkdirAll(bindDir, 0644); err != nil {
+		log.Errorf("error creating directory %s: %+v", bindDir, err)
+		return err
+	}
+
+	parentDir := filepath.Dir(filepath.Clean(source))
```
Comment (matthewavery) [inline lib/tether/ops_linux.go]: `source` has already had `filepath.Clean()` called on it at this point. I believe that `filepath.Dir()` calls a clean on the supplied target. So maybe just eliminate the nested function call here.

File: lib/tether/tether.go [hunk 3]
```diff
@@ -252,6 +257,41 @@ func (t *tether) setMounts() error {
 			return fmt.Errorf("unsupported volume mount type for %s: %s", k, v.Source.Scheme)
 		}
 	}
+	return t.populateVolumes()
```
Comment (matthewavery) [inline lib/tether/tether.go]: So this is getting called after we already mount the nfs/device. I am not sure of the behavior of a bind mount after you have already mounted the target. I believe that you will actually end up with the mounted contents of the mounted device. I have not tried it yet though, so I could be wrong.

File: lib/tether/tether.go [hunk 4]
```diff
@@ -42,11 +44,16 @@ import (
...
 const (
-	// The maximum number of records to keep for restarting processes
+	// MaxDeathRecords The maximum number of records to keep for restarting processes
 	MaxDeathRecords = 5
 
 	// the length of a truncated ID for use as hostname
 	shortLen = 12
+
+	// temp directory to copy existing data to mounts
+	bindDir = "/.bind"
```
Comment (jakedsouza) [inline lib/tether/tether.go]: We don't have a label for nfs mounts. We could use a combination of hostname and path replacing `/` with `-`.

File: lib/tether/tether.go (hunk 3 above)
Comment (jakedsouza) [inline lib/tether/tether.go]: This works fine because we bind mount the parent directory and not the actual target. Bind mounting the parent directory results in mounting the original dir and not the mounted device 

https://superuser.com/a/389262/486095

File: lib/tether/ops_linux.go (hunk 2 above)
Comment (jakedsouza) [inline lib/tether/ops_linux.go]: My bad, had it twice. 
We still need to call clean once even though filepath.Dir calls clean. We are trying to get the parent directory here. If the source has a trailing slash, filepath.Dir returns the same source instead of the parent 

https://play.golang.org/p/8evsPBsDH9

Comment (matthewavery) [inline lib/tether/ops_linux.go]: Sure thing 😄 yeah I was mainly just looking at the filepath.clean in the function call.

File: lib/tether/tether.go (hunk 1 above)
Comment (jakedsouza) [inline lib/tether/tether.go]: Same question as above. 
1. What do we do for NFS volumes with a URL? 
2. Do we create a different file per volume?

File: lib/tether/ops_linux.go (hunk 2 above)
Comment (jakedsouza) [inline lib/tether/ops_linux.go]: Fixed

File: lib/tether/tether.go (hunk 3 above)
Comment (matthewavery) [inline lib/tether/tether.go]: Ah yes, I had tried this when I left this comment, but indeed from our conversation above if the `/` is left on the end you actually end up with the mount being bound to the target location. Sans the `/` works great! Sorry about that.

Comment (matthewavery) [inline lib/tether/tether.go]: Ah I see, hence the Dir call we talked about above. makes sense, sorry about that.

File: cmd/vic-init/tether_test.go [hunk 5]
```diff
@@ -165,6 +165,13 @@ func (t *Mocker) MountTarget(ctx context.Context, source url.URL, target string,
 	return nil
 }
 
+// CopyExistingContent copies the underlying files shadowed by a mount on a directory
+// to the volume mounted on the directory
+func (t *Mocker) CopyExistingContent(source string) error {
```
Comment (hickeng) [inline cmd/vic-init/tether_test.go]: @caglar10ur Please think about how we can change this test setup when continuing with the tether restructure. It was painful at the time to have to duplicate code but with time to do it correctly there should be a better option.

File: lib/tether/tether.go [hunk 6]
```diff
@@ -252,6 +258,46 @@ func (t *tether) setMounts() error {
...
+}
+
+func (t *tether) populateVolumes() error {
+	defer trace.End(trace.Begin(fmt.Sprintf("populateVolumes")))
+	// skip if no mounts present
+	if len(t.config.Mounts) == 0 {
+		return nil
+	}
+	// skip if this was done before
+	if _, err := os.Stat(mountsCopied); err == nil {
```
Comment (hickeng) [inline lib/tether/tether.go]: This is fine for now, but somewhat violates our goal of idempotent behaviour - if Reload is called and a new volume has been configured (or the CopyMode has changed) then we will not populate newly added volumes.

If we add more complex Copy behaviours (rsync for example) then this would be more simply phrased as a checking function per Copy type that takes a source and dest and returns whether or not to perform the copy, or just copies if needed.

Please open a follow up issue as a child of #4774 to revisit this in a tech debt, with a reference in #696 as that's where we will likely need the revised behaviour.

File: tests/test-cases/Group1-Docker-Commands/1-06-Docker-Run.robot [hunk 7]
```diff
@@ -133,3 +133,13 @@ Docker run verify name and id are not conflated
...
+
+Docker run verify anonymous volume contains files
+    ${rc}  ${output}=  Run And Return Rc And Output  docker %{VCH-PARAMS} run jakedsouza/group-1-06-docker-verify-volume-files:1.0 ls /etc/example
+	Should Be Equal As Integers  ${rc}  0
+	Should Contain  ${output}  thisshouldexist
+	Should Contain  ${output}  testfile.txt
+
+	${rc}  ${output}=  Run And Return Rc And Output  docker %{VCH-PARAMS} run jakedsouza/group-1-06-docker-verify-volume-files:1.0 cat /etc/example/testfile.txt
+    Should Be Equal As Integers  ${rc}  0
+	Should Contain  ${output}  TestFile
```
Comment (hickeng) [inline tests/test-cases/Group1-Docker-Commands/1-06-Docker-Run.robot]: IIRC you said that if a volume is explicitly specified with `-v name:/path` then this copy behaviour doesn't occur.
Please add a test for this case as well.

File: lib/config/executor/container_vm.go [hunk 8]
```diff
@@ -79,6 +79,17 @@ type ExitLog struct {
 	Message    string
 }
 
+// CopyMode type to define whether to copy data from the base image on mount
+type CopyMode int
```
Comment (hickeng) [inline lib/config/executor/container_vm.go]: Please move this to the top of the file with the `State` enum.

File: lib/portlayer/storage/volume.go [hunk 9]
```diff
@@ -70,10 +71,12 @@ type Volume struct {
 
 	// Backing device
 	Device Disk
+
+	CopyMode executor.CopyMode
 }
 
 // NewVolume creates a Volume
-func NewVolume(store *url.URL, ID string, info map[string][]byte, device Disk) (*Volume, error) {
+func NewVolume(store *url.URL, ID string, info map[string][]byte, device Disk, copyMode executor.CopyMode) (*Volume, error) {
```
Comment (hickeng) [inline lib/portlayer/storage/volume.go]: This probably doesn't need a backwards compatibility check given CopyNew is the default (by virtual of `0` being the nil value of `int`) but worth confirming that the backwards compatibility tests have a volume configuration that will exercise the copy paths in the future.

File: lib/tether/ops_linux.go [hunk 10]
```diff
@@ -699,6 +700,52 @@ func (t *BaseOperations) MountTarget(ctx context.Context, source url.URL, target
...
+// to the volume mounted on the directory
+// see bug https://github.com/vmware/vic/issues/3482
+func (t *BaseOperations) CopyExistingContent(source string) error {
+	defer trace.End(trace.Begin(fmt.Sprintf("copyExistingContent from %s", source)))
+
+	source = filepath.Clean(source)
+
+	log.Debugf("creating directory %s", bindDir)
+	if err := os.MkdirAll(bindDir, 0644); err != nil {
+		log.Errorf("error creating directory %s: %+v", bindDir, err)
```
Comment (fdawg4l) [inline lib/tether/ops_linux.go]: Might want to check for `EEXISTS` and continue in that case.

File: lib/tether/ops_linux.go [hunk 11]
```diff
@@ -699,6 +700,52 @@ func (t *BaseOperations) MountTarget(ctx context.Context, source url.URL, target
...
 }
 
+// CopyExistingContent copies the underlying files shadowed by a mount on a directory
+// to the volume mounted on the directory
+// see bug https://github.com/vmware/vic/issues/3482
+func (t *BaseOperations) CopyExistingContent(source string) error {
+	defer trace.End(trace.Begin(fmt.Sprintf("copyExistingContent from %s", source)))
+
+	source = filepath.Clean(source)
+
```
Comment (fdawg4l) [inline lib/tether/ops_linux.go]: Before creating directories and `bind` mounting the underlying mount point, it may be worth checking if there are even files there.  There's no sense descending down the mount/copy path if there's nothing to copy, right?

File: lib/tether/ops_linux.go [hunk 12]
```diff
@@ -699,6 +700,52 @@ func (t *BaseOperations) MountTarget(ctx context.Context, source url.URL, target
...
+		return err
+	}
+
+	log.Debugf("unmounting %s", bindDir)
+	if err := Sys.Syscall.Unmount(bindDir, syscall.MNT_DETACH); err != nil {
+		log.Errorf("error unmounting %+v", err)
+		return err
+	}
+	log.Debugf("removing %s", bindDir)
+	if err := os.Remove(bindDir); err != nil {
```
Comment (fdawg4l) [inline lib/tether/ops_linux.go]: I would do this in a `defer` after 712 (in the err == nil case).

File: lib/tether/ops_linux.go [hunk 13]
```diff
@@ -699,6 +700,52 @@ func (t *BaseOperations) MountTarget(ctx context.Context, source url.URL, target
...
+	// copy data from the bindDir to the source
+	// e.g if source is /foo/bar, copy ./bindDir/bar to /foo/bar
+	log.Debugf("copying contents from to %s to %s", mountedSource, source)
+	if err := archive.CopyWithTar(mountedSource, source); err != nil {
+		log.Errorf("err copying %s to %s: %+v", mountedSource, source, err)
+		return err
+	}
+
+	log.Debugf("unmounting %s", bindDir)
+	if err := Sys.Syscall.Unmount(bindDir, syscall.MNT_DETACH); err != nil {
```
Comment (fdawg4l) [inline lib/tether/ops_linux.go]: I would defer this after `Mount` is successful.

File: lib/tether/tether.go (hunk 6 above)
Comment (fdawg4l) [inline lib/tether/tether.go]: Echo'ing @hickeng here.  For NFS volumes where 2 containers mount the same volume, the 2nd container will attempt to copy the contents of the mount point *again*.  I thought we discussed this and were simply going to skip copying anything into the volume if the volume was non-empty.

File: lib/tether/ops_linux.go [hunk 14]
```diff
@@ -699,6 +700,52 @@ func (t *BaseOperations) MountTarget(ctx context.Context, source url.URL, target
...
+	if err := Sys.Syscall.Mount(parentDir, bindDir, ext4FileSystemType, syscall.MS_BIND, ""); err != nil {
+		log.Errorf("error mounting to %s: %+v", bindDir, err)
+		return err
+	}
+
+	mountedSource := filepath.Join(bindDir, filepath.Base(source))
+	// copy data from the bindDir to the source
+	// e.g if source is /foo/bar, copy ./bindDir/bar to /foo/bar
+	log.Debugf("copying contents from to %s to %s", mountedSource, source)
+	if err := archive.CopyWithTar(mountedSource, source); err != nil {
```
Comment (fdawg4l) [inline lib/tether/ops_linux.go]: Isn't this an explicit copy?  It will copy over the dest even if the dest exists, no?  We really don't want that.  Infact, we shouldn't be copying at all if anything exists in the volume (except for the `lost+found` directory).

File: lib/config/executor/container_vm.go [hunk 15]
```diff
@@ -79,6 +79,17 @@ type ExitLog struct {
...
+
+const (
+	// CopyNever Dont copy data on mount
+	CopyNever CopyMode = iota
```
Comment (caglar10ur) [inline lib/config/executor/container_vm.go]: make this iota + 1 so that we can differentiate zero value

File: lib/portlayer/storage/nfs/volume.go [hunk 16]
```diff
@@ -117,7 +118,7 @@ func (v *VolumeStore) VolumeCreate(op trace.Operation, ID string, store *url.URL
 		return nil, fmt.Errorf("Unexpected scheme (%s) for volume store (%s)", u.Scheme, v.Name)
 	}
 
-	vol, err := storage.NewVolume(v.SelfLink, ID, info, NewVolume(u, v.volDirPath(ID)))
+	vol, err := storage.NewVolume(v.SelfLink, ID, info, NewVolume(u, v.volDirPath(ID)), executor.CopyNew)
```
Comment (caglar10ur) [inline lib/portlayer/storage/nfs/volume.go]: Just ranting, no change necessary. I'm really not a big fan of keep adding parameters to the functions. It would be really great to introduce option types for these NewX calls and pass them (like https://github.com/vmware/vic/blob/5126aeb0d93a99e8d21d5ba04072a8d75923c1ad/lib/dns/dns.go#L53)

File: lib/tether/ops_linux.go [hunk 17]
```diff
@@ -31,6 +31,7 @@ import (
 
 	log "github.com/Sirupsen/logrus"
 	"github.com/d2g/dhcp4"
+	"github.com/docker/docker/pkg/archive"
```
Comment (caglar10ur) [inline lib/tether/ops_linux.go]: pfffff, here comes a docker dep into tether :/

Comment (fdawg4l) [inline lib/tether/ops_linux.go]: We didn't like this either.  But, this is a fairly concise package.  *coughs*

File: lib/tether/tether.go (hunk 6 above)
Comment (jakedsouza) [inline lib/tether/tether.go]: Done. Removed check for mountsCopied 

Added functionality, if the mounted volume is non empty (except for lost+found) skip the copy flow.

File: tests/test-cases/Group1-Docker-Commands/1-06-Docker-Run.robot (hunk 7 above)
Comment (jakedsouza) [inline tests/test-cases/Group1-Docker-Commands/1-06-Docker-Run.robot]: I was wrong about the copy behaviour. As per the docker docs 

*Volumes are initialized when a container is created. If the container’s base image contains data at the specified mount point, that existing data is copied into the new volume upon volume initialization. **(Note that this does not apply when mounting a host directory.)***

So the only case when data is *not* copied is when a host directory is mounted. This is something vic does not support.   

I added a test case to verify that the data is copied to a named volume. This is the same as  dockers current behaviour

File: lib/config/executor/container_vm.go (hunk 8 above)
Comment (jakedsouza) [inline lib/config/executor/container_vm.go]: Done

File: lib/portlayer/storage/volume.go (hunk 9 above)
Comment (jakedsouza) [inline lib/portlayer/storage/volume.go]: `CopyNever` is the default, `CopyNew` has a value 1 

Changed the enum to be iota+1 by default as requested by @caglar10ur below

File: lib/tether/ops_linux.go (hunk 11 above)
Comment (jakedsouza) [inline lib/tether/ops_linux.go]: We would need to bind anyways mount to check if there are any files in the underlying directory 

To avoid doing a bind mount, we could change the code flow to the steps below 
1. In mountLabel and mountTarget, check if the original folder is empty 
2. Mount the volume 
3. If step 1 is false then go ahead with copy

File: lib/tether/ops_linux.go (hunk 10 above)
Comment (jakedsouza) [inline lib/tether/ops_linux.go]: For MkdirAll `If path is already a directory, MkdirAll does nothing and returns nil.` so we dont need to check for EEXISTS

File: lib/tether/ops_linux.go (hunk 14 above)
Comment (jakedsouza) [inline lib/tether/ops_linux.go]: Will do. Also added a test case for this.

File: lib/tether/ops_linux.go (hunk 13 above)
Comment (jakedsouza) [inline lib/tether/ops_linux.go]: Done

File: lib/tether/ops_linux.go (hunk 12 above)
Comment (jakedsouza) [inline lib/tether/ops_linux.go]: Done

File: lib/config/executor/container_vm.go (hunk 15 above)
Comment (jakedsouza) [inline lib/config/executor/container_vm.go]: Done

**Comment by jakedsouza** [comment]
> Question before approving. What will happen if tether receives a reload in the middle of copy operation?

The `populateVolumes` operation occurs during tether.Start during which, the reload chan is already blocked. So calling reload should not affect this operation.  I might be wrong here though

File: lib/tether/interfaces.go [hunk 18]
```diff
@@ -37,6 +37,7 @@ type Operations interface {
 	Apply(endpoint *NetworkEndpoint) error
 	MountLabel(ctx context.Context, label, target string) error
 	MountTarget(ctx context.Context, source url.URL, target string, mountOptions string) error
+	CopyExistingContent(source string) error
```
Comment (jakedsouza) [inline lib/tether/interfaces.go]: > Is there a reason we do this after all of the volumes have been mounted? Another option would have been to inline this behaviour with the MountTarget logic.

I chose to follow this approach to avoid duplicating the code in MountLabel and MountTarget functions. 

If I understood your second question correctly,
Contents are not copied from VolumeA to VolumeB, they are always from the base image to a volume. One, cannot mount two volumes on the same path.

**Comment by caglar10ur** [comment]
Can you try or write a test to make sure?

**Comment by caglar10ur** [comment]
Otherwise LGTM

**Comment by rajanashok** [comment]
lgtm

**Comment by jakedsouza** [comment]
> Can you try or write a test to make sure?

@caglar10ur Tried to repro manually. I see a single error which I opened up as a separate issue. Im able to repro it on master https://github.com/vmware/vic/issues/4881

**Comment by matthewavery** [comment]
@jakedsouza this looks great 😄
