### PR TITLE
[specific ci=Group6-VIC-Machine]fix dc suggestion issue in vic-machine ls

### LINKED ISSUE #2859: vic-machine: doesn't handle datacenter `/` and doesn't suggest options with `ls`
Running against a local ESX I see the following when target has a trailing `/`, e.g. `https://user:password@esx/`

```
INFO[2016-10-23T16:16:44Z] ### Installing VCH ####
time=2016-10-23T16:16:44.152291463Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.CreateNoDCCheck:80]
DEBU[2016-10-23T16:16:44Z] Using to login by username/password
DEBU[2016-10-23T16:16:44Z] Session Environment Info:                     API Type=HostAgent API Version=6.0 Build=3380124 Name=VMware ESXi OS Type=vmnix-x86 Product ID=embeddedEsx UUID= Vendor=VMware, Inc. Version=6.0.0
DEBU[2016-10-23T16:16:44Z] vSphere resource cache populating...
DEBU[2016-10-23T16:16:44Z] Error count populating vSphere cache: (5)
time=2016-10-23T16:16:44.227323863Z level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.CreateNoDCCheck:80] [75.013344ms]
ERRO[2016-10-23T16:16:44Z] Datacenter must be specified in --target (e.g. https://addr/datacenter)
time=2016-10-23T16:16:44.227859362Z level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/validate.(*Validator).suggestDatacenter:170]
INFO[2016-10-23T16:16:44Z] Suggesting valid values for datacenter in --target
INFO[2016-10-23T16:16:44Z] Suggested datacenters:
INFO[2016-10-23T16:16:44Z]   "ha-datacenter"
time=2016-10-23T16:16:44.234730178Z level=debug msg=[ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).suggestDatacenter:170] [6.746422ms]
ERRO[2016-10-23T16:16:44Z] Create cannot continue: failed to create validator
ERRO[2016-10-23T16:16:44Z] --------------------
ERRO[2016-10-23T16:16:44Z] vic-machine-linux failed: Datacenter must be specified in --target (e.g. https://addr/datacenter)
```

Also for `ls` with that same target there's no suggestion at all:

```
INFO[2016-10-23T16:18:41Z] ### Listing VCHs ####
INFO[2016-10-23T16:18:41Z] Validating target
ERRO[2016-10-23T16:18:41Z] --------------------
ERRO[2016-10-23T16:18:41Z] Failed to get host system: please specify a datacenter
ERRO[2016-10-23T16:18:41Z] List cannot continue - target validation failed: validation of configuration failed
ERRO[2016-10-23T16:18:41Z] --------------------
ERRO[2016-10-23T16:18:41Z] vic-machine-linux failed: validation of configuration failed
```

Datacenter selection and validation should be a common path for all vic-machine commands as it's an inherent part of the target, which is required for all commands.

### PR DESCRIPTION
**Pull request by emlin**
fixes #2859 

This is to fix the datacenter suggestion issue in vic-machine ls

### CODE REVIEW

File: lib/install/validate/validator.go [hunk 1]
```diff
@@ -161,18 +156,27 @@ func CreateNoDCCheck(ctx context.Context, input *data.Data) (*Validator, error)
...
+	var detail string
+	if v.DatacenterPath != "" {
+		detail = fmt.Sprintf("Datacenter %q in --target is not found", strings.TrimPrefix(v.DatacenterPath, "/"))
+	} else {
+		// this means multiple datacenter exists, but user did not specify it in --target
+		detail = "Datacenter must be specified in --target (e.g. https://addr/datacenter)"
 	}
-	v.DatacenterPath = v.Session.Datacenter.InventoryPath
-	return nil
+	log.Error(detail)
```
Comment (vburenin) [inline lib/install/validate/validator.go]: As a good SOLID practice, It is not validator's job to log errors. Only caller should be logging an error when needed.

File: cmd/vic-machine/list/list.go [hunk 2]
```diff
@@ -161,7 +161,7 @@ func (l *List) Run(clic *cli.Context) (err error) {
 
 	var validator *validate.Validator
 	if l.Data.ComputeResourcePath == "" {
-		validator, err = validate.CreateNoDCCheck(ctx, l.Data)
+		validator, err = validate.NewValidatorAllowEmptyDC(ctx, l.Data, true)
```
Comment (vburenin) [inline cmd/vic-machine/list/list.go]: Using different constructors to handle different cases is not the best practice.
To make it looking better you should add a separate method that would allow EmptyDC.
Something like.
validator.AllowEmptyDC().AllowEmptyWaterTank().AllowNoHumans()

This, you may extend functionality in a less harmless way, otherwise it gets really hacky.

File: lib/install/validate/validator.go (hunk 1 above)
Comment (emlin) [inline lib/install/validate/validator.go]: I understand your point, but current suggestion methods logging out message. We should have a separate PR for that refactor.

File: cmd/vic-machine/list/list.go (hunk 2 above)
Comment (emlin) [inline cmd/vic-machine/list/list.go]: good point

File: cmd/vic-machine/list/list.go [hunk 3]
```diff
@@ -161,24 +161,26 @@ func (l *List) Run(clic *cli.Context) (err error) {
...
 		return errors.New("list failed")
 	}
+	// If dc is not set, and multiple datacenter is available, vic-machine ls will list VCHs under all datacenters.
+	validator.AllowEmptyDC()
 
 	_, err = validator.ValidateTarget(ctx, l.Data)
 	if err != nil {
 		log.Errorf("List cannot continue - target validation failed: %s", err)
-		return err
+		return errors.New("list failed")
```
Comment (vburenin) [inline cmd/vic-machine/list/list.go]: Uppercase for List?

File: cmd/vic-machine/delete/delete.go [hunk 4]
```diff
@@ -142,15 +148,15 @@ func (d *Uninstall) Run(clic *cli.Context) (err error) {
...
+		return errors.New("Delete failed")
 	}
 
 	// compare vch version and vic-machine version
 	installerBuild := version.GetBuild()
 	if vchConfig.Version == nil || !installerBuild.Equal(vchConfig.Version) {
 		if !d.Data.Force {
 			log.Errorf("VCH version %q is different than installer version %s. Specify --force to force delete", vchConfig.Version.ShortVersion(), installerBuild.ShortVersion())
-			return errors.New("delete failed")
+			return errors.New("Delete failed")
```
Comment (vburenin) [inline cmd/vic-machine/delete/delete.go]: I suspect it should be lowercase "delete" since you use lowercased error in other places.

File: cmd/vic-machine/list/list.go (hunk 3 above)
Comment (vburenin) [inline cmd/vic-machine/list/list.go]: As it happened, it should be as is, but lowercase should be used for "delete" error.

Comment (emlin) [inline cmd/vic-machine/list/list.go]: As you mentioned, delete and upgrade are changed to lower case

**Comment by andrewtchin** [comment]
lgtm
