### PR TITLE
fixed incorrect image digest persistance

### LINKED ISSUE #4282: docker persona not saving image repo digest correctly
The docker persona is not saving the image metadata repo digest correctly.  This results in the `docker images` command providing incorrect output.

Current - 1.11.2 client:
```
docker images
REPOSITORY          TAG                                                                IMAGE ID            CREATED             SIZE
busybox             latest                                                             00f017a8c2a6        7 days ago          1.11 MB
sha256              32f093055929dbc23dec4d03e09dfe971f5973a9ca5cf059cbfb644c206aa83f   00f017a8c2a6        7 days ago          1.11 MB
```
Expected - 1.11.2 client:
```
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             latest              00f017a8c2a6        7 days ago          1.11 MB
busybox             <none>              00f017a8c2a6        7 days ago          1.11 MB
```

### PR DESCRIPTION
**Pull request by cgtexmex**
The image digest was being persisted as part of image metadata
and not in the repository cache.  That has been corrected.

Additionally, the docker 1.11.2 client presents the docker images command
differently than 1.13, so tests were updated to satisfy our current
testing client of 1.11.2.

Fixes #4282

### CODE REVIEW

File: lib/apiservers/engine/backends/filter/image.go [hunk 1]
```diff
@@ -101,14 +101,18 @@ func IncludeImage(imgFilters filters.Args, listContext *ImageListContext) Filter
 		refs := cache.RepositoryCache().References(listContext.ID)
 		// reference filters
 		refFilters := imgFilters.Get("reference")
+
+		// current filter matches
+		listContext.Tags = make([]string, 0)
```
Comment (vburenin) [inline lib/apiservers/engine/backends/filter/image.go]: not sure if it makes sense to even bother, but if there is a chance that these arrays will hold at least 1 element, it is better to add some capacity into these array. Let say for 4 elements. However, if there are no elements expected, its better to just keep nil, since nil is treated as a perfect empty array.

File: lib/imagec/imagec.go [hunk 2]
```diff
@@ -289,13 +289,23 @@ func updateRepositoryCache(ic *ImageC) error {
...
-	// to the portlayer k/v
+	// AddReference will add the repo:tag to the repositoryCache and save to the portLayer
 	err = repoCache.AddReference(ref, ic.ImageID, true, imageLayerID, true)
 	if err != nil {
 		return fmt.Errorf("Unable to Add Image Reference(%s): %s", ref.String(), err.Error())
 	}
 
+	dig, err := reference.ParseNamed(fmt.Sprintf("%s@%s", ref.Name(), ic.ManifestDigest))
+	if err != nil {
+		return fmt.Errorf("Unable to parse digest: %s", err.Error())
```
Comment (vburenin) [inline lib/imagec/imagec.go]: Why do you add your own error here? Would not it be better just return original one?
