### PR TITLE
skip deleting -sesparse.vmdk file in vic-machine delete

### LINKED ISSUE #7549: vic-machine delete fails if there are pulled images
Running vic-machine-{os} delete fails every time if there are pulled images.
The VCH is created with the vic-machine command using a vCenter server as a target
After the command fails the VM and resource pool remain in place, the VM is in off state. The command succeeds if there are no images pulled.

Steps to reproduce:

1.Create a VCH with minimal configuration 
```
./vic-machine-linux create --target {vcenter-ip} --user {username} --password {password} --bridge-network vch-bridge --image-store datastore0 --volume-store datastore0/volumes:default --no-tlsverify --thumbprint {vcenter-cert-thumbprint} --name virtual-container-host
```
2.Pull an image with a docker client
```
docker --tls -H {VCH-IP}:2376 pull alpine
```
3.Try to delete the VCH
```
./vic-machine-linux delete --target {vcenter-ip} --user {username} --password {password} --force --name virtual-container-host
```

The command output with **--debug 3** is as follows:
```
INFO[0000] ### Removing VCH ####
DEBU[0000] Accepting host "###" thumbprint ###
DEBU[0000] Creating VMOMI session with thumbprint ###
DEBU[0000] Session Environment Info:                     API Type=VirtualCenter API Version=6.5 Build=7092793 Name="VMware vCenter Server" OS Type=linux-x64 Product ID=vpx UUID=d7548279-cca9-4d40-859b-177c379cce90 Vendor="VMware, Inc." Version=6.5.0
DEBU[0000] vSphere resource cache populating...
DEBU[0000] Cached dc:
DEBU[0000] Cached cluster:
DEBU[0000] Cached host:
DEBU[0000] Cached pool:
DEBU[0000] Cached folders:
DEBU[0000] Error count populating vSphere cache: (1)
DEBU[0000] new validator Session.Populate: Failure finding ds (): default datastore resolves to multiple instances, please specify
INFO[0000] Validating target
DEBU[0000] Using default resource pool for compute resource: "/vcqaDC/host/cls/Resources"
DEBU[0000] properties: [config.extraConfig summary.runtime.connectionState]
DEBU[0000] Cannot find image stores from configuration; attempting to find from vm datastore
DEBU[0000] properties: [datastore summary.runtime.connectionState]
INFO[0001]
INFO[0001] VCH ID: VirtualMachine:vm-34
DEBU[0001] properties: [config.extraConfig summary.runtime.connectionState]
INFO[0001] Removing VMs
DEBU[0001] properties: [config.extraConfig summary.runtime.connectionState]
DEBU[0001] No disks found attached to VM
INFO[0001] Removing image stores
DEBU[0001] Failed to delete "[datastore0] virtual-container-host/VIC": Cannot delete file [datastore0] virtual-container-host/VIC
DEBU[0001] Attempt to delete top level folder [datastore0] virtual-container-host/VIC failed. Remove the children files instead.
DEBU[0006] Failed to delete "[datastore0] virtual-container-host/VIC/421dd98a-6350-5a15-4f20-030a456ed2ef/images/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5-sesparse.vmdk": File /vmfs/volumes/5aaf8a69-8f102c7e-9616-02001c4697c8/virtual-container-host/VIC/421dd98a-6350-5a15-4f20-030a456ed2ef/images/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5-sesparse.vmdk was not found
DEBU[0006] Image store parent directory not empty, leaving in place.
INFO[0006] Removing volume stores
DEBU[0006] Provided datastore URL: "[datastore0] volumes"
DEBU[0006] Parsed volume store path: "volumes"
INFO[0006] Deleting volume store "default" on Datastore "datastore0" at path "volumes"
INFO[0006] Removing appliance VM network devices
DEBU[0007] Remove network is not supported for vCenter
INFO[0007] Collecting d7548279-cca9-4d40-859b-177c379cce90 vpxd.log
ERRO[0007] File /vmfs/volumes/5aaf8a69-8f102c7e-9616-02001c4697c8/virtual-container-host/VIC/421dd98a-6350-5a15-4f20-030a456ed2ef/images/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5/9797e5e798a034d53525968de25bd25c913e7bb17c6d068ebc778cb33e3ff6e5-sesparse.vmdk was not found
ERRO[0007] --------------------
ERRO[0007] vic-machine-linux delete failed: delete failed
```

### PR DESCRIPTION
**Pull request by AngieCris**
Fixes #7549 

`[specific ci=6-03-Delete]`

Skip `-sesparse.vmdk` file when removing VMFS files. 

Before, we only skipped `-delta.vmdk` and `-flat.vmdk` files, but we didn't skip `-sesparse.vmdk` snapshot file. Since we didn't skip it, the file will be removed separately. However vSphere already removed the `-sesparse.vmdk` file automatically when deleting the original vmdk by vSphere. A second delete will result in a not found failure.

It's hard to add a test for this change, because `-sesparse.vmdk` snapshot is a format for disks larger than 2TB. However in `6-03-Delete` suite, pulling ubuntu image will result in multiple `-delta.vmdk` in image layers, so passing 6-03 tests would prove that vmdk related files are all successfully cleaned up after vic-machine delete.

### CODE REVIEW

File: lib/install/management/store_files.go [hunk 1]
```diff
@@ -187,9 +187,9 @@ func (d *Dispatcher) deleteFilesIteratively(m *object.DatastoreFileManager, ds *
 func (d *Dispatcher) deleteVMFSFiles(m *object.DatastoreFileManager, ds *object.Datastore, dsPath string) error {
 	defer trace.End(trace.Begin(dsPath, d.op))
 
-	for _, ext := range []string{"-delta.vmdk", "-flat.vmdk"} {
+	for _, ext := range []string{"-delta.vmdk", "-flat.vmdk", "-sesparse.vmdk"} {
 		if strings.HasSuffix(dsPath, ext) {
-			// Skip backing files as Delete() will do so via DeleteVirtualDisk
+			// Skip delete of snapshot files, as Delete() will remove all snapshot files when deleting the vmdk
```
Comment (hickeng) [inline lib/install/management/store_files.go]: snapshot is a somewhat misleading term as it's specific terminology in vSphere and we do not use snapshots as such. We're attempting to avoid deleting the actual backing file (*.vmdk is a textual descriptor file that references the backing file).
