### PR TITLE
remove timeout and combine logs

### LINKED ISSUE #1303: vic-machine timeout
timeout usage message is wrong in vic-machine delete
timeout parameter is not necessary for vic-machine inspect

### PR DESCRIPTION
**Pull request by emlin**
Fixes #1303 #1262 

This request will remove timeout from vic-machine respect, cause that command just query objects from vsphere.

Also combine all vic-machine command log to one single log file, vic-machine.log. Separated logs files does not make the story easier. And will lose some log information, if that's returned to vic-machine main file.

### CODE REVIEW

**Comment by andrewtchin** [comment]
lgtm

File: cmd/vic-machine/main.go [hunk 1]
```diff
@@ -72,9 +79,21 @@ func main() {
 	} else {
 		app.Version = fmt.Sprintf("%s-%s", BuildID, CommitID)
 	}
+	// Open log file
+	f, err := os.OpenFile(LOG_FILE, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0644)
+	if err != nil {
+		fmt.Printf("Error opening logfile %s: %v", LOG_FILE, err)
+	}
+	defer f.Close()
```
Comment (dougm) [inline cmd/vic-machine/main.go]: This should be inside an `} else {`, otherwise will panic() in the case where we cannot OpenFile() above.

File: cmd/vic-machine/main.go [hunk 2]
```diff
@@ -72,9 +79,21 @@ func main() {
...
+
+	// Initiliaze logger with default TextFormatter
+	log.SetFormatter(&log.TextFormatter{ForceColors: true, FullTimestamp: true})
+	// SetOutput to io.MultiWriter so that we can log to stdout and a file
+	log.SetOutput(io.MultiWriter(os.Stdout, f))
```
Comment (dougm) [inline cmd/vic-machine/main.go]: Let's also avoid writing to 'f' when nil.  Above you can start with:
```go 
logs := []io.Writer{io.Stdout}
```

When os.OpenFile is ok, then:

```go
logs = append(f, logs)
```
And here:

```go
log.SetOutput(io.MultiWriter(logs...))
```

File: cmd/vic-machine/main.go [hunk 3]
```diff
@@ -72,9 +79,21 @@ func main() {
 	} else {
 		app.Version = fmt.Sprintf("%s-%s", BuildID, CommitID)
 	}
+	// Open log file
+	f, err := os.OpenFile(LOG_FILE, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0644)
+	if err != nil {
+		fmt.Printf("Error opening logfile %s: %v", LOG_FILE, err)
```
Comment (dougm) [inline cmd/vic-machine/main.go]: This message should be written to os.Stderr

File: cmd/vic-machine/main.go [hunk 4]
```diff
@@ -72,9 +79,21 @@ func main() {
...
+	}
+	defer f.Close()
+
+	// Initiliaze logger with default TextFormatter
+	log.SetFormatter(&log.TextFormatter{ForceColors: true, FullTimestamp: true})
+	// SetOutput to io.MultiWriter so that we can log to stdout and a file
+	log.SetOutput(io.MultiWriter(os.Stdout, f))
+
 	if err := app.Run(os.Args); err != nil {
 		fmt.Println("--------------------")
```
Comment (dougm) [inline cmd/vic-machine/main.go]: This line should also be switched to log.Errorf, or removed

File: lib/install/data/data.go [hunk 5]
```diff
@@ -89,6 +89,7 @@ func NewData() *Data {
 		MappedNetworksGateways: make(map[string]net.IPNet),
 		MappedNetworksIPRanges: make(map[string][]ip.Range),
 		MappedNetworksDNS:      make(map[string][]net.IP),
+		Timeout:                3 * time.Minute,
```
Comment (dougm) [inline lib/install/data/data.go]: I can't see what this timeout is for, 3 minutes seems too short if it is install related.

Comment (emlin) [inline lib/install/data/data.go]: This is a default value. In general, default value can be set in argument default, but if there is no timeout option at all, the default value cannot be set, and then it will be 0 second timeout.
So this is to solve the issue in commands without timeout option.

In addition, the timeout is set for application initialization waiting, not for the whole process, so 3 minutes by default for install is ok as well.

**Comment by dougm** [comment]
lgtm

**Comment by emlin** [comment]
♻️
