### PR TITLE
Fix state change logic for fixing invalid state cVM

### LINKED ISSUE #4397: Container's "fixing" state is handled incorrectly while fixing invalid state
**VIC version:**

master / 6a162e77b2f86ccfc81ddbd46f0d59ced79a6be7

**Details:**

Seen in CI master build https://ci.vmware.run/vmware/vic/9102

```
Test 11-01-Upgrade

Running command 'docker -H 192.168.31.70:2376 --tls ps -aq | xargs -n1 docker -H 192.168.31.70:2376 --tls rm 2>&1'.	
11:41:17.338	INFO	${rc} = 123	
11:41:17.339	INFO	${output} = 720868f2efba
b3c55fccebe0
06988b22e76c
Error response from daemon: No such container: 3c28911287be
8b0ed1f7f89b
```

Container `3c28911287be` was in invalid state and got dropped from the portlayer's container cache before the portlayer's [`Remove`](https://github.com/vmware/vic/blob/master/lib/apiservers/portlayer/restapi/handlers/containers_handlers.go#L235) func could be called.

While fixing the invalid state, the VM was [unregistered](https://github.com/vmware/vic/blob/master/pkg/vsphere/vm/vm.go#L496), which triggered a remove event that was [handled](https://github.com/vmware/vic/blob/master/lib/portlayer/exec/container.go#L612) _after_ the [VM left its "fixing" state](https://github.com/vmware/vic/blob/master/pkg/vsphere/vm/vm.go#L495). This caused the container to be [dropped](https://github.com/vmware/vic/blob/master/lib/portlayer/exec/container.go#L619) from the cache.

This can happen if the remove event was delivered late. Per @emlin, the fix is to call `vm.LeaveFixingState()` when the event is handled, not [here](https://github.com/vmware/vic/blob/master/pkg/vsphere/vm/vm.go#L495).

**Logs:**

PL log snippet
```
Mar 25 2017 16:41:16.470Z DEBUG get vm properties [config runtime] of vm VirtualMachine:8571
Mar 25 2017 16:41:16.470Z DEBUG properties: [config runtime summary.runtime.connectionState]
Mar 25 2017 16:41:16.483Z INFO  vm VirtualMachine:8571 is in invalid state
Mar 25 2017 16:41:16.483Z DEBUG Fix invalid state VM: VirtualMachine:8571
Mar 25 2017 16:41:16.485Z DEBUG Get vm properties [summary.config summary.runtime.host resourcePool parentVApp]
Mar 25 2017 16:41:16.487Z DEBUG Unregister VM vch-restart-tes-3c28911287be6d2fda331cba7c50285f0143044927ad7d6ca29c23d754df8453
Mar 25 2017 16:41:16.493Z DEBUG Register VM vch-restart-tes-3c28911287be6d2fda331cba7c50285f0143044927ad7d6ca29c23d754df8453
Mar 25 2017 16:41:16.493Z DEBUG Found 2 subscribers to vsphere.VMEvent: Removed vch-restart-tes-3c28911287be6d2fda331cba7c50285f0143044927ad7d6ca29c23d754df8453 on ns539601.ip-144-217-72.net from ha-datacenter
Mar 25 2017 16:41:16.493Z DEBUG Event manager calling back to exec
Mar 25 2017 16:41:16.493Z DEBUG Event manager calling back to logging
Mar 25 2017 16:41:16.493Z DEBUG [BEGIN] [github.com/vmware/vic/lib/portlayer/logging.eventCallback:52]
Mar 25 2017 16:41:16.493Z DEBUG [ END ] [github.com/vmware/vic/lib/portlayer/logging.eventCallback:52] [7.864µs] 
Mar 25 2017 16:41:16.562Z DEBUG Retry properties query [config runtime] of vm VirtualMachine:8575
...
3c28911287be6d2fda331cba7c50285f0143044927ad7d6ca29c23d754df8453
Mar 25 2017 16:41:16.587Z DEBUG Container(3c28911287be6d2fda331cba7c50285f0143044927ad7d6ca29c23d754df8453) Removed via event activity
Mar 25 2017 16:41:16.587Z DEBUG Found 2 subscribers to events.ContainerEvent: Container 3c28911287be6d2fda331cba7c50285f0143044927ad7d6ca29c23d754df8453 Removed
Mar 25 2017 16:41:16.587Z DEBUG Event manager calling back to netCtx(0xc420b43c80)
Mar 25 2017 16:41:16.587Z DEBUG Event manager calling back to PLE-310c4ac0ae0c245415c9b7c5a631e1536387d7756192f73a6131b7d9ec1c7e43
Mar 25 2017 16:41:16.588Z DEBUG [BEGIN] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).RemoveContainerHandler:226] 3c28911287be6d2fda331cba7c50285f0143044927ad7d6ca29c23d754df8453
Mar 25 2017 16:41:16.588Z DEBUG [ END ] [github.com/vmware/vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).RemoveContainerHandler:226] [20.924µs] 3c28911287be6d2fda331cba7c50285f0143044927ad7d6ca29c23d754df8453
```

[Test-Cases.Group11-Upgrade.11-01-Upgrade-VCH-9102-7933-container-logs.zip](https://github.com/vmware/vic/files/870355/Test-Cases.Group11-Upgrade.11-01-Upgrade-VCH-9102-7933-container-logs.zip)

### PR DESCRIPTION
**Pull request by anchal-agrawal**
Fixes #4397

### CODE REVIEW

File: pkg/vsphere/vm/vm.go [hunk 1]
```diff
@@ -492,9 +492,12 @@ func (vm *VirtualMachine) fixVM(ctx context.Context) error {
 	name := mvm.Summary.Config.Name
 	log.Debugf("Unregister VM %s", name)
 	vm.EnterFixingState()
-	defer vm.LeaveFixingState()
 	if err := vm.Unregister(ctx); err != nil {
 		log.Errorf("Unable to unregister vm %q: %s", name, err)
+
+		// Leave fixing state if unregister failed and the fixing state was not
```
Comment (emlin) [inline pkg/vsphere/vm/vm.go]: was/will ?

**Comment by emlin** [comment]
lgtm
