### PR TITLE
Wait for MAC address ready

### LINKED ISSUE #628: vic-machine: argument validation
Just tried an install with vic-machine. It's not remotely obvious from the error message that I need to specify -external-network (there are multiple switches on this machine).

```
$ ./vic-machine -target=192.168.78.128 -user=root -compute-resource=/ha-datacenter/host/* -generate-cert -image-store=datastore1
INFO[2016-05-04T00:05:53Z] ### Installing VCH ####
INFO[2016-05-04T00:05:53Z] Generating certificate/key pair - private key in ./docker-appliance-key.pem
INFO[2016-05-04T00:05:53Z] Validating supplied configuration
INFO[2016-05-04T00:05:55Z] Creating a Resource Pool
INFO[2016-05-04T00:05:55Z] Network docker-appliance exists
INFO[2016-05-04T00:05:55Z] Creating appliance on target
INFO[2016-05-04T00:05:55Z] Uploading images for container
INFO[2016-05-04T00:05:55Z]      bootstrap.iso
INFO[2016-05-04T00:05:55Z]      appliance.iso
ERRO[2016-05-04T00:06:06Z] Operation failed: A specified parameter was not correct: config.extraConfig["guestinfo.vch/networks/client"] - (&{{} %!!(MISSING)s(*types.InvalidArgument=&{{{<nil> []}} config.extraConfig["guestinfo.vch/networks/client"]}) A specified parameter was not correct: config.extraConfig["guestinfo.vch/networks/client"]})
ERRO[2016-05-04T00:06:06Z] Error to set MacAddress into guestinfo: Operation failed: A specified parameter was not correct: config.extraConfig["guestinfo.vch/networks/client"] - (&{{} %!s(*types.InvalidArgument=&{{{<nil> []}} config.extraConfig["guestinfo.vch/networks/client"]}) A specified parameter was not correct: config.extraConfig["guestinfo.vch/networks/client"]})
INFO[2016-05-04T00:06:06Z] Collecting ha-host hostd.log
FATA[2016-05-04T00:06:07Z] Failed to set Mac address Operation failed: A specified parameter was not correct: config.extraConfig["guestinfo.vch/networks/client"] - (&{{} %!s(*types.InvalidArgument=&{{{<nil> []}} config.extraConfig["guestinfo.vch/networks/client"]}) A specified parameter was not correct: config.extraConfig["guestinfo.vch/networks/client"]}). Exiting...
```

### PR DESCRIPTION
**Pull request by emlin**
Fixes #628
Fail installation if empty MAC address is got

### CODE REVIEW

**Comment by caglar10ur** [comment]
LGTM :sheep: :it:

File: install/management/appliance.go [hunk 1]
```diff
@@ -363,16 +363,42 @@ func (d *Dispatcher) setMacToGuestInfo() error {
 	return nil
 }
 
+func (d *Dispatcher) waitingForMAC(dul time.Duration) (map[string]string, error) {
```
Comment (dougm) [inline install/management/appliance.go]: Looks like you could use the property collector Wait method, so rather than poll at an interval, you'd be waiting for a push from the property collector.  Have a look at this section of the recently added: VirtualMachine.WaitForNetIP helper: https://github.com/vmware/govmomi/commit/388df2f1d8cb5a0059850fdf10520df7923474ef#diff-aee13781bca461bd01dfe83f8c8fa2ecR257

**Comment by emlin** [comment]
Doug, that looks good. Just not clear if the wait will timeout?

Btw, the new method looks very useful for user of govmomi, would it be possible to abstract the method you point to me, to two common methods, as WaitMac, and WaitGuest?
You already had waitmac function, that can be a public method, and the WaitForNetIp, could easily be changed to wait any custom guestInfo, with custom attribute name, right?

**Comment by dougm** [comment]
@emlin you can use the context.Context param to set a timeout.

Let's start with getting this to function in vic, and we can revisit splitting the methods on the govmomi side later.  The main point is to make use of the gomvomi property.Wait() function, rather than poll for property changes on an interval.

**Comment by caglar10ur** [comment]
You can timeout on wait, in fact following is what I'm doing right now for blocking the docker start until we have confirmation

```
	//
	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	return vm.WaitForExtraConfig(ctx, key, expected)
```

vm.WaitForExtraConfig is a new method on VM which uses property.Wait

**Comment by emlin** [comment]
Is using the context timeout to get mac address, but I still didn't see your VM method to query extra config in master branch.
Can refactor code after you check in to get VM ip address.

**Comment by dougm** [comment]
Nice, LGTM

**Comment by dougm** [comment]
@emlin the code @caglar10ur refers to is in PR #653
