### PR TITLE
Vic machine configure tlsverify

### LINKED ISSUE #7378: vic-machine configure won't regenerate TLSverify-enabled self-signed certificates
`vic-machine configure` has the ability to regenerate certificates, and will do so if called with `--no-tlsverify`, and an empty `--tls-cert-path`.

Unfortunately it seems that this same functionality doesn't work/exist/was overlooked for TLSverify.

When the user calls 
`vic-machine configure --tls-cname="bar.foo.com" --tls-cert-path="empty_directory"` 
we should regenerate the TLSverify enabled certificates and output them to `empty_directory` and update them in the VCH. This is necessary to prevent manual intervention necessary to renew expiring certificates.

Current behavior:
`INFO[0006] No certificate regeneration requested. No new certificates provided. Certificates left unchanged. `

Desired behavior:
Generate certs.

Labelled this both `bug` and `feature` because it's a feature gap.

### PR DESCRIPTION
**Pull request by gigawhitlocks**
Very small change to fix an oversight in `vic-machine configure`
Manual test passed; automated test WIP.

`[specific ci=6-17-Configure-TLS]`
Resolves #7378

### CODE REVIEW

File: cmd/vic-machine/configure/configure.go [hunk 1]
```diff
@@ -252,7 +252,7 @@ func updateSessionEnv(sess *executor.SessionConfig, envName, envValue string) {
 
 func (c *Configure) processCertificates(op trace.Operation, client, public, management data.NetworkConfig) error {
 
-	if !c.certificates.NoTLSverify && (c.certificates.Skey == "" || c.certificates.Scert == "") {
+	if len(c.certificates.Cname) == 0 && !c.certificates.NoTLSverify && (c.certificates.Skey == "" || c.certificates.Scert == "") {
```
Comment (vburenin) [inline cmd/vic-machine/configure/configure.go]: c.certificates.Cname == ""

Comment (gigawhitlocks) [reply cmd/vic-machine/configure/configure.go]: I thought that for some reason using len on strings was more idiomatic? where did i get that idea?
