### PR TITLE
[specific ci=1-27-Docker-Login] Fix whitelist matching and whitelist test

### LINKED ISSUE #5538: nightly test 21-1-whitelist unable to confirm secure registry
Seen on vsphere 6.5 

[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1089156/21-1-Whitelist.zip)

also 6.0
[21-1-Whitelist.zip](https://github.com/vmware/vic/files/1089167/21-1-Whitelist.zip)

From vic-machine log
```
Jun 20 2017 08:26:17.631Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Head:361] [606.93µs] http://harbor.ci.drone.local/v2/
Jun 20 2017 08:26:17.631Z WARN  Unable to confirm insecure registry harbor.ci.drone.local is a valid registry at this time.
Jun 20 2017 08:26:17.631Z DEBUG URL: 10.160.126.191/v2/
Jun 20 2017 08:26:17.631Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Head:361] 10.160.126.191/v2/
Jun 20 2017 08:26:17.631Z DEBUG [ END ] [github.com/vmware/vic/pkg/fetcher.(*URLFetcher).Head:361] [40.38µs] 10.160.126.191/v2/
Jun 20 2017 08:26:17.631Z WARN  Unable to confirm secure registry 10.160.126.191 is a valid registry at this time.
Jun 20 2017 08:26:17.631Z INFO  Insecure registries = harbor.ci.drone.local
Jun 20 2017 08:26:17.631Z INFO  Whitelist registries = 10.160.126.191, harbor.ci.drone.local
```

### LINKED ISSUE #5622: Cannot login to an insecure-registry with http://
**VIC version:**

vic 1.1 (actually based on binaries compiled from this branch https://github.com/sflxn/vic/tree/docker-push)

**Deployment details:**
```
vic-machine-linux create --force --name=vch-1 --insecure-registry http://kang.eng.vmware.com --target=root:pwd@192.168.213.129 --debug 1 --image-store=datastore1 --no-tlsverify --no-tls
```

**Steps to reproduce:**
after deploying the vch, run `sudo docker -H ... login http://kang.eng.vmware.com` or `sudo docker -H ... kang.eng.vmware.com`.  Here `kang.vmware.com` is a harbor instance deployed on a Ubuntu desktop VM.

**Actual behavior:**
Both return the same error msg: `rror response from daemon: Head https://kang.eng.vmware.com/v2/: dial tcp 10.17.109.201:443: getsockopt: connection refused`. However, both cmds suceeed on vanilla docker. 

**Expected behavior:**
`sudo docker login kang.eng.vmware.com` succeeds.

**Logs:**
[container-logs.zip](https://github.com/vmware/vic/files/1112605/container-logs.zip)

**Additional details as necessary:**

### PR DESCRIPTION
**Pull request by gigawhitlocks**
Fixes the way that we do matching on user input against whitelist/blacklist when a user uses `docker login`, `docker push` and during validation in vic-machine. Resolves #5538 and maybe #5622 but I won't close #5622 until we have a test that demonstrates that it is also resolved.

### CODE REVIEW

File: pkg/registry/entry.go [hunk 1]
```diff
@@ -129,8 +129,41 @@ func (u *urlEntry) Contains(e Entry) bool {
...
+	if !ok {
+		return false
+	}
+
+	result = u.Contains(query)
+	if result {
+		return
+	}
+
+	if query.URL().Scheme != "" {
```
Comment (gigawhitlocks) [inline pkg/registry/entry.go]: currently collapsing this nested if into a && instead, just did this at first cause it was a little easier to see the logic I was implementing

**Comment by gigawhitlocks** [comment]
@hmahmood -- with the change in the behavior of `Contains` there's now a change in the behavior of `Merge`. Not sure if this is desirable. If it's fine I'll just update the unit tests to reflect that but otherwise, I guess one solution is to move that port logic back out of `Contains` like it was originally

**Comment by hmahmood** [comment]
@gigawhitlocks you should update the unit tests.

File: pkg/registry/entry.go [hunk 2]
```diff
@@ -129,8 +132,25 @@ func (u *urlEntry) Contains(e Entry) bool {
...
+
+	result = u.Contains(query)
+	if result {
+		return
+	}
+
+	if query.URL().Scheme != "" && u.URL().Scheme == "" {
+		query.URL().Scheme = u.URL().Scheme
+	} else if u.URL().Scheme != "" && query.URL().Scheme == "" {
+		u.URL().Scheme = query.URL().Scheme
```
Comment (hmahmood) [inline pkg/registry/entry.go]: You should not modify the local object.

File: pkg/registry/entry.go [hunk 3]
```diff
@@ -129,8 +132,25 @@ func (u *urlEntry) Contains(e Entry) bool {
...
+	}
+
+	return u.Contains(query)
```
Comment (hmahmood) [inline pkg/registry/entry.go]: I think you can do this without calling `Contains` twice.

File: lib/install/validate/validator.go [hunk 4]
```diff
@@ -642,7 +642,14 @@ func (v *Validator) reachableRegistries(ctx context.Context, input *data.Data, p
 			continue
 		}
 
-		if _, err = registry.Reachable(w.String(), w.URL().Scheme, "", "", pool, registryValidationTime, false); err != nil {
+		var scheme string
+		if w.URL().Scheme == "" {
```
Comment (gigawhitlocks) [inline lib/install/validate/validator.go]: LOL, yes. wow. CS 101 mistake right here

File: pkg/registry/entry.go (hunk 2 above)
Comment (gigawhitlocks) [inline pkg/registry/entry.go]: Ah, I misunderstood our discussion two days ago a little in that case 😆

File: pkg/registry/entry.go (hunk 3 above)
Comment (gigawhitlocks) [inline pkg/registry/entry.go]: Sure, yeah I guess `Contains` could potentially be expensive. I thought it'd make sense to try `Contains` before any special logic, in case it Just Matches™, but maybe not

**Comment by gigawhitlocks** [comment]
Comments should be addressed at this time @hmahmood

File: lib/apiservers/engine/backends/system.go [hunk 5]
```diff
@@ -319,10 +319,8 @@ func (s *System) AuthenticateToRegistry(ctx context.Context, authConfig *types.A
 		registryAddress = registryAddress + "/v2/"
 	}
 
-	// TODO(jzt) Ensuring the scheme exists in the url happens at several places in our code.
-	// We should consolidate these into a common method to deal with this.
-	if !strings.HasPrefix(registryAddress, "https://") && !strings.HasPrefix(registryAddress, "http://") {
-		registryAddress = "https://" + registryAddress
+	if !strings.HasPrefix(registryAddress, "http") {
+		registryAddress = "//" + registryAddress
```
Comment (hmahmood) [inline lib/apiservers/engine/backends/system.go]: Is this going work with line 362?

File: pkg/registry/entry_test.go [hunk 6]
```diff
@@ -203,7 +203,7 @@ func TestEntryMatch(t *testing.T) {
 		{
 			e:   ParseEntry("http://192.168.1.1"),
 			s:   "192.168.1.1/foo/bar", // ambiguous scheme and entry is restricted to http, so no match
```
Comment (hmahmood) [inline pkg/registry/entry_test.go]: Should update the comment.

File: lib/apiservers/engine/backends/system.go (hunk 5 above)
Comment (gigawhitlocks) [inline lib/apiservers/engine/backends/system.go]: Yes, look at the way `dologin` is called on line 389
