### PR TITLE
Correct handling of incorrect --id option [specific ci=6-11-Debug]

### LINKED ISSUE #4918: Panic in `vic-machine debug` if incorrect id is specified
Observed in a debugging session - if an incorrect ID is specified a panic results.
Looking at the code this would apply to:
* inspect
* debug
* delete

### PR DESCRIPTION
**Pull request by hickeng**
Previously this was resulting in a panic. This now reports that the id
provided could not be found.

Fixes #4918

### CODE REVIEW

File: lib/install/management/finder.go [hunk 1]
```diff
@@ -55,7 +55,7 @@ func (d *Dispatcher) NewVCHFromID(id string) (*vm.VirtualMachine, error) {
 			return nil, err
 		}
 		log.Debugf("Appliance is not found")
-		return nil, nil
+		return nil, fmt.Errorf("id \"%s\" could not be found", id)
```
Comment (caglar10ur) [inline lib/install/management/finder.go]: use %q instead
