### PR TITLE
Fixes container log collection in vicadmin

### LINKED ISSUE #1150: container-logs.tar.gz does not contain container logs
#1075 was opened to collect container logs - turns out that's because vicadmin is not putting the container logs into the container-logs.tar.gz bundle any more.
This is a significant reduction in diagnostic capability and should be addressed asap.

@dougm Assigned to you as you're the original author - not intending this to take much of your time so if it's more than an hour or two let me know and we'll assign it to someone else to dig into.

### PR DESCRIPTION
**Pull request by hickeng**
Fixes #1150 
Towards #709

vicadmin was not collecting the logs for containers - the assumptions
carried over from bonneville were not valid (and would have been broken on
vsan anyway).

This code also adds some restructuring in anticipation of adding pprof
collection to the other appliance components and, ideally, the containerVMs

### CODE REVIEW

File: cmd/vicadmin/vicadm.go [hunk 1]
```diff
@@ -300,56 +325,76 @@ type datastoreReader struct {
...
+		path, err := child.DSPath(ctx)
+		if err != nil {
+			log.Errorf("Unable to get datastore path for child VM %s: %s", child.Reference(), err)
+			// we need to get as many logs as possible
+			continue
+		}
 
-	if info.Error != nil {
-		return nil, errors.New(info.Error.LocalizedMessage)
+		log.Debugf("Adding VM for log collection: %s", path.String())
```
Comment (hickeng) [inline cmd/vicadmin/vicadm.go]: If anyone can tell me why:
a. the log package qualifier isn't visible here but is in the full file view
b. why this line doesn't print out, but does compile and the line below executes...
I will owe them thanks. Same for line 397

Comment (dougm) [inline cmd/vicadmin/vicadm.go]: Not sure what you mean by a ?  Regarding b, I assume you're seeing other log.Debug's ?  Do you see the message if you change to another log level?

File: lib/metadata/virtual_container_host.go [hunk 2]
```diff
@@ -24,6 +24,19 @@ import (
 	"github.com/vmware/govmomi/vim25/types"
 )
 
+// PatternToken is a set of tokens that can be placed into string constants
```
Comment (dougm) [inline lib/metadata/virtual_container_host.go]: Not seeing this referenced anywhere, other than the const below?

**Comment by dougm** [comment]
lgtm

Just not seeing the PatternToken type being used anywhere.

File: cmd/vicadmin/vicadm.go (hunk 1 above)
Comment (hickeng) [inline cmd/vicadmin/vicadm.go]: By a, I mean in the diff above I see:
`+		Debugf("Adding VM for log collection: %s", path.String())`

but when I paste from the diff:
`+		log.Debugf("Adding VM for log collection: %s", path.String())`

I have tried deleting and recreating the line in case of non-printable characters, but it does compile and that had no effect.

File: lib/metadata/virtual_container_host.go (hunk 2 above)
Comment (hickeng) [inline lib/metadata/virtual_container_host.go]: https://github.com/vmware/vic/pull/1217/files#diff-227bcd7fc9072cf62ac2d3ed69ba4071R391

File: cmd/vicadmin/vicadm.go (hunk 1 above)
Comment (dougm) [inline cmd/vicadmin/vicadm.go]: Oh strange, I see 'log.Debugf' the diff above.

**Comment by matthewavery** [comment]
lgtm

**Comment by hickeng** [comment]
poke

**Comment by hickeng** [comment]
poke
