### PR TITLE
Tmp copy for mutating array iteration

### LINKED ISSUE #7365: Portlayer panic github.com/vmware/vic/lib/portlayer/network.(*Endpoint).copy on VC
The test container is hung on this command:
```
root         1  0.0  0.0   4344   636 ?        Ss   16:01   0:00 /bin/sh -c echo $CI_SCRIPT | base64 -d | /bin/sh -e
root         9  0.0  0.0   4344   688 ?        S    16:01   0:00 /bin/sh -e
root        51  0.0  0.0  11684  2500 ?        S    16:01   0:00 /bin/bash tests/integration-test.sh
root       182  0.2  1.0 142580 82132 ?        S    16:01   0:31 /usr/bin/python /usr/local/bin/pybot --removekeywords TAG:secret --exclude skip tests/test-cases
root      4563  0.0  0.0      0     0 ?        Zs   16:35   0:00 [sh] <defunct>
root     11039  0.0  0.0   4344   732 ?        S    17:15   0:00 sh -c docker -H 10.158.214.77:2376 --tls run --name verify-anon-1 jakedsouza/group-1-19-docker-verify-volume-files:1.0 ls /etc/example 2>&1
root     11040  0.0  0.1 200516 16340 ?        Sl   17:15   0:00 docker -H 10.158.214.77:2376 --tls run --name verify-anon-1 jakedsouza/group-1-19-docker-verify-volume-files:1.0 ls /etc/example
root     11047  0.0  0.0  20304  3308 pts/0    Ss   19:27   0:00 /bin/bash
root     11057  0.0  0.0  17508  2076 pts/0    R+   19:28   0:00 ps aux
```

The container id of concern:

`074b7ed656e57633397df644b879ef4ca317f79a1c907644d663d687854c0326`

Failure - personality:
```
Feb 22 2018 17:18:08.160Z INFO  container attach: stdout (074b7ed656e57633397df644b879ef4ca317f79a1c907644d663d687854c0326) done
Feb 22 2018 17:18:08.160Z INFO  container attach: stderr (074b7ed656e57633397df644b879ef4ca317f79a1c907644d663d687854c0326) done
Feb 22 2018 17:18:08.160Z INFO  cleaned up connections to 074b7ed656e57633397df644b879ef4ca317f79a1c907644d663d687854c0326. Checking errors
Feb 22 2018 17:18:08.160Z INFO  No error found. Returning nil...
Feb 22 2018 17:18:08.160Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [6.516497515s] 
Feb 22 2018 17:18:08.160Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.(*Container).ContainerAttach:1709] [6.516526515s] 074b7ed656e57633397df644b879ef4ca317f79a1c907644d663d687854c0326
Feb 22 2018 17:18:10.294Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [8.309730848s] 
Feb 22 2018 17:18:10.294Z DEBUG [ END ] op=296.26 [vic/lib/apiservers/engine/backends.(*Container).ContainerStart:906] [8.309765394s] 074b7ed656e57633397df644b879ef4ca317f79a1c907644d663d687854c0326
```

Pass - personality (example output from a passing run):
```
Feb 21 2018 22:48:10.314Z DEBUG Calling POST /v1.25/containers/f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d/start
Feb 21 2018 22:48:10.314Z DEBUG op=290.30: [NewOperation] op=290.30 [vic/lib/apiservers/engine/backends.(*Container).ContainerStart:905]
Feb 21 2018 22:48:10.314Z DEBUG [BEGIN] op=290.30 [vic/lib/apiservers/engine/backends.(*Container).ContainerStart:906] f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d
Feb 21 2018 22:48:10.314Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Feb 21 2018 22:48:10.314Z DEBUG op=290.30: Obtained container lock for f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d
Feb 21 2018 22:48:10.329Z DEBUG op=290.30: Binding network to container f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d
Feb 21 2018 22:48:10.329Z DEBUG [BEGIN]  [vic/lib/apiservers/engine/backends.(*Container).cleanupPortBindings:853] f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d
Feb 21 2018 22:48:10.329Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.(*Container).cleanupPortBindings:853] [9.751µs] f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d
Feb 21 2018 22:48:10.329Z DEBUG op=290.30: Setting container f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d state to running
Feb 21 2018 22:48:10.330Z DEBUG op=290.30: Commit container f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d
Feb 21 2018 22:48:16.534Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [6.220302911s] 
Feb 21 2018 22:48:16.534Z DEBUG [ END ] op=290.30 [vic/lib/apiservers/engine/backends.(*Container).ContainerStart:906] [6.220329195s] f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d
Feb 21 2018 22:48:16.541Z DEBUG [BEGIN]  [vic/lib/apiservers/engine/backends.DockerEventPublisher.PublishEvent:220] Event Monitor received eventID(296.884) for container(f3e551c887af) - Started
Feb 21 2018 22:48:16.541Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.DockerEventPublisher.PublishEvent:220] [58.711µs] Event Monitor received eventID(296.884) for container(f3e551c887af) - Started
Feb 21 2018 22:48:16.562Z INFO  container attach: stderr (f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d) done
Feb 21 2018 22:48:16.562Z DEBUG * stdout attach end Wed Feb 21 22:48:16 UTC 2018
Feb 21 2018 22:48:16.562Z INFO  container attach: stdout (f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d) done
Feb 21 2018 22:48:16.562Z INFO  cleaned up connections to f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d. Checking errors
Feb 21 2018 22:48:16.562Z INFO  No error found. Returning nil...
Feb 21 2018 22:48:16.562Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [6.432662056s] 
Feb 21 2018 22:48:16.562Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.(*Container).ContainerAttach:1709] [6.432687101s] f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d
Feb 21 2018 22:48:16.937Z DEBUG [BEGIN]  [vic/lib/apiservers/engine/backends.DockerEventPublisher.PublishEvent:220] Event Monitor received eventID(296.886) for container(f3e551c887af) - PoweredOff
Feb 21 2018 22:48:16.937Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.DockerEventPublisher.PublishEvent:220] [33.207µs] Event Monitor received eventID(296.886) for container(f3e551c887af) - PoweredOff
Feb 21 2018 22:48:16.937Z DEBUG [BEGIN]  [vic/lib/apiservers/engine/backends.(*ContainerProxy).exitCode:879]
Feb 21 2018 22:48:16.984Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.(*ContainerProxy).exitCode:879] [46.107997ms] 
Feb 21 2018 22:48:16.984Z INFO  Sending die event for container(f3e551c887af) with exitCode[0] - eventID(296.886)
Feb 21 2018 22:48:16.984Z DEBUG UnmapPorts for f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d: map[]
Feb 21 2018 22:48:16.988Z DEBUG Client context cancelled, stop sending events
```

Failure - portlayer:
```
Feb 22 2018 17:18:10.572Z DEBUG [ END ] op=442.473 [vic/lib/portlayer/network.(*Context).UnbindContainer:961] [71.199µs] UnbindContainer
Feb 22 2018 17:18:10.572Z DEBUG [BEGIN] op=442.473 [vic/lib/portlayer/exec.Commit:34] 074b7ed656e57633397df644b879ef4ca317f79a1c907644d663d687854c0326
Feb 22 2018 17:18:10.572Z INFO  op=442.473: Reconfigure: attempting update to 074b7ed656e57633397df644b879ef4ca317f79a1c907644d663d687854c0326 with change version "2018-02-22T17:18:02.11905Z" (poweredOff)
Feb 22 2018 17:18:10.789Z INFO  op=442.473: Reconfigure: committed update to 074b7ed656e57633397df644b879ef4ca317f79a1c907644d663d687854c0326 with change version: 2018-02-22T17:18:02.11905Z
Feb 22 2018 17:18:10.789Z INFO  op=442.473: Attempting to perform a guest reconfigure operation on (074b7ed656e57633397df644b879ef4ca317f79a1c907644d663d687854c0326)
Feb 22 2018 17:18:10.789Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Feb 22 2018 17:18:10.789Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [6.198µs] 
Feb 22 2018 17:18:10.789Z DEBUG op=442.473: Update: updated change version from handle: 2018-02-22T17:18:02.11905Z
Feb 22 2018 17:18:10.789Z DEBUG [ END ] op=442.473 [vic/lib/portlayer/exec.Commit:34] [216.823085ms] 074b7ed656e57633397df644b879ef4ca317f79a1c907644d663d687854c0326
```

Pass - portlayer (example from a passing run):
```
Feb 21 2018 22:48:16.967Z DEBUG [ END ] op=296.887 [vic/lib/portlayer/network.(*Context).UnbindContainer:961] [61.62µs] UnbindContainer
Feb 21 2018 22:48:16.967Z DEBUG [BEGIN] op=296.887 [vic/lib/portlayer/exec.Commit:34] f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d
Feb 21 2018 22:48:16.967Z INFO  op=296.887: Reconfigure: attempting update to f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d with change version "2018-02-21T22:48:11.203752Z" (poweredOff)
Feb 21 2018 22:48:16.968Z DEBUG [BEGIN] op=296.888 [vic/lib/portlayer/exec.(*containerBase).updates:119] f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d
Feb 21 2018 22:48:16.968Z DEBUG op=296.888: Update: for f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d, refreshing from change version 2018-02-21T22:48:11.203752Z
Feb 21 2018 22:48:16.968Z DEBUG [BEGIN] op=296.888 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:519] VM(VirtualMachine:10532) Properties([config runtime])
Feb 21 2018 22:48:16.968Z DEBUG op=296.888: properties: [config runtime summary.runtime.connectionState]
Feb 21 2018 22:48:16.983Z DEBUG [ END ] op=296.888 [vic/pkg/vsphere/vm.(*VirtualMachine).Properties:519] [15.091843ms] VM(VirtualMachine:10532) Properties([config runtime])
Feb 21 2018 22:48:16.983Z DEBUG op=296.888: Update: for f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d, change version 2018-02-21T22:48:11.203752Z, extraconfig id: f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d
Feb 21 2018 22:48:16.983Z DEBUG [ END ] op=296.888 [vic/lib/portlayer/exec.(*containerBase).updates:119] [15.652628ms] f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d
Feb 21 2018 22:48:16.983Z DEBUG [ END ] op=296.888 [vic/lib/apiservers/portlayer/restapi/handlers.(*ContainersHandlersImpl).GetContainerInfoHandler:276] [19.360418ms] f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d
Feb 21 2018 22:48:17.105Z INFO  op=296.887: Reconfigure: committed update to f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d with change version: 2018-02-21T22:48:11.203752Z
Feb 21 2018 22:48:17.105Z INFO  op=296.887: Attempting to perform a guest reconfigure operation on (f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d)
Feb 21 2018 22:48:17.105Z DEBUG [BEGIN]  [vic/pkg/retry.DoWithConfig:73]
Feb 21 2018 22:48:17.105Z DEBUG [ END ]  [vic/pkg/retry.DoWithConfig:73] [6.108µs] 
Feb 21 2018 22:48:17.105Z DEBUG op=296.887: Update: updated change version from handle: 2018-02-21T22:48:11.203752Z
Feb 21 2018 22:48:17.105Z DEBUG [ END ] op=296.887 [vic/lib/portlayer/exec.Commit:34] [137.494467ms] f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d
```

From the looks of it, the portlayer output is generally the same, so it looks like the personality either missed a signal from the portlayer or got hung up somewhere else.

Mainly it looks like we missed this in the failing case:
```
Feb 21 2018 22:48:16.937Z DEBUG [BEGIN]  [vic/lib/apiservers/engine/backends.DockerEventPublisher.PublishEvent:220] Event Monitor received eventID(296.886) for container(f3e551c887af) - PoweredOff
Feb 21 2018 22:48:16.937Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.DockerEventPublisher.PublishEvent:220] [33.207µs] Event Monitor received eventID(296.886) for container(f3e551c887af) - PoweredOff
Feb 21 2018 22:48:16.937Z DEBUG [BEGIN]  [vic/lib/apiservers/engine/backends.(*ContainerProxy).exitCode:879]
Feb 21 2018 22:48:16.984Z DEBUG [ END ]  [vic/lib/apiservers/engine/backends.(*ContainerProxy).exitCode:879] [46.107997ms] 
Feb 21 2018 22:48:16.984Z INFO  Sending die event for container(f3e551c887af) with exitCode[0] - eventID(296.886)
Feb 21 2018 22:48:16.984Z DEBUG UnmapPorts for f3e551c887af4035e355b8900b9f805925f3fb0feb90992ffcf8838674a29e5d: map[]
Feb 21 2018 22:48:16.988Z DEBUG Client context cancelled, stop sending events
```
specifically -the exitCode, which presumably means that we never return an exitcode to the client...

[container-logs.zip](https://github.com/vmware/vic/files/1749435/container-logs.zip)

### PR DESCRIPTION
**Pull request by hickeng**
Should not be iterating using `range` on an array that is being
modified. 

```
[skip unit]
[specific ci=*Network*]
```

Fixes #7365

### CODE REVIEW

File: lib/portlayer/network/context.go [hunk 1]
```diff
@@ -933,10 +933,14 @@ func (c *Context) RemoveIDFromScopes(op trace.Operation, id string) ([]*Endpoint
 		return nil, nil // not bound
 	}
 
+	// take a copy of the array we'll be modifying as we iterate
+	tmpEndpoints := con.endpoints
```
Comment (vburenin) [inline lib/portlayer/network/context.go]: You are not making a copy of a content if it is a slice. That copy for slices only includes slice metadata.

Comment (hickeng) [reply lib/portlayer/network/context.go]: Thanks for the sanity check - should know better than to make a PR from hurried placeholder code but wanted it up as reference in case someone was able to pick it up while I was in the air. Appreciate the weekend review!

File: lib/portlayer/network/context.go [hunk 2]
```diff
@@ -942,14 +942,17 @@ func (c *Context) RemoveIDFromScopes(op trace.Operation, id string) ([]*Endpoint
...
-			return nil, err
-		}
-
 		aliases = append(aliases, c.populateAliases(con, s, e)...)
 		endpoints = append(endpoints, e)
 	}
 
+	// remove the container from all bound scopes
+	for _, ne := range endpoints {
+		if err := ne.scope.RemoveContainer(con); err != nil {
```
Comment (vburenin) [inline lib/portlayer/network/context.go]: I guess it would be good to add a comment here that ne.scope.RemoveContainer modified con.endpoints
