### PR TITLE
[specific ci=Group6-VIC-Machine] Show cert path in vic-machine inspect output

### LINKED ISSUE #4490: Update vic-machine inspect with DOCKER_CERT_PATH for tlsverify configurations
**Story**
As a user of vic-machine I expect `vic-machine inspect` to provide the information I require to access a VCH

**Details**
Inspect is not returning a certificate path - this is because it's potentially hard to do so without some foreknowledge - however it's also not warning about the fact that necessary data is missing.
With the actual output you cannot connect to the docker API as you do not have the client cert.

Actual:
```
vagrant@devbox:~/vic$ vic-inspect
Mar 31 2017 14:21:10.319Z INFO  ### Inspecting VCH ####
Mar 31 2017 14:21:10.517Z INFO  Validating target
Mar 31 2017 14:21:10.675Z WARN  Disabling ha-host hostd.log collection (ServerFaultCode: Cannot complete the operation due to an incorrect request to the server.)
Mar 31 2017 14:21:10.676Z INFO
Mar 31 2017 14:21:10.676Z INFO  VCH ID: VirtualMachine:874
Mar 31 2017 14:21:10.691Z INFO
Mar 31 2017 14:21:10.691Z INFO  Installer version: v0.9.0-0-63b1d99
Mar 31 2017 14:21:10.692Z INFO  VCH version: v0.9.0-0-63b1d99
Mar 31 2017 14:21:10.692Z INFO
Mar 31 2017 14:21:10.692Z INFO  VCH upgrade status:
Mar 31 2017 14:21:10.692Z INFO  Installer has same version as VCH
Mar 31 2017 14:21:10.692Z INFO  No upgrade available with this installer version
Mar 31 2017 14:21:10.812Z INFO
Mar 31 2017 14:21:10.814Z INFO  VCH Admin Portal:
Mar 31 2017 14:21:10.814Z INFO  https://192.168.78.127:2378
Mar 31 2017 14:21:10.814Z INFO
Mar 31 2017 14:21:10.814Z INFO  Published ports can be reached at:
Mar 31 2017 14:21:10.814Z INFO  192.168.78.127
Mar 31 2017 14:21:10.825Z INFO
Mar 31 2017 14:21:10.825Z INFO  Docker environment variables:
Mar 31 2017 14:21:10.826Z INFO  DOCKER_TLS_VERIFY=1 DOCKER_HOST=192.168.78.127:2376
Mar 31 2017 14:21:10.826Z INFO
Mar 31 2017 14:21:10.826Z INFO  Connect to docker:
Mar 31 2017 14:21:10.826Z INFO  docker -H 192.168.78.127:2376 --tlsverify  info
Mar 31 2017 14:21:10.826Z INFO  Completed successfully
```

Expected (cert path is specific to the actual environment):
```
vagrant@devbox:~/vic$ vic-inspect
Mar 31 2017 14:21:10.319Z INFO  ### Inspecting VCH ####
Mar 31 2017 14:21:10.517Z INFO  Validating target
Mar 31 2017 14:21:10.676Z INFO
Mar 31 2017 14:21:10.676Z INFO  VCH ID: VirtualMachine:874
Mar 31 2017 14:21:10.691Z INFO
Mar 31 2017 14:21:10.691Z INFO  Installer version: v0.9.0-0-63b1d99
Mar 31 2017 14:21:10.692Z INFO  VCH version: v0.9.0-0-63b1d99
Mar 31 2017 14:21:10.692Z INFO
Mar 31 2017 14:21:10.692Z INFO  VCH upgrade status:
Mar 31 2017 14:21:10.692Z INFO  Installer has same version as VCH
Mar 31 2017 14:21:10.692Z INFO  No upgrade available with this installer version
Mar 31 2017 14:21:10.812Z INFO
Mar 31 2017 14:21:10.814Z INFO  VCH Admin Portal:
Mar 31 2017 14:21:10.814Z INFO  https://192.168.78.127:2378
Mar 31 2017 14:21:10.814Z INFO
Mar 31 2017 14:21:10.814Z INFO  Published ports can be reached at:
Mar 31 2017 14:21:10.814Z INFO  192.168.78.127
Mar 31 2017 14:21:10.825Z INFO
Mar 31 2017 14:21:10.825Z INFO  Docker environment variables:
Mar 31 2017 14:21:10.826Z INFO  DOCKER_TLS_VERIFY=1 DOCKER_HOST=192.168.78.127:2376 DOCKER_CERT_PATH=~/localtls/
Mar 31 2017 14:21:10.826Z INFO
Mar 31 2017 14:21:10.826Z INFO  Connect to docker:
Mar 31 2017 14:21:10.826Z INFO  docker -H 192.168.78.127:2376 --tlsverify  info
Mar 31 2017 14:21:10.826Z INFO  Completed successfully
```

**Acceptance**
- [ ] check the following locations for suitable certs
  - $PWD
  - directory named for the target VCH in the vic-machine location
  - $HOME/.docker
- [ ] do not display the .docker cert path (or any path) if the ccerts found in it are not appropriate 
- [ ] if no valid certificate can be found, then add `DOCKER_CERT_PATH=${DOCKER_CERT_PATH:?certificate path must be provided in environment, or certificates specified individually via CLI arguments}`

### PR DESCRIPTION
**Pull request by anchal-agrawal**
Fixes #4490
User doc impact: https://github.com/vmware/vic-product/issues/211

This change furnishes a valid `DOCKER_CERT_PATH` (if found) for a VCH with tls-verify.

`vic-machine inspect`:

```
...
May  4 2017 19:38:57.873Z INFO  cert-path not supplied - checking in current directory, VCH-0-6641/ and /root/.docker/
...
May  4 2017 19:38:57.887Z INFO  Docker environment variables:
May  4 2017 19:38:57.887Z INFO  DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=/drone/src/github.com/vmware/vic/VCH-0-6641 DOCKER_HOST=<vch>:2376
May  4 2017 19:38:57.887Z INFO  
May  4 2017 19:38:57.887Z INFO  Connect to docker:
May  4 2017 19:38:57.887Z INFO  docker -H <vch>:2376 --tlsverify info
```

`vic-machine inspect --cert-path=foo`, with no valid certs in `$PWD/foo`:

```
...
May  4 2017 19:38:57.873Z INFO  cert-path supplied - only checking in foo/ for certs
...
May  4 2017 19:39:12.887Z WARN  Unable to find valid client certs
May  4 2017 19:39:12.887Z WARN  DOCKER_CERT_PATH must be provided in environment or certificates specified individually via CLI arguments
May  4 2017 19:38:57.887Z INFO 
May  4 2017 19:38:57.887Z INFO  Docker environment variables:
May  4 2017 19:38:57.887Z INFO  DOCKER_TLS_VERIFY=1 DOCKER_HOST=<vch>:2376
May  4 2017 19:38:57.887Z INFO  
May  4 2017 19:38:57.887Z INFO  Connect to docker:
May  4 2017 19:38:57.887Z INFO  docker -H <vch>:2376 --tlsverify info
```

### CODE REVIEW

File: lib/install/management/inspect.go [hunk 1]
```diff
@@ -89,10 +102,81 @@ func (d *Dispatcher) InspectVCH(vch *vm.VirtualMachine, conf *config.VirtualCont
...
+			log.Infof("cert-path supplied - only checking in %s/ for certs", certPath)
+			possibleCertPaths = append(possibleCertPaths, certPath)
+		} else {
+			possibleCertPaths = append(possibleCertPaths, conf.Name, ".")
+			logMsg := fmt.Sprintf("cert-path not supplied - checking in current directory, %s/", conf.Name)
+
+			dockerConfPath := ""
+			user, err := user.Current()
+			if err == nil {
+				dockerConfPath = fmt.Sprintf("%s/%s", user.HomeDir, ".docker")
```
Comment (dougm) [inline lib/install/management/inspect.go]: `filepath.Join` instead of Sprintf

File: lib/install/management/inspect.go [hunk 2]
```diff
@@ -89,10 +102,81 @@ func (d *Dispatcher) InspectVCH(vch *vm.VirtualMachine, conf *config.VirtualCont
...
+			if err = verifyClientCert(conf.CertificateAuthorities, possibleCertPaths[i]); err == nil {
+				certPath = possibleCertPaths[i]
+				break
+			} else {
+				log.Debugf("Unable to verify client cert in %s: %s", possibleCertPaths[i], err)
+			}
+		}
+	}
+
+	d.ShowVCH(conf, "", "", "", "", certPath)
```
Comment (dougm) [inline lib/install/management/inspect.go]: At some point we should change ShowVCH to take a single struct param instead of N string params.  Easier to read and maintain.

File: lib/install/management/inspect.go [hunk 3]
```diff
@@ -89,10 +102,81 @@ func (d *Dispatcher) InspectVCH(vch *vm.VirtualMachine, conf *config.VirtualCont
...
 	return nil
 }
 
+// verifyClientCert checks whether the input path has a client cert that's valid for the VCH.
+func verifyClientCert(ca []byte, path string) error {
+	var err error
+
+	certFile := fmt.Sprintf("%s/%s", path, ClientCert)
```
Comment (dougm) [inline lib/install/management/inspect.go]: filepath.Join

File: cmd/vic-machine/debug/debug.go [hunk 4]
```diff
@@ -192,7 +192,7 @@ func (d *Debug) Run(clic *cli.Context) (err error) {
 	}
 
 	// display the VCH endpoints again for convenience
-	if err = executor.InspectVCH(vch, vchConfig); err != nil {
+	if err = executor.InspectVCH(vch, vchConfig, ""); err != nil {
```
Comment (emlin) [inline cmd/vic-machine/debug/debug.go]: I know it might be out of the scope of this issue, but it would be better to show correct connection info to user anytime. 😄

Comment (emlin) [inline cmd/vic-machine/debug/debug.go]: okay, never mind, you did it

File: lib/install/management/inspect.go [hunk 5]
```diff
@@ -89,10 +102,81 @@ func (d *Dispatcher) InspectVCH(vch *vm.VirtualMachine, conf *config.VirtualCont
...
+
+		// Check if a valid client cert exists in one of possibleCertPaths
+		certPath = ""
+		for i := range possibleCertPaths {
+			if err = verifyClientCert(conf.CertificateAuthorities, possibleCertPaths[i]); err == nil {
+				certPath = possibleCertPaths[i]
+				break
+			} else {
+				log.Debugf("Unable to verify client cert in %s: %s", possibleCertPaths[i], err)
+			}
```
Comment (emlin) [inline lib/install/management/inspect.go]:
```
if err = ...; err != nil {
  log.Debugf("Unable to verify client cert in %s: %s", possibleCertPaths[i], err)
  continue
}
certPath = possibleCertPaths[i]
break
}
```

Comment (anchal-agrawal) [inline lib/install/management/inspect.go]: I feel that `continue` and `break` (specially when used together, like the above snippet) always add a layer of complexity while reading code. I prefer the current approach. Thoughts?

File: lib/install/management/inspect.go [hunk 6]
```diff
@@ -89,10 +102,81 @@ func (d *Dispatcher) InspectVCH(vch *vm.VirtualMachine, conf *config.VirtualCont
...
+		}
+	}
+
+	d.ShowVCH(conf, "", "", "", "", certPath)
 	return nil
 }
 
+// verifyClientCert checks whether the input path has a client cert that's valid for the VCH.
+func verifyClientCert(ca []byte, path string) error {
```
Comment (emlin) [inline lib/install/management/inspect.go]: hmm.. we already have similar code in cmd create.go for certificate checking, and that did cname check as well.
In appliance.go, we have another piece of code using certificate to actually connect remote docker service.
I think it would be ideal if refactor create.go and here to use same method, and add a piece of code to connect vch in inspect, with same code used in appliance.go.

File: tests/test-cases/Group6-VIC-Machine/6-09-Inspect.robot [hunk 7]
```diff
@@ -0,0 +1,61 @@
...
+    ${output}=  Run  bin/vic-machine-linux create --name=%{VCH-NAME} --target="%{TEST_USERNAME}:%{TEST_PASSWORD}@%{TEST_URL}" --thumbprint=%{TEST_THUMBPRINT} --image-store=%{TEST_DATASTORE} --bridge-network=%{BRIDGE_NETWORK} --public-network=%{PUBLIC_NETWORK} --no-tlsverify
+    Should Contain  ${output}  Installer completed successfully
+    Get Docker Params  ${output}  ${true}
+
+    ${output}=  Run  bin/vic-machine-linux inspect --name=%{VCH-NAME} --target="%{TEST_USERNAME}:%{TEST_PASSWORD}@%{TEST_URL}" --thumbprint=%{TEST_THUMBPRINT}
+    Should Not Contain  ${output}  DOCKER_CERT_PATH=${EXECDIR}/%{VCH-NAME}
+    Should Not Contain  ${output}  Unable to find valid client certs
+    Should Not Contain  ${output}  DOCKER_CERT_PATH must be provided in environment or certificates specified individually via CLI arguments
+
+    Cleanup VIC Appliance On Test Server
```
Comment (emlin) [inline tests/test-cases/Group6-VIC-Machine/6-09-Inspect.robot]: 👍

File: lib/install/management/inspect.go (hunk 6 above)
Comment (anchal-agrawal) [inline lib/install/management/inspect.go]: Refactored `VerifyClientCert` to make it usable during client cert validation in `cmd/vic-machine/create/create.go` - commit e9f6c7e.

File: lib/install/management/inspect.go [hunk 8]
```diff
@@ -140,41 +149,31 @@ func (d *Dispatcher) InspectVCH(vch *vm.VirtualMachine, conf *config.VirtualCont
 	return nil
 }
 
-// verifyClientCert checks whether the input path has a client cert that's valid for the VCH.
-func verifyClientCert(ca []byte, path string) error {
+// VerifyClientCert verifies the loaded client cert keypair against the input CA and
+// returns the certificate on success.
+func VerifyClientCert(ca []byte, ckp *certificate.KeyPair) (*tls.Certificate, error) {
```
Comment (emlin) [inline lib/install/management/inspect.go]: This is nice. 👍 
Ideally, all verification should happen in cmd package or lib/install/validate. Looks like move it to validate package will be better

File: lib/install/management/inspect.go (hunk 5 above)
Comment (emlin) [inline lib/install/management/inspect.go]: My suggestion will reduce nested if/else in later code, feels like that will be more readable. nitpicking anyway

File: lib/install/management/inspect.go (hunk 8 above)
Comment (anchal-agrawal) [inline lib/install/management/inspect.go]: Based on our offline discussion, this func is now generic enough to belong in `pkg/certificate`.

File: lib/install/management/inspect.go (hunk 5 above)
Comment (anchal-agrawal) [inline lib/install/management/inspect.go]: Sounds good! I made the change.

File: cmd/vic-machine/create/create.go [hunk 9]
```diff
@@ -1088,26 +1080,15 @@ func (c *Create) loadCertificates() ([]byte, *certificate.KeyPair, error) {
...
-			KeyUsages: []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth},
-		}
-
-		_, err = clientCert.Leaf.Verify(opts)
+		clientCert, err := certificate.VerifyClientCert(certs, cpair)
 		if err != nil {
-			log.Warnf("Client certificate in certificate path does not validate with provided CA - continuing without client certificate")
+			switch err.(type) {
+			case certificate.CertParseError, certificate.CreateCAPoolError:
+				log.Debugf(err.Error())
```
Comment (gigawhitlocks) [inline cmd/vic-machine/create/create.go]: What happens here from the user's perspective? Is this an error that should be suppressed? I assume in this case we generate certs or something so there's a reason we're not displaying this error to the user outside of debug mode?

File: cmd/vic-machine/inspect/inspect.go [hunk 10]
```diff
@@ -45,7 +47,7 @@ func NewInspect() *Inspect {
 	return d
 }
 
-// Flags return all cli flags for inspect
+// Flags returns all cli flags for inspect
```
Comment (gigawhitlocks) [inline cmd/vic-machine/inspect/inspect.go]: :+1:

File: lib/install/management/inspect.go [hunk 11]
```diff
@@ -89,7 +91,50 @@ func (d *Dispatcher) InspectVCH(vch *vm.VirtualMachine, conf *config.VirtualCont
 		log.Debugf("No host certificates provided")
 	}
 
-	d.ShowVCH(conf, "", "", "", "", "")
+	// Check for valid client cert for a tls-verify configuration
+	if len(conf.CertificateAuthorities) > 0 {
```
Comment (gigawhitlocks) [inline lib/install/management/inspect.go]: Could we break this out into a helper method?

File: cmd/vic-machine/create/create.go (hunk 9 above)
Comment (anchal-agrawal) [inline cmd/vic-machine/create/create.go]: vic-machine's logger prints to stdout, so these will show up in `vic-machine inspect` output depending on the value of `--debug`.

Comment (anchal-agrawal) [inline cmd/vic-machine/create/create.go]: Regarding whether we should elevate `log.Debugf` to `log.Warnf` or higher - this logic comes from e09b387bea05b062f7fb2108f94586b3d798dfef.

File: lib/install/management/inspect.go (hunk 11 above)
Comment (anchal-agrawal) [inline lib/install/management/inspect.go]: Done. Also added a unit test for the helper.

File: tests/test-cases/Group6-VIC-Machine/6-09-Inspect.md [hunk 12]
```diff
@@ -1,18 +1,30 @@
...
+2. Inspect the VCH without specifying --cert-path
+3. Inspect the VCH with a valid --cert-path
+4. Inspect the VCH with an invalid --cert-path
+5. Create a VCH with --no-tls
+6. Inspect the VCH without specifying --cert-path
+7. Create a VCH with --no-tlsverify
+8. Inspect the VCH without specifying --cert-path
+
+# Expected Outcome:
+* All steps should complete successfully
```
Comment (mhagen-vmware) [inline tests/test-cases/Group6-VIC-Machine/6-09-Inspect.md]: no, most are error cases.
