### PR TITLE
Fixes the Volume Create integration tests

### LINKED ISSUE #1564: Volume create with a bad driver specified results in success
Actual behavior:
Running command 'docker -H 192.168.254.168:2376 --tls volume create -d fakeDriver --name=test2'
${rc} = 0 	
${output} = test2

Expected behavior:
Error looking up volume plugin fakeDriver: plugin not found

### PR DESCRIPTION
**Pull request by matthewavery**
Fixes #1564 #1562 #1563 #1561 

Handles bad drivers rather than just ignoring the driver name field. We now reject anything that isn't `local` or `vsphere`. 

This PR will also clear all the problems that were inherent to the `Volume Create` use path. There are now much more friendly error messages. and The tests check disk sizes on successful mount. Tests have been run many many times locally to ensure that everything appears to work well on both VC and ESX. Once a VSAN testbed is available these will be run against those as well.

### CODE REVIEW

**Comment by anchal-agrawal** [comment]
LGTM 🐑 🇮🇹

File: lib/apiservers/engine/backends/volume.go [hunk 1]
```diff
@@ -234,7 +242,7 @@ func translateInputsToPortlayerRequestModel(name, driverName string, opts, label
 	model.Metadata = make(map[string]string)
 	model.Metadata[dockerMetadataModelKey] = metadata
 	if err := validateDriverArgs(opts, model); err != nil {
-		return nil, err
+		return nil, fmt.Errorf("Bad Driver Arg: %s", err)
```
Comment (hickeng) [inline lib/apiservers/engine/backends/volume.go]: Is this the message docker returns when an unknown driver is provided?

Comment (matthewavery) [inline lib/apiservers/engine/backends/volume.go]: I do no think that it handles the driver args at all. Since those args are specific to the plugin itself. I am not sure what docker returns to be honest. since their `local` default driver does not have any driver args that I am aware off.

Comment (matthewavery) [inline lib/apiservers/engine/backends/volume.go]: When you look at the docker code for their volume plugin handling they return the raw error codes from the actual VolumeDriver calls. for example: https://github.com/docker/docker/blob/62215920871b8d15a6ffe538baac5abe2b715409/volume/local/local.go#L153

That is the local driver returning filesystem errors. and that gets passed through this section : https://github.com/docker/docker/blob/62215920871b8d15a6ffe538baac5abe2b715409/volume/drivers/proxy.go#L27

Comment (matthewavery) [inline lib/apiservers/engine/backends/volume.go]: Should we potentially clean things up? right now an invalid capacity will yield the message `Bad driver arg: Invalid capacity: HelloWorld` if you passed in `--opt Capactiy=HelloWorld` on the create call.

Comment (matthewavery) [inline lib/apiservers/engine/backends/volume.go]: e.g. `Bad Driver Arg: Invalid Capacity: HelloWorld` for a `--opt Capacity=HelloWorld`

File: lib/apiservers/portlayer/restapi/handlers/storage_handlers.go [hunk 2]
```diff
@@ -288,6 +287,14 @@ func (handler *StorageHandlersImpl) CreateVolume(params storage.CreateVolumePara
 	volume, err := storageVolumeLayer.VolumeCreate(context.TODO(), params.VolumeRequest.Name, storeURL, capacity*1024, byteMap)
 	if err != nil {
 		log.Errorf("storagehandler: VolumeCreate error: %s", err)
+
+		if err == os.ErrNotExist {
```
Comment (hmahmood) [inline lib/apiservers/portlayer/restapi/handlers/storage_handlers.go]: Use [`os.IsNotExist`](https://golang.org/pkg/os/#IsNotExist)

File: tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot [hunk 3]
```diff
@@ -8,86 +8,62 @@ Suite Teardown  Cleanup VIC Appliance On Test Server
...
-    #${rc}  ${output}=  Run And Return Rc And Output  docker ${params} volume create --name=test4 --opt Capacity=100
-    #Should Be Equal As Integers  ${rc}  0
-    #Should Be Equal As Strings  ${output}  test4
-    #${rc}  ${output}=  Run And Return Rc And Output  govc datastore.ls -json=true test/VIC/volumes/test4
-    #Should Be Equal As Integers  ${rc}  0
-    #Should Contain  ${output}  "FileSize":100
+    ${rc}  ${output}=  Run And Return Rc And Output  docker ${params} volume create --name=test4 --opt Capacity=100000
+    Should Be Equal As Integers  ${rc}  0
+    Should Be Equal As Strings  ${output}  test4
+    ${disk-size}=  Run  docker ${params} logs $(docker ${params} start $(docker ${params} create -v ${output}:/mydata busybox /bin/df -Ph) && sleep 10) | grep by-label | awk '{print $2}'
```
Comment (matthewavery) [inline tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot]: Credit for this goes to Ian Whitlock 👍

File: lib/apiservers/engine/backends/volume.go [hunk 4]
```diff
@@ -103,11 +108,12 @@ func (v *Volume) VolumeCreate(name, driverName string, opts, labels map[string]s
 	}
 
 	// TODO: support having another driver besides vsphere.
-	// assign the values of the model to be passed to the portlayer handler
+	// assign the values of the model to be paassed to the portlayer handler
```
Comment (hmahmood) [inline lib/apiservers/engine/backends/volume.go]: s/paassed/passed

File: lib/apiservers/engine/backends/volume.go [hunk 5]
```diff
@@ -117,6 +123,10 @@ func (v *Volume) VolumeCreate(name, driverName string, opts, labels map[string]s
 	if err != nil {
 		switch err := err.(type) {
 
+		case *storage.CreateVolumeConflict:
+			return result, derr.NewBadRequestError(fmt.Errorf("A volume named %s already exists. Choose a different volume name.", model.Name))
```
Comment (hmahmood) [inline lib/apiservers/engine/backends/volume.go]: According to the [docker volume create docs](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#/create-a-volume), only `201` and `500` are valid return status codes.

File: lib/apiservers/engine/backends/volume.go [hunk 6]
```diff
@@ -211,15 +221,44 @@ func validateDriverArgs(args map[string]string, model *models.VolumeRequest) err
 		return nil
 	}
 
+	//check if it is just a numerical value
+	validator, _ := regexp.Compile("^[0-9][0-9]*$") //note this is a global line match. Find will return 1 or no matches.
```
Comment (hmahmood) [inline lib/apiservers/engine/backends/volume.go]: Why do you need the regex? The call to `ParseInt` does this for you.

File: lib/apiservers/engine/backends/volume.go [hunk 7]
```diff
@@ -211,15 +221,44 @@ func validateDriverArgs(args map[string]string, model *models.VolumeRequest) err
...
+		return nil
+	}
+
 	capacity, err := units.FromHumanSize(capstr)
 	if err != nil {
 		return err
 	}
+
+	if capacity < 1 {
+		return fmt.Errorf("Capacity value too large: %s", capstr)
```
Comment (hmahmood) [inline lib/apiservers/engine/backends/volume.go]: Don't understand this error. `capacity < 1` is too large?

File: lib/apiservers/engine/backends/volume.go (hunk 6 above)
Comment (matthewavery) [inline lib/apiservers/engine/backends/volume.go]: I suppose I can just try and parse the int. `go-units` mysteriously returns 0 for a value without units. which is why that check is there to begin with.

File: lib/apiservers/engine/backends/volume.go [hunk 8]
```diff
@@ -211,15 +221,44 @@ func validateDriverArgs(args map[string]string, model *models.VolumeRequest) err
...
 
 func translateInputsToPortlayerRequestModel(name, driverName string, opts, labels map[string]string) (*models.VolumeRequest, error) {
+	defaultDriver := driverName == "local"
+	vsphereDriver := driverName == "vsphere"
+
+	if !defaultDriver && !vsphereDriver {
+		return nil, fmt.Errorf("Error looking up volume plugin %s: plugin not found", driverName)
+	}
+
+	if !VolumeNameRegex.Match([]byte(name)) && name != "" {
```
Comment (hmahmood) [inline lib/apiservers/engine/backends/volume.go]: Should this be reversed, i.e. `name != ""` should be first?

File: lib/apiservers/engine/backends/volume.go [hunk 9]
```diff
@@ -37,6 +39,9 @@ const (
 	dockerMetadataModelKey string = "DockerMetaData"
 )
 
+//Validation pattern for Volume Names
+var VolumeNameRegex = regexp.MustCompile("^[a-zA-Z0-9][a-zA-Z0-9_.-]*$")
```
Comment (hmahmood) [inline lib/apiservers/engine/backends/volume.go]: Does this need to be exported from the package? Only export it if needed.

File: lib/apiservers/portlayer/restapi/handlers/storage_handlers.go [hunk 10]
```diff
@@ -287,7 +286,22 @@ func (handler *StorageHandlersImpl) CreateVolume(params storage.CreateVolumePara
 
 	volume, err := storageVolumeLayer.VolumeCreate(context.TODO(), params.VolumeRequest.Name, storeURL, capacity*1024, byteMap)
 	if err != nil {
-		log.Errorf("storagehandler: VolumeCreate error: %s", err)
+		log.Errorf("storagehandler: VolumeCreate error: %#v", err)
+
+		if os.IsExist(err) {
+			return storage.NewCreateVolumeConflict().WithPayload(&models.Error{
+				Code:    swag.Int64(http.StatusNotFound),
```
Comment (hmahmood) [inline lib/apiservers/portlayer/restapi/handlers/storage_handlers.go]: `NewVolumeConflict()` would set a `409` on the http response, yet you have `404` set in the body of the error code?

File: lib/portlayer/storage/vsphere/volume.go [hunk 11]
```diff
@@ -248,3 +248,23 @@ func (v *VolumeStore) VolumesList(ctx context.Context) ([]*storage.Volume, error
 
 	return volumes, nil
 }
+
+//Custom Error Types
+
+// VolumeStoreNotFoundError : custom error type for when we fail to find a target volume store
+type VolumeStoreNotFoundError struct {
```
Comment (hmahmood) [inline lib/portlayer/storage/vsphere/volume.go]: See https://github.com/golang/go/wiki/Errors#naming for naming error types.

File: lib/apiservers/engine/backends/volume.go [hunk 12]
```diff
@@ -211,15 +221,42 @@ func validateDriverArgs(args map[string]string, model *models.VolumeRequest) err
 		return nil
 	}
 
-	capacity, err := units.FromHumanSize(capstr)
+	//check if it is just a numerical value
+	capacity, err := strconv.ParseInt(capstr, 10, 64)
```
Comment (hmahmood) [inline lib/apiservers/engine/backends/volume.go]: Would `FromHumanSize` below take care of this case where `capstr` is a number?

Comment (hmahmood) [inline lib/apiservers/engine/backends/volume.go]: I guess you already answered that one. Nevermind.

File: tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot [hunk 13]
```diff
@@ -8,86 +8,62 @@ Suite Teardown  Cleanup VIC Appliance On Test Server
...
+    Should Be Equal As Strings  ${disk-size}  975.9M
 
 Docker volume create already named volume
-    ${status}=  Get State Of Github Issue  1562
-    Run Keyword If  '${status}' == 'closed'  Fail  Test 1-19-Docker-Volume-Create.robot needs to be updated now that Issue #1562 has been resolved
-    Log  Issue \#1562 is blocking implementation  WARN
-    #${rc}  ${output}=  Run And Return Rc And Output  docker ${params} volume create --name=test
-    #Should Be Equal As Integers  ${rc}  1
-    #Should Contain  ${output}  Error response from daemon: A volume named test already exists. Choose a different volume name.
+    ${rc}  ${output}=  Run And Return Rc And Output  docker ${params} volume create --name=test
```
Comment (mhagen-vmware) [inline tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot]: This test should really be independent of the other tests in case they fail for some reason. Can you do a volume create --name=testAlready followed by a volume create --name=testAlready?

File: tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot [hunk 14]
```diff
@@ -8,86 +8,62 @@ Suite Teardown  Cleanup VIC Appliance On Test Server
 Simple docker volume create
     ${rc}  ${output}=  Run And Return Rc And Output  docker ${params} volume create
     Should Be Equal As Integers  ${rc}  0
+    ${disk-size}=  Run  docker ${params} logs $(docker ${params} start $(docker ${params} create -v ${output}:/mydata busybox /bin/df -Ph) && sleep 10) | grep by-label | awk '{print $2}' 
+    Should Be Equal As Strings  ${disk-size}  975.9M
```
Comment (mhagen-vmware) [inline tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot]: awesome! nicely done

File: tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot (hunk 13 above)
Comment (matthewavery) [inline tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot]: yeah we can modify that one.

File: tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot [hunk 15]
```diff
@@ -8,86 +8,62 @@ Suite Teardown  Cleanup VIC Appliance On Test Server
...
 Docker volume create with bad volumestore
-    ${status}=  Get State Of Github Issue  1561
-    Run Keyword If  '${status}' == 'closed'  Fail  Test 1-19-Docker-Volume-Create.robot needs to be updated now that Issue #1561 has been resolved
-    Log  Issue \#1561 is blocking implementation  WARN
-    #${rc}  ${output}=  Run And Return Rc And Output  docker ${params} volume create --name=test3 --opt VolumeStore=fakeStore
-    #Should Be Equal As Integers  ${rc}  1
-    #Should Contain  ${output}  Error looking up volume store fakeStore: datastore not found
+    ${rc}  ${output}=  Run And Return Rc And Output  docker ${params} volume create --name=test3 --opt VolumeStore=fakeStore
+    Should Be Equal As Integers  ${rc}  1
+    Should Contain  ${output}  No volume store named (fakeStore) exists
```
Comment (mhagen-vmware) [inline tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot]: That is kinda awkward, can we do better here? There was in fact a volume store named... it just doesn't exist.

File: lib/apiservers/engine/backends/volume.go (hunk 7 above)
Comment (matthewavery) [inline lib/apiservers/engine/backends/volume.go]: It indicates and overflow from `FromHumanSize` they do not return an error with it as far as I can tell... it actually will return a negative number. I may need to do an additional error check.

File: tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot [hunk 16]
```diff
@@ -8,86 +8,62 @@ Suite Teardown  Cleanup VIC Appliance On Test Server
...
 Docker volume create with zero capacity
-    ${status}=  Get State Of Github Issue  1562
-    Run Keyword If  '${status}' == 'closed'  Fail  Test 1-19-Docker-Volume-Create.robot needs to be updated now that Issue #1562 has been resolved
-    Log  Issue \#1562 is blocking implementation  WARN
-    #${rc}  ${output}=  Run And Return Rc And Output  docker ${params} volume create --name=test5 --opt Capacity=0
-    #Should Be Equal As Integers  ${rc}  1
-    #Should Contain  ${output}  Error
+    ${rc}  ${output}=  Run And Return Rc And Output  docker ${params} volume create --name=test5 --opt Capacity=0
+    Should Be Equal As Integers  ${rc}  1
+    Should Contain  ${output}  Error
```
Comment (mhagen-vmware) [inline tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot]: can we put the actual error in here? is it reasonable?

File: tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot [hunk 17]
```diff
@@ -8,86 +8,62 @@ Suite Teardown  Cleanup VIC Appliance On Test Server
...
 Docker volume create with negative one capacity
-    ${status}=  Get State Of Github Issue  1562
-    Run Keyword If  '${status}' == 'closed'  Fail  Test 1-19-Docker-Volume-Create.robot needs to be updated now that Issue #1562 has been resolved
-    Log  Issue \#1562 is blocking implementation  WARN
-    #${rc}  ${output}=  Run And Return Rc And Output  docker ${params} volume create --name=test6 --opt Capacity=-1
-    #Should Be Equal As Integers  ${rc}  1
-    #Should Contain  ${output}  Error    
+    ${rc}  ${output}=  Run And Return Rc And Output  docker ${params} volume create --name=test6 --opt Capacity=-1
+    Should Be Equal As Integers  ${rc}  1
+    Should Contain  ${output}  Error
```
Comment (mhagen-vmware) [inline tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot]: can we put the actual error in here? is it reasonable?
 Add a line note

File: tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot [hunk 18]
```diff
@@ -8,86 +8,62 @@ Suite Teardown  Cleanup VIC Appliance On Test Server
...
 Docker volume create with capacity too big
-    ${status}=  Get State Of Github Issue  1562
-    Run Keyword If  '${status}' == 'closed'  Fail  Test 1-19-Docker-Volume-Create.robot needs to be updated now that Issue #1562 has been resolved
-    Log  Issue \#1562 is blocking implementation  WARN
-    #${rc}  ${output}=  Run And Return Rc And Output  docker ${params} volume create --name=test7 --opt Capacity=2147483647
-    #Should Be Equal As Integers  ${rc}  1
-    #Should Contain  ${output}  Error
+    ${rc}  ${output}=  Run And Return Rc And Output  docker ${params} volume create --name=test7 --opt Capacity=9223372036854775808
+    Should Be Equal As Integers  ${rc}  1
+    Should Contain  ${output}  Error
```
Comment (mhagen-vmware) [inline tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot]: can we put the actual error in here? is it reasonable?
 Add a line note

File: tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot [hunk 19]
```diff
@@ -8,86 +8,62 @@ Suite Teardown  Cleanup VIC Appliance On Test Server
...
 Docker volume create with capacity exceeding int size
-    ${status}=  Get State Of Github Issue  1562
-    Run Keyword If  '${status}' == 'closed'  Fail  Test 1-19-Docker-Volume-Create.robot needs to be updated now that Issue #1562 has been resolved
-    Log  Issue \#1562 is blocking implementation  WARN
-    #${rc}  ${output}=  Run And Return Rc And Output  docker ${params} volume create --name=test8 --opt Capacity=9999999999
-    #Should Be Equal As Integers  ${rc}  1
-    #Should Contain  ${output}  Error
+    ${rc}  ${output}=  Run And Return Rc And Output  docker ${params} volume create --name=test8 --opt Capacity=9999999999999999999
+    Should Be Equal As Integers  ${rc}  1
+    Should Contain  ${output}  Error
```
Comment (mhagen-vmware) [inline tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot]: can we put the actual error in here? is it reasonable?
 Add a line note

File: tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot (hunk 14 above)
Comment (matthewavery) [inline tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot]: Haha that was something that Ian put together and I just borrowed it and added some.

File: tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot (hunk 16 above)
Comment (matthewavery) [inline tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot]: I will take a look at the most recent logs. It should be reasonable. Should be an `invalid size` type error

File: lib/apiservers/engine/backends/volume.go (hunk 9 above)
Comment (matthewavery) [inline lib/apiservers/engine/backends/volume.go]: oh yeah, that should be private. My bad.

File: tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot (hunk 15 above)
Comment (matthewavery) [inline tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot]: That really sounds like a validator thing then. I misunderstood this test.

Comment (mhagen-vmware) [inline tests/test-cases/Group1-Docker-Commands/1-19-Docker-Volume-Create.robot]: nvm, I read that completely wrong.  This is good!

**Comment by mhagen-vmware** [comment]
LGTM

**Comment by hmahmood** [comment]
lgtm

**Comment by matthewavery** [comment]
♻️

**Comment by matthewavery** [comment]
♻️

File: lib/apiservers/engine/backends/volume.go (hunk 1 above)
Comment (matthewavery) [inline lib/apiservers/engine/backends/volume.go]: @hickeng I now see what your quetion was. No it is not. But we check for the driver sooner than this portion. There is an integration test that checks this. Though I can probably also add it to the unit tests that are there.
