### PR TITLE
[specific ci=Group6-VIC-Machine] Fix the outputted --cert-path

### LINKED ISSUE #4683: vic-machine output and generated env is wrong if --cert-path specified
If you run vic-machine with --cert-path and ask it to generate certificates into the path specified, it does that fine. However, the .env file it creates and the helpful output produced by vic-machine does not take the --cert-path into account and shows the default path.

Example:

```
vic-machine-linux create --tls-cname *.eng.vmware.com --cert-path=/certs --thumbprint=F2:97:19:09:64:0A:06:3C:67:57:F7:CB:B5:3A:21:50:30:46:A0:54 --name=dev-cert --target=10.118.69.238 --user=Administrator@vsphere.local --image-store=iSCSI-nas-2 --password='xxxxxxxx' --bridge-network=dev-bridge --public-network=ExternalNetwork --compute-resource=iSCSI --timeout 60s --volume-store=iSCSI-nas-2/dev:default --container-network=ExternalNetwork
```

The above cmd-line generates certs into the right place, but the instructions from VIC machine and the output of the env file are wrong:

```
Apr 11 2017 16:00:22.309Z INFO  Docker environment variables:
Apr 11 2017 16:00:22.309Z INFO  DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=/home/vagrant/vic/src/github.com/vmware/dev-release/vic/dev-cert DOCKER_HOST=office2-sfo2-dhcp335.eng.vmware.com:2376
Apr 11 2017 16:00:22.310Z INFO  
Apr 11 2017 16:00:22.310Z INFO  Environment saved in /certs/dev-cert.env

> cat /certs/dev-cert.env 
DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=/home/vagrant/vic/src/github.com/vmware/dev-release/vic/dev-cert DOCKER_HOST=office2-sfo2-dhcp335.eng.vmware.com:2376
```

### PR DESCRIPTION
**Pull request by gigawhitlocks**
Fixes #4683 

Also prevents destruction of provided path after --cert-path if files already exist there
Also causes the browser-friendly certificate to be generated in the right place when --cert-path is specified.

### CODE REVIEW

File: cmd/vic-machine/create/create.go [hunk 1]
```diff
@@ -1091,7 +1091,12 @@ func (c *Create) generateCertificates(server bool, client bool) ([]byte, *certif
 
 	var certs []byte
 	// generate the certs and keys with names conforming the default the docker client expects
-	err := os.MkdirAll(c.certPath, 0700)
+	files, err := ioutil.ReadDir(c.certPath)
+	if len(files) > 0 {
```
Comment (emlin) [inline cmd/vic-machine/create/create.go]: hmm... why should we do this? Feels like if user wants to generate certificate, that could be put into whatever directories

Comment (gigawhitlocks) [inline cmd/vic-machine/create/create.go]: Makes sure it's empty before we go writing files there all willy-nilly. Do note that it tries to load certificates first, so we only bother to do this if the load failed. So this way, vic-machine will not overwrite certificates that were inadvertently used for the install that don't work for the VCH.

The old way was: try to load. If failure -> generate certs. If certs exist and have the same name as the outputs, they get overwritten. This is what was happening to me trying to provide a cert and produced an undue amount of confusion because I didn't realize my certs had been overwritten and couldn't figure out why vic-machine wasn't accepting them :(

I can write a test for this behavior if it makes it clearer and/or makes you feel more comfortable with this functionality

Comment (emlin) [inline cmd/vic-machine/create/create.go]: I looked at the certificate validation code, which looks not bad. 
My opinion is that we'd better to stop the installation after a failed validation, instead of here. But might need @andrewtchin comments.

Comment (andrewtchin) [inline cmd/vic-machine/create/create.go]: I'm good with the implementation in this PR

Comment (emlin) [inline cmd/vic-machine/create/create.go]: okay 👍

File: tests/test-cases/Group6-VIC-Machine/6-13-TLS.robot [hunk 2]
```diff
@@ -32,7 +32,27 @@ Create VCH - defaults with --no-tls
     Run Regression Tests
     Cleanup VIC Appliance On Test Server
 
+Create VCH - defaults custom cert path
+    Set Test Environment Variables
+    Run Keyword And Ignore Error  Cleanup Dangling VMs On Test Server
+    Run Keyword And Ignore Error  Cleanup Datastore On Test Server
+
+    ${pwd}=     Run  pwd
```
Comment (mhagen-vmware) [inline tests/test-cases/Group6-VIC-Machine/6-13-TLS.robot]: I think you just want ${CURDIR} or ${EXECDIR}, looks like the latter.

Comment (mhagen-vmware) [inline tests/test-cases/Group6-VIC-Machine/6-13-TLS.robot]: curdir is the absolute path to the directory the test file is located in and execdir is the absolute path to the directory that execution of the script occurred in

File: tests/test-cases/Group6-VIC-Machine/6-13-TLS.robot [hunk 3]
```diff
@@ -32,7 +32,27 @@ Create VCH - defaults with --no-tls
...
+    ${output}=  Run  bin/vic-machine-linux create ${vicmachinetls} --name=%{VCH-NAME} --target="%{TEST_USERNAME}:%{TEST_PASSWORD}@%{TEST_URL}" --thumbprint=%{TEST_THUMBPRINT} --image-store=%{TEST_DATASTORE} --bridge-network=%{BRIDGE_NETWORK} --public-network=%{PUBLIC_NETWORK} --cert-path=${pwd}/foo-bar-certs/
+    Should Contain  ${output}  --tlscacert="${pwd}/foo-bar-certs/ca.pem" --tlscert="${pwd}/foo-bar-certs/cert.pem" --tlskey="${pwd}/foo-bar-certs/key.pem"
```
Comment (mhagen-vmware) [inline tests/test-cases/Group6-VIC-Machine/6-13-TLS.robot]: does this work?  I think you need to at least escape the = signs?

File: tests/test-cases/Group6-VIC-Machine/6-13-TLS.robot [hunk 4]
```diff
@@ -32,7 +32,27 @@ Create VCH - defaults with --no-tls
...
+    ${save_env}=  Run  cat ${pwd}/foo-bar-certs/%{VCH-NAME}.env
+    Should Contain  ${save_env}  DOCKER_CERT_PATH=${pwd}/foo-bar-certs
```
Comment (mhagen-vmware) [inline tests/test-cases/Group6-VIC-Machine/6-13-TLS.robot]: weird intermix here... I would prefer you exhaust all ${output} checks first before jumping to a different testable item.

File: tests/test-cases/Group6-VIC-Machine/6-13-TLS.robot (hunk 3 above)
Comment (gigawhitlocks) [inline tests/test-cases/Group6-VIC-Machine/6-13-TLS.robot]: yeah this works. I had accidentally put `$(pwd)` on my first iteration and that didn't pass, but this does, which indicates to me that that argument is interpreted as a string

File: tests/test-cases/Group6-VIC-Machine/6-13-TLS.robot (hunk 2 above)
Comment (gigawhitlocks) [inline tests/test-cases/Group6-VIC-Machine/6-13-TLS.robot]: ${EXECDIR}, thank you, didn't know it was a variable.

File: tests/test-cases/Group6-VIC-Machine/6-13-TLS.robot (hunk 4 above)
Comment (gigawhitlocks) [inline tests/test-cases/Group6-VIC-Machine/6-13-TLS.robot]: k

**Comment by gigawhitlocks** [comment]
OK @mhagen-vmware 's comments are addressed and assuming that's good for him in the morning hopefully @stuclem can also approve the 1-line doc change and this will be ready to go

File: doc/user/usage.md [hunk 5]
```diff
@@ -241,7 +241,6 @@ ERRO[2016-11-07T19:53:44Z] vic-machine-linux failed: provide Common Name for ser
 
 The [`--cert-path`](#certificate-names-and---cert-path) option applies to all of the TLS configurations other than --no-tls.
 
-Using `--force` will allow a `create` operation to move past some certificate checks performed for existing certificates, however will do so by generating __new__ certificates, __overwriting__ the old.
```
Comment (stuclem) [inline doc/user/usage.md]: @gigawhitlocks I am fine with removing this from usage.md. I checked the user docs and the only thing that we say about using` vic-machine create --force` in relation to certs is that it skips the VC thumbprint check. So, I think that we're fine.

Comment (gigawhitlocks) [inline doc/user/usage.md]: Yes, that part is still valid

File: cmd/vic-machine/create/create.go [hunk 6]
```diff
@@ -1097,7 +1097,12 @@ func (c *Create) generateCertificates(server bool, client bool) ([]byte, *certif
...
+		return nil, nil, fmt.Errorf("Specified directory to store certificates, \"%s\", is not empty. Please specify a new path in which to store generated certificates using --cert-path or remove the contents of \"%s\" and run vic-machine again.", c.certPath, c.certPath)
```
Comment (hickeng) [inline cmd/vic-machine/create/create.go]: I think we can be a little more concise - if certPath is long this error message is going to become unwieldy. It's also imperative so drop the "Please".
`("\"%s\" is not empty. Remove the contents or specify a different path for generated certificates via -cert-path", c.certPath)`

I also agree with @emlin that if we're not overwriting certs then it would make sense to bail immediately after validation of existing certificates fails, with a similar, but specific error message:
`("cannot validate certificates in \"%s\" for use with this VCH. Specify a different path via -cert-path, or remove existing certificates to generate new ones", c.certPath)`

Agree completely that silently overwriting is an issue and that we should change that behaviour unless --force is specified.
Not sure whether `--force` should overwrite, or use unvalidated certs.... It's a very coarse mechanism.

File: lib/install/management/inspect.go [hunk 7]
```diff
@@ -89,11 +89,11 @@ func (d *Dispatcher) InspectVCH(vch *vm.VirtualMachine, conf *config.VirtualCont
 		log.Debugf("No host certificates provided")
 	}
 
-	d.ShowVCH(conf, "", "", "", "")
+	d.ShowVCH(conf, "", "", "", "", "")
```
Comment (hickeng) [inline lib/install/management/inspect.go]: Is there any way we can guess at a cert path and then in ShowVCH check the certs against the VCH for validity? As it stands `inspect` is never going to provide useful output for secure deployments.

We could check:
default cert-path location
DOCKER_CERT_PATH location

for existing certs.

Comment (emlin) [inline lib/install/management/inspect.go]: pulled #4490 into 1.2 milestone, which should address this issue.

Comment (gigawhitlocks) [inline lib/install/management/inspect.go]: We have another issue open to address this in `inspect`, so that will be addressed along with that issue

File: cmd/vic-machine/create/create.go (hunk 6 above)
Comment (gigawhitlocks) [inline cmd/vic-machine/create/create.go]: @hickeng reviewing the code the only path I see, which is the one I was hitting, where we do not bail entirely upon failing to load certificates is when the `Leaf` of the certificate is `nil`. See the error on line 996 in `create.go`:

```log.Warnf("Failed to load x509 leaf: Unable to confirm server certificate cname matches provided cname %q. Continuing...", c.cname)```

I was hitting this path by using a wildcard certificate, which (apparently) has a `nil` `Leaf` in the certificate itself, presumably because it's not defined in a wildcard certificate due to the nature of that type of certificate. I don't think we want to bail in this situation, or we would block the usage of valid wildcard certificates, which is why this simply emits a warning.

Before my change, however, in that case the certificate would be overwritten on the filesystem if it existed in the same place as specified by `--cert-path`. Basically, this is a final-step cover-our-butts check for ridiculous corner cases like the one described (that I somehow managed to hit myself). The behavior you've requested is already present for the vast majority of cases.

Also I'm going to make that error statement more terse, as requested.

**Comment by gigawhitlocks** [comment]
Went ahead and merged @hickeng -- let me know if you have any further issues with that behavior after seeing the reply I left you above (hidden under an "outdated" block because I updated the error message) and I'm more than happy to refine it post-hoc
