### PR TITLE
Switch to DRS-aware VM power-on

### LINKED ISSUE #7237: Use DRS aware power on placement when target is vCenter
**Story**
As a viadmin I expect containerVMs to be distributed across my cluster in a sane and load aware manner when DRS semi-auto or auto is enabled.

**Details**
There is a separate call necessary to power on a VM in a way to allow DRS to provide intelligent placement at a sub-sample interval. vmware/govmomi#1026 is open to add support for the call into the library.
Why this seems to be intermittent or environment specific is unclear.

This issue will be fixed by consuming the govmomi update, adding whatever switching logic necessary (hopefully none if @dougm is happy with my request for intelligent switching based on target type in object.VirtualMachine.PowerOn), and adding appropriate testing to ensure wide distribution of power-on operations.

@lgayatri Is power on clustering something you have observed in scale testing? Is it something you have a way of quantifying as a metric so we can detect regressions? If not we should ask the perf team if they have a usable measure. 

Estimate is for code fix and basic test, excluding govmomi work and scale/stress metrics/tests.

### PR DESCRIPTION
**Pull request by jzt**
This change switches over to using the DRS-aware `PowerOnMultiVM` call when powering on VMs in vSphere. If attempting to power-on a VM in ESX, it will use the standard power-on call.

Fixes #7237.

[specific ci=Group0-Bugs]

### CODE REVIEW

File: pkg/vsphere/vm/vm.go [hunk 1]
```diff
@@ -861,6 +861,37 @@ func (vm *VirtualMachine) relocate(op trace.Operation, host *object.HostSystem)
...
+	})
+	if err != nil {
+		return err
+	}
+
+	switch r := t.Result.(type) {
+	case types.ClusterPowerOnVmResult:
+		attempts := len(r.Attempted)
+		if attempts != 1 {
+			return fmt.Errorf("Attempt to power on the wrong number of VMs. Expected 1, attempted %d", attempts)
```
Comment (cgtexmex) [inline pkg/vsphere/vm/vm.go]: Attempted instead of Attempt

File: pkg/vsphere/vm/vm.go [hunk 2]
```diff
@@ -861,6 +861,37 @@ func (vm *VirtualMachine) relocate(op trace.Operation, host *object.HostSystem)
...
+		}
+
+		info := r.Attempted[0]
+		task := object.NewTask(vm.Session.Vim25(), *info.Task)
+		_, err := task.WaitForResult(op, nil)
+		return err
+	default:
+		return fmt.Errorf("Unknown error when attempting to power on VM")
```
Comment (cgtexmex) [inline pkg/vsphere/vm/vm.go]: just a reminder of our conversation to provide type info in the error...blah...

File: pkg/vsphere/vm/vm.go [hunk 3]
```diff
@@ -861,6 +861,37 @@ func (vm *VirtualMachine) relocate(op trace.Operation, host *object.HostSystem)
...
+	}
+}
+
+func (vm *VirtualMachine) powerOnDRS(op trace.Operation) error {
```
Comment (cgtexmex) [inline pkg/vsphere/vm/vm.go]: is this needed?

Comment (jzt) [reply pkg/vsphere/vm/vm.go]: Nope, forgot to remove it, thanks

**Comment by cgtexmex** [comment]
@hickeng yes it works on standalone ESXi

File: pkg/vsphere/vm/vm.go [hunk 4]
```diff
@@ -861,10 +861,34 @@ func (vm *VirtualMachine) relocate(op trace.Operation, host *object.HostSystem)
...
-	_, err := vm.WaitForResult(op, func(op context.Context) (tasks.Task, error) {
-		return vm.VirtualMachine.PowerOn(op)
+	dc := vm.Datacenter
+
+	option := &types.OptionValue{
+		Key:   string(types.ClusterPowerOnVmOptionOverrideAutomationLevel),
+		Value: string(types.DrsBehaviorFullyAutomated),
+	}
+
+	t, err := vm.WaitForResult(op, func(op context.Context) (tasks.Task, error) {
```
[the remark this answers is not in the document]
Comment (cgtexmex) [reply pkg/vsphere/vm/vm.go]: Yes..it does...uses `pkg/vsphere/tasks` and will retry on the [identified conditions](https://github.com/vmware/vic/blob/master/pkg/vsphere/tasks/waiter.go#L107)

**Comment by jzt** [comment]
@hickeng more info: https://github.com/vmware/govmomi/blob/master/object/datacenter.go#L95
