### PR TITLE
[full ci] change NetworkMode to user-defined network (if any) when validating createConfig

### LINKED ISSUE #3542: Deploying a multi-container wordpress application **With Network** on VCH via Admiral fails
**VIC version:** 

vic-machine-linux version v0.8.0-7489-f116b8b

**Deployment details:**
```
./vic-machine-linux create --target 10.20.132.199 --image-store datastore1 --name bhu-docker-1 --user root --password 'password' --no-tlsverify --thumbprint 'xx:xx:xx:xx:xx:xx' --public-network 'VM Network' --volume-store=datastore1/vic-vol:default

 ### Installing VCH ####
 Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
 Generating self-signed certificate/key pair - private key in bhu-docker-1/server-key.pem
 Configuring without TLS verify - certificate-based authentication disabled
 Validating supplied configuration
 Firewall status: DISABLED on "/ha-datacenter/host/prome-1s-dhcp199.eng.vmware.com/prome-1s-dhcp199.eng.vmware.com"
 Firewall configuration will be incorrect if firewall is reenabled on hosts:
   "/ha-datacenter/host/prome-1s-dhcp199.eng.vmware.com/prome-1s-dhcp199.eng.vmware.com"
 Firewall must permit dst 2377/tcp outbound to VCH management interface if firewall is reenabled
 License check OK
 DRS check SKIPPED - target is standalone host

 Creating Resource Pool "bhu-docker-1"
 Creating VirtualSwitch
 Creating Portgroup
 Creating directory [datastore1] vic-vol
 datastore root [datastore1] vic-vol already exists
 Datastore path is [datastore1] vic-vol
 Creating appliance on target
 Network role "client" is sharing NIC with "public"
 Network role "management" is sharing NIC with "public"
 Uploading images for container
   "bootstrap.iso"
   "appliance.iso"
 Waiting for IP information
 Waiting for major appliance components to launch
 Checking VCH connectivity with vSphere target
 Could not run VCH vSphere API target check due to ServerFaultCode: The guest authentication being used does not have sufficient permissions to perform the operation.
 Initialization of appliance successful

 VCH Admin Portal:
 https://10.20.132.44:2378

 Published ports can be reached at:
 10.20.132.44

 Docker environment variables:
 DOCKER_HOST=10.20.132.44:2376

 Environment saved in bhu-docker-1/bhu-docker-1.env

 Connect to docker:
 docker -H 10.20.132.44:2376 --tls info
 Installer completed successfully
```

**Steps to reproduce:**

1. Deploy the VCH using the above mentioned command.
2. Register the host on admiral.
3. Upload an application template with the following specification (With Network Definition):
```
---
name: "New-WP"
components:
  wordpress:
    type: "App.Container"
    data:
      name: "wordpress"
      image: "wordpress:4.3.1"
      _cluster: 2
      env:
      - var: "WORDPRESS_DB_PASSWORD"
        value: "pass@word01"
      - var: "WORDPRESS_DB_NAME"
        value: "wordpress"
      - var: "WORDPRESS_DB_HOST"
        value: "mysql:3306"
      networks:
      - name: "new-net"
      publish_all: true
      ports:
      - container_port: "80"
      links:
      - service: "mysql"
        alias: "mysql"
      restart_policy: "no"
    dependsOn:
    - "mysql"
  new-net:
    type: "App.Network"
    data:
      name: "new-net"
      external: false
  mysql:
    type: "App.Container"
    data:
      name: "mysql"
      image: "mariadb:10.0.26"
      _cluster: 1
      env:
      - var: "MYSQL_ROOT_PASSWORD"
        value: "pass@word01"
      networks:
      - name: "new-net"
      publish_all: true
      ports:
      - container_port: "3306"
      restart_policy: "no"
```
**Actual behavior:**
The mysql container is sucessfully deployed however, the wordpress container goes offline after reporting the following error in the console:
screen shot 2016-12-20 at 3 31 40 pm
**Expected behavior:**
The application should have successfully deployed.
**Logs:**
[container-logs.zip](https://github.com/vmware/vic/files/665055/container-logs.zip)

```
docker -H 10.20.132.44:2376 --tls ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS                          NAMES
ae93a018cc43        wordpress:4.3.1     "/entrypoint.sh apach"   7 hours ago         Exited (1) 19 minutes ago   10.20.132.44:32776->80/tcp     wordpress-mcm368_30668812143
b891a58cc295        wordpress:4.3.1     "/entrypoint.sh apach"   7 hours ago         Exited (1) 43 minutes ago   10.20.132.44:32777->80/tcp     wordpress-mcm369_30668812143
10078bd3bff8        mariadb:10.0.26     "docker-entrypoint.sh"   7 hours ago         Up 44 minutes               10.20.132.44:32775->3306/tcp   mysql-mcm367_30668805634
22926c1659a5        wordpress:4.3.1     "/entrypoint.sh apach"   8 hours ago         Up About an hour            10.20.132.44:32770->80/tcp     wordpress-mcm360_30664839918
3ccac4bd5ba6        wordpress:4.3.1     "/entrypoint.sh apach"   8 hours ago         Up About an hour            10.20.132.44:32769->80/tcp     wordpress-mcm359_30664559422
0aef1a3a67b2        mariadb:10.0.26     "docker-entrypoint.sh"   8 hours ago         Up About an hour            10.20.132.44:32768->3306/tcp   mysql-mcm358_30664556128
```
```
docker -H 10.20.132.44:2376 --tls network ls
NETWORK ID          NAME                         DRIVER
3228c2b77bda        bridge                       bridge              
3e36c16d6114        new-net-mcm366_30668802410   bridge  
```
```
docker -H 10.20.132.44:2376 --tls network inspect new-net-mcm366_30668802410
[
    {
        "Name": "new-net-mcm366_30668802410",
        "Id": "3e36c16d61146e5ae4e5cc570dccc97b94cd34281f72890e7a2d2ee4b0f41a3a",
        "Scope": "",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "10078bd3bff8930a558180eac5fa412d0a1cb6b5069d294fcefd3cfe6953d96a": {
                "Name": "mysql-mcm367_30668805634",
                "EndpointID": "10078bd3bff8930a558180eac5fa412d0a1cb6b5069d294fcefd3cfe6953d96a",
                "MacAddress": "",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```
```
docker -H 10.20.132.44:2376 --tls inspect wordpress-mcm368_30668812143
[
    {
        "Id": "ae93a018cc43241fd6f04beda5ebba486023979126662c1bc75e88919dbcf26e",
        "Created": "2016-12-20T16:38:18Z",
        "Path": "/entrypoint.sh",
        "Args": [
            "apache2-foreground"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2016-12-20T17:02:59Z",
            "FinishedAt": "2016-12-20T17:03:38Z"
        },
        "Image": "db54b37edfcffd257f0db461bb75cdd88656f65ed57375ea88f9d7afb0b6c66b",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "",
        "Name": "/wordpress-mcm368_30668812143",
        "RestartCount": 0,
        "Driver": "vSphere Integrated Containers v0.8.0-7489-f116b8b Backend Engine",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": ""
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "vSphere Integrated Containers v0.8.0-7489-f116b8b Backend Engine",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": true,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "StorageOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "BlkioIOps": 0,
            "BlkioBps": 0,
            "SandboxSize": 0
        },
        "GraphDriver": {
            "Name": "vSphere Integrated Containers v0.8.0-7489-f116b8b Backend Engine",
            "Data": null
        },
        "Mounts": null,
        "Config": {
            "Hostname": "ae93a018cc43",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": [
                "WORDPRESS_DB_PASSWORD=pass@word01",
                "WORDPRESS_DB_NAME=wordpress",
                "WORDPRESS_DB_HOST=mysql:3306",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TERM=xterm",
                "PHP_INI_DIR=/usr/local/etc/php",
                "PHP_EXTRA_BUILD_DEPS=apache2-dev",
                "PHP_EXTRA_CONFIGURE_ARGS=--with-apxs2",
                "GPG_KEYS=0BD78B5F97500D450838F95DFE857D9A90D90EC1 6E4F6AB321FDC07F2C332E3AC2BF0BC433CFC8B3",
                "PHP_VERSION=5.6.16",
                "WORDPRESS_VERSION=4.3.1",
                "WORDPRESS_SHA1=b2e5652a6d2333cabe7b37459362a3e5b8b66221"
            ],
            "Cmd": [
                "apache2-foreground"
            ],
            "Image": "wordpress:4.3.1",
            "Volumes": {
                "/var/www/html": {}
            },
            "WorkingDir": "/var/www/html",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
            "OnBuild": [],
            "Labels": null
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32776"
                    }
                ]
            },
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "",
                    "EndpointID": "192",
                    "Gateway": "172.16.0.1/16",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                },
                "new-net-mcm366_30668802410": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "mysql",
                        "wordpress",
                        "ae93a018cc43"
                    ],
                    "NetworkID": "",
                    "EndpointID": "192",
                    "Gateway": "172.18.0.1/16",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]
```
* If you can access the VCH Admin portal, please download and attach the log bundle(s). See https://vmware.github.io/vic/assets/files/html/vic_admin/log_bundles.html for details.
* If the VCH Admin portal is inaccessible, you can enable SSH to the VCH endpoint VM to obtain logs manually. See https://vmware.github.io/vic/assets/files/html/vic_admin/vch_ssh_access.html for details. The VCH logs will be under /var/log/vic/ on the VM.

**Additional details as necessary:**

### PR DESCRIPTION
**Pull request by chengwang86**
Admiral sends docker rest api calls the docker daemon to create containers and networks. It does not specify the "HostConfig.NetworkMode" value in the form-data. Docker api would set "NetworkMode" to "default" if it is not set in the form-data.

On vic, if the NetworkMode is default, it will connect the container to the bridge network and ommit the user-defined network specified in the "NetworkConfig". However, if NetworkConfig is specified in the form-data, regular docker would connect the container to the user-defined network instead of the bridge network.

To address this, when validating the CreateConfig, we set the NetworkMode to the user-defined network if it is specified, which would connect the container to the user-defined network when creating the container instead of the bridge network.

Fixes #3542

### CODE REVIEW

File: lib/apiservers/engine/backends/container.go [hunk 1]
```diff
@@ -1377,14 +1377,20 @@ func validateCreateConfig(config *types.ContainerCreateConfig) error {
...
-
 	if config.HostConfig == nil || config.Config == nil {
 		return BadRequestError("invalid config")
 	}
 
+	if config.NetworkingConfig == nil {
+		config.NetworkingConfig = &dnetwork.NetworkingConfig{}
+	} else {
+		// If NetworkConfig exists, set NetworkMode to the default endpoint network, assuming only one endpoint network as the default network during container create
+		for networkName := range config.NetworkingConfig.EndpointsConfig {
```
Comment (hmahmood) [inline lib/apiservers/engine/backends/container.go]: You can check here that there is more than one endpoint and error out in that case.

Comment (chengwang86) [inline lib/apiservers/engine/backends/container.go]: So just to confirm again: we don't allow the the container to have more than one endpoint network upon creation, right? Additional user-defined networks can be added by "docker network connect" after "docker create".

File: lib/apiservers/engine/backends/container.go [hunk 2]
```diff
@@ -1377,14 +1377,22 @@ func validateCreateConfig(config *types.ContainerCreateConfig) error {
...
-
 	if config.HostConfig == nil || config.Config == nil {
 		return BadRequestError("invalid config")
 	}
 
+	if config.NetworkingConfig == nil {
+		config.NetworkingConfig = &dnetwork.NetworkingConfig{}
+	} else {
+		if l := len(config.NetworkingConfig.EndpointsConfig); l > 1 {
+			return fmt.Errorf("Error setting NetWorkMode: Container cannot be connected to more than one network endpoints; current endpoints: %d", l)
```
Comment (vburenin) [inline lib/apiservers/engine/backends/container.go]: "NetworkMode error: Container can be connected to one network endpoint only" Number of current endpoints doesn't look as an interesting data.

File: lib/apiservers/engine/backends/container.go [hunk 3]
```diff
@@ -1377,14 +1377,22 @@ func validateCreateConfig(config *types.ContainerCreateConfig) error {
...
+		}
+		// If NetworkConfig exists, set NetworkMode to the default endpoint network, assuming only one endpoint network as the default network during container create
+		for networkName := range config.NetworkingConfig.EndpointsConfig {
```
Comment (vburenin) [inline lib/apiservers/engine/backends/container.go]: taking into account EndpointsConfig is expected to be only 1 in length. for loop is not necessary here. Using if check is cheaper.

File: lib/apiservers/engine/backends/container.go [hunk 4]
```diff
@@ -1377,14 +1377,22 @@ func validateCreateConfig(config *types.ContainerCreateConfig) error {
...
 
-	if config.NetworkingConfig == nil {
-		config.NetworkingConfig = &dnetwork.NetworkingConfig{}
-	}
-
 	if config.HostConfig == nil || config.Config == nil {
 		return BadRequestError("invalid config")
 	}
 
+	if config.NetworkingConfig == nil {
```
Comment (vburenin) [inline lib/apiservers/engine/backends/container.go]: Is there any unit test code coverage for this?

File: lib/apiservers/engine/backends/container.go (hunk 3 above)
Comment (chengwang86) [inline lib/apiservers/engine/backends/container.go]: Sorry but I'm not clear how to obtain the network name from endpointsConfig (map) by if check.

File: lib/apiservers/engine/backends/container.go (hunk 2 above)
Comment (chengwang86) [inline lib/apiservers/engine/backends/container.go]: Thanks. I will change it.

File: lib/apiservers/engine/backends/container.go (hunk 4 above)
Comment (chengwang86) [inline lib/apiservers/engine/backends/container.go]: There is one file "backends/container_test.go" which I think does unit test for this file backends/container.go. But I don't think there is a test which creates a container without NetworkingConfig. Should I add test code?

**Comment by shadjiiski** [comment]
@chengwang86 Just to inform you that Admiral **may** specify the HostConfig.NetworkMode property - it can be changed from the default (empty) value to bridge, host or none. The choice is up to the user (see the bottom of the Network tab when specifying additional details for a new container). However, on docker this appears to be a valid case  only if there are no user-defined networks so we might need to change this in the future.

File: lib/apiservers/engine/backends/container.go (hunk 4 above)
Comment (vburenin) [inline lib/apiservers/engine/backends/container.go]: Of course!

File: lib/apiservers/engine/backends/container.go (hunk 3 above)
Comment (vburenin) [inline lib/apiservers/engine/backends/container.go]: my bad, I thought it is an array. It actually means used data type might be wrong.

File: lib/apiservers/engine/backends/container.go [hunk 5]
```diff
@@ -1377,14 +1377,22 @@ func validateCreateConfig(config *types.ContainerCreateConfig) error {
...
+		config.NetworkingConfig = &dnetwork.NetworkingConfig{}
+	} else {
+		if l := len(config.NetworkingConfig.EndpointsConfig); l > 1 {
+			return fmt.Errorf("NetworkMode error: Container can be connected to one network endpoint only")
+		}
+		// If NetworkConfig exists, set NetworkMode to the default endpoint network, assuming only one endpoint network as the default network during container create
+		for networkName := range config.NetworkingConfig.EndpointsConfig {
+			config.HostConfig.NetworkMode = containertypes.NetworkMode(networkName)
```
Comment (hickeng) [inline lib/apiservers/engine/backends/container.go]: This may cause issues w.r.t. links:
https://github.com/vmware/vic/blob/master/lib/apiservers/engine/backends/container_proxy.go#L892

File: lib/apiservers/engine/backends/container_test.go [hunk 6]
```diff
@@ -665,3 +665,28 @@ func TestPortInformation(t *testing.T) {
 	ports = portInformation(mockContainerInfo, ips)
 	assert.Equal(t, len(ports), 2, "Expected 2 port binding, found %d", len(ports))
 }
+
+// TestCreateConfigNetowrkMode() whether the HostConfig.NetworkMode is set correctly in ValidateCreateConfig()
+func TestCreateConfigNetworkMode(t *testing.T) {
+
+	// mock a container create config
+	var mockConfig types.ContainerCreateConfig
```
Comment (vburenin) [inline lib/apiservers/engine/backends/container_test.go]: please init object inline.

**Comment by sflxn** [comment]
lgtm

**Comment by mhagen-vmware** [comment]
lgtm
