### PR TITLE
Removing specially created clients for docker logs and stats [full ci]

### LINKED ISSUE #5685: VIC Port layer reporting socket: too many open files
When using Admiral with VCH endpoint seeing messages in the logs similar to:

**Port-layer.log**
ServerFaultCode: A specified parameter was not correct: spec.url

accept4: too many open files; retrying in 5ms

**Docker-personality.log**
ERROR Handler for GET /v1.21/volumes returned error: error from portlayer server: Get http://127.0.0.1:2377/storage/volumes: dial tcp 127.0.0.1:2377: socket: too many open files

ERROR Handler for GET /v1.21/containers/json returned error: Error invoking GetContainerList: Get http://127.0.0.1:2377/containers/list?all=true: dial tcp 127.0.0.1:2377: socket: too many open files

**Version**: `1.1.1`

bug-ref 1912860

### PR DESCRIPTION
**Pull request by hmahmood**
Fixes #5685

### CODE REVIEW

File: lib/apiservers/engine/backends/backends.go [hunk 1]
```diff
@@ -109,6 +110,8 @@ func Init(portLayerAddr, product string, config *config.VirtualContainerHostConf
 	}
 
 	t := rc.New(portLayerAddr, "/", []string{"http"})
+	t.Consumers["application/x-tar"] = archive.TarConsumer()
```
Comment (hickeng) [inline lib/apiservers/engine/backends/backends.go]: Looks like the original also included "application/x-gzip" mime type.

Comment (hmahmood) [inline lib/apiservers/engine/backends/backends.go]: But the port layer does not have an endpoint that either consumes or produces that mime-type, so it looks its now being used.

**Comment by corrieb** [comment]
@hmahmood Does this fix 5685 or does it just fix one element of that bug? It would be worth explaining how this fixes the "too many open files" problem, because it's not obvious from the commit.
