### PR TITLE
[full ci]Do not remove container if it's fixing

### LINKED ISSUE #3196: Error response from daemon: No such container: 1069fb0efd2f
From command in the CI build (https://ci.vmware.run/vmware/vic/6919):
```
docker -H dhcp-192-168-31-152.ci.drone.local:2376 --tls ps -aq | xargs -n1 docker -H dhcp-192-168-31-152.ci.drone.local:2376 --tls rm -f
```
```
	${output} = 5cd2c9a3166b
Error response from daemon: No such container: 1069fb0efd2f
4f51e5765af0
97bbcadf7124
1afecec824de
e1e05cb19b59
a514e546f78c
c5c215244d36
b4c792b7ddd9
```

[integration_logs_6919_2f30898a21a0caf6d8db00ddce758990b48856d0.zip](https://github.com/vmware/vic/files/594898/integration_logs_6919_2f30898a21a0caf6d8db00ddce758990b48856d0.zip)

Somehow, a container reported in ps -aq doesn't exist for docker rm -f?

### PR DESCRIPTION
**Pull request by emlin**
@hickeng agree to drop the error handler solution in PR #3478 for the benefit of that solution for vmomit gateway is not clear yet, but will introduce much more error to manage handlers from everywhere.
And the issue of invalid state VM is not easy to be avoided even we didn't have non-persistent guestinfo values.

This PR is the easiest solution so far to workaround the problem.
fix #3196

### CODE REVIEW

**Comment by emlin** [comment]
@hickeng @hmahmood @vburenin This PR is the solution without error handler. Please help to have another round of review.
thanks

File: lib/portlayer/exec/exec.go [hunk 1]
```diff
@@ -169,6 +162,15 @@ func eventCallback(ie events.Event) {
 				}()
 			case StateRemoved:
 				log.Debugf("Container(%s) %s via event activity", container, newState)
+				if container.vm != nil {
+					isFixing := container.vm.Fixing.Load()
+					if isFixing != nil && isFixing.(bool) {
+						// is fixing vm, which will be registered back soon, so do not remove from containers cache
+						log.Debugf("Container(%s) %s is being fixed", container.ExecConfig.ID)
+						container.vm.Fixing.Store(false)
```
Comment (hmahmood) [inline lib/portlayer/exec/exec.go]: Why are we setting it to false here? Shouldn't it be set to false in `fixVM` after the fixing is done?

Comment (emlin) [inline lib/portlayer/exec/exec.go]: make sense, should reset in vm fixing method

File: pkg/vsphere/vm/vm.go [hunk 2]
```diff
@@ -52,6 +53,9 @@ type VirtualMachine struct {
 	*object.VirtualMachine
 
 	*session.Session
+
+	// Fixing is true means the VM will be unregistered and registered back.
+	Fixing *atomic.Value
```
Comment (vburenin) [inline pkg/vsphere/vm/vm.go]: for clarity if I was doing that I would use an integer value for this flag.
atomic.Value is a lot of overhead for a simple flag.

```
// supposed to be atomic.
	var fixFlag int32
	
	v := atomic.LoadInt32(&fixFlag)
	atomic.StoreInt32(&fixFlag, 1)
```

File: lib/portlayer/exec/exec.go [hunk 3]
```diff
@@ -169,6 +162,14 @@ func eventCallback(ie events.Event) {
 				}()
 			case StateRemoved:
 				log.Debugf("Container(%s) %s via event activity", container, newState)
+				if container.vm != nil {
+					isFixing := container.vm.Fixing.Load()
```
Comment (vburenin) [inline lib/portlayer/exec/exec.go]: you would not need this type assertion at all if you use atomic integer.

Comment (vburenin) [inline lib/portlayer/exec/exec.go]: vm object wants to have a method isFixing.
