### PR TITLE
Check resolv.conf file for updated --dns-server instead of guestinfo.

### LINKED ISSUE #7775: Configure VCH DNS server fails to remove non-persistent assigned.dns entries
Seen here:
https://ci-vic.vmware.com/vmware/vic/18515
https://ci-vic.vmware.com/vmware/vic/18484
https://ci-vic.vmware.com/vmware/vic/18487

```
guestinfo.vice./init/networks|client/network/dns:                               1
    guestinfo.vice./init/networks|client/network/dns|0:                             AAAAAAAAAAAAAP//CnZRAQ==
    guestinfo.vice./init/networks|client/network/dns|1:                             AAAAAAAAAAAAAP//CnZRAg==
    guestinfo.vice./init/networks|management/network/dns:                           1
    guestinfo.vice./init/networks|management/network/dns|0:                         AAAAAAAAAAAAAP//CnZRAQ==
    guestinfo.vice./init/networks|management/network/dns|1:                         AAAAAAAAAAAAAP//CnZRAg==
    guestinfo.vice./init/networks|public/network/dns:                               1
    guestinfo.vice./init/networks|public/network/dns|0:                             AAAAAAAAAAAAAP//CnZRAQ==
    guestinfo.vice./init/networks|public/network/dns|1:                             AAAAAAAAAAAAAP//CnZRAg==
    guestinfo.vice..init.networks|client.network.assigned.dns:                      2
    guestinfo.vice..init.networks|client.network.assigned.dns|0:                    Co4HFQ==
    guestinfo.vice..init.networks|client.network.assigned.dns|1:                    Co4HFg==
    guestinfo.vice..init.networks|client.network.assigned.dns|2:                    CqYRWg==
    guestinfo.vice..init.networks|management.network.assigned.dns:                  2
    guestinfo.vice..init.networks|management.network.assigned.dns|0:                Co4HFQ==
    guestinfo.vice..init.networks|management.network.assigned.dns|1:                Co4HFg==
    guestinfo.vice..init.networks|management.network.assigned.dns|2:                CqYRWg==
    guestinfo.vice..init.networks|public.network.assigned.dns:                      2
    guestinfo.vice..init.networks|public.network.assigned.dns|0:                    Co4HFQ==
    guestinfo.vice..init.networks|public.network.assigned.dns|1:                    Co4HFg==
    guestinfo.vice..init.networks|public.network.assigned.dns|2:                    CqYRWg==' contains 'assigned.dns'
```
This is easily reproducible on our 6.5 HaaS test systems, seems to pass on the 6.7 Nimbus systems.

On further experimentation, power cycling the VCH one more time resolves the issue.  The assigned.dns field appears to be a non-persistent VM guestinfo field, so it is not written to the vmx file and it is populated by the portlayer on power on?

The test did change recently here:
https://github.com/vmware/vic/commit/5e13301082e800f55c519f539653d6e497bf3460

But all I did was try to cut down on a race condition by waiting longer, which apparently didn't fix it as the original failure is actually the same.  This appears be the first instance of this failure:
https://ci-vic.vmware.com/vmware/vic/18416/7

but this error also only shows up in HaaS runs so most of the merges to master prior to that ran on Nimbus.

### PR DESCRIPTION
**Pull request by vburenin**
Ready for review.

Fixes #7775 

[specific ci=6-16-Config]

### CODE REVIEW

File: isos/base/utils.sh [hunk 1]
```diff
@@ -179,6 +179,10 @@ END {
 ensure_apt_packages() {
     local install
 
+    if [ -x /usr/local/bin/xorriso -a -x /usr/bin/cpio ]; then
```
Comment (hickeng) [inline isos/base/utils.sh]: Why? We're passing in the package names we depend on to confirm and instead you've hardcoded a check for specific binaries.
I also see absolutely no correlation between this change and #7775

Comment (vburenin) [reply isos/base/utils.sh]: this is just to trigger CI, nothing else.
