### PR TITLE
[specific ci=6-13-TLS] Allow use of combination of vendor signed and self signed certs 

### LINKED ISSUE #3745: Combination of vendor supplied server certificate and docker self-generated Docker client certificates
Hello :),

**User Statement:**

I have a case with a customer where he would like to use the combination of server certificate from a vendor for its VCH web site, docker endpoint with the docker self-generated client certificates.

**Details:**
He used these vic-machine options to deploy the VCH : 

```
  --tls-cname                "virt-vic-$name-lab.andrew.local.cmu.edu"
  --tls-ca                "$certpath/virt-vic-$name-lab_andrew_local_cmu_edu_interm.cer"
  --cert                "$certpath/virt-vic-$name-lab_andrew_local_cmu_edu_cert.cer"
  --key                        "$certpath/virt-vic-$name-lab.key"
```

By reading the code from here (https://github.com/vmware/vic/blob/master/cmd/vic-machine/create/create.go line 649), he found out that when he provides the "--tls-ca" option, client certificate generation is disabled as the second argument "client" to generateCertificates() will always be set to flase because the "cas" varible contains all CAs given via the "--tls-ca" option : 

c.generateCertificates(keypair == nil, !c.noTLSverify && len(cas) == 0)

However, if he doesn't provide the intermediate and signing certs with the option "--tls-ca", he gets these logs warnings.

```
INFO[] Loaded server certificate /Users/jackson/vic-certs/virt-vic-storvirt-lab_andrew_local_cmu_edu_cert.cer 
DEBU[] Unable to locate existing CA in cert path
```

and the deployment fails with an error and these related messages (timestamps removed for clarity):

```
time= level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CheckDockerAPI:709] 
DEBU[] Loading CAs for client auth                  
time= level=debug msg=[BEGIN] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] 
time= level=debug msg=[ END ] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] [245.653µs]  
DEBU[] Loading CAs for client auth                  
DEBU[] Checked VIRT-VIC-STORVIRT-LAB.ANDREW.LOCAL.CMU.EDU., no match for host cert 
DEBU[] Checked W.X.Y.Z, no match for host cert 
WARN[] Unable to determine address to use with remote certificate, skipping API liveliness checks 
DEBU[] Assigning certificates for client auth       
DEBU[] connection refused                           
DEBU[] Components not yet initialized, retrying     
DEBU[] Unhandled net error type: x509.HostnameError{Certificate:(*x509.Certificate)(0xc4201c3200), Host:" W.X.Y.Z"} 
time= level=debug msg=[ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CheckDockerAPI:709] [1.936117385s]  
time= level=debug msg=[BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs:171] 
time= level=debug msg=[ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs:171] [8.354µs]  
ERRO[] --------------------                         
ERRO[] vic-machine-darwin failed: x509: cannot validate certificate for W.X.Y.Z because it doesn't contain any IP SANs

```

**Work around from the customer:**

He runs the "vic-machine create" without the --tls-ca, then "vic-machine delete" to clean up from the failed installation, putting the vendor CA certs at the end of <name>/ca.cer, then running "vic-machine create" again.

**My analyse:**

At first sight, I thought the VCH failed because the customer specified a CIDR in its network options as I remember this issue https://github.com/vmware/vic/pull/2553 where we can find the same error message at the end of the deployment.
`ERRO[]` vic-machine-darwin failed: x509: cannot validate certificate for  W.X.Y.Z because it doesn't contain any IP SANs`
But it is not as I checked the customer vic-machine create command.

As far as I understand by reading the documentation, isn't a logical behavior as the self-generated client certificates are signed by a CA generated by the vic-machine and not by the CA he provides with the --tls-ca ? Would it explain why his workaround works as he pastes directly the cert on the client system ?

I did read documentation about certification in general, and the different security options for the VCHs. But still don't really feel confident about this topic, I would appreciate your help.

**Deployment details:**

```
./vic-machine-darwin create \
  --debug		1 \
  --name		"$name"-vch \
  --timeout		10m0s \cd
  --target		"vc-lab.andrew.local.cmu.edu/$datac" \
  --user		administrator@vsphere.local \
  --appliance-iso	appliance.iso \
  --bootstrap-iso	bootstrap.iso \
  --compute-resource	"$cluster" \
  --tls-cname		"virt-vic-$name-lab.andrew.local.cmu.edu" \
  --cert		"$certpath/virt-vic-$name-lab_andrew_local_cmu_edu_cert.cer" \
  --key			"$certpath/virt-vic-$name-lab.key" \
  --registry-ca		"$certpath/virt-vic-harbor_andrew_local_cmu_edu_cert.cer" \
  --image-store		"$imagestore/$name" \
  --volume-store	"$volumestore/${name}:default" \
  --bridge-network	"virt-vic-$name" \
  --client-network	cyh-233-lab-priv \
  --public-network	cyh-233-lab-pub \
  --management-network	cyh-233-lab-priv \
  --container-network	"$contnet1" \
  --container-network	"$contnet2" \
  --container-network	"$contnet3" \
  --container-network	"$contnet4" \
  --container-network	"$contnet5" \
  --ops-user		vic-vch-user@vsphere.local \
  --dns-server			 W.X.Y.Z \
  --dns-server			 W.X.Y.Z \
  --public-network-ip		"virt-vic-$name-public-lab.andrew.cmu.edu" \
  --public-network-gateway	 W.X.Y.Z/XX \
  --management-network-ip	"virt-vic-$name-lab.andrew.local.cmu.edu" \
  --management-network-gateway	 W.X.Y.Z/X: W.X.Y.Z/XX \
  --http-proxy			http://proxy:XXXX \
  --bridge-network-range	"$bridgenet"

```

Many thanks for your help.

### PR DESCRIPTION
**Pull request by andrewtchin**
This allows the user to specify a vendor signed cert for the server/vic-admin/Docker API, while using the vic-machine generated certs for client auth.
Moved TLS related integration tests to their own file and added new tests

New tests pass locally
Fixes #3745

User supplied cert signed by a CA not in the system root store:
```
Feb 28 2017 18:11:15.246Z INFO  ### Installing VCH ####
Feb 28 2017 18:11:15.246Z DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processParams:495]
Feb 28 2017 18:11:15.246Z WARN  Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
Feb 28 2017 18:11:15.246Z DEBUG client network: IP {<nil> <nil>} gateway <nil> dest: []
Feb 28 2017 18:11:15.246Z DEBUG public network: IP {<nil> <nil>} gateway <nil> dest: []
Feb 28 2017 18:11:15.246Z DEBUG management network: IP {<nil> <nil>} gateway <nil> dest: []
Feb 28 2017 18:11:15.246Z DEBUG VCH DNS servers: []
Feb 28 2017 18:11:15.246Z DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).loadCertificates:936]
Feb 28 2017 18:11:15.247Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245]
Feb 28 2017 18:11:15.248Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] [871.705µs] 
Feb 28 2017 18:11:15.248Z INFO  Loaded server certificate bundle/*.eng.vmware.com.cert.pem
Feb 28 2017 18:11:15.248Z DEBUG Unable to locate existing CA in cert path
Feb 28 2017 18:11:15.248Z DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).loadCertificates:936] [1.851151ms] 
Feb 28 2017 18:11:15.248Z DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).generateCertificates:1084]
Feb 28 2017 18:11:15.248Z INFO  Generating CA certificate/key pair - private key in VCH-0-1718/ca-key.pem
Feb 28 2017 18:11:15.248Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.CreateRootCA:279]
Feb 28 2017 18:11:15.334Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.createCertificate:162]
Feb 28 2017 18:11:15.337Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.createCertificate:162] [3.223035ms] 
Feb 28 2017 18:11:15.337Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.CreateRootCA:279] [89.571659ms] 
Feb 28 2017 18:11:15.337Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.saveCertificate:196]
Feb 28 2017 18:11:15.337Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.saveCertificate:196] [78.351µs] 
Feb 28 2017 18:11:15.337Z INFO  Generating client certificate/key pair - private key in VCH-0-1718/key.pem
Feb 28 2017 18:11:15.337Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.CreateClientCertificate:308]
Feb 28 2017 18:11:15.337Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245]
Feb 28 2017 18:11:15.338Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] [381.949µs] 
Feb 28 2017 18:11:15.776Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.createCertificate:162]
Feb 28 2017 18:11:15.780Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.createCertificate:162] [3.538538ms] 
Feb 28 2017 18:11:15.780Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.CreateClientCertificate:308] [442.196541ms] 
Feb 28 2017 18:11:15.780Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.saveCertificate:196]
Feb 28 2017 18:11:15.780Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.saveCertificate:196] [79.549µs] 
Feb 28 2017 18:11:15.781Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245]
Feb 28 2017 18:11:15.781Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] [381.154µs] 
Feb 28 2017 18:11:15.787Z INFO  Generated browser friendly PFX client certificate - certificate in ./VCH-0-1718/cert.pfx
Feb 28 2017 18:11:15.787Z DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).generateCertificates:1084] [539.498842ms] 
Feb 28 2017 18:11:15.787Z DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processVolumeStores:876]
Feb 28 2017 18:11:15.787Z DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processVolumeStores:876] [38.415µs] 
Feb 28 2017 18:11:15.787Z DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processParams:495] [541.527915ms] 
Feb 28 2017 18:11:15.787Z DEBUG --target=https://10.17.109.130
Feb 28 2017 18:11:15.787Z DEBUG --thumbprint=C1:7A:E4:A4:22:B8:8A:68:F9:A4:E4:C2:38:91:3B:0D:8E:E0:C8:FB
Feb 28 2017 18:11:15.787Z DEBUG --name=VCH-0-1718
Feb 28 2017 18:11:15.787Z DEBUG --image-store=datastore1
Feb 28 2017 18:11:15.787Z DEBUG --bridge-network=VCH-0-1718-bridge
Feb 28 2017 18:11:15.787Z DEBUG --public-network=VM Network
Feb 28 2017 18:11:15.787Z DEBUG --tls-cname=*.eng.vmware.com
Feb 28 2017 18:11:15.787Z DEBUG --key=VCH-0-1718/server-key.pem
Feb 28 2017 18:11:15.787Z DEBUG --cert=VCH-0-1718/server-cert.pem
Feb 28 2017 18:11:15.787Z DEBUG --debug=1
...
Feb 28 2017 18:11:37.190Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CheckDockerAPI:724] 
Feb 28 2017 18:11:37.190Z DEBUG Loading CAs for client auth 
Feb 28 2017 18:11:37.202Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] 
Feb 28 2017 18:11:37.202Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] [137.175µs]
Feb 28 2017 18:11:37.271Z DEBUG Checked "ib-aus-office-196.eng.vmware.com.", no match for host certificate 
Feb 28 2017 18:11:37.271Z DEBUG Checked "10.17.109.196", no match for host certificate 
Feb 28 2017 18:11:37.271Z DEBUG Unable to determine address to use with remote certificate, checking SANs 
Feb 28 2017 18:11:37.271Z DEBUG Loading CAs for client auth 
Feb 28 2017 18:11:37.272Z DEBUG Unable to perform IP lookup of "*.eng.vmware.com": lookup *.eng.vmware.com: invalid domain name F
eb 28 2017 18:11:37.329Z DEBUG Checked "ib-aus-office-196.eng.vmware.com.", no match for host certificate 
Feb 28 2017 18:11:37.330Z DEBUG Checked "10.17.109.196", no match for host certificate 
Feb 28 2017 18:11:37.330Z DEBUG Using host address: 
Feb 28 2017 18:11:37.330Z DEBUG Failed to find a viable address for Docker API from certificates 
Feb 28 2017 18:11:37.330Z DEBUG Host address set to: "10.17.109.196" 
Feb 28 2017 18:11:37.330Z DEBUG Assigning certificates for client auth 
Feb 28 2017 18:11:37.330Z DEBUG Docker API endpoint: https://10.17.109.196:2376/info 
Feb 28 2017 18:11:37.331Z DEBUG connection refused 
Feb 28 2017 18:11:38.331Z DEBUG Components not yet initialized, retrying 
Feb 28 2017 18:11:38.333Z DEBUG connection refused 
Feb 28 2017 18:11:39.331Z DEBUG Components not yet initialized, retrying 
Feb 28 2017 18:11:39.333Z DEBUG connection refused 
Feb 28 2017 18:11:40.330Z DEBUG Components not yet initialized, retrying 
Feb 28 2017 18:11:40.331Z DEBUG connection refused 
Feb 28 2017 18:11:41.331Z DEBUG Components not yet initialized, retrying 
Feb 28 2017 18:11:41.379Z WARN Unable to validate server certificate (hostname doesn't match): x509: cannot validate certificate for 10.17.109.196 because it doesn't contain any IP SANs 
Feb 28 2017 18:11:41.379Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CheckDockerAPI:724] [4.188801276s] 
Feb 28 2017 18:11:41.379Z INFO Docker API endpoint check failed: x509: cannot validate certificate for 10.17.109.196 because it doesn't contain any IP SANs 
Feb 28 2017 18:11:41.379Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs:221] 
Feb 28 2017 18:11:41.379Z INFO Collecting ha-host hostd.log 
Feb 28 2017 18:11:41.516Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CollectDiagnosticLogs:221] [137.474152ms] 
Feb 28 2017 18:11:41.516Z INFO API may be slow to start - try to connect to API after a few minutes: 
Feb 28 2017 18:11:41.516Z INFO Run command: docker -H 10.17.109.196:2376 --tlsverify --tlscacert="VCH-0-1718/ca.pem" --tlscert="VCH-0-1718/cert.pem" --tlskey="VCH-0-1718/key.pem" info 
Feb 28 2017 18:11:41.516Z INFO If command succeeds, VCH is started. If command fails, VCH failed to install - see documentation for troubleshooting. 
Feb 28 2017 18:11:41.516Z ERROR -------------------- 
Feb 28 2017 18:11:41.516Z ERROR vic-machine-linux create failed: Docker API endpoint check failed: x509: cannot validate certificate for 10.17.109.196 because it doesn't contain any IP SANs
```

User supplied cert signed by a trusted root CA:
```
Feb 28 2017 18:12:11.557Z INFO  ### Installing VCH ####
Feb 28 2017 18:12:11.557Z DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processParams:495]
Feb 28 2017 18:12:11.557Z WARN  Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
Feb 28 2017 18:12:11.557Z DEBUG client network: IP {<nil> <nil>} gateway <nil> dest: []
Feb 28 2017 18:12:11.557Z DEBUG public network: IP {<nil> <nil>} gateway <nil> dest: []
Feb 28 2017 18:12:11.557Z DEBUG management network: IP {<nil> <nil>} gateway <nil> dest: []
Feb 28 2017 18:12:11.557Z DEBUG VCH DNS servers: []
Feb 28 2017 18:12:11.557Z DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).loadCertificates:936]
Feb 28 2017 18:12:11.558Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245]
Feb 28 2017 18:12:11.559Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] [856.974µs] 
Feb 28 2017 18:12:11.559Z INFO  Loaded server certificate bundle/*.eng.vmware.com.cert.pem
Feb 28 2017 18:12:11.559Z DEBUG Unable to locate existing CA in cert path
Feb 28 2017 18:12:11.559Z DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).loadCertificates:936] [1.85639ms] 
Feb 28 2017 18:12:11.559Z DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).generateCertificates:1084]
Feb 28 2017 18:12:11.559Z INFO  Generating CA certificate/key pair - private key in VCH-0-7973/ca-key.pem
Feb 28 2017 18:12:11.559Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.CreateRootCA:279]
Feb 28 2017 18:12:11.821Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.createCertificate:162]
Feb 28 2017 18:12:11.824Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.createCertificate:162] [3.159708ms] 
Feb 28 2017 18:12:11.824Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.CreateRootCA:279] [265.508188ms] 
Feb 28 2017 18:12:11.824Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.saveCertificate:196]
Feb 28 2017 18:12:11.825Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.saveCertificate:196] [92.669µs] 
Feb 28 2017 18:12:11.825Z INFO  Generating client certificate/key pair - private key in VCH-0-7973/key.pem
Feb 28 2017 18:12:11.825Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.CreateClientCertificate:308]
Feb 28 2017 18:12:11.825Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245]
Feb 28 2017 18:12:11.825Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] [380.32µs] 
Feb 28 2017 18:12:12.058Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.createCertificate:162]
Feb 28 2017 18:12:12.061Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.createCertificate:162] [3.048055ms] 
Feb 28 2017 18:12:12.061Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.CreateClientCertificate:308] [236.318495ms] 
Feb 28 2017 18:12:12.061Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.saveCertificate:196]
Feb 28 2017 18:12:12.061Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.saveCertificate:196] [90.448µs] 
Feb 28 2017 18:12:12.061Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245]
Feb 28 2017 18:12:12.063Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] [1.387481ms] 
Feb 28 2017 18:12:12.069Z INFO  Generated browser friendly PFX client certificate - certificate in ./VCH-0-7973/cert.pfx
Feb 28 2017 18:12:12.069Z DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).generateCertificates:1084] [509.786206ms] 
Feb 28 2017 18:12:12.069Z DEBUG [BEGIN] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processVolumeStores:876]
Feb 28 2017 18:12:12.069Z DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processVolumeStores:876] [7.543µs] 
Feb 28 2017 18:12:12.069Z DEBUG [ END ] [github.com/vmware/vic/cmd/vic-machine/create.(*Create).processParams:495] [511.787042ms] 
Feb 28 2017 18:12:12.069Z DEBUG --target=https://10.17.109.130
Feb 28 2017 18:12:12.069Z DEBUG --thumbprint=C1:7A:E4:A4:22:B8:8A:68:F9:A4:E4:C2:38:91:3B:0D:8E:E0:C8:FB
Feb 28 2017 18:12:12.069Z DEBUG --name=VCH-0-7973
Feb 28 2017 18:12:12.069Z DEBUG --image-store=datastore1
Feb 28 2017 18:12:12.069Z DEBUG --bridge-network=VCH-0-7973-bridge
Feb 28 2017 18:12:12.069Z DEBUG --public-network=VM Network
Feb 28 2017 18:12:12.069Z DEBUG --tls-cname=*.eng.vmware.com
Feb 28 2017 18:12:12.069Z DEBUG --key=VCH-0-7973/server-key.pem
Feb 28 2017 18:12:12.069Z DEBUG --cert=VCH-0-7973/server-cert.pem
Feb 28 2017 18:12:12.069Z DEBUG --debug=1
...
Feb 28 2017 18:12:32.274Z DEBUG [BEGIN] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CheckDockerAPI:724] 
Feb 28 2017 18:12:32.274Z DEBUG Loading CAs for client auth Feb 28 2017 18:12:32.287Z DEBUG [BEGIN] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] 
Feb 28 2017 18:12:32.287Z DEBUG [ END ] [github.com/vmware/vic/pkg/certificate.ParseCertificate:245] [134.421µs] 
Feb 28 2017 18:12:32.344Z DEBUG Matched "ib-aus-office-110.eng.vmware.com." for use against host certificate 
Feb 28 2017 18:12:32.344Z DEBUG Host address set to: "ib-aus-office-110.eng.vmware.com" 
Feb 28 2017 18:12:32.344Z DEBUG Assigning certificates for client auth 
Feb 28 2017 18:12:32.344Z DEBUG Docker API endpoint: https://ib-aus-office-110.eng.vmware.com:2376/info F
eb 28 2017 18:12:32.398Z DEBUG connection refused Feb 28 2017 18:12:33.345Z DEBUG Components not yet initialized, retrying 
Feb 28 2017 18:12:33.395Z DEBUG connection refused Feb 28 2017 18:12:34.347Z DEBUG Components not yet initialized, retrying 
Feb 28 2017 18:12:34.394Z DEBUG connection refused Feb 28 2017 18:12:35.346Z DEBUG Components not yet initialized, retrying 
Feb 28 2017 18:12:35.396Z DEBUG connection refused Feb 28 2017 18:12:36.345Z DEBUG Components not yet initialized, retrying 
Feb 28 2017 18:12:36.572Z DEBUG Confirmed port layer is operational Feb 28 2017 18:12:36.572Z DEBUG [ END ] [github.com/vmware/vic/lib/install/management.(*Dispatcher).CheckDockerAPI:724] [4.297517127s] 
Feb 28 2017 18:12:36.572Z INFO Initialization of appliance successful 
Feb 28 2017 18:12:36.572Z INFO 
Feb 28 2017 18:12:36.572Z INFO VCH Admin Portal: 
Feb 28 2017 18:12:36.572Z INFO https://ib-aus-office-110.eng.vmware.com:2378 
Feb 28 2017 18:12:36.572Z INFO 
Feb 28 2017 18:12:36.572Z INFO Published ports can be reached at: 
Feb 28 2017 18:12:36.572Z INFO 10.17.109.110 
Feb 28 2017 18:12:36.572Z INFO 
Feb 28 2017 18:12:36.572Z INFO Docker environment variables: 
Feb 28 2017 18:12:36.572Z INFO DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=/drone/src/github.com/vmware/vic/VCH-0-7973 DOCKER_HOST=ib-aus-office-110.eng.vmware.com:2376 
Feb 28 2017 18:12:36.572Z INFO 
Feb 28 2017 18:12:36.572Z INFO Environment saved in VCH-0-7973/VCH-0-7973.env 
Feb 28 2017 18:12:36.572Z INFO 
Feb 28 2017 18:12:36.572Z INFO Connect to docker: 
Feb 28 2017 18:12:36.572Z INFO docker -H ib-aus-office-110.eng.vmware.com:2376 --tlsverify --tlscacert="VCH-0-7973/ca.pem" --tlscert="VCH-0-7973/cert.pem" --tlskey="VCH-0-7973/key.pem" info
```

### CODE REVIEW

File: lib/install/management/appliance.go [hunk 1]
```diff
@@ -783,20 +783,24 @@ func (d *Dispatcher) CheckDockerAPI(conf *config.VirtualContainerHostConfigSpec,
 
 				cip := net.ParseIP(d.HostIP)
 				if err != nil {
-					log.Debugf("Unable to process client ip address: %s", err)
+					log.Debugf("Unable to process Docker API address from %q: %s", d.HostIP, err)
```
Comment (vburenin) [inline lib/install/management/appliance.go]: Docker API host address.

File: lib/install/management/appliance.go [hunk 2]
```diff
@@ -783,20 +783,24 @@ func (d *Dispatcher) CheckDockerAPI(conf *config.VirtualContainerHostConfigSpec,
...
+					log.Debugf("Unable to determine address to use with remote certificate, checking SANs")
+					addr, _ = viableHostAddress([]net.IP{cip}, cert, conf.CertificateAuthorities)
+					log.Debugf("Using host address: %s", addr)
 				}
-
-				d.HostIP = addr
+				if addr != "" {
+					d.HostIP = addr
+				} else {
+					log.Debug("Failed to find a viable address for Docker API from certificates")
```
Comment (vburenin) [inline lib/install/management/appliance.go]: It is not a failure, address is simply not available in the certificae.

File: lib/install/management/appliance.go [hunk 3]
```diff
@@ -902,9 +906,14 @@ func (d *Dispatcher) CheckDockerAPI(conf *config.VirtualContainerHostConfigSpec,
 					// This will occur if the server certificate was signed by a CA that is not the one used for client authentication
 					// and does not have a trusted root registered on the system running vic-machine
 					// This is a legitimate deployment so no error, but definitely requires a warning.
-					log.Warnf("Unable to verify server certificate with configured CAs: %s", neterr.Error())
+					log.Warnf("Unable to validate server certificate with configured CAs (unknown authority): %s", neterr.Error())
 					return nil
 
+				case x509.HostnameError:
+					// e.g. "doesn't contain any IP SANs"
+					log.Warnf("Unable to validate server certificate (hostname doesn't match): %s", neterr.Error())
```
Comment (vburenin) [inline lib/install/management/appliance.go]: "Server certificate hostname doesn't match." What does neterr say in this case?

Comment (andrewtchin) [inline lib/install/management/appliance.go]: `x509: cannot validate certificate for 10.17.109.117 because it doesn't contain any IP SANs`

File: lib/install/management/dispatcher.go [hunk 4]
```diff
@@ -306,23 +306,27 @@ func (d *Dispatcher) CheckAccessToVCAPI(ctx context.Context, vch *vm.VirtualMach
...
+		pool = x509.NewCertPool()
+	}
 	pool.AppendCertsFromPEM(cas)
 
 	// update target to use FQDN
 	for _, ip := range candidateIPs {
 		names, err := net.LookupAddr(ip.String())
 		if err != nil {
-			log.Debugf("Unable to perform reverse lookup of IP address: %s", err)
+			log.Debugf("Unable to perform reverse lookup of IP address %q: %s", ip.String(), err)
```
Comment (vburenin) [inline lib/install/management/dispatcher.go]: log.Debugf("Unable to perform reverse lookup of IP address %s: %s", ip, err)

Comment (vburenin) [inline lib/install/management/dispatcher.go]: ip is a stringer, so using %s will call String automatically.

File: lib/install/management/appliance.go (hunk 3 above)
Comment (andrewtchin) [inline lib/install/management/appliance.go]: fixed

File: lib/install/management/appliance.go (hunk 1 above)
Comment (andrewtchin) [inline lib/install/management/appliance.go]: fixed

File: lib/install/management/dispatcher.go (hunk 4 above)
Comment (andrewtchin) [inline lib/install/management/dispatcher.go]: cool thanks fixed

File: lib/install/management/appliance.go (hunk 2 above)
Comment (andrewtchin) [inline lib/install/management/appliance.go]: i think the statement is true and it's a debug message

**Comment by anchal-agrawal** [comment]
LGTM

File: lib/install/management/appliance.go (hunk 2 above)
Comment (hickeng) [inline lib/install/management/appliance.go]: should this be setting `tlsErrExpected = true`?

File: lib/install/management/appliance.go [hunk 5]
```diff
@@ -902,9 +906,14 @@ func (d *Dispatcher) CheckDockerAPI(conf *config.VirtualContainerHostConfigSpec,
 					// This will occur if the server certificate was signed by a CA that is not the one used for client authentication
 					// and does not have a trusted root registered on the system running vic-machine
 					// This is a legitimate deployment so no error, but definitely requires a warning.
-					log.Warnf("Unable to verify server certificate with configured CAs: %s", neterr.Error())
+					log.Warnf("Unable to validate server certificate with configured CAs (unknown authority): %s", neterr.Error())
```
Comment (hickeng) [inline lib/install/management/appliance.go]: I think this is only a warning if `tlsErrExpected` is true, but an error otherwise. If we get this, but thought we knew the correct address to use then it's an error.

File: lib/install/management/appliance.go [hunk 6]
```diff
@@ -902,9 +906,14 @@ func (d *Dispatcher) CheckDockerAPI(conf *config.VirtualContainerHostConfigSpec,
...
 					return nil
 
+				case x509.HostnameError:
+					// e.g. "doesn't contain any IP SANs"
+					log.Warnf("Server certificate hostname doesn't match: %s", neterr.Error())
```
Comment (hickeng) [inline lib/install/management/appliance.go]: same as the previous clause?

File: tests/resources/VCH-Util.robot [hunk 7]
```diff
@@ -303,3 +303,18 @@ Cleanup Dangling Containers On Test Server
     \   ${name}=  Fetch From Right  ${vm}  /
     \   ${out}=  Run  govc datastore.rm ${name}
     \   Wait Until Keyword Succeeds  6x  5s  Check Delete Success  ${name}
+
+
+Get VCH IP
```
Comment (hickeng) [inline tests/resources/VCH-Util.robot]: We have (or had) an existing drone library call for this: `Get Docker Params`
It's specifically for parsing the install output, but it's the same exercise that we're doing here.

File: lib/install/management/appliance.go (hunk 5 above)
Comment (andrewtchin) [inline lib/install/management/appliance.go]: you're right, fixed

File: lib/install/management/appliance.go (hunk 6 above)
Comment (andrewtchin) [inline lib/install/management/appliance.go]: fixed

File: tests/resources/VCH-Util.robot (hunk 7 above)
Comment (andrewtchin) [inline tests/resources/VCH-Util.robot]: fixed
