### PR TITLE
toolbox: Limit NIC list

### LINKED ISSUE #5267: 223K instances of "[ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow." found in vmware-vmsvc logs
VCH is deployed with 1.1.1rc2 release build

root@vic-st-h2-132 [ /var/log ]# cat vmware-vmsvc.* | grep " GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow." | wc -l
223947
I have just 5 logs of vmware-vmsvc* and they are filled with these messages.

Snippet:
[May 26 11:48:27.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:48:57.081] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:48:57.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:48:57.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:48:57.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:48:57.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:48:57.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:49:27.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:49:27.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:49:27.082] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:49:27.083] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:49:27.083] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.
[May 26 11:49:27.083] [ message] [vmsvc] GuestInfoAddNicEntry: NIC limit (16) reached, skipping overflow.

Every 30 seconds, 6 entries are being made to the log file.
AFAIK, this message needs no user action. Can we suppress this?

Found similar stack trace in: https://github.com/vmware/open-vm-tools/issues/128

Logs attached.
[vmsvc.tar.gz](https://github.com/vmware/vic/files/1031728/vmsvc.tar.gz)

Expected:
Avoid filling logs with this message for better log readability.

### PR DESCRIPTION
**Pull request by dougm**
There is a max of 16 NICs that can be reported.

Filter out NICs without a MAC or IP, as they are not useful outside of the guest anyhow.

Fixes #5267

### CODE REVIEW

**Comment by frapposelli** [comment]
This might help a lot with #4995 /cc: @andrewtchin (would require to port toolbox to the OVA)

File: pkg/vsphere/toolbox/guest_info.go [hunk 1]
```diff
@@ -144,30 +144,47 @@ func GuestInfoCommand(kind int, req []byte) []byte {
 	return append([]byte(request), req...)
 }
 
+var (
+	netInterfaces = net.Interfaces
```
Comment (caglar10ur) [inline pkg/vsphere/toolbox/guest_info.go]: first I said wat? then saw the test, wish there was another way :/

**Comment by dougm** [comment]
@frapposelli sure, we can tweak further as desired.

@caglar10ur there is another way, it's called "Java" ;)
