### PR TITLE
[full ci] Fix the wrong version info in vApp

### LINKED ISSUE #2158: vApp showing VIC version as 0.0.1 not 0.5.0
image

This file seems the one where the version is set:
https://github.com/vmware/vic/blob/af71181d82f0bff404f7109cd3176ed0ecc21ca7/lib/install/management/virtual_app.go

### PR DESCRIPTION
**Pull request by jooskim**
This simple PR fixes #2158 in that the version of vApp in vSphere Web Client currently showing 0.0.1 is corrected to 0.5.5.

After fix:
image

### CODE REVIEW

File: lib/install/management/virtual_app.go [hunk 1]
```diff
@@ -79,7 +79,7 @@ func (d *Dispatcher) createVApp(conf *config.VirtualContainerHostConfigSpec, set
 			Name:      "vSphere Integrated Containers",
 			Vendor:    "VMware",
 			VendorUrl: "http://www.vmware.com/",
-			Version:   "0.0.1",
+			Version:   "0.5.5",
```
Comment (anchal-agrawal) [inline lib/install/management/virtual_app.go]: Using the `Version` var from the `version` pkg would be a better alternative to hardcoding the value. https://github.com/vmware/vic/blob/master/pkg/version/version.go#L25

Comment (jooskim) [inline lib/install/management/virtual_app.go]: Great. Thanks for letting me know.

Comment (sgairo) [inline lib/install/management/virtual_app.go]: I agree about the version package, however, it currently doesn't show the correct version. Right now it shows as 0.4.0, so you might not always have the most up-to-date version by using the package.

Comment (jooskim) [inline lib/install/management/virtual_app.go]: Hmm.. I am building vic-machine after making the change to see if it shows the right version. I have a couple older binaries on my laptop and I just tried running vic-machine with build 4430 and it seems to fetch the right version. (v0.5.0-4430-f5c412b) I thought it was getting from the same version package. I'll see if I get 0.4.0 as well once I get the binary!

Comment (sgairo) [inline lib/install/management/virtual_app.go]: I'm going to see why mine is showing 0.4.0

Comment (anchal-agrawal) [inline lib/install/management/virtual_app.go]: @jooskim Yes, it should show the latest version.

Comment (jooskim) [inline lib/install/management/virtual_app.go]: It seems to work nice for me. Not sure where the version info is set explicitly though. Or it might be set automatically from a git tag.. Anybody know about this?

Comment (anchal-agrawal) [inline lib/install/management/virtual_app.go]: See #1815

File: lib/install/management/virtual_app.go [hunk 2]
```diff
@@ -24,6 +24,7 @@ import (
 	"github.com/vmware/vic/lib/install/data"
 	"github.com/vmware/vic/pkg/errors"
 	"github.com/vmware/vic/pkg/trace"
+  "github.com/vmware/vic/pkg/version"
```
Comment (anchal-agrawal) [inline lib/install/management/virtual_app.go]: `go fmt` :)

Comment (jooskim) [inline lib/install/management/virtual_app.go]: yeah i was wondering why spacemacs was not allowing me to do indentation the way i wanted. another new stuff learned

Comment (anchal-agrawal) [inline lib/install/management/virtual_app.go]: The [spacemacs go layer](https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Blang/go) runs `go fmt` on every file save.

**Comment by anchal-agrawal** [comment]
Thanks @jooskim! LGTM

File: lib/install/management/virtual_app.go (hunk 2 above)
Comment (jooskim) [inline lib/install/management/virtual_app.go]: yup, i just realized my spacemacs doesn't have go layer installed and that was why. now it does :-)

**Comment by jooskim** [comment]
@andrewtchin Mind taking a look? Thanks!

**Comment by andrewtchin** [comment]
lgtm

**Comment by andrewtchin** [comment]
not sure how granular you want, but to differentiate between different builds you could use `version.GetBuild().ShortVersion()` that's the version the update process will look at vs `version.Version` is just the latest git tag so wouldn't necessarily change between builds

**Comment by jooskim** [comment]
@andrewtchin i tended to display only the major minor patch digits so `version.Version` should be fine for me. thanks!

**Comment by jooskim** [comment]
♻️
