### PR TITLE
Partial fix for issues: #5235, #5245

### LINKED ISSUE #5235: "Docker ps only running containers" fail in ci test 1-10-Docker-PS
Seen here https://ci.vcna.io/vmware/vic/10853.

### PR DESCRIPTION
**Pull request by lcastellano**
This fixes a real problem where events go missing. It was seen in multiple/concurrent container create/start. However, there could be other problems. In particular if an event is not received from VSphere, VIC engine could still be in an inconsistent state. Where the VM is powered off but the container is still listed as running.

Fixes #5235

### CODE REVIEW

File: lib/portlayer/event/collector/vsphere/collector.go [hunk 1]
```diff
@@ -176,7 +176,7 @@ func evented(ec *EventCollector, page []types.BaseEvent) {
 			ec.callback(NewVMEvent(page[i]))
 		case *types.VmReconfiguredEvent:
 			// reconfigures happen often, so completely ignore for now
-			return
+			continue
 		default:
```
Comment (cgtexmex) [inline lib/portlayer/event/collector/vsphere/collector.go]: Ugh...nice catch I totally screwed that up...FTR this was added to help identify missed events but this would've made it worse.
