### PR TITLE
Inspect all property changes before exiting WaitForKeyInExtraConfig

### LINKED ISSUE #5629: container failed to start due to "unable to launch process status: container VM has unexpectedly powered off"
This is seen in our ci test https://ci.vcna.io/vmware/vic/12028

[Test-Cases.Group1-Docker-Commands.1-37-Docker-USER-VCH-12028-9391-container-logs.zip](https://github.com/vmware/vic/files/1116105/Test-Cases.Group1-Docker-Commands.1-37-Docker-USER-VCH-12028-9391-container-logs.zip)

From log.html
```
Running command 'docker -H dhcp-192-168-31-228.ci.drone.local:2376 --tls run -u root:nonexistent busybox whoami 2>&1'.	
${rc} = 125	
${output} = docker: Error response from daemon: Server error from portlayer: unable to wait for process launch status: container VM has unexpectedly powered off.
```

From tether.debug of the failed container:
```
Jun 29 2017 22:33:04.165Z DEBUG [BEGIN] [main.backchannel:274] establish tether backchannel
Jun 29 2017 22:33:04.167Z ERROR user lookup failed root:nonexistent, Unable to find group nonexistent
Jun 29 2017 22:33:04.168Z DEBUG Calling close on writers
Jun 29 2017 22:33:04.169Z DEBUG [0xc420104f00] Close on writers
Jun 29 2017 22:33:04.169Z DEBUG [0xc420104f00] Closing writer &{Clock:{} w:0xc42000e120 prev:[] m:{state:0 sema:0} closed:false}
Jun 29 2017 22:33:04.170Z DEBUG [0xc420104f00] is a Closer%!(EXTRA *iolog.LogWriter=&{{} 0xc42000e120 [] {0 0} false})
Jun 29 2017 22:33:04.172Z DEBUG [0xc420104f00] Closing writer &{file:0xc42000c0c0}
Jun 29 2017 22:33:04.172Z DEBUG [0xc420104f90] Close on writers
Jun 29 2017 22:33:04.173Z DEBUG [0xc420104f90] Closing writer &{Clock:{} w:0xc42000e120 prev:[] m:{state:0 sema:0} closed:true}
Jun 29 2017 22:33:04.174Z DEBUG [0xc420104f90] is a Closer%!(EXTRA *iolog.LogWriter=&{{} 0xc42000e120 [] {0 0} true})
Jun 29 2017 22:33:04.175Z DEBUG [0xc420104f90] Closing writer &{file:0xc42000c0e0}
Jun 29 2017 22:33:04.176Z DEBUG Calling close on reader
Jun 29 2017 22:33:04.176Z DEBUG [0xc420162ec0] Close on readers
Jun 29 2017 22:33:04.177Z DEBUG Calling close chan: f2d5087562e75414b37da3d024d6f211fd3df9f1c2598e4801e27e38e8859213
Jun 29 2017 22:33:04.178Z DEBUG Encoding result of launch for session f2d5087562e75414b37da3d024d6f211fd3df9f1c2598e4801e27e38e8859213 under key: guestinfo.vice./sessions|f2d5087562e75414b37da3d024d6f211fd3df9f1c2598e4801e27e38e8859213
Jun 29 2017 22:33:04.180Z DEBUG GuestInfoSink: setting key: guestinfo.vice..sessions|f2d5087562e75414b37da3d024d6f211fd3df9f1c2598e4801e27e38e8859213.detail.createtime, value: "0"
Jun 29 2017 22:33:04.187Z DEBUG GuestInfoSink: setting key: guestinfo.vice..sessions|f2d5087562e75414b37da3d024d6f211fd3df9f1c2598e4801e27e38e8859213.detail.starttime, value: "1498775578"
Jun 29 2017 22:33:04.193Z DEBUG GuestInfoSink: setting key: guestinfo.vice..sessions|f2d5087562e75414b37da3d024d6f211fd3df9f1c2598e4801e27e38e8859213.detail.stoptime, value: "0"
Jun 29 2017 22:33:04.200Z DEBUG GuestInfoSink: setting key: guestinfo.vice..sessions|f2d5087562e75414b37da3d024d6f211fd3df9f1c2598e4801e27e38e8859213.diagnostics.resurrections, value: "0"
Jun 29 2017 22:33:04.207Z DEBUG GuestInfoSink: setting key: guestinfo.vice..sessions|f2d5087562e75414b37da3d024d6f211fd3df9f1c2598e4801e27e38e8859213.status, value: "0"
Jun 29 2017 22:33:04.214Z DEBUG GuestInfoSink: setting key: guestinfo.vice..sessions|f2d5087562e75414b37da3d024d6f211fd3df9f1c2598e4801e27e38e8859213.started, value: "Unable to find group nonexistent"
Jun 29 2017 22:33:04.223Z DEBUG GuestInfoSink: setting key: guestinfo.vice..sessions|f2d5087562e75414b37da3d024d6f211fd3df9f1c2598e4801e27e38e8859213.runblock, value: "false"
Jun 29 2017 22:33:04.234Z DEBUG [ END ] [github.com/vmware/vic/lib/tether.(*tether).launch:655] [72.371813ms] launching session f2d5087562e75414b37da3d024d6f211fd3df9f1c2598e4801e27e38e8859213
Jun 29 2017 22:33:04.234Z ERROR failed to launch whoami for f2d5087562e75414b37da3d024d6f211fd3df9f1c2598e4801e27e38e8859213: Unable to find group nonexistent
Jun 29 2017 22:33:04.235Z ERROR failed to launch whoami for f2d5087562e75414b37da3d024d6f211fd3df9f1c2598e4801e27e38e8859213: Unable to find group nonexistent
Jun 29 2017 22:33:04.237Z DEBUG [BEGIN] [github.com/vmware/vic/lib/tether.(*tether).cleanup:176] main tether cleanup
Jun 29 2017 22:33:04.237Z DEBUG [BEGIN] [github.com/vmware/vic/lib/tether.(*tether).stopReaper:157] Shutting down child reaping
Jun 29 2017 22:33:04.237Z DEBUG Removing the signal notifier
Jun 29 2017 22:33:04.238Z DEBUG Closing the reapers signal channel
Jun 29 2017 22:33:04.239Z DEBUG [ END ] [github.com/vmware/vic/lib/tether.(*tether).stopReaper:157] [1.682752ms] Shutting down child reaping
Jun 29 2017 22:33:04.239Z INFO  Stopping extension Attach
Jun 29 2017 22:33:04.239Z DEBUG [BEGIN] [main.(*attachServerSSH).Stop:161] stop attach server
Jun 29 2017 22:33:04.240Z DEBUG [BEGIN] [main.(*attachServerSSH).stop:238] stop attach server
Jun 29 2017 22:33:04.240Z DEBUG Canceling AttachServer's context
Jun 29 2017 22:33:04.240Z DEBUG Closing the RawConn (/dev/ttyS0:/dev/ttyS0)
Jun 29 2017 22:33:04.242Z INFO  Stopped reaping child processes
Jun 29 2017 22:33:04.242Z DEBUG Pushing EOF to any blocked readers on the raw connection (/dev/ttyS0:/dev/ttyS0)
Jun 29 2017 22:33:04.244Z DEBUG [ END ] [main.backchannel:274] [78.974121ms] establish tether backchannel
Jun 29 2017 22:33:04.244Z ERROR failed to establish backchannel: context canceled
Jun 29 2017 22:33:04.245Z ERROR failed to establish backchannel: context canceled
Jun 29 2017 22:33:04.246Z INFO  Ready to service attach requests
Jun 29 2017 22:33:04.246Z DEBUG [BEGIN] [main.(*attachServerSSH).globalMux:565] attach server global request handler
Jun 29 2017 22:33:04.245Z DEBUG Close called again on rawconn - squashing
Jun 29 2017 22:33:04.247Z DEBUG Close called again on RawConn (/dev/ttyS0:/dev/ttyS0) - dropping
Jun 29 2017 22:33:04.248Z DEBUG [ END ] [main.(*attachServerSSH).stop:238] [8.281228ms] stop attach server
Jun 29 2017 22:33:04.248Z DEBUG [ END ] [main.(*attachServerSSH).Stop:161] [8.406637ms] stop attach server
Jun 29 2017 22:33:04.248Z INFO  Stopping extension Toolbox
Jun 29 2017 22:33:04.250Z DEBUG [ END ] [github.com/vmware/vic/lib/tether.(*tether).cleanup:176] [12.756213ms] main tether cleanup
Jun 29 2017 22:33:04.250Z DEBUG [ END ] [github.com/vmware/vic/lib/tether.(*tether).Start:482] [582.961054ms] main tether loop
[    2.304350] reboot: Power down
```
Here `ERROR user lookup failed root:nonexistent, Unable to find group nonexistent
Jun 29 2017 22:33:04.168Z DEBUG Calling close on writers` is the expected output for the failed test.

### PR DESCRIPTION
**Pull request by sflxn**
There are cases where a container starts up and shuts down very quickly.  We
treated this case as early termination because the tether failed to initialize.
However, in quick to shut down containers, the tether may have initialized and
written out return codes, but we read the power off before we read the codes.
We now read the status code before the power state changes in WaitForKeyInExtraConfig.
This should allow us to not misinterpret quick ending containers.

Resolves #5629

### CODE REVIEW

File: pkg/vsphere/vm/vm.go [hunk 1]
```diff
@@ -198,30 +199,30 @@ func (vm *VirtualMachine) WaitForKeyInExtraConfig(ctx context.Context, key strin
...
 		}
-		return false
+		return exitEarly
 	}
 
+	// if poweredOff != nil && detail == "" then assume tether did not initialize.
+	// if poweredOff != nil && detail != "" then assume tether did initialize but VM shutdown quickly for valid reasons
 	err := vm.WaitForExtraConfig(ctx, waitFunc)
-	if err == nil && poweredOff != nil {
+	if err == nil && poweredOff != nil && detail == "" {
```
Comment (emlin) [inline pkg/vsphere/vm/vm.go]: I think the check `detail == ""` can help to avoid powerdOff error if the value is already set by tether.
But what's the benefit to set exitEarly above? If you want, maybe you could just return at line 202, https://github.com/vmware/vic/pull/5938/files#diff-818b18702ad1cb5203eeaccc54071e09R202

**Comment by dougm** [comment]
Simpler fix would be to swap the property order here: https://github.com/vmware/vic/blob/master/pkg/vsphere/vm/vm.go#L176

So if we get both properties in the same update set, we examine the extraConfig before the powerState.

**Comment by sflxn** [comment]
Thanks Doug.  I was wondering if I could do that also, but I wasn't sure if that actually affected the ordering.

**Comment by dougm** [comment]
The test will need fixing too:
```diff
modified   pkg/vsphere/vm/vm_test.go
@@ -339,7 +339,6 @@ func TestWaitForKeyInExtraConfig(t *testing.T) {
 
 	opt := &types.OptionValue{Key: "foo", Value: "bar"}
 	obj := simulator.Map.Get(vm.Reference()).(*simulator.VirtualMachine)
-	obj.Config.ExtraConfig = append(obj.Config.ExtraConfig, opt)
 
 	val, err := vm.WaitForKeyInExtraConfig(ctx, opt.Key)
 
@@ -347,6 +346,7 @@ func TestWaitForKeyInExtraConfig(t *testing.T) {
 		t.Error("expected error")
 	}
 
+	obj.Config.ExtraConfig = append(obj.Config.ExtraConfig, opt)
 	obj.Summary.Runtime.PowerState = types.VirtualMachinePowerStatePoweredOn
 
 	val, err = vm.WaitForKeyInExtraConfig(ctx, opt.Key)
```

File: pkg/vsphere/vm/vm.go [hunk 2]
```diff
@@ -198,30 +199,30 @@ func (vm *VirtualMachine) WaitForKeyInExtraConfig(ctx context.Context, key strin
 					if key == value.GetOptionValue().Key {
 						detail = value.GetOptionValue().Value.(string)
 						if detail != "" && detail != "<nil>" {
-							return true
+							exitEarly = true
 						}
 						break // continue the outer loop as we may have a powerState change too
```
Comment (vburenin) [inline pkg/vsphere/vm/vm.go]: break is not needed here.

File: pkg/vsphere/vm/vm.go [hunk 3]
```diff
@@ -198,30 +199,30 @@ func (vm *VirtualMachine) WaitForKeyInExtraConfig(ctx context.Context, key strin
 					if key == value.GetOptionValue().Key {
 						detail = value.GetOptionValue().Value.(string)
 						if detail != "" && detail != "<nil>" {
-							return true
+							exitEarly = true
```
Comment (vburenin) [inline pkg/vsphere/vm/vm.go]: How does it help to iterate over all values? It literally looks like you just need to exist in place where you assign true.
