### PR TITLE
Parse datastore path with space and/or DS scheme

### LINKED ISSUE #5354: 6.5 5-6-2-VSAN-Complex: vic-machine create failure while parsing datastore path
```
Running command 'bin/vic-machine-linux create --debug 1 --name=VCH-0-2044 --target=<> 
--thumbprint=<>  --user=<> --image-store="vsanDatastore (1)" --appliance-iso=bin/appliance.iso --bootstrap-iso=bin/bootstrap.iso --password=<> 
--force=true --bridge-network=bridge --public-network=vm-network --compute-resource=cluster-vsan-1 --timeout 30m 
--insecure-registry harbor.ci.drone.local --volume-store="vsanDatastore (1)"/test:default --tls-cname=*.eng.vmware.com  2>&1'
```
Output:
```
...
Jun  3 2017 04:28:19.210Z ERROR error parsing datastore path: parse ds://vsanDatastore%20%281%29/test: invalid URL escape "%20"
Jun  3 2017 04:28:19.210Z DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).ListIssues:257] [170.726µs] 
Jun  3 2017 04:28:19.210Z DEBUG [ END ] [github.com/vmware/vic/lib/install/validate.(*Validator).Validate:282] [13.9943954s] 
Jun  3 2017 04:28:19.210Z ERROR Create cannot continue: configuration validation failed
Jun  3 2017 04:28:19.210Z ERROR --------------------
Jun  3 2017 04:28:19.210Z ERROR vic-machine-linux create failed: validation of configuration failed
' does not contain 'Installer completed successfully'
```

Logs:
[5-6-2-VSAN-Complex.zip](https://github.com/vmware/vic/files/1049712/5-6-2-VSAN-Complex.zip)

### PR DESCRIPTION
**Pull request by rogeliosanchez**
Fixes #5354

This fixes an issue where parsing a datastore path with a space and/or DS scheme specified in the volume store would cause a parse issue due to Golang's own url.Parse not liking escaped characters in the path.

### CODE REVIEW

File: lib/install/validate/storage.go [hunk 1]
```diff
@@ -65,11 +65,11 @@ func (v *Validator) storage(ctx context.Context, input *data.Data, conf *config.
 			v.NoteIssue(vsErr)
 		case common.DsScheme:
 			// TODO: change v.DatastoreHelper to take url struct instead of string and modify tests.
-			targetURL, _, vsErr = v.DatastoreHelper(ctx, targetURL.String(), label, "--volume-store")
+			targetURL, _, vsErr = v.DatastoreHelper(ctx, targetURL.Path, label, "--volume-store")
 			v.NoteIssue(vsErr)
 		default:
 			// We should not reach here, if we do we will attempt to treat this as a vsphere datastore
-			targetURL, _, vsErr = v.DatastoreHelper(ctx, targetURL.String(), label, "--volume-store")
+			targetURL, _, vsErr = v.DatastoreHelper(ctx, targetURL.Path, label, "--volume-store")
```
Comment (emlin) [inline lib/install/validate/storage.go]: feels like for this one, we could keep the old behavior, cause we might just assume special case for `ds://` scheme, everything else e.g. `nfs` should still follow the URL protocol.

File: lib/install/validate/config_to_data.go [hunk 2]
```diff
@@ -281,7 +283,8 @@ func setVolumeLocations(d *data.Data, conf *config.VirtualContainerHostConfigSpe
 			continue
 		}
 		u := *v
-		u.Path = dsURL.Path
+		u.Path = filepath.Join(dsURL.Datastore, dsURL.Path)
+		u.Host = ""
```
Comment (rogeliosanchez) [inline lib/install/validate/config_to_data.go]: @emlin I updated this file. I want to make sure you are ok with this.
