### PR TITLE
Show correct output during rm on a running container

### LINKED ISSUE #1311: docker rm to a running container returns incorrect output
Actual:
Error response from daemon: server error from portlayer

Expected:
Error response from daemon: Conflict, You cannot remove a running container. Stop the container before attempting removal or use -f

### PR DESCRIPTION
**Pull request by anchal-agrawal**
* Fixes output during a `docker rm` on a running container

Vanilla docker:
```
$ sudo docker create busybox /bin/top
<container-id>
$ sudo docker start <container-id>
<container-id>
$ sudo docker rm <container-id>
Error response from daemon: You cannot remove a running container <container-id>. Stop the container before attempting removal or use -f
```

VIC:
```
$ docker -H <host> --tls create busybox /bin/top
<container-id>
$ docker -H <host> --tls start <container-id>
<container-id>
$ docker -H <host> --tls rm <container-id>
Error response from daemon: You cannot remove a running container. Stop the container before attempting removal or use -f
```

* Enables the related integration test in the `docker rm` suite

Fixes #1311

### CODE REVIEW

**Comment by mhagen-vmware** [comment]
lgtm

**Comment by anchal-agrawal** [comment]
@corrieb @caglar10ur @matthewavery I'd really appreciate your input on this. I added an HTTP 409 in swagger to mirror [docker's remote API for `rm`](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#/remove-a-container).

@caglar10ur, I do a string comparison on the error [here](https://github.com/vmware/vic/pull/1753/files#diff-b26a5f740e99039b0c7fd95ab80ce082R227), which is related to #1710.

File: lib/apiservers/engine/backends/container.go [hunk 1]
```diff
@@ -515,6 +515,9 @@ func (c *Container) ContainerRm(name string, config *types.ContainerRmConfig) er
 		if errModel, ok := err.(*containers.ContainerRemoveDefault); ok {
 			return derr.NewErrorWithStatusCode(fmt.Errorf("server error from portlayer : %s", errModel.Payload.Message), http.StatusInternalServerError)
 		}
+		if _, ok := err.(*containers.ContainerRemoveConflict); ok {
+			return derr.NewErrorWithStatusCode(fmt.Errorf("You cannot remove a running container. Stop the container before attempting removal or use -f"), http.StatusConflict)
+		}
 		return derr.NewErrorWithStatusCode(fmt.Errorf("server error from portlayer : %s", err), http.StatusInternalServerError)
```
Comment (matthewavery) [inline lib/apiservers/engine/backends/container.go]: this error handling section should be moved to a `type switch` instead of a series of `if` statements see lib/apiservers/engine/backends/volume.go for an example.

File: lib/apiservers/portlayer/restapi/handlers/containers_handlers.go [hunk 2]
```diff
@@ -223,6 +224,9 @@ func (handler *ContainersHandlersImpl) RemoveContainerHandler(params containers.
 
 	err := h.Container.Remove(context.Background(), handler.handlerCtx.Session)
 	if err != nil {
+		if strings.Contains(err.Error(), "The attempted operation cannot be performed in the current state (Powered on)") {
```
Comment (dougm) [inline lib/apiservers/portlayer/restapi/handlers/containers_handlers.go]: That message is localized, so it is best to check the error type instead.  In this case you could use the following helper:

```go
func isInvalidPowerStateError(err error) bool {
	if terr, ok := err.(task.Error); ok {
		_, invalid := terr.Fault().(*types.InvalidPowerState)
		return invalid
	}
	return false
}
```

Comment (hmahmood) [inline lib/apiservers/portlayer/restapi/handlers/containers_handlers.go]: You should instead return a typed error instead. See https://blog.golang.org/error-handling-and-go

File: lib/portlayer/exec/container.go [hunk 3]
```diff
@@ -258,6 +266,16 @@ func (c *Container) Remove(ctx context.Context, sess *session.Session) error {
...
 	dsPath := fmt.Sprintf("[%s] %s", url.Host, url.Path)
 
+	state, err := c.vm.PowerState(ctx)
+	if err != nil {
+		return fmt.Errorf("Failed to get vm power status %q: %s", c.vm.Reference(), err)
+	}
+
+	// don't remove the containerVM if it is powered on
+	if state == types.VirtualMachinePowerStatePoweredOn {
+		return RemovePowerError{fmt.Errorf("You cannot remove a running container. Stop the container before attempting removal or use -f")}
```
Comment (hmahmood) [inline lib/portlayer/exec/container.go]: This error string is docker specific and should be in the docker personality. The port layer does not know what `-f` is. You should view the port layer as a library that can stand on its own, and so the errors should reflect that. Over here just "container is running," or something similar would suffice.

**Comment by hmahmood** [comment]
lgtm

**Comment by anchal-agrawal** [comment]
♻️
