### PR TITLE
Fix insecure-registry URL parsing in GO1.8, #4141

### LINKED ISSUE #4141: vic machine fails install when insecure-registry specified
if installing a VCH and you specify an insecure registry the vic-machine parsing of the flag fails.

vic built from source using `go1.8`

vic-machine create command:
`vic-machine-linux create -t 172.16.73.170 -u root -p vagrant -n vickie -vs datastore1/vickie-vols:default -vs datastore1/vickie-vols:jojo -k -f --insecure-registry 172.16.73.147:5000`

vic-machine result:
```
Mar  3 2017 22:59:57.228Z INFO  ### Installing VCH ####
Mar  3 2017 22:59:57.229Z WARN  Using administrative user for VCH operation - use --ops-user to improve security (see -x for advanced help)
Mar  3 2017 22:59:57.229Z WARN  Configuring without TLS - all communications will be insecure
Mar  3 2017 22:59:57.229Z ERROR --------------------
Mar  3 2017 22:59:57.230Z ERROR vic-machine-linux create failed: 172.16.73.147:5000 is an invalid format for registry url
```

This worked with `go version 1.7.x` but fails with `go version 1.8` -- specifically the call to `url.Parse(registry_string)` throws an error.  An example is at:  https://play.golang.org/p/SwZAq5NszD -- this is executing in go1.8, but if you run locally with go1.7x no error will be thrown.

Additionally, if you provide a url that will pass the validation then the pull from the private registry doesn't work.

From my perspective this effectively breaks insecure-registry support.

### PR DESCRIPTION
**Pull request by lcastellano**
This change includes:
- New URL parsing function (originally from GOVMOMI)
- Changed vic-machine to use new parser
- Changed backend to read host:port from the Host component of the URL

Fixes #4141

### CODE REVIEW

File: lib/install/validate/validator.go [hunk 1]
```diff
@@ -156,6 +157,30 @@ func NewValidator(ctx context.Context, input *data.Data) (*Validator, error) {
 	return v, nil
 }
 
+var schemeMatch = regexp.MustCompile(`^\w+://`)
```
Comment (caglar10ur) [inline lib/install/validate/validator.go]: I really prefer using strings package (HasPrefix) instead of regex

Comment (dougm) [inline lib/install/validate/validator.go]: How to in this case, since it could be "http", "https", maybe even another scheme.

File: lib/install/validate/validator.go [hunk 2]
```diff
@@ -156,6 +157,30 @@ func NewValidator(ctx context.Context, input *data.Data) (*Validator, error) {
...
+
+// Starting from GO 1.8 the URL parser does not
```
Comment (dougm) [inline lib/install/validate/validator.go]: Doc should start with the function name (to avoid go-lint warnings).
s/GO/Go/
s/Schema/Scheme/g

File: lib/install/validate/validator.go (hunk 1 above)
Comment (caglar10ur) [inline lib/install/validate/validator.go]: https://play.golang.org/p/mRrrzoOS1_ could work but I'm OK with the change if I'm the only one stuck on regex :)

File: lib/apiservers/engine/backends/backends.go [hunk 3]
```diff
@@ -112,7 +112,13 @@ func Init(portLayerAddr, product string, config *config.VirtualContainerHostConf
 
 	serviceOptions := registry.ServiceOptions{}
 	for _, r := range insecureRegs {
-		insecureRegistries = append(insecureRegistries, r.Path)
+		/*
```
Comment (anchal-agrawal) [inline lib/apiservers/engine/backends/backends.go]: Nitpick - we should use Go's idiomatic way of (non-package level) multi-line comments. We should stick to `//` for this.

https://golang.org/doc/effective_go.html#commentary
> Comments do not need extra formatting such as banners of stars.

**Comment by gigawhitlocks** [comment]
Could we put the URL parsing function in a more generic location? I think it's going to be needed in places outside of the installer and it feels weird importing `lib/install/validator.go` to get the URL parsing function that you wrote.

**Comment by jzt** [comment]
LGTM

**Comment by mdubya66** [comment]
Approved for merge to unblock others

**Comment by mdubya66** [comment]
Successful build was https://ci.vmware.run/vmware/vic/9035

File: lib/install/validate/validator.go [hunk 4]
```diff
@@ -156,6 +157,30 @@ func NewValidator(ctx context.Context, input *data.Data) (*Validator, error) {
 	return v, nil
 }
 
+var schemeMatch = regexp.MustCompile(`^\w+://`)
+
+// Starting from Go 1.8 the URL parser does not
```
Comment (vburenin) [inline lib/install/validate/validator.go]: This might be misleading comment. Is a Go bug? If so, then a reference to that bug needs to be added.
If it is a corrected behavior that was not good before then change a comment to be something like:
"ParseURL parses URL adding default https scheme if no scheme is provided."

File: lib/install/validate/validator.go [hunk 5]
```diff
@@ -156,6 +157,30 @@ func NewValidator(ctx context.Context, input *data.Data) (*Validator, error) {
...
+// work properly with URLs with no Scheme,
+// this function adds "https" as Scheme if necessary
+func ParseURL(s string) (*url.URL, error) {
```
Comment (vburenin) [inline lib/install/validate/validator.go]: It seems like this function can be drastically reduced to:

```
func ParseURL(s string) (*url.URL, error) {
	if s != "" && !schemeMatch.MatchString(s) {

		s = "https://" + s
	}
	return url.Parse(s)
}
```

File: lib/apiservers/engine/backends/backends.go [hunk 6]
```diff
@@ -253,7 +257,7 @@ func createImageStore() error {
 }
 
 func InsecureRegistries() []string {
-	registries := make([]string, len(insecureRegistries))
+	registries := []string{}
```
Comment (vburenin) [inline lib/apiservers/engine/backends/backends.go]: This is incorrect fix. Initial line had a bug not providing size only.
Correct fix is this:
```registries := make([]string, 0, len(insecureRegistries))```

File: lib/install/validate/validator_test.go [hunk 7]
```diff
@@ -32,12 +32,85 @@ import (
 	"github.com/vmware/vic/pkg/vsphere/simulator"
 
 	"context"
+	"fmt"
```
Comment (vburenin) [inline lib/install/validate/validator_test.go]: imports order needs to be fixed.

File: lib/install/validate/validator.go [hunk 8]
```diff
@@ -22,6 +22,7 @@ import (
 	"strings"
 
 	"context"
+	"regexp"
```
Comment (vburenin) [inline lib/install/validate/validator.go]: built-in import blocks should be merged.

**Comment by dougm** [comment]
Just learned we already had similar code here: https://github.com/vmware/vic/blob/master/pkg/flags/url_flag.go#L29-L42
