### PR TITLE
Fixes to support concurrent VCH and container VM state changes [full ci]

### LINKED ISSUE #3137: Shutdown and (re)Start of VCH has an improper behaviour
Version 0.7.0

Freshly deployed VCH.

```
user1@ubuntu:~/vic$ docker run -d -p 81:80 --name nginx1 nginx 
bca2d70d6d85a656d81ac1a5c4bf66697c536bee613b4651422237a3d9dfe85a

user1@ubuntu:~/vic$ docker run -d -p 82:80 --name nginx2 nginx 
ef75aa8277eb110f3bec52407345d2154eb3dac35b129079a17164fea279ee0b

user1@ubuntu:~/vic$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                     NAMES
ef75aa8277eb        nginx               "nginx -g daemon off;"   About a minute ago   Up 36 seconds       192.168.8.57:82->80/tcp   nginx2
bca2d70d6d85        nginx               "nginx -g daemon off;"   2 minutes ago        Up About a minute   192.168.8.57:81->80/tcp   nginx1
```

At this point we *SHUTDOWN THE VCH* 

We then *START THE VCH* back up 

On the vSphere side both containerVMs have re-started (along with the VCH EndPoint Docker VM).  

But the docker client doesn’t seem to be able to cope with what’s going on:
```
user1@ubuntu:~/vic$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
ef75aa8277eb        nginx               "nginx -g daemon off;"   8 minutes ago       Stopped             192.168.8.57:82->80/tcp   nginx2
bca2d70d6d85        nginx               "nginx -g daemon off;"   8 minutes ago       Stopped             192.168.8.57:81->80/tcp   nginx1
```

I believe there are two things here:

https://github.com/vmware/vic/issues/701 should address this inconsistency between the Docker view and the vSphere view.

https://github.com/vmware/vic/issues/744 should implement the proper logic to be applied when the VCH is shut-down and then restarted. Ultimately (IMO) the VCH should behave pretty much like a Docker host that is shutdown and then restarted. 

/cc @emlin

### PR DESCRIPTION
**Pull request by hmahmood**
- Added subscriber implementation that can be "paused", i.e. not
  process events until "unpaused"
- Event manager no longer launches a go routine to process each
  event that is received; instead thee event is not queued to
  preserve the order the events are recieved
- Modified high availability test to include stopped and running
  containers at time HA is triggered
 
Fixes #3137

### CODE REVIEW

File: lib/portlayer/exec/container.go [hunk 1]
```diff
@@ -555,6 +551,96 @@ func (c *Container) Remove(ctx context.Context, sess *session.Session) error {
...
+	// do we have a state change
+	if newState != c.state {
+		switch newState {
+		case StateStopping,
+			StateRunning,
+			StateStopped,
+			StateSuspended:
+
+			// container state has changed so we need to update the container attributes
+			// we'll do this in a go routine to avoid blocking
```
Comment (cgtexmex) [inline lib/portlayer/exec/container.go]: should remove reference to use of a go routine

**Comment by cgtexmex** [comment]
small comment change requested, but LGTM

File: lib/portlayer/event/subscriber.go [hunk 2]
```diff
@@ -0,0 +1,208 @@
...
+			}
+
+			// not suspended
+			select {
+			case e := <-s.eventQ:
+				s.callback(e)
+			case c := <-s.suspend:
+				suspended = c.suspend
+				done = c.done
+			}
```
Comment (caglar10ur) [inline lib/portlayer/event/subscriber.go]: I think this non suspended case needs to go into the select statement above. Otherwise - if I'm reading it correctly - it can be paused just after the suspended check and before the 2nd select statement and blocks there forever. No?

Comment (hmahmood) [inline lib/portlayer/event/subscriber.go]: If suspended is false, that indicates Resume() was called before. If we end up on line 110, and Suspend() is called, line 113 should be hit, and we should set suspended to true, and loop back around.
