### PR TITLE
[specific ci=Group6-VIC-Machine]vic-machine configure/upgrade: set correct compute resource if input is VCH ID

### LINKED ISSUE #5379: vic-machine upgrade to patch failed
Here is the message copied from #5343 

I went with a forced upgrade; but, it did not succeed. Below snippet from vic-machine.log.
```
goroutine 1 [running]:
runtime/debug.Stack(0xfadf39, 0x2f, 0xc042460ee0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
main.main.func1(0xc04201bba0, 0xc0420041d0)
	/go/src/github.com/vmware/vic/cmd/vic-machine/main.go:142 +0x184
panic(0xd8d880, 0x1677c80)
	/usr/local/go/src/runtime/panic.go:489 +0x2dd
github.com/vmware/vic/lib/install/validate.(*Validator).AddDeprecatedFields(0xc042062480, 0x16540a0, 0xc0421de680, 0xc04206c380, 0xc0421af800, 0x0)
	/go/src/github.com/vmware/vic/lib/install/validate/validator.go:778 +0x241
github.com/vmware/vic/cmd/vic-machine/upgrade.(*Upgrade).Run(0xc042197990, 0xc0421d0000, 0x0, 0x0)
	/go/src/github.com/vmware/vic/cmd/vic-machine/upgrade/upgrade.go:198 +0xd01
github.com/vmware/vic/cmd/vic-machine/upgrade.(*Upgrade).Run-fm(0xc0421d0000, 0x10101010100, 0xc0421d0000)
	/go/src/github.com/vmware/vic/cmd/vic-machine/main.go:93 +0x3b
github.com/vmware/vic/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xd430e0, 0xc0421979f0, 0xc0421d0000, 0xc042031300, 0x0)
	/go/src/github.com/vmware/vic/vendor/gopkg.in/urfave/cli.v1/app.go:485 +0xdb
github.com/vmware/vic/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xf71a98, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf95e2e, 0x1d, 0x0, ...)
	/go/src/github.com/vmware/vic/vendor/gopkg.in/urfave/cli.v1/command.go:193 +0xb79
github.com/vmware/vic/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc04201bba0, 0xc0420360d0, 0xd, 0xd, 0x0, 0x0)
	/go/src/github.com/vmware/vic/vendor/gopkg.in/urfave/cli.v1/app.go:250 +0x7d7
main.main()
	/go/src/github.com/vmware/vic/cmd/vic-machine/main.go:146 +0x1dad
```

### PR DESCRIPTION
**Pull request by emlin**
Fixes #5379

### CODE REVIEW

File: cmd/vic-machine/configure/configure.go [hunk 1]
```diff
@@ -270,6 +270,11 @@ func (c *Configure) Run(clic *cli.Context) (err error) {
 		log.Error(err)
 		return err
 	}
+	if err = validate.SetDataFromVM(ctx, validator.Session.Finder, vch, oldData); err != nil {
+		log.Error("Configuring cannot continue: querying configuration from vm failed")
```
Comment (anchal-agrawal) [inline cmd/vic-machine/configure/configure.go]: s/vm/VM

File: tests/test-cases/Group6-VIC-Machine/6-16-Config.robot [hunk 2]
```diff
@@ -40,21 +40,21 @@ Configure VCH debug state
...
+    ${rc}  ${output}=  Run And Return Rc And Output  bin/vic-machine-linux inspect --name=%{VCH-NAME} --conf --target=%{TEST_URL}%{TEST_DATACENTER} --thumbprint=%{TEST_THUMBPRINT} --user=%{TEST_USERNAME} --password=%{TEST_PASSWORD} --timeout %{TEST_TIMEOUT}
     Should Be Equal As Integers  0  ${rc}
     Should Contain  ${output}  --debug=1
 
 Configure VCH Container Networks
     ${out}=  Run  govc host.portgroup.remove vm-network
     ${out}=  Run  govc host.portgroup.add -vswitch vSwitchLAN vm-network
 
-    ${output}=  Run  bin/vic-machine-linux configure --name=%{VCH-NAME} --target=%{TEST_URL} --thumbprint=%{TEST_THUMBPRINT} --user=%{TEST_USERNAME} --password=%{TEST_PASSWORD} --timeout %{TEST_TIMEOUT} --container-network vm-network:vmnet
+    ${output}=  Run  bin/vic-machine-linux configure --name=%{VCH-NAME} --target=%{TEST_URL}%{TEST_DATACENTER} --thumbprint=%{TEST_THUMBPRINT} --user=%{TEST_USERNAME} --password=%{TEST_PASSWORD} --timeout %{TEST_TIMEOUT} --container-network vm-network:vmnet
```
Comment (anchal-agrawal) [inline tests/test-cases/Group6-VIC-Machine/6-16-Config.robot]: For my understanding - why is this needed?

Comment (emlin) [inline tests/test-cases/Group6-VIC-Machine/6-16-Config.robot]: This code change is for complicated environment only, it doesn't reproduce at simple VC, with single dc and cluster.
It will be useful after we switch the CI to VC with multiple DC and cluster.
