### PR TITLE
Prevent truncation of log output [full ci]

### LINKED ISSUE #2669: Failure in build 5688 - cross container ping
Cross container ping test is failing. It's expecting `2 packets transmitted, 2 packets received` but the test isn't seeing it.

The tether logs shows us writing it (to both the console and the log):

```
time="2016-10-12T00:27:01Z" level=debug msg="[0xc4201a7e00] write \"64 bytes from 172.18.0.2: seq=1 ttl=64 time=0.170 ms\\n\\n--- cross1-container ping statistics ---\\n2 packets transmitted, 2 packets received, 0% packet loss\\nround-trip min/avg/max = 0.170/0.210/0.251 ms\\n\" to 2 writers (err: <nil>)" 
```

output.xml

```
<msg timestamp="20161012 00:29:18.982" level="INFO">Running command 'docker -H 192.168.31.210:2375 network connect cross1-network2 084b85f3cbc9457ec277c16603c4441cad79e505bf8f43631f70509f7e8a6b47 2&gt;&amp;1'.</msg>
<msg timestamp="20161012 00:29:19.129" level="INFO">${rc} = 0</msg>
<msg timestamp="20161012 00:29:19.129" level="INFO">${output} = </msg>
<status status="PASS" endtime="20161012 00:29:19.129" starttime="20161012 00:29:18.979"></status>
</kw>
<kw name="Should Be Equal As Integers" library="BuiltIn">
<doc>Fails if objects are unequal after converting them to integers.</doc>
<arguments>
<arg>${rc}</arg>
<arg>0</arg>
</arguments>
<msg timestamp="20161012 00:29:19.130" level="INFO">Argument types are:
&lt;type 'int'&gt;
&lt;type 'unicode'&gt;</msg>
<status status="PASS" endtime="20161012 00:29:19.130" starttime="20161012 00:29:19.130"></status>
</kw>
<kw name="Run And Return Rc And Output" library="OperatingSystem">
<doc>Runs the given command in the system and returns the RC and output.</doc>
<arguments>
<arg>docker ${params} start ${containerID}</arg>
</arguments>
<assign>
<var>${rc}</var>
<var>${output}</var>
</assign>
<msg timestamp="20161012 00:29:19.133" level="INFO">Running command 'docker -H 192.168.31.210:2375 start 084b85f3cbc9457ec277c16603c4441cad79e505bf8f43631f70509f7e8a6b47 2&gt;&amp;1'.</msg>
<msg timestamp="20161012 00:29:30.371" level="INFO">${rc} = 0</msg>
<msg timestamp="20161012 00:29:30.371" level="INFO">${output} = 084b85f3cbc9457ec277c16603c4441cad79e505bf8f43631f70509f7e8a6b47</msg>
<status status="PASS" endtime="20161012 00:29:30.371" starttime="20161012 00:29:19.131"></status>
</kw>
<kw name="Should Be Equal As Integers" library="BuiltIn">
<doc>Fails if objects are unequal after converting them to integers.</doc>
<arguments>
<arg>${rc}</arg>
<arg>0</arg>
</arguments>
<msg timestamp="20161012 00:29:30.372" level="INFO">Argument types are:
&lt;type 'int'&gt;
&lt;type 'unicode'&gt;</msg>
<status status="PASS" endtime="20161012 00:29:30.372" starttime="20161012 00:29:30.371"></status>
</kw>
<kw name="Run And Return Rc And Output" library="OperatingSystem">
<doc>Runs the given command in the system and returns the RC and output.</doc>
<arguments>
<arg>docker ${params} logs --follow cross1-container2</arg>
</arguments>
<assign>
<var>${rc}</var>
<var>${output}</var>
</assign>
<msg timestamp="20161012 00:29:30.374" level="INFO">Running command 'docker -H 192.168.31.210:2375 logs --follow cross1-container2 2&gt;&amp;1'.</msg>
<msg timestamp="20161012 00:29:32.507" level="INFO">${rc} = 0</msg>
<msg timestamp="20161012 00:29:32.508" level="INFO">${output} = PING cross1-container (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: seq=0 ttl=64 time=0.251 ms
64 bytes from 172.18.0.2: seq=1 ttl=64 time=0.170 ms

--- cros</msg>
<status status="PASS" endtime="20161012 00:29:32.508" starttime="20161012 00:29:30.372"></status>
</kw>
<kw name="Should Be Equal As Integers" library="BuiltIn">
<doc>Fails if objects are unequal after converting them to integers.</doc>
<arguments>
<arg>${rc}</arg>
<arg>0</arg>
</arguments>
<msg timestamp="20161012 00:29:32.508" level="INFO">Argument types are:
&lt;type 'int'&gt;
&lt;type 'unicode'&gt;</msg>
<status status="PASS" endtime="20161012 00:29:32.508" starttime="20161012 00:29:32.508"></status>
</kw>
<kw name="Should Contain" library="BuiltIn">
<doc>Fails if ``container`` does not contain ``item`` one or more times.</doc>
<arguments>
<arg>${output}</arg>
<arg>2 packets transmitted, 2 packets received</arg>
</arguments>
<msg timestamp="20161012 00:29:32.509" level="FAIL">'PING cross1-container (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: seq=0 ttl=64 time=0.251 ms
64 bytes from 172.18.0.2: seq=1 ttl=64 time=0.170 ms

--- cros' does not contain '2 packets transmitted, 2 packets received'</msg>
<status status="FAIL" endtime="20161012 00:29:32.509" starttime="20161012 00:29:32.509"></status>
</kw>
<status status="FAIL" endtime="20161012 00:29:32.510" critical="yes" starttime="20161012 00:29:05.776">'PING cross1-container (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: seq=0 ttl=64 time=0.251 ms
64 bytes from 172.18.0.2: seq=1 ttl=64 time=0.170 ms

--- cros' does not contain '2 packets transmitted, 2 packets received'</status>
</test>
<test id="s1-s1-s9-t5" name="Connect containers to multiple networks non-overlapping">
<kw name="Run And Return Rc And Output" library="OperatingSystem">
```

@matthewavery we do not have the `output.log` file **winces** so we cannot say whether this was an issue with `logs --follow` or a data flushing problem to the datastore. We should add that back in for `debug > 2` - collecting application level state is a serious change in behaviour so shouldn't be:

```
debug==1 # increase in verbosity of logging
debug==2 # slight changes in runtime behaviour
```

@dougm @sflxn Do you know what impact the container shutting down will have on the logs command? I assume there is logic to end `logs` when the container powers off, but I don't know if we do one last call to the datastore after to ensure we got all of the data. @dougm I remember you mentioning a final attempt but not the details.

[Test-Cases.Group1-Docker-Commands.1-17-Docker-Network-Connect-VCH-5688-6570-container-logs.zip](https://github.com/vmware/vic/files/523447/Test-Cases.Group1-Docker-Commands.1-17-Docker-Network-Connect-VCH-5688-6570-container-logs.zip)

[output.zip](https://github.com/vmware/vic/files/523451/output.zip)

### PR DESCRIPTION
**Pull request by hickeng**
Addresses two possible vectors for log truncation:
1. In-flight Write's get torn by Close
2. did not wait for PTY copying to complete

This does NOT address truncation on the interactive channel.

Fixes #2669

### CODE REVIEW

**Comment by caglar10ur** [comment]
LGTM

File: lib/tether/config.go [hunk 1]
```diff
@@ -96,10 +96,11 @@ type SessionConfig struct {
 	Group string `vic:"0.1" scope:"read-only" key:"group"`
 
 	// if there's a pty then we need additional management data
-	Pty       *os.File
+	Pty       *os.File               `vic:"0.1" scope:"read-only" recurse:"depth=0"`
 	Outwriter dio.DynamicMultiWriter `vic:"0.1" scope:"read-only" recurse:"depth=0"`
 	Errwriter dio.DynamicMultiWriter `vic:"0.1" scope:"read-only" recurse:"depth=0"`
 	Reader    dio.DynamicMultiReader `vic:"0.1" scope:"read-only" recurse:"depth=0"`
+	wait      *sync.WaitGroup        `vic:"0.1" scope:"read-only" recurse:"depth=0"`
```
Comment (caglar10ur) [inline lib/tether/config.go]: [cosmetic] this could be named as wg :) Or alternatively this could be a channel struct{} as well

File: lib/tether/tether_linux.go [hunk 2]
```diff
@@ -210,26 +211,32 @@ func lookPath(file string, env []string, dir string) (string, error) {
 	return "", fmt.Errorf("%s: no such executable in PATH", file)
 }
 
-func establishPty(session *SessionConfig) error {
+func establishPty(session *SessionConfig) (*sync.WaitGroup, error) {
```
Comment (hmahmood) [inline lib/tether/tether_linux.go]: Instead of returning it here, we can just set it on the session object.

File: pkg/dio/writer.go [hunk 3]
```diff
@@ -49,34 +50,41 @@ func (t *multiWriter) Write(p []byte) (int, error) {
 	}
 
 	t.mutex.Lock()
+
+	t.waitGroup.Add(1)
```
Comment (hmahmood) [inline pkg/dio/writer.go]: If I am reading the other changes right, Close() will always be called after the last Write(). This may still be a good idea, but not sure if this contributes to the actual fix.

File: lib/tether/tether_linux.go [hunk 4]
```diff
@@ -210,26 +211,32 @@ func lookPath(file string, env []string, dir string) (string, error) {
...
 		go func() {
 			_, gerr := io.Copy(session.Outwriter, session.Pty)
-			log.Debug(gerr)
+			log.Debugf("PTY stdout copy: %s", gerr)
+			wg.Done()
 		}()
 		go func() {
 			_, gerr := io.Copy(session.Pty, session.Reader)
-			log.Debug(gerr)
+			log.Debugf("PTY stdin copy: %s", gerr)
```
Comment (fdawg4l) [inline lib/tether/tether_linux.go]: Does this need to be tracked by `wg`?

Comment (caglar10ur) [inline lib/tether/tether_linux.go]: Nope, that's the stdin from processes point of view

File: pkg/dio/writer.go (hunk 3 above)
Comment (hickeng) [inline pkg/dio/writer.go]: Any in-flight writes should be protected - any higher level behaviour needs to be enforced by callers.

Comment (hmahmood) [inline pkg/dio/writer.go]: There is a race here where if Close() gets the lock first, it will close and clear out the writers. When Write() gets through, it is left with no writers, and just returns without writing anything (and no error). This is borderline acceptable; the wait group does not prevent this case. It appears to be safe to use though, although I think just grabbing the lock for the duration of the writes would have the same affect.

**Comment by hmahmood** [comment]
There is still a chance that writes will be dropped if the sequence of Write() followed by Close() is not enforced. However, we are doing that as well in this PR, so LGTM.

**Comment by hickeng** [comment]
poke
