### PR TITLE
Use absolute vSAN disk paths for container rw layer

### LINKED ISSUE #8408: Hit 'Server error from portlayer: Invalid datastore path' when creating container in vSAN env
In this 2 day VIC scenario testing, cases using vSAN env are all failure.  Error is as **${container} = Error response from daemon: Server error from portlayer: Invalid datastore path './83decb61cac80c352e270e391483dc74d30455e211d7a962e2a1462df23a0970.vmdk'** when regression testing is creating container with the pulled image(busybox)

robot logs is https://vic-jenkins.eng.vmware.com/job/vic-master-scenario/80/robot/report/log.html#s1-s4-s22 and the related VCH logs are http://pa-dbc1134.eng.vmware.com/luwang/Logs/Suites.Group5-Functional-Tests.5-6-1-VSAN-Simple-VCH-0-2454-container-logs.zip

@hickeng George, I see you merge a code in vic 2 days ago for https://github.com/vmware/vic/pull/7397. Would you mind helping checking it?

Thanks,
Lu

### PR DESCRIPTION
**Pull request by hickeng**
This fixes an issue on vSAN introduced by the storage function reorg(##7397).
vSAN cannot use disk paths expressed relative to the VM being created.

Fixes #8408

### CODE REVIEW

File: lib/portlayer/storage/image/vsphere/join.go [hunk 1]
```diff
@@ -30,7 +29,7 @@ func Join(op trace.Operation, handle *exec.Handle, id, imgID, repoName string, i
 	// set the rw layer name
 	// NOTE: this is a POOR assumption - I'm not clear on how it's functioning on vSAN at all in shipping code given the assumption that
```
Comment (zjs) [inline lib/portlayer/storage/image/vsphere/join.go]: Is this comment no longer relevant given this change?
