### PR TITLE
Fix incorrect assumption for bootstrap.iso path

### LINKED ISSUE #1351: Incorrect formulation of bootstrap iso path
The location of the bootstrap iso image should be set in the VCH config data:
https://github.com/vmware/vic/blob/master/lib/metadata/virtual_container_host.go#L111

and pulled from there when creating containers:
https://github.com/vmware/vic/blob/master/lib/portlayer/exec/handle.go#L221

### PR DESCRIPTION
**Pull request by caglar10ur**
The ISO path that's generated is based off the display name, not the
actual VM folder path. This pr fixes that also removes the hardcoded
appliance.iso file name.

Fixes #1351 2nd time

### CODE REVIEW

**Comment by caglar10ur** [comment]
Created https://github.com/vmware/vic/issues/1883 for the integration test part

**Comment by fdawg4l** [comment]
LGTM

**Comment by caglar10ur** [comment]
```
[conur@vir:/opt/go/src/github.com/vmware/vic(iso)] govc datastore.ls ZzZ/*.iso
b.iso
a.iso
[conur@vir:/opt/go/src/github.com/vmware/vic(iso)] govc datastore.download ZzZ/ZzZ.vmx ZzZ.vmx; grep iso ZzZ.vmx
[09-08-16 10:34:30] Downloading... OK
48:ide0:0.fileName = "a.iso"
102:guestinfo./bootstrap_image_path = "[vsanDatastore] 980faa57-97c1-5f89-4578-000c298a9889/b.iso"
[conur@vir:/opt/go/src/github.com/vmware/vic(iso)]
```

File: lib/install/management/appliance.go [hunk 1]
```diff
@@ -359,7 +359,7 @@ func (d *Dispatcher) configIso(conf *config.VirtualContainerHostConfigSpec, vm *
 		log.Errorf("Failed to create Cdrom device for appliance: %s", err)
 		return nil, err
 	}
-	cdrom = devices.InsertIso(cdrom, fmt.Sprintf("[%s] %s/appliance.iso", conf.ImageStores[0].Host, d.vmPathName))
+	cdrom = devices.InsertIso(cdrom, fmt.Sprintf("[%s] %s/%s", conf.ImageStores[0].Host, d.vmPathName, settings.ApplianceISO))
```
Comment (hickeng) [inline lib/install/management/appliance.go]: Should we be using the actual path of the appliance VM rather than composing in this fashion. It'll currently work because we use ImageStores[0] as the applianceVM datastore, but if that ever changes then this will break.

**Comment by hickeng** [comment]
LGTM other than future proofing.

File: lib/install/management/appliance.go (hunk 1 above)
Comment (caglar10ur) [inline lib/install/management/appliance.go]: conf.ImageStores[0] used everywhere in the vic-machine code so will open a issue to address that if needed

**Comment by emlin** [comment]
Caglar, this change is good. 
Just wondering if we should custom the iso files in datastore.
I mean we uploaded the file here https://github.com/vmware/vic/blob/master/lib/install/management/create.go#L122, with the filename from local file system, would it be better to use "appliance.iso" and "bootstrap.iso" during uploading, no matter how user name them?
then we could assume them in our code as a constant name.
