### PR TITLE
CreateImageStore returns vSphere error allowing retry

### LINKED ISSUE #4858: Nightly 6.5 HA test fails during rmi busybox
```KEYWORD ${rc}, ${output} = OperatingSystem . Run And Return Rc And Output docker %{VCH-PARAMS} rmi busybox
Documentation:	
Runs the given command in the system and returns the RC and output.
Start / End / Elapsed:	20170423 21:38:08.550 / 20170423 21:38:10.326 / 00:00:01.776
21:38:08.558	INFO	Running command 'docker -H 10.160.68.255:2376 --tls rmi busybox 2>&1'.	
21:38:10.326	INFO	${rc} = 1	
21:38:10.326	INFO	${output} = Error response from daemon: [DELETE /storage/{store_name}/info/{id}][500] DeleteImage default  &{Code:500 Message:Can't find parent http:///storage/images/4209e5d7-0c7c-6382-7742-5ce5e99ae0c9/d0fb090f...

### PR DESCRIPTION
**Pull request by cgtexmex**
- Propagate vSphere error allowing retry
- Log when a new operation is created
- Additional logging during ImageStore creation

Fixes #4858

### CODE REVIEW

File: pkg/trace/operation.go [hunk 1]
```diff
@@ -226,7 +226,11 @@ func opID(opNum uint64) string {
 
 // NewOperation will return a new operation with operationID added as a value to the context
 func NewOperation(ctx context.Context, format string, args ...interface{}) Operation {
-	return newOperation(ctx, opID(atomic.AddUint64(&opCount, 1)), 3, fmt.Sprintf(format, args...))
+	o := newOperation(ctx, opID(atomic.AddUint64(&opCount, 1)), 3, fmt.Sprintf(format, args...))
+
+	frame := o.t[0]
+	o.Debugf("[NewOperation] %s [%s:%d]", o.header(), frame.funcName, frame.lineNo)
```
Comment (hickeng) [inline pkg/trace/operation.go]: Are you intentionally adding this back in? I seem to recall it was removed during the big operation trace PR.

File: lib/portlayer/storage/image_cache.go [hunk 2]
```diff
@@ -60,9 +60,20 @@ func NewLookupCache(ds ImageStorer) *NameLookupCache {
 	}
 }
 
+// isRetry will check the error for retryability - if so reset the cache
+func (c *NameLookupCache) isRetry(op trace.Operation, err error) bool {
+	if tasks.IsRetryError(op, err) {
+		op.Debugf("%s is retryable, resetting store cache", err)
+		c.storeCache = make(map[url.URL]*index.Index)
```
Comment (hickeng) [inline lib/portlayer/storage/image_cache.go]: Am I correct in assuming that there's no single place where we can purge the cache before regenerating it, e.g at the start of GetImageStore, and that's why it's done in the error type check?

Comment (cgtexmex) [reply lib/portlayer/storage/image_cache.go]: I didn't see a good place to do it -- originally I had it as part of the retry function, but it didn't quite work....so went with this approach...open to suggestions.

File: pkg/trace/operation.go (hunk 1 above)
Comment (cgtexmex) [reply pkg/trace/operation.go]: Yes...this is intentional.  If you recall when we were looking into the `fixVM` issue I lamented that I removed it -- so I'm returning it.
